import { describe, it, expect, vi, beforeEach } from 'vitest';
import { shallowMount, flushPromises } from '@vue/test-utils';
import { isProxy, nextTick } from 'vue';
import PowerWorkflow from '../src/components/dag/PowerWorkflow.vue';
import InstanceDetail from '../src/components/common/InstanceDetail.vue';
import WorkflowInstanceDetail from '../src/components/dag/WorkflowInstanceDetail.vue';
import WorkflowEditor from '../src/components/dag/WorkflowEditor.vue';
vi.mock('../src/components/dag/JSEditor.vue', () => ({ default:{name:'JSEditor',props:['code','editorOptions'],template:'<textarea :value="code" />'} }));
vi.mock('../src/components/views/WorkflowManager.vue', () => ({ default:{name:'WorkflowManager',template:'<div />'} }));
vi.mock('../src/components/common/TimeExpressionValidator.vue', () => ({ default:{name:'TimeExpressionValidator',template:'<div />'} }));
const globals = (axios={get:vi.fn(),post:vi.fn()}, route={query:{},params:{}}) => ({
  mocks:{axios,$route:route,$router:{push:vi.fn(),replace:vi.fn()},$t:key=>key,$confirm:vi.fn().mockResolvedValue('confirm'),$message:{success:vi.fn(),warning:vi.fn(),error:vi.fn()},common:{translateInstanceStatus:status=>String(status),translateWfInstanceStatus:status=>String(status)}},
  stubs:{...Object.fromEntries(['ElInput','ElFormItem','ElForm','ElOption','ElSelect','ElDatePicker','ElInputNumber','ElCard','ElSwitch','ElTableColumn','ElTable','ElPagination','ElDrawer','ElDialog','ElDescriptions','ElDescriptionsItem','ElTabs','ElTabPane','ElDivider','ElCollapse','ElCollapseItem','ElEmpty'].map(name=>[name,true])),ElButton:{template:'<button><slot/></button>'},ElTooltip:{template:'<span><slot/></span>'}},
  directives:{loading:()=>{}},
});
beforeEach(() => { vi.stubGlobal('ResizeObserver',class { observe(){} disconnect(){} }); });
const nodes=[{nodeId:'1',nodeType:1,nodeName:'first',jobId:'11',enable:true},{nodeId:'2',nodeType:2,nodeName:'condition',nodeParams:'true'},{nodeId:'3',nodeType:3,nodeName:'child',jobId:'22'}];
describe('native workflow canvas interaction', () => {
  it('removes each fullscreen observer and keyboard surface after repeated mount/unmount',async()=>{const add=vi.spyOn(document,'addEventListener'),remove=vi.spyOn(document,'removeEventListener');const disconnected=[];vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){disconnected.push(true);}});for(let i=0;i<3;i++){const wrapper=shallowMount(PowerWorkflow,{props:{nodes,edges:[]},global:globals()});await nextTick();const callback=add.mock.calls.filter(([name])=>name==='fullscreenchange').at(-1)[1];const surface=wrapper.find('.workflow-canvas');await surface.trigger('keydown',{key:'Delete'});wrapper.unmount();expect(remove.mock.calls.some(([name,fn])=>name==='fullscreenchange'&&fn===callback)).toBe(true);}expect(disconnected).toHaveLength(3);add.mockRestore();remove.mockRestore();});
  it('exposes a raw graph adapter and selects the actual decimal node ID',async()=>{const wrapper=shallowMount(PowerWorkflow,{props:{nodes,edges:[]},global:globals()});await nextTick();const [flow]=wrapper.emitted('getDag')[0];expect(isProxy(flow)).toBe(false);expect(isProxy(flow.graph)).toBe(false);await wrapper.find('[data-node-id="1"]').trigger('pointerdown',{button:0,clientX:100,clientY:100});expect(wrapper.emitted('onSelectedNode').at(-1)[0].get('model').id).toBe('1');expect(flow.graph.save().nodes).toHaveLength(3);wrapper.unmount();});
  it('connects a condition using Y and N and deletes the selected edge',async()=>{const wrapper=shallowMount(PowerWorkflow,{props:{nodes,edges:[]},global:globals()});wrapper.vm.connect('2','1','Y');wrapper.vm.connect('2','3','N');expect(wrapper.vm.powerFlow.graph.save().edges.map(e=>e.label)).toEqual(['Y','N']);wrapper.vm.selectEdge(wrapper.vm.dag.edges[0]);wrapper.vm.deleteSelection();expect(wrapper.vm.dag.edges).toHaveLength(1);expect(wrapper.vm.dag.edges[0].label).toBe('N');wrapper.unmount();});
  it('rejects a cycle with a visible message and deletes attached edges with a node',()=>{const wrapper=shallowMount(PowerWorkflow,{props:{nodes,edges:[]},global:globals()});wrapper.vm.connect('1','2');wrapper.vm.connect('2','3');wrapper.vm.connect('3','1');expect(wrapper.vm.$message.warning).toHaveBeenCalledWith('message.workflowInvalidEdge');expect(wrapper.vm.dag.edges).toHaveLength(2);wrapper.vm.selectNode(wrapper.vm.dag.nodes[1]);wrapper.vm.deleteSelection();expect(wrapper.vm.dag.edges).toHaveLength(0);expect(wrapper.vm.dag.nodes.map(n=>n.id)).toEqual(['1','3']);wrapper.unmount();});
  it('protects view mode and text entry from deletion, and clamps zoom',()=>{const wrapper=shallowMount(PowerWorkflow,{props:{nodes,edges:[],mode:'view'},global:globals()});wrapper.vm.selectNode(wrapper.vm.dag.nodes[0]);wrapper.vm.deleteSelection();expect(wrapper.vm.dag.nodes).toHaveLength(3);wrapper.vm.setZoom(100);expect(wrapper.vm.zoom).toBe(2);wrapper.vm.setZoom(-1);expect(wrapper.vm.zoom).toBe(.25);wrapper.vm.onKeydown({key:'Delete',target:{tagName:'INPUT'}});expect(wrapper.vm.dag.nodes).toHaveLength(3);wrapper.unmount();});
  it('drags node coordinates and pans independently of graph state',()=>{const wrapper=shallowMount(PowerWorkflow,{props:{nodes,edges:[]},global:globals()});wrapper.vm.$refs.svg.getBoundingClientRect=()=>({left:0,top:0,width:900,height:600});wrapper.vm.size={width:900,height:600};wrapper.vm.zoom=1;wrapper.vm.pan={x:0,y:0};const node=wrapper.vm.dag.nodes[0];wrapper.vm.startNodeDrag({button:0,clientX:node.x,clientY:node.y,pointerId:1},node);wrapper.vm.movePointer({clientX:250,clientY:300});expect(node).toMatchObject({x:250,y:300});wrapper.vm.endPointer({clientX:250,clientY:300});wrapper.vm.startPan({button:0,clientX:10,clientY:20,pointerId:2});wrapper.vm.movePointer({clientX:40,clientY:60});expect(wrapper.vm.pan).toEqual({x:30,y:40});wrapper.unmount();});
  it('fits every column after opening a detail pane, deferring a resize during drag',()=>{const wrapper=shallowMount(PowerWorkflow,{props:{nodes,edges:[{from:'1',to:'2'},{from:'2',to:'3',property:'true'}]},global:globals()});const initial=wrapper.vm.dag.nodes.map(node=>({x:node.x,y:node.y}));wrapper.vm.$refs.canvasContainer.getBoundingClientRect=()=>({width:600,height:600});const fit=vi.spyOn(wrapper.vm,'fitView');wrapper.vm.gesture={type:'node'};wrapper.vm.resize();expect(fit).not.toHaveBeenCalled();expect(wrapper.vm.fitAfterGesture).toBe(true);wrapper.vm.endPointer({});expect(fit).toHaveBeenCalledTimes(1);expect(wrapper.vm.dag.nodes.map(node=>({x:node.x,y:node.y}))).toEqual(initial);const rightmost=Math.max(...wrapper.vm.dag.nodes.map(node=>node.x))+122;expect(rightmost*wrapper.vm.zoom+wrapper.vm.pan.x).toBeLessThan(600);wrapper.unmount();});
  it('keeps node positions while refreshing statuses and cleans its observer',async()=>{const disconnect=vi.fn();vi.stubGlobal('ResizeObserver',class{observe(){}disconnect(){disconnect();}});const wrapper=shallowMount(PowerWorkflow,{props:{nodes,edges:[]},global:globals()});wrapper.vm.dag.nodes[0].x=777;await wrapper.setProps({nodes:nodes.map(node=>({...node,status:5}))});expect(wrapper.vm.dag.nodes[0]).toMatchObject({x:777,status:5});wrapper.unmount();expect(disconnect).toHaveBeenCalledTimes(1);});
});
describe('instance details regression',()=>{
  it('ignores old log responses after switching instances and closes polling without stale writes',async()=>{vi.useFakeTimers();let finishOld;const axios={post:vi.fn().mockResolvedValue({status:3}),get:vi.fn().mockReturnValueOnce(new Promise(resolve=>{finishOld=resolve;})).mockResolvedValue({data:'new instance log',totalPages:1})};const wrapper=shallowMount(InstanceDetail,{props:{instanceId:'1'},global:globals(axios)});await flushPromises();wrapper.vm.activeTab='log';const pending=wrapper.vm.fetchLog();wrapper.vm.autoRefresh=true;await wrapper.setProps({instanceId:'2'});await flushPromises();expect(wrapper.vm.log.data).toBe('new instance log');finishOld({data:'old instance log',totalPages:9});await pending;expect(wrapper.vm.log.data).toBe('new instance log');const requests=axios.get.mock.calls.length;wrapper.unmount();await vi.advanceTimersByTimeAsync(15000);expect(axios.get).toHaveBeenCalledTimes(requests);vi.useRealTimers();});
  it('fetches ordinary instances with null node details and refreshes the request ID after selection changes',async()=>{const axios={post:vi.fn().mockResolvedValue({status:5,result:'ok'}),get:vi.fn()};const wrapper=shallowMount(InstanceDetail,{props:{instanceId:'9223372036854775806',nodeDetail:null},global:globals(axios)});await flushPromises();expect(axios.post).toHaveBeenLastCalledWith('/instance/detailPlus',expect.objectContaining({instanceId:'9223372036854775806'}));await wrapper.setProps({instanceId:'2'});await flushPromises();expect(axios.post).toHaveBeenLastCalledWith('/instance/detailPlus',expect.objectContaining({instanceId:'2'}));wrapper.unmount();});
  it('does not request missing instances or treat a nested workflow as an ordinary job',async()=>{const axios={post:vi.fn(),get:vi.fn()};const wrapper=shallowMount(InstanceDetail,{props:{nodeDetail:{nodeType:2,nodeParams:'true'}},global:globals(axios)});await flushPromises();expect(axios.post).not.toHaveBeenCalled();await wrapper.setProps({nodeDetail:{nodeType:3,instanceId:'999'}});wrapper.vm.handleToDetail();expect(wrapper.vm.$router.push).toHaveBeenCalledWith({name:'WorkflowInstanceDetail',query:{wfInstanceId:'999'}});wrapper.unmount();});
  it('keeps MR query controls when a changed query returns no rows',async()=>{const axios={post:vi.fn().mockResolvedValue({queriedTaskDetailInfoList:[]}),get:vi.fn()};const wrapper=shallowMount(InstanceDetail,{props:{instanceId:'1'},global:globals(axios)});await flushPromises();expect(wrapper.vm.showQueriedTaskDetailInfoList).toBe(true);wrapper.vm.customQuery="task_name = 'missing'";await wrapper.vm.fetchInstanceDetail();expect(axios.post).toHaveBeenLastCalledWith('/instance/detailPlus',{instanceId:'1',customQuery:"task_name = 'missing'"});expect(wrapper.vm.showQueriedTaskDetailInfoList).toBe(true);wrapper.unmount();});
  it('ignores an older response after the user selects another instance',async()=>{let resolveOld;const old=new Promise(resolve=>{resolveOld=resolve;});const axios={post:vi.fn().mockReturnValueOnce(old).mockResolvedValueOnce({result:'new'}),get:vi.fn()};const wrapper=shallowMount(InstanceDetail,{props:{instanceId:'1'},global:globals(axios)});await wrapper.setProps({instanceId:'2'});await flushPromises();resolveOld({result:'old'});await flushPromises();expect(wrapper.vm.instanceDetail.result).toBe('new');wrapper.unmount();});
  it('uses zero-based log pagination and stops auto-refresh after unmount',async()=>{vi.useFakeTimers();const axios={post:vi.fn().mockResolvedValue({status:3}),get:vi.fn().mockResolvedValue({data:'line',totalPages:3})};const wrapper=shallowMount(InstanceDetail,{props:{instanceId:'9'},global:globals(axios)});await flushPromises();wrapper.vm.activeTab='log';wrapper.vm.changeLogPage(2);await flushPromises();expect(axios.get).toHaveBeenLastCalledWith('/instance/log',{params:expect.objectContaining({instanceId:'9',index:1})});wrapper.vm.autoRefresh=true;await nextTick();await vi.advanceTimersByTimeAsync(5000);expect(axios.get).toHaveBeenCalledTimes(2);wrapper.unmount();await vi.advanceTimersByTimeAsync(5000);expect(axios.get).toHaveBeenCalledTimes(2);vi.useRealTimers();});
});
describe('workflow instance operations',()=>{
  it('keeps the new workflow instance open when an older initial detail request rejects',async()=>{let rejectOld;const route={query:{wfInstanceId:'1'},params:{}};const axios={get:vi.fn().mockReturnValueOnce(new Promise((resolve,reject)=>{rejectOld=reject;})).mockResolvedValue({wfInstanceId:'2',peworkflowDAG:{nodes:[],edges:[]}})};const wrapper=shallowMount(WorkflowInstanceDetail,{global:globals(axios,route)});route.query.wfInstanceId='2';await wrapper.vm.fetchWfInstanceInfo();rejectOld(new Error('Old request network failure'));await flushPromises();expect(wrapper.vm.wfInstanceDetail.wfInstanceId).toBe('2');expect(wrapper.vm.$router.replace).not.toHaveBeenCalled();wrapper.unmount();});
  it('cancels a stop confirmation after switching workflow instance IDs',async()=>{let confirm;const route={query:{wfInstanceId:'1'},params:{}};const axios={get:vi.fn().mockResolvedValue({peworkflowDAG:{nodes:[],edges:[]}})};const global=globals(axios,route);global.mocks.$confirm=vi.fn(()=>new Promise(resolve=>{confirm=resolve;}));const wrapper=shallowMount(WorkflowInstanceDetail,{global});await flushPromises();const stopping=wrapper.vm.stop();route.query.wfInstanceId='2';wrapper.vm.$options.watch.wfInstanceId.call(wrapper.vm);await flushPromises();confirm('confirm');await stopping;expect(axios.get.mock.calls.filter(([url])=>url==='/wfInstance/stop')).toEqual([]);expect(wrapper.vm.$message.success).not.toHaveBeenCalled();wrapper.unmount();});
  it('cancels a pending stop after unmount but permits ordinary refreshes of the same instance',async()=>{let confirm;const axios={get:vi.fn().mockResolvedValue({peworkflowDAG:{nodes:[],edges:[]}})};const global=globals(axios,{query:{wfInstanceId:'1'},params:{}});global.mocks.$confirm=vi.fn(()=>new Promise(resolve=>{confirm=resolve;}));const wrapper=shallowMount(WorkflowInstanceDetail,{global});await flushPromises();let stopping=wrapper.vm.stop();await wrapper.vm.fetchWfInstanceInfo();confirm('confirm');await stopping;expect(axios.get.mock.calls.filter(([url])=>url==='/wfInstance/stop')).toHaveLength(1);axios.get.mockClear();stopping=wrapper.vm.stop();wrapper.unmount();confirm('confirm');await stopping;expect(axios.get.mock.calls.filter(([url])=>url==='/wfInstance/stop')).toEqual([]);});
  it('still redirects after a current initial workflow instance request rejects',async()=>{const axios={get:vi.fn().mockRejectedValue(new Error('Current missing instance'))};const wrapper=shallowMount(WorkflowInstanceDetail,{global:globals(axios,{query:{wfInstanceId:'1'},params:{}})});await flushPromises();expect(wrapper.vm.$router.replace).toHaveBeenCalledWith('/oms/wfinstance');wrapper.unmount();});
  it('ignores an older workflow detail after ID switching and disposes its auto-refresh timer',async()=>{vi.useFakeTimers();let finishOld;const route={query:{wfInstanceId:'1'},params:{}};const axios={get:vi.fn().mockReturnValueOnce(new Promise(resolve=>{finishOld=resolve;})).mockResolvedValue({wfInstanceId:'2',workflowName:'new',peworkflowDAG:{nodes:[],edges:[]}})};const wrapper=shallowMount(WorkflowInstanceDetail,{global:globals(axios,route)});route.query.wfInstanceId='2';await wrapper.vm.fetchWfInstanceInfo();await flushPromises();finishOld({wfInstanceId:'1',workflowName:'old',peworkflowDAG:{nodes:[],edges:[]}});await flushPromises();expect(wrapper.vm.wfInstanceDetail.wfInstanceId).toBe('2');wrapper.vm.autoRefresh=true;await nextTick();const requests=axios.get.mock.calls.length;wrapper.unmount();await vi.advanceTimersByTimeAsync(15000);expect(axios.get).toHaveBeenCalledTimes(requests);vi.useRealTimers();});
  it('restores a copied deep link and handles malformed context',async()=>{const axios={get:vi.fn().mockResolvedValue({wfInstanceId:'9223372036854775806',wfContext:'{broken',peworkflowDAG:{nodes:[],edges:[]}})};const wrapper=shallowMount(WorkflowInstanceDetail,{global:globals(axios,{query:{wfInstanceId:'9223372036854775806'},params:{}})});await flushPromises();expect(axios.get).toHaveBeenCalledWith('/wfInstance/info',{params:expect.objectContaining({wfInstanceId:'9223372036854775806'})});expect(wrapper.vm.formattedContext).toBe('{broken');wrapper.unmount();});
  it('marks only a failed node, retries and stops with the original Server API contract',async()=>{const axios={get:vi.fn().mockResolvedValue({peworkflowDAG:{nodes:[],edges:[]}})};const wrapper=shallowMount(WorkflowInstanceDetail,{global:globals(axios,{query:{wfInstanceId:'7'},params:{}})});await flushPromises();wrapper.vm.selectedModel={id:'8',status:5};wrapper.vm.markedSuccess();expect(axios.get).not.toHaveBeenCalledWith('/wfInstance/markNodeAsSuccess',expect.anything());wrapper.vm.selectedModel={id:'8',status:4};wrapper.vm.markedSuccess();await flushPromises();expect(axios.get).toHaveBeenCalledWith('/wfInstance/markNodeAsSuccess',{params:expect.objectContaining({wfInstanceId:'7',nodeId:'8'})});wrapper.vm.restart();await flushPromises();wrapper.vm.stop();await flushPromises();expect(axios.get).toHaveBeenCalledWith('/wfInstance/retry',expect.anything());expect(axios.get).toHaveBeenCalledWith('/wfInstance/stop',expect.anything());wrapper.unmount();});
});
describe('workflow editor persisted nodes and metadata',()=>{
  it('keeps the new workflow editor open when an older initial fetch rejects',async()=>{let rejectOld;const route={query:{workflowId:'1'},params:{}};const axios={get:vi.fn((url,config)=>url==='/user/list'?Promise.resolve([]):config.params.workflowId==='1'?new Promise((resolve,reject)=>{rejectOld=reject;}):Promise.resolve({id:'2',wfName:'New workflow',peworkflowDAG:{nodes:[],edges:[]}}))};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios,route)});route.query.workflowId='2';await wrapper.vm.restoreWorkflow();rejectOld(new Error('Old request network failure'));await flushPromises();expect(wrapper.vm.workflowInfo.id).toBe('2');expect(wrapper.vm.$router.replace).not.toHaveBeenCalled();wrapper.unmount();});
  it('forwards unknown fields already returned by a future Server while changing only the name',async()=>{const future={format:'vNext',largeId:'9223372036854775806',explicitNull:null,nested:{threshold:0}};const axios={get:vi.fn(url=>Promise.resolve(url==='/user/list'?[]:{id:'9',wfName:'old',wfDescription:null,enable:false,notifyUserIds:[],lifeCycle:{start:null,end:200},futureMetadata:future,peworkflowDAG:{nodes:[{nodeId:'1',nodeType:1}],edges:[]}})),post:vi.fn().mockResolvedValue('9')};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios,{query:{workflowId:'9'},params:{}})});await flushPromises();wrapper.vm.powerFlow={graph:{save:()=>({nodes:[{id:'1',nodeType:1}],edges:[]})}};wrapper.vm.workflowInfo.wfName='new';await wrapper.vm.saveWorkflow();expect(axios.post).toHaveBeenLastCalledWith('/workflow/save',expect.objectContaining({id:'9',wfName:'new',wfDescription:null,enable:false,notifyUserIds:[],lifeCycle:{start:null,end:200},futureMetadata:future}));wrapper.unmount();});
  it('does not apply a delayed node save result to a selected node in another workflow',async()=>{let finishSave;const axios={get:vi.fn().mockResolvedValue([]),post:vi.fn(()=>new Promise(resolve=>{finishSave=resolve;}))};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios)});await flushPromises();const graph={updateItem:vi.fn()};wrapper.vm.powerFlow={graph};wrapper.vm.nodeInfo={id:'9',type:1,nodeParams:'old'};const saving=wrapper.vm.handleNodeSave();wrapper.vm.fetchSequence++;wrapper.vm.nodeInfo={id:'10',type:1,nodeParams:'new'};wrapper.vm.pendingNodes={'10':{id:'10',nodeParams:'new'}};finishSave([{id:'9',type:1,nodeParams:'old'}]);await saving;expect(graph.updateItem).not.toHaveBeenCalled();expect(wrapper.vm.pendingNodes['10'].nodeParams).toBe('new');expect(wrapper.vm.nodeSaveLoading).toBe(false);wrapper.unmount();});
  it('does not serialize an old graph into a new workflow while a node save is pending',async()=>{let completeNodeSave;const route={query:{workflowId:'9'},params:{}};const axios={get:vi.fn((url,config)=>Promise.resolve(url==='/user/list'?[]:{id:config.params.workflowId,wfName:`wf-${config.params.workflowId}`,peworkflowDAG:{nodes:[{nodeId:config.params.workflowId,nodeType:1}],edges:[]}})),post:vi.fn(url=>url==='/workflow/saveNode'?new Promise(resolve=>{completeNodeSave=resolve;}):Promise.resolve('10'))};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios,route)});await flushPromises();wrapper.vm.powerFlow={graph:{save:()=>({nodes:[{id:'9',nodeType:1}],edges:[]}),layout:vi.fn()}};wrapper.vm.pendingNodes={'9':{id:'9',type:1,nodeParams:'old draft'}};const saving=wrapper.vm.saveWorkflow();route.query.workflowId='10';await wrapper.vm.restoreWorkflow();wrapper.vm.pendingNodes={'10':{id:'10',type:1,nodeParams:'new draft'}};completeNodeSave([]);await saving;expect(axios.post).not.toHaveBeenCalledWith('/workflow/save',expect.anything());expect(wrapper.vm.workflowInfo.id).toBe('10');expect(wrapper.vm.pendingNodes['10'].nodeParams).toBe('new draft');expect(wrapper.vm.$router.replace).not.toHaveBeenCalled();wrapper.unmount();});
  it('clears the existing identity, metadata and dirty graph when navigating to a new draft without an ID',async()=>{const route={query:{workflowId:'9'},params:{}};const axios={get:vi.fn(url=>Promise.resolve(url==='/user/list'?[]:{id:'9',wfName:'old',lifeCycle:{end:200},notifyUserIds:['19'],peworkflowDAG:{nodes,edges:[]}})),post:vi.fn()};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios,route)});await flushPromises();wrapper.vm.pendingNodes={'1':{id:'1',nodeParams:'dirty'}};wrapper.vm.nodeInfo={id:'1'};wrapper.vm.workflowInfo.futureField='old';const previousGeneration=wrapper.vm.fetchSequence;route.query.workflowId=undefined;wrapper.vm.$options.watch['$route.query.workflowId'].call(wrapper.vm,undefined);await nextTick();expect(wrapper.vm.workflowInfo).toMatchObject({id:'',wfName:'',lifeCycle:null,notifyUserIds:[],timeExpressionType:'API'});expect(wrapper.vm.workflowInfo.futureField).toBeUndefined();expect(wrapper.vm.peworkflowDAG).toEqual({nodes:[],edges:[]});expect(wrapper.vm.pendingNodes).toEqual({});expect(wrapper.vm.nodeInfo).toBeNull();expect(wrapper.vm.fetchSequence).toBeGreaterThan(previousGeneration);expect(axios.get.mock.calls.filter(([url])=>url==='/workflow/fetch')).toHaveLength(1);wrapper.unmount();});
  it.each([{start:200,end:100},{start:'invalid',end:null}])('rejects invalid lifecycle bounds before any node or graph write: %j',async lifeCycle=>{const axios={get:vi.fn().mockResolvedValue([]),post:vi.fn()};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios)});await flushPromises();wrapper.vm.workflowInfo.wfName='Name';wrapper.vm.workflowInfo.lifeCycle=lifeCycle;wrapper.vm.pendingNodes={'1':{id:'1',type:1,nodeParams:'draft'}};wrapper.vm.powerFlow={graph:{save:()=>({nodes:[{id:'1',nodeType:1}],edges:[]})}};await wrapper.vm.saveWorkflow();expect(axios.post).not.toHaveBeenCalled();expect(wrapper.vm.$message.warning).toHaveBeenCalledWith('message.lifeCycleInvalid');expect(wrapper.vm.pendingNodes['1'].nodeParams).toBe('draft');wrapper.unmount();});
  it('loads an existing workflow after a refresh and retains life cycle and notification IDs',async()=>{const axios={get:vi.fn(url=>Promise.resolve(url==='/user/list'?[]:{id:'9',wfName:'wf',lifeCycle:{start:100,end:200},notifyUserIds:['19'],peworkflowDAG:{nodes,edges:[]}})),post:vi.fn()};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios,{query:{workflowId:'9'},params:{}})});await flushPromises();expect(axios.get).toHaveBeenCalledWith('/workflow/fetch',{params:expect.objectContaining({workflowId:'9'})});expect(wrapper.vm.workflowInfo.lifeCycle).toEqual({start:100,end:200});expect(wrapper.vm.workflowInfo.notifyUserIds).toEqual(['19']);wrapper.unmount();});
  it('saves all dirty node forms before serializing the graph and persists the ID in the URL',async()=>{const axios={get:vi.fn().mockResolvedValue([]),post:vi.fn(url=>Promise.resolve(url==='/workflow/save'?'999':[]))};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios)});await flushPromises();wrapper.vm.powerFlow={graph:{save:()=>({nodes:[{id:'1',nodeType:2},{id:'2',nodeType:1},{id:'3',nodeType:1}],edges:[{source:'1',target:'2',label:'Y'},{source:'1',target:'3',label:'N'}]})}};wrapper.vm.workflowInfo.wfName='Name';wrapper.vm.workflowInfo.lifeCycle={start:'100',end:'200'};wrapper.vm.pendingNodes={'1':{id:'1',type:2,nodeParams:'true'}};await wrapper.vm.saveWorkflow();expect(axios.post.mock.calls.map(call=>call[0])).toEqual(['/workflow/saveNode','/workflow/save']);expect(axios.post).toHaveBeenLastCalledWith('/workflow/save',expect.objectContaining({dag:{nodes:[{nodeId:'1'},{nodeId:'2'},{nodeId:'3'}],edges:[{from:'1',to:'2',property:'true'},{from:'1',to:'3',property:'false'}]},lifeCycle:{start:100,end:200}}));expect(wrapper.vm.$router.replace).toHaveBeenCalledWith({name:'workflowEditor',query:{workflowId:'999'}});expect(wrapper.vm.saveLoading).toBe(false);wrapper.unmount();});
  it('keeps a one-sided lifecycle and unknown fields when saving existing metadata',async()=>{const axios={get:vi.fn().mockResolvedValue([]),post:vi.fn().mockResolvedValue('9')};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios)});await flushPromises();wrapper.vm.powerFlow={graph:{save:()=>({nodes:[{id:'1',nodeType:1}],edges:[]})}};wrapper.vm.workflowInfo.wfName='Name';wrapper.vm.workflowInfo.lifeCycle={start:null,end:'1800000000000',future:'kept'};await wrapper.vm.saveWorkflow();expect(axios.post).toHaveBeenLastCalledWith('/workflow/save',expect.objectContaining({lifeCycle:{start:null,end:1800000000000,future:'kept'}}));wrapper.vm.workflowInfo.lifeCycle=null;await wrapper.vm.saveWorkflow();expect(axios.post).toHaveBeenLastCalledWith('/workflow/save',expect.objectContaining({lifeCycle:{start:null,end:null}}));wrapper.unmount();});
  it('blocks incomplete condition graphs before persisting dirty nodes',async()=>{const axios={get:vi.fn().mockResolvedValue([]),post:vi.fn()};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios)});await flushPromises();wrapper.vm.workflowInfo.wfName='Name';wrapper.vm.powerFlow={graph:{save:()=>({nodes:[{id:'1',nodeType:2}],edges:[]})}};wrapper.vm.pendingNodes={'1':{id:'1',type:2,nodeParams:'true'}};await wrapper.vm.saveWorkflow();expect(axios.post).not.toHaveBeenCalled();expect(wrapper.vm.$message.warning).toHaveBeenCalledWith('message.workflowIncompleteCondition');wrapper.unmount();});
  it('resets loading after a rejected save and keeps unsaved node changes for retry',async()=>{const axios={get:vi.fn().mockResolvedValue([]),post:vi.fn().mockRejectedValue(new Error('failed'))};const wrapper=shallowMount(WorkflowEditor,{global:globals(axios)});await flushPromises();wrapper.vm.workflowInfo.wfName='Name';wrapper.vm.powerFlow={graph:{save:()=>({nodes:[{id:'1',nodeType:1}],edges:[]})}};wrapper.vm.pendingNodes={'1':{id:'1',type:2,nodeParams:'true'}};await expect(wrapper.vm.saveWorkflow()).resolves.toBeUndefined();expect(wrapper.vm.saveLoading).toBe(false);expect(wrapper.vm.pendingNodes['1']).toBeTruthy();axios.post.mockImplementation(url=>Promise.resolve(url==='/workflow/save'?'99':[]));await wrapper.vm.saveWorkflow();expect(axios.post).toHaveBeenLastCalledWith('/workflow/save',expect.objectContaining({wfName:'Name',dag:{nodes:[{nodeId:'1'}],edges:[]}}));expect(wrapper.vm.pendingNodes).toEqual({});expect(wrapper.vm.workflowInfo.id).toBe('99');expect(wrapper.vm.$router.replace).toHaveBeenCalledWith({name:'workflowEditor',query:{workflowId:'99'}});wrapper.unmount();});
});
