import { describe, it, expect } from 'vitest';
import { normalizeDag, canConnect, layoutDag, removeNode, serializeDag, formatContext, instanceRequest, validateDag } from '../src/components/dag/workflow-model.js';
import { readLogBlob } from '../src/components/dag/instance-log.js';
const nodes = normalizeDag([{ nodeId:'9223372036854775806', nodeType:1 },{ nodeId:'2',nodeType:2 },{ nodeId:'3',nodeType:3 },{ nodeId:'4',nodeType:1 }]).nodes;
describe('Server-compatible workflow DAG', () => {
  it('preserves 64-bit decimal IDs and normalizes fetched and imported types', () => { const dag = normalizeDag([{id:'9223372036854775806',type:'3'}],[{from:'9223372036854775806',to:'2',property:'false',enable:false}]); expect(dag.nodes[0]).toMatchObject({id:'9223372036854775806',nodeId:'9223372036854775806',nodeType:3}); expect(dag.edges[0]).toMatchObject({source:'9223372036854775806',target:'2',label:'N',enable:false}); expect(serializeDag(dag)).toEqual({nodes:[{nodeId:'9223372036854775806'}],edges:[{from:'9223372036854775806',to:'2',property:'false'}]}); });
  it('accepts empty and null historical graphs', () => { expect(normalizeDag(null,null)).toEqual({nodes:[],edges:[]}); expect(layoutDag([],[])).toEqual([]); });
  it('allows many ordinary successors without creating branches', () => { expect(canConnect(nodes,[],'9223372036854775806','2','Y')).toEqual({valid:true,label:''}); expect(canConnect(nodes,[{source:'9223372036854775806',target:'2'}],'9223372036854775806','3')).toEqual({valid:true,label:''}); });
  it('rejects self links, duplicates, missing nodes, and direct/transitive cycles', () => { const edges = [{source:'9223372036854775806',target:'2'},{source:'2',target:'3'}]; for (const [source,target] of [['2','2'],['2','3'],['3','9223372036854775806'],['3','2'],['missing','3'],['3','missing']]) expect(canConnect(nodes,edges,source,target)).toMatchObject({valid:false,reason:'workflowInvalidEdge'}); });
  it('assigns Y then N for condition branches, including restoring a deleted branch', () => { expect(canConnect(nodes,[],'2','3')).toEqual({valid:true,label:'Y'}); expect(canConnect(nodes,[{source:'2',target:'3',label:'Y'}],'2','4')).toEqual({valid:true,label:'N'}); expect(canConnect(nodes,[{source:'2',target:'3',label:'N'}],'2','4')).toEqual({valid:true,label:'Y'}); });
  it('rejects repeated condition polarity and a third successor', () => { expect(canConnect(nodes,[{source:'2',target:'3',label:'Y'}],'2','4','Y')).toMatchObject({valid:false,reason:'workflowConditionLimit'}); expect(canConnect(nodes,[{source:'2',target:'3',label:'Y'},{source:'2',target:'4',label:'N'}],'2','9223372036854775806')).toMatchObject({valid:false,reason:'workflowConditionLimit'}); });
  it('deletes every attached edge with a removed node and retains other edges', () => { const dag = {nodes,edges:[{source:'9223372036854775806',target:'2'},{source:'2',target:'3'},{source:'3',target:'4'}]}; const removed = removeNode(dag,'2'); expect(removed.nodes.map(n=>n.id)).not.toContain('2'); expect(removed.edges).toEqual([{source:'3',target:'4'}]); expect(dag.nodes).toHaveLength(4); });
  it('lays out branching and disconnected components deterministically without changing metadata', () => { const edges = [{source:'9223372036854775806',target:'2'},{source:'2',target:'3'},{source:'2',target:'4'}]; const result = layoutDag(nodes,edges); expect(result[0].x).toBeLessThan(result[1].x); expect(result[1].x).toBeLessThan(result[2].x); expect(result[2].x).toEqual(result[3].x); expect(result[2].y).not.toEqual(result[3].y); expect(layoutDag(nodes,edges)).toEqual(result); expect(result[0].id).toBe('9223372036854775806'); });
  it('requires both condition branches before save and accepts independent ordinary roots', () => { expect(validateDag({nodes,edges:[]})).toMatchObject({valid:false,reason:'workflowIncompleteCondition'}); expect(validateDag({nodes,edges:[{source:'2',target:'3',label:'Y'},{source:'2',target:'4',label:'N'}]})).toEqual({valid:true}); expect(validateDag({nodes:[],edges:[]})).toMatchObject({valid:false}); expect(validateDag({nodes:[nodes[0],nodes[0]],edges:[]})).toMatchObject({valid:false}); });
  it('renders structured and malformed workflow contexts without throwing', () => { expect(formatContext('{"x":1}')).toBe('{\n  "x": 1\n}'); expect(formatContext('{bad')).toBe('{bad'); expect(formatContext(null)).toBe(''); expect(formatContext({a:1})).toContain('"a": 1'); });
  it('guards ordinary-instance null node details and updates the instance ID per request', () => { expect(instanceRequest(undefined,'x')).toBeNull(); expect(instanceRequest('','x')).toBeNull(); expect(instanceRequest('9223372036854775806','status in (5, 6)')).toEqual({instanceId:'9223372036854775806',customQuery:'status in (5, 6)'}); });
});
describe('workflow node log downloads', () => {
  it('allows archived binary logs and preserves bytes', async () => { const data = new Blob(['hello\n中文'],{type:'application/octet-stream'}); expect(await readLogBlob({data,headers:{}})).toBe(data); });
  it('rejects business errors and unexpected documents before creating a download', async () => { await expect(readLogBlob({data:new Blob(['{"success":false,"message":"log expired"}'],{type:'application/json'}),headers:{}})).rejects.toThrow('log expired'); await expect(readLogBlob({data:new Blob(['<html>'],{type:'text/html'}),headers:{}})).rejects.toThrow('Unexpected log download response'); });
});
