import { test, expect, selectors, fill, choose, enterSamples, login, clickAndResponse, observation, ownedName, id, type RecordDTO, type PageDTO } from './helpers'
import { AdminFixtures } from './admin-fixtures'

test('admin namespace selection · edited namespace options and two owned application filters retain exact namespace associations', async ({ page, backend }, info) => {
  page.setDefaultTimeout(15_000); const fixtures = new AdminFixtures(backend)
  try { const first = await fixtures.space('filter_after_edit_one'); const second = await fixtures.space('filter_after_edit_two'); const one = await fixtures.app('namespace_filter_one', id(first.id)); const two = await fixtures.app('namespace_filter_two', id(second.id)); await page.goto('/#/admin/namespace'); await page.reload(); await fill(page, 'Code', String(first.code)); await clickAndResponse(page, '/namespace/list', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => response.request().postDataJSON()?.codeLike === first.code); await selectors.row(page, String(first.code)).getByRole('button', { name: 'Edit', exact: true }).click(); const dialog = selectors.dialog(page, 'Edit namespace'); const changed = ownedName('namespace_option_edited'); await fill(dialog, 'Name', changed); const saved = await clickAndResponse(page, '/namespace/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(saved.success).toBe(true); const independent = (await backend.call<PageDTO<RecordDTO>>('/namespace/list', { method: 'POST', data: { codeLike: first.code, index: 0, pageSize: 10 } })).data[0]; expect(independent.name).toBe(changed)
    await page.goto('/#/admin/app'); for (const [space, label, app] of [[first, changed, one], [second, second.name, two]] as const) { await choose(page, 'Namespace', String(label) + '(' + String(space.code) + ')'); const filtered = await clickAndResponse<PageDTO<RecordDTO>>(page, '/appInfo/list', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => String(response.request().postDataJSON()?.namespaceId) === id(space.id)); expect(filtered.success).toBe(true); expect(Number(filtered.data.totalItems)).toBe(1); expect(filtered.data.data.map(row => id(row.id))).toEqual([id(app.id)]); expect(filtered.data.data[0].namespaceName).toBe(label); await expect(selectors.row(page, String(app.appName))).toHaveCount(1); const reset = await clickAndResponse(page, '/appInfo/list', () => page.getByRole('button', { name: 'Reset', exact: true }).click(), response => !response.request().postDataJSON()?.namespaceId); expect(reset.success).toBe(true); await expect(page.getByLabel('Namespace', { exact: true }).filter({ visible: true })).toHaveValue('') }
    await observation(info, 'UI-006', 'namespace-app-filter', { namespaceIDs: [id(first.id), id(second.id)], applicationIDs: [id(one.id), id(two.id)], actualNamespaceNameEditAndIndependentReadback: true, actualUpdatedOptionSelectedAndBothFilteredOriginalResponsesMatchExactAssociations: true, normalCurrentGlobalAdministratorPermission: true })
  } finally { await fixtures.cleanup(info) }
})

test('admin network list · real offline query reports failure, retains selected context and online Retry applies current filter', async ({ page, backend: _backend, credentials }, info) => {
  page.setDefaultTimeout(15_000); await enterSamples(page, credentials); await page.goto('/#/admin/app'); await fill(page, 'Application ID', String(credentials.app_id)); const initial = await clickAndResponse<PageDTO<RecordDTO>>(page, '/appInfo/list', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => String(response.request().postDataJSON()?.appId) === String(credentials.app_id)); expect(initial.success).toBe(true); await expect(selectors.row(page, credentials.app_name)).toHaveCount(1); const before = await page.evaluate(() => ({ jwt: localStorage.getItem('PowerJwt'), app: localStorage.getItem('Power_appId') })); const missing = ownedName('missing_after_network'); await fill(page, 'Application ID', ''); await fill(page, 'Application name', missing)
  try { await page.context().setOffline(true); await page.getByRole('button', { name: 'Query', exact: true }).click(); await expect(page.locator('.error-banner[role=alert]')).toBeVisible(); await expect(page.getByRole('button', { name: 'Retry', exact: true })).toBeEnabled(); expect(await page.evaluate(() => ({ jwt: localStorage.getItem('PowerJwt'), app: localStorage.getItem('Power_appId') }))).toEqual(before); await expect(page.getByLabel('Application name', { exact: true }).filter({ visible: true })).toHaveValue(missing); await page.context().setOffline(false); const recovered = await clickAndResponse<PageDTO<RecordDTO>>(page, '/appInfo/list', () => page.getByRole('button', { name: 'Retry', exact: true }).click(), response => response.request().postDataJSON()?.appNameLike === missing); expect(recovered.success).toBe(true); expect(recovered.data.data).toHaveLength(0); await expect(page.locator('.data-table tbody tr')).toHaveCount(0); await expect(page.locator('.error-banner[role=alert]')).toHaveCount(0); expect(await page.evaluate(() => ({ jwt: localStorage.getItem('PowerJwt'), app: localStorage.getItem('Power_appId') }))).toEqual(before)
    await observation(info, 'UI-030', 'network-list-recovery-partial', { actualBrowserNetworkOfflineAndOnline: true, failedListErrorAndRetryVisible: true, selectedAppAndSessionUnchanged: true, actualRetryOriginalResponseAppliedCurrentFilterAndClearedPriorRows: true, saveRecovery: 'SEPARATE_GREEN_ADMIN_DRAFT_GROUP', businessWrites: 0 })
  } finally { await page.context().setOffline(false) }
})

test('admin profile clearing · formal server cannot clear a contact field, UI reports readback failure and keeps draft until corrected', async ({ page, backend, credentials }, info) => {
  page.setDefaultTimeout(15_000); const fixtures = new AdminFixtures(backend)
  try { const account = await fixtures.user('profile_cannot_clear', { phone: '100800600', email: 'retained@example.invalid' }); await page.getByLabel('Account', { exact: true }).filter({ visible: true }).click(); await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await login(page, { ...credentials, admin_username: account.origin, admin_password: account.password }); await page.goto('/#/admin/personal'); await expect(page.getByLabel('Phone', { exact: true }).filter({ visible: true })).toHaveValue('100800600'); await fill(page, 'Phone', ''); const accepted = await clickAndResponse(page, '/user/modify', () => page.getByRole('button', { name: 'Save profile', exact: true }).click()); expect(accepted.success).toBe(true); await expect(page.locator('.error-banner[role=alert]')).toContainText('cannot clear'); await expect(page.getByRole('status').filter({ hasText: 'Profile saved' })).toHaveCount(0); await expect(page.getByLabel('Phone', { exact: true }).filter({ visible: true })).toHaveValue(''); expect((await account.own.call<RecordDTO>('/user/detail')).phone).toBe('100800600'); await fill(page, 'Phone', '100800700'); const corrected = await clickAndResponse(page, '/user/modify', () => page.getByRole('button', { name: 'Save profile', exact: true }).click()); expect(corrected.success).toBe(true); await expect(page.getByRole('status').filter({ hasText: 'Profile saved' })).toBeVisible(); expect((await account.own.call<RecordDTO>('/user/detail')).phone).toBe('100800700'); await page.reload(); await expect(page.getByLabel('Phone', { exact: true }).filter({ visible: true })).toHaveValue('100800700'); await observation(info, 'UI-008', 'profile-clear-server-contract-extra', { ownedAccountID: account.id, actualModifyAcceptedButOriginalDetailRetainedOldPhone: true, falseSuccessNotShownAndDraftRetained: true, correctedValueActuallySavedAndHardRefreshed: true, serverSourceUnchanged: true })
  } finally { await fixtures.cleanup(info) }
})
