import { test, expect, fill, choose, enterSamples, enterApplication, login, clickAndResponse, observation, id, type ID } from './helpers'
import { AdminFixtures, sameIDs } from './admin-fixtures'
import type { Page } from '@playwright/test'

async function logout(page: Page) { await page.getByLabel('Account', { exact: true }).filter({ visible: true }).click(); await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await expect(page).toHaveURL(/#\/loginHomepage$/) }
async function listAction(page: Page, label: 'Application name' | 'Code' | 'User ID', endpoint: string) { await fill(page, label, ''); const response = await clickAndResponse(page, endpoint, () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => response.request().postDataJSON()?.index == null || response.request().postDataJSON()?.index === 0); expect(response.success).toBe(true); const reset = await clickAndResponse(page, endpoint, () => page.getByRole('button', { name: 'Reset', exact: true }).click()); expect(reset.success).toBe(true) }

test('admin navigation · five actual menus, back/forward, debug aliases, application return and anonymous root/direct route recovery', async ({ page, backend: _backend, credentials }, info) => {
  page.setDefaultTimeout(15_000)
  const menus = [['Apps', '/admin/app', 'Applications'], ['Spaces', '/admin/namespace', 'Namespaces'], ['Users', '/admin/user', 'Users'], ['Profile', '/admin/personal', 'Profile'], ['Settings', '/admin/settings', 'Settings']] as const
  const visited: string[] = []
  for (const [label, route, title] of menus) { await page.locator('aside.rail').getByRole('link', { name: label, exact: true }).click(); await expect(page).toHaveURL(new RegExp('#' + route + '$')); await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible(); if (route === '/admin/app') await listAction(page, 'Application name', '/appInfo/list'); if (route === '/admin/namespace') await listAction(page, 'Code', '/namespace/list'); if (route === '/admin/user') await listAction(page, 'User ID', '/user/query'); if (route === '/admin/personal') { await expect(page.getByLabel('Username', { exact: true }).filter({ visible: true })).toHaveAttribute('readonly', ''); await page.getByRole('button', { name: 'Change password', exact: true }).click(); const dialog = page.getByRole('dialog', { name: 'Change password', exact: true }); await dialog.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(dialog).not.toBeVisible() } if (route === '/admin/settings') { await fill(page, 'Search users', 'No matching synthetic account'); await expect(page.getByText('No matching users', { exact: true })).toBeVisible(); await fill(page, 'Search users', '') } await page.reload(); await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible(); visited.push(route) }
  await page.goto('/#/admin'); await expect(page).toHaveURL(/#\/admin\/app$/); await listAction(page, 'Application name', '/appInfo/list'); await page.reload(); await expect(page.getByRole('heading', { name: 'Applications', exact: true })).toBeVisible(); await page.locator('aside.rail').getByRole('link', { name: 'Apps', exact: true }).click(); await expect(page).toHaveURL(/#\/admin\/app$/); await page.locator('aside.rail').getByRole('link', { name: 'Spaces', exact: true }).click(); await expect(page).toHaveURL(/#\/admin\/namespace$/); await expect(page.getByRole('heading', { name: 'Namespaces', exact: true })).toBeVisible(); await page.locator('aside.rail').getByRole('link', { name: 'Users', exact: true }).click(); await expect(page).toHaveURL(/#\/admin\/user$/); await expect(page.getByRole('heading', { name: 'Users', exact: true })).toBeVisible(); await page.goBack(); await expect(page.getByRole('heading', { name: 'Namespaces', exact: true })).toBeVisible(); await listAction(page, 'Code', '/namespace/list'); await page.goForward(); await expect(page.getByRole('heading', { name: 'Users', exact: true })).toBeVisible(); await listAction(page, 'User ID', '/user/query')
  await enterSamples(page, credentials); await page.getByRole('link', { name: 'Switch application', exact: true }).click(); await expect(page).toHaveURL(/#\/admin\/app$/); await enterApplication(page, credentials.app_name); await expect(page.getByRole('heading', { name: 'Operations overview', exact: true })).toBeVisible(); await page.goto('/#/sidebar'); await expect(page).toHaveURL(/#\/oms\/home$/); await page.reload(); await expect(page.getByRole('heading', { name: 'Operations overview', exact: true })).toBeVisible(); await page.goto('/#/navbar'); await expect(page).toHaveURL(/#\/admin\/app$/); await page.reload(); await expect(page.getByRole('heading', { name: 'Applications', exact: true })).toBeVisible()
  await logout(page); const routes = ['/', '/loginHomepage', '/powerjobLogin'] as const
  for (const route of routes) { await page.goto('/#' + route); await expect(page.getByRole('heading', { name: route === '/powerjobLogin' ? 'Sign in with PowerJob' : 'Sign in to your workspace', exact: true })).toBeVisible(); await page.reload(); await expect(page.getByRole('heading', { name: route === '/powerjobLogin' ? 'Sign in with PowerJob' : 'Sign in to your workspace', exact: true })).toBeVisible(); if (route !== '/powerjobLogin') { await page.getByRole('button', { name: 'PowerJob account', exact: true }).click(); await expect(page).toHaveURL(/#\/powerjobLogin$/); await page.goBack(); await expect(page.getByRole('heading', { name: 'Sign in to your workspace', exact: true })).toBeVisible() } else { await page.getByRole('link', { name: '← Other sign-in methods', exact: true }).click(); await expect(page).toHaveURL(/#\/loginHomepage$/) } }
  await login(page, credentials)
  for (const [caseId, variants] of Object.entries({ 'UI-003': ['history-navigation'], 'UI-029': ['admin-menus', 'app-return-logout', 'debug-routes'], 'UI-040': ['route-root', 'route-loginHomepage', 'route-powerjobLogin', 'route-admin', 'route-admin-app', 'route-admin-namespace', 'route-admin-user', 'route-navbar'] })) for (const variant of variants) await observation(info, caseId, variant, { menusActuallyClicked: visited, actualListQueryAndReset: true, profileDialogOpenedAndCancelledWithoutWrite: true, settingsSearchWithoutWrite: true, nativeBackForwardVerified: true, debugAliasesActualTargetAndHardRefreshVerified: true, anonymousRootDirectRefreshAndBackVerified: true, normalAppReturnReentryAndLogout: true, businessWrites: 0 })
})

test('admin storage · exact legacy session keys restore a new profile and both languages survive actual refresh/new-tab deep links', async ({ page, browser, backend: _backend, credentials }, info) => {
  page.setDefaultTimeout(15_000)
  await enterSamples(page, credentials)
  const legacy = await page.evaluate(() => Object.fromEntries(['PowerJwt', 'Power_appId', 'Power_appName'].map(key => [key, localStorage.getItem(key)])))
  expect(legacy.Power_appId).toBe(String(credentials.app_id)); expect(legacy.Power_appName).toBe(credentials.app_name); expect(Boolean(legacy.PowerJwt)).toBe(true)
  const context = await browser.newContext({ viewport: { width: 1440, height: 900 } }); const restored = await context.newPage(); const errors: string[] = []; restored.on('pageerror', error => errors.push(error.message)); await restored.addInitScript(values => { for (const [key, value] of Object.entries(values)) if (value != null) localStorage.setItem(key, value); localStorage.setItem('oms_lang', 'en') }, legacy)
  try { await restored.goto(new URL('/#/oms/job', page.url()).href); await expect(restored.getByRole('heading', { name: 'Jobs', exact: true })).toBeVisible(); await expect(restored.getByRole('link', { name: 'Switch application', exact: true })).toContainText(credentials.app_name); const response = await clickAndResponse(restored, '/job/list', () => restored.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().headers().appid === String(credentials.app_id)); expect(response.success).toBe(true); await restored.reload(); await expect(restored.getByRole('heading', { name: 'Jobs', exact: true })).toBeVisible(); expect(errors).toEqual([]) } finally { await context.close() }
  for (const [option, title, heading, label] of [['简体中文', '任务', '应用', '语言'], ['English', 'Jobs', 'Applications', 'Language']] as const) { await choose(page, /^(Language|语言)$/, option); await page.reload(); await expect(page.getByRole('heading', { name: option === 'English' ? 'Operations overview' : '运行概览', exact: true })).toBeVisible(); const sibling = await page.context().newPage(); try { await sibling.goto(new URL('/#/oms/job', page.url()).href); await expect(sibling.getByRole('heading', { name: title, exact: true })).toBeVisible(); await expect(sibling.getByLabel(label, { exact: true })).toHaveValue(option === 'English' ? 'en' : 'zh'); await sibling.reload(); await expect(sibling.getByRole('heading', { name: title, exact: true })).toBeVisible(); await sibling.getByRole('link', { name: option === 'English' ? 'Switch application' : '切换应用', exact: true }).click(); await expect(sibling.getByRole('heading', { name: heading, exact: true })).toBeVisible() } finally { await sibling.close() } }
  await observation(info, 'UI-003', 'legacy-storage', { originalConsoleStorageKeys: ['PowerJwt', 'Power_appId', 'Power_appName', 'oms_lang'], tokenFromNormalRealUILogin: true, newBrowserContextRestoredAppAndActualJobRequestHeader: true, actualHardRefresh: true, valuesNeverPublished: true })
  for (const variant of ['chinese-refresh', 'english-refresh']) await observation(info, 'UI-030', variant, { actualLanguageSelectAndRefresh: true, actualNewTabJobDeepLinkAndRefresh: true, localeValueAndHeadingChecked: true, businessWrites: 0 })
})

test('admin settings · own global administrator page add/remove hard-refresh readback preserves every original administrator', async ({ page, backend, credentials }, info) => {
  page.setDefaultTimeout(15_000)
  const fixtures = new AdminFixtures(backend); const original = await backend.call<ID[]>('/auth/listGlobalAdmin'); let ownID = ''
  try { const account = await fixtures.user('settings_fresh'); ownID = account.id; await page.goto('/#/admin/settings'); await page.reload(); await fill(page, 'Search users', account.origin); const option = page.getByRole('checkbox', { name: new RegExp(account.origin) }); await expect(option).toHaveCount(1); await option.check(); const saved = await clickAndResponse(page, '/auth/saveGlobalAdmin', () => page.getByRole('button', { name: 'Save', exact: true }).click()); expect(saved.success).toBe(true); expect(sameIDs(await backend.call<ID[]>('/auth/listGlobalAdmin'), [...original, account.id])).toBe(true); await page.reload(); await fill(page, 'Search users', account.origin); await expect(option).toBeChecked(); await expect(page.locator('.admin-chip').filter({ hasText: account.origin })).toHaveCount(1); await logout(page); await login(page, { ...credentials, admin_username: account.origin, admin_password: account.password }); await page.goto('/#/admin/settings'); const ownSave = await clickAndResponse(page, '/auth/saveGlobalAdmin', () => page.getByRole('button', { name: 'Save', exact: true }).click()); expect(ownSave.success).toBe(true); await page.reload(); await expect(page.locator('.admin-chip').filter({ hasText: account.origin })).toHaveCount(1)
    await logout(page); await login(page, credentials); await page.goto('/#/admin/settings'); await fill(page, 'Search users', account.origin); await option.uncheck(); const removed = await clickAndResponse(page, '/auth/saveGlobalAdmin', () => page.getByRole('button', { name: 'Save', exact: true }).click()); expect(removed.success).toBe(true); await page.reload(); await fill(page, 'Search users', account.origin); await expect(option).not.toBeChecked(); await expect(page.locator('.admin-chip').filter({ hasText: account.origin })).toHaveCount(0); expect(sameIDs(await backend.call<ID[]>('/auth/listGlobalAdmin'), original)).toBe(true)
    for (const variant of ['add-admin', 'remove-admin']) await observation(info, 'UI-009', variant, { ownedAccountID: ownID, actualUIAddRemoveSavesAndHardRefresh: true, ownNewGlobalAdministratorCouldActuallySave: true, everyOriginalAdministratorPreserved: true, finalIndependentSetEqualsOriginal: true })
    await observation(info, 'UI-040', 'route-admin-settings', { actualMenuAndDeepLink: true, realOwnRoleSaveAndHardRefresh: true, returnedAndExitedViaNormalUI: true, originalAdminSetRestored: true })
  } finally { const current = await backend.call<ID[]>('/auth/listGlobalAdmin'); const retained = ownID ? current.filter(value => id(value) !== ownID) : current; if (!sameIDs(retained, original)) throw new Error('Unrelated administrator set changed; refusing restore'); if (!sameIDs(current, original)) await backend.call('/auth/saveGlobalAdmin', { method: 'POST', data: { admin: original } }); await fixtures.cleanup(info) }
})

test('admin session race · actual old-user detail held until fresh account login cannot replace current profile or session', async ({ page, backend, credentials }, info) => {
  page.setDefaultTimeout(15_000)
  const fixtures = new AdminFixtures(backend); let release: (() => void) | undefined
  try { const account = await fixtures.user('session_race'); const oldJWT = await page.evaluate(() => localStorage.getItem('PowerJwt')); expect(Boolean(oldJWT)).toBe(true); let ready!: () => void; const held = new Promise<void>(resolve => { ready = resolve }); const gate = new Promise<void>(resolve => { release = resolve }); let realOldUser = false
    await page.route('**/user/detail', async route => { if (route.request().headers().powerjwt !== oldJWT) { await route.continue(); return } const original = await route.fetch(); const body = await original.json(); realOldUser = body.success === true && body.data?.username === 'PWJB_' + credentials.admin_username; ready(); await gate; await route.fulfill({ response: original }).catch(() => {}) })
    await page.goto('/#/admin/personal'); await held; expect(realOldUser).toBe(true); await expect(page.getByRole('status').filter({ hasText: 'Loading' })).toBeVisible(); await login(page, { ...credentials, admin_username: account.origin, admin_password: account.password }); await page.goto('/#/admin/personal'); await expect(page.getByLabel('Username', { exact: true }).filter({ visible: true })).toHaveValue('PWJB_' + account.origin); const currentJWT = await page.evaluate(() => localStorage.getItem('PowerJwt')); expect(Boolean(currentJWT) && currentJWT !== oldJWT).toBe(true); if (!release) throw new Error('Original user response gate was not initialized'); release(); await page.unroute('**/user/detail'); await expect(page.getByLabel('Username', { exact: true }).filter({ visible: true })).toHaveValue('PWJB_' + account.origin); expect(await page.evaluate(() => localStorage.getItem('PowerJwt')) === currentJWT).toBe(true); await page.reload(); await expect(page.getByLabel('Username', { exact: true }).filter({ visible: true })).toHaveValue('PWJB_' + account.origin); expect(await page.evaluate(() => localStorage.getItem('PowerJwt')) === currentJWT).toBe(true)
    await observation(info, 'UI-038', 'stale-session-response', { ownedNewAccountID: account.id, actualOriginalRootUserDetailBeforeDelay: true, oldResponseReleasedOnlyAfterNewNormalUILoginAndOwnProfileReadback: true, freshSessionAndProfilePreservedBeforeAfterHardRefresh: true, noFabricatedResponseBodyOrAuthResult: true })
  } finally { release?.(); await page.unroute('**/user/detail'); await fixtures.cleanup(info) }
})

test('auth entry · fresh anonymous root matches actual server methods and four legacy language key profiles render their real locale', async ({ page, browser }, info) => {
  page.setDefaultTimeout(15_000)
  const root = await clickAndResponse<{ type: string; name: string }[]>(page, '/auth/supportLoginTypes', () => page.goto('/#/')); expect(root.success).toBe(true); expect(root.data.some(method => method.type === 'PWJB')).toBe(true); for (const method of root.data) await expect(page.getByRole('button', { name: method.type === 'PWJB' ? 'PowerJob account' : method.name, exact: true })).toBeVisible(); expect(await page.evaluate(() => localStorage.getItem('PowerJwt'))).toBeNull(); await page.getByRole('button', { name: 'PowerJob account', exact: true }).click(); await expect(page).toHaveURL(/#\/powerjobLogin$/); await expect(page.getByRole('heading', { name: 'Sign in with PowerJob', exact: true })).toBeVisible()
  const axes: { key: string; value: string; language: string }[] = []
  for (const key of ['lang', 'oms_lang']) for (const value of ['cn', 'en']) { const context = await browser.newContext(); const fresh = await context.newPage(); const errors: string[] = []; fresh.on('pageerror', error => errors.push(error.message)); await fresh.addInitScript(({ key, value }) => { localStorage.clear(); localStorage.setItem(key, value) }, { key, value }); try { await fresh.goto(new URL('/#/loginHomepage', page.url()).href); await expect(fresh.getByRole('heading', { name: value === 'en' ? 'Sign in to your workspace' : '登录工作台', exact: true })).toBeVisible(); await fresh.reload(); await expect(fresh.getByRole('heading', { name: value === 'en' ? 'Sign in to your workspace' : '登录工作台', exact: true })).toBeVisible(); expect(await fresh.evaluate(() => document.documentElement.lang)).toBe(value === 'en' ? 'en' : 'zh-CN'); expect(errors).toEqual([]); axes.push({ key, value, language: value === 'en' ? 'en' : 'zh-CN' }) } finally { await context.close() } }
  await observation(info, 'UI-001', 'fresh-supported-types', { freshAnonymousRoot: true, methodsComparedWithOriginalCurrentServerResponse: true, actualBuiltInNavigation: true, thirdPartyRedirectsNotExercised: true, businessWrites: 0 })
  await observation(info, 'UI-030', 'legacy-language-key', { freshBrowserContexts: axes, actualLocaleHeadingsDocumentLanguageAndRefresh: true, businessWrites: 0 })
})
