import fs from 'node:fs/promises'
import crypto from 'node:crypto'
import { test, expect, selectors, fill, secretFill, login, enterSamples, clickAndResponse, cancelDialog, observation, ownedName, type RecordDTO } from './helpers'
import { AdminFixtures, sameIDs } from './admin-fixtures'
import type { Page, Locator } from '@playwright/test'

async function logout(page: Page) { await page.getByLabel('Account', { exact: true }).filter({ visible: true }).click(); await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await expect(page).toHaveURL(/#\/loginHomepage$/) }
async function formPassword(scope: Page | Locator, label: string, value: string) { await secretFill(scope.getByLabel(label, { exact: true }).filter({ visible: true }), value) }

test('auth boundaries · supported methods, wrong/empty/Enter login, duplicate registration recovery, full profile/password and global rescue', async ({ page, backend, credentials }, info) => {
  const fixtures = new AdminFixtures(backend)
  try {
    const account = await fixtures.user('boundary_account', { phone: '100800100', email: 'initial@example.invalid', webHook: 'https://example.invalid/initial' })
    await logout(page)
    await expect(page.getByRole('button', { name: 'PowerJob account', exact: true })).toBeVisible()
    const supported = await clickAndResponse<RecordDTO[]>(page, '/auth/supportLoginTypes', () => page.reload()); expect(supported.success).toBe(true)
    for (const provider of supported.data) await expect(page.getByRole('button', { name: provider.type === 'PWJB' ? 'PowerJob account' : String(provider.name), exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'PowerJob account', exact: true }).click(); await expect(page).toHaveURL(/#\/powerjobLogin$/)
    const attempts: string[] = []; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/auth/thirdPartyLoginDirect')) attempts.push(request.url()) })
    const form = page.locator('form').filter({ has: page.getByRole('button', { name: 'Sign in', exact: true }) })
    await form.getByRole('button', { name: 'Sign in', exact: true }).click(); await fill(form, 'Username', account.origin); await form.getByRole('button', { name: 'Sign in', exact: true }).click(); await fill(form, 'Username', ''); await formPassword(form, 'Password', account.password); await form.getByRole('button', { name: 'Sign in', exact: true }).click(); expect(attempts).toHaveLength(0)
    await fill(form, 'Username', account.origin); await formPassword(form, 'Password', 'wrong-synthetic-' + crypto.randomUUID())
    const wrong = await clickAndResponse(page, '/auth/thirdPartyLoginDirect', () => form.getByRole('button', { name: 'Sign in', exact: true }).click()); expect(wrong.success).toBe(false); await expect(page.getByRole('alert')).toBeVisible(); expect(await page.evaluate(() => localStorage.getItem('PowerJwt'))).toBeNull(); await expect(page).toHaveURL(/#\/powerjobLogin$/)
    await formPassword(form, 'Password', account.password); await expect(form.getByLabel('Password', { exact: true }).filter({ visible: true })).toHaveAttribute('type', 'password'); await form.getByRole('button', { name: 'Show password', exact: true }).click(); await expect(form.getByLabel('Password', { exact: true }).filter({ visible: true })).toHaveAttribute('type', 'text'); expect(await form.getByLabel('Password', { exact: true }).filter({ visible: true }).inputValue() === account.password).toBe(true); await form.getByRole('button', { name: 'Hide password', exact: true }).click(); expect(await form.getByLabel('Password', { exact: true }).filter({ visible: true }).inputValue() === account.password).toBe(true); const beforeEnter = attempts.length
    const entered = await clickAndResponse(page, '/auth/thirdPartyLoginDirect', () => form.getByLabel('Password', { exact: true }).filter({ visible: true }).press('Enter')); expect(entered.success).toBe(true); expect(attempts.length - beforeEnter).toBe(1); await expect(page).toHaveURL(/#\/admin\/app$/); await page.reload(); await expect(page.getByRole('heading', { name: 'Applications', exact: true })).toBeVisible()
    await page.goto('/#/admin/personal'); await expect(page.getByLabel('Username', { exact: true }).filter({ visible: true })).toHaveValue('PWJB_' + account.origin)
    const changed = { Nickname: ownedName('changed_contact'), Phone: '100800200', Email: 'changed@example.invalid', Webhook: 'https://example.invalid/changed?x=%E4%B8%AD&v=1' }
    for (const [label, value] of Object.entries(changed)) await fill(page, label, value)
    const profile = await clickAndResponse(page, '/user/modify', () => page.getByRole('button', { name: 'Save profile', exact: true }).click()); expect(profile.success).toBe(true); await expect(page.getByRole('status').filter({ hasText: 'Profile saved' })).toBeVisible(); await page.reload()
    for (const [label, value] of Object.entries(changed)) await expect(page.getByLabel(label, { exact: true }).filter({ visible: true })).toHaveValue(value)
    const actual = await account.own.call<RecordDTO>('/user/detail'); expect(actual).toMatchObject({ id: account.profile.id, nick: changed.Nickname, phone: changed.Phone, email: changed.Email, webHook: changed.Webhook })
    const passwordRequests: string[] = []; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/pwjbUser/changePassword')) passwordRequests.push(request.url()) })
    await page.getByRole('button', { name: 'Change password', exact: true }).click(); let dialog = selectors.dialog(page, 'Change password')
    await formPassword(dialog, 'Old password', account.password); await formPassword(dialog, 'New password', 'different-a'); await formPassword(dialog, 'Confirm new password', 'different-b'); await dialog.getByRole('button', { name: 'Change password', exact: true }).click(); await expect(dialog.getByRole('alert')).toContainText('do not match'); expect(passwordRequests).toHaveLength(0)
    await cancelDialog(page, 'Change password'); await page.getByRole('button', { name: 'Change password', exact: true }).click(); dialog = selectors.dialog(page, 'Change password'); await expect(dialog.getByLabel('Old password', { exact: true }).filter({ visible: true })).toHaveValue(''); expect(passwordRequests).toHaveLength(0)
    const newPassword = 'Changed-' + crypto.randomUUID(); await formPassword(dialog, 'Old password', account.password); await formPassword(dialog, 'New password', newPassword); await formPassword(dialog, 'Confirm new password', newPassword)
    const changedPassword = await clickAndResponse(page, '/pwjbUser/changePassword', () => dialog.getByRole('button', { name: 'Change password', exact: true }).click()); expect(changedPassword.success).toBe(true); await expect(page).toHaveURL(/#\/loginHomepage$/)
    await page.goto('/#/powerjobLogin'); await fill(page, 'Username', account.origin); await formPassword(page, 'Password', account.password); const oldDenied = await clickAndResponse(page, '/auth/thirdPartyLoginDirect', () => page.getByRole('button', { name: 'Sign in', exact: true }).click()); expect(oldDenied.success).toBe(false)
    await login(page, { ...credentials, admin_username: account.origin, admin_password: newPassword }); await page.goto('/#/admin/personal'); await page.getByRole('button', { name: 'Change password', exact: true }).click(); dialog = selectors.dialog(page, 'Change password'); await formPassword(dialog, 'Old password', newPassword); await formPassword(dialog, 'New password', account.password); await formPassword(dialog, 'Confirm new password', account.password); const restored = await clickAndResponse(page, '/pwjbUser/changePassword', () => dialog.getByRole('button', { name: 'Change password', exact: true }).click()); expect(restored.success).toBe(true); await login(page, { ...credentials, admin_username: account.origin, admin_password: account.password })
    await logout(page); await page.goto('/#/powerjobLogin'); await page.getByRole('button', { name: 'Create an account', exact: true }).click(); dialog = selectors.dialog(page, 'Create an account')
    const creates: string[] = []; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/pwjbUser/create')) creates.push(request.url()) })
    await dialog.getByRole('button', { name: 'Create account', exact: true }).click(); await fill(dialog, 'Username', ownedName('missing')); await dialog.getByRole('button', { name: 'Create account', exact: true }).click(); await fill(dialog, 'Username', ''); await formPassword(dialog, 'Password', account.password); await formPassword(dialog, 'Confirm password', account.password); await dialog.getByRole('button', { name: 'Create account', exact: true }).click(); expect(creates).toHaveLength(0)
    await fill(dialog, 'Username', account.origin); await fill(dialog, 'Nickname', ownedName('draft_retained'))
    await dialog.getByRole('button', { name: 'Show password', exact: true }).first().click(); await expect(dialog.getByLabel('Password', { exact: true }).filter({ visible: true })).toHaveAttribute('type', 'text'); expect(await dialog.getByLabel('Password', { exact: true }).filter({ visible: true }).inputValue() === account.password).toBe(true); await dialog.getByRole('button', { name: 'Hide password', exact: true }).first().click(); expect(await dialog.getByLabel('Password', { exact: true }).filter({ visible: true }).inputValue() === account.password).toBe(true)
    const duplicate = await clickAndResponse(page, '/pwjbUser/create', () => dialog.getByRole('button', { name: 'Create account', exact: true }).click()); expect(duplicate.success).toBe(false); await expect(dialog.getByRole('alert')).toBeVisible(); await expect(dialog.getByLabel('Nickname', { exact: true }).filter({ visible: true })).toHaveValue(ownedName('draft_retained')); expect((await backend.call<RecordDTO[]>('/user/list', { query: { name: 'PWJB_' + account.origin } })).filter(row => row.username === 'PWJB_' + account.origin)).toHaveLength(1)
    const recoveredName = ownedName('registration_recovered'); await fill(dialog, 'Username', recoveredName); const recovered = await clickAndResponse(page, '/pwjbUser/create', () => dialog.getByRole('button', { name: 'Create account', exact: true }).click()); expect(recovered.success).toBe(true); fixtures.trackCommitted(recoveredName, account.password); await expect(page.locator('.registration-notice')).toContainText('Account created')
    await login(page, credentials); const admins = await backend.call<(string | number)[]>('/auth/listGlobalAdmin'); await page.goto('/#/admin/settings'); await expect(page.locator('.admin-chip')).toHaveCount(admins.length)
    let globalWrites = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/auth/saveGlobalAdmin')) globalWrites++ }); while (await page.locator('.admin-chip').count()) await page.locator('.admin-chip').first().click(); await page.getByRole('button', { name: 'Save', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('Keep at least one'); expect(globalWrites).toBe(0); expect(sameIDs(await backend.call<(string | number)[]>('/auth/listGlobalAdmin'), admins)).toBe(true); await page.reload(); await expect(page.locator('.admin-chip')).toHaveCount(admins.length)
    for (const [caseId, variants] of Object.entries({ 'UI-001': ['fresh-supported-types', 'wrong-password', 'empty-fields', 'correct-login', 'keyboard-submit'], 'UI-002': ['duplicate-register', 'missing-required', 'register-error-draft', 'password-mask'], 'UI-008': ['profile-all-fields', 'password-mismatch', 'password-cancel', 'password-success'], 'UI-009': ['reject-empty-admins'] })) for (const variant of variants) await observation(info, caseId, variant, { realNativeAction: true, originalBusinessResponse: true, exactOwnedAccount: account.id, zeroWriteGuardsAndIndependentReadbackChecked: true })
  } finally { await fixtures.cleanup(info) }
})

test('auth boundaries · correctly signed expired session reaches the real list, clears context and fresh login recovers', async ({ page, backend: _backend, credentials }, info) => {
  const filename = process.env.POWERJOB_E2E_EXPIRED_SESSION
  test.skip(!filename, 'Requires a private current-signature expired fixture')
  const fixture = JSON.parse(await fs.readFile(filename!, 'utf8')) as { expiredToken: string; officialOriginalSignatureVerified: boolean; currentServerSignatureVerified: boolean }
  expect(fixture.officialOriginalSignatureVerified && fixture.currentServerSignatureVerified).toBe(true)
  await enterSamples(page, credentials); await page.goto('/#/admin/app'); await expect(page.getByRole('heading', { name: 'Applications', exact: true })).toBeVisible(); await expect(page.locator('.data-table tbody tr').first()).toBeVisible()
  await page.evaluate(token => localStorage.setItem('PowerJwt', token), fixture.expiredToken)
  const result = await clickAndResponse(page, '/appInfo/list', () => page.reload(), response => response.request().headers().powerjwt === fixture.expiredToken); expect(result.success).toBe(false); expect(String(result.code)).toBe('-100'); await expect(page).toHaveURL(/#\/loginHomepage$/)
  expect(await page.evaluate(() => ({ jwt: localStorage.getItem('PowerJwt'), app: localStorage.getItem('Power_appId') }))).toEqual({ jwt: null, app: null }); await expect(page.getByRole('heading', { name: 'Sign in to your workspace', exact: true })).toBeVisible(); await login(page, credentials)
  await observation(info, 'UI-003', 'expired-session', { realCorrectlySignedExpiredToken: true, originalCurrentServerSignatureVerified: true, realListFailureCode: String(result.code), sessionAndAppCleared: true, freshNormalLoginRecovered: true, numericAndStringNormalization: 'SEPARATE_NATIVE_CORE_UNIT_CONTRACT' })
})
