import { test, expect, selectors, secretFill, enterSamples, observation, ownedName } from './helpers'
import type { Locator } from '@playwright/test'

async function dialogFocus(dialog: Locator) { await expect.poll(() => dialog.evaluate(element => element.contains(document.activeElement))).toBe(true) }

test('native keyboard workspace · 390px menu reaches real Jobs, form Escape restores trigger and account Enter navigation works', async ({ page, backend: _backend, credentials }, info) => {
  page.setDefaultTimeout(15_000); await enterSamples(page, credentials); await page.setViewportSize({ width: 390, height: 844 }); const mutations: string[] = []; page.on('request', request => { if (['/job/save', '/pwjbUser/changePassword', '/user/modify'].some(path => new URL(request.url()).pathname.endsWith(path))) mutations.push(new URL(request.url()).pathname) })
  const opener = page.getByRole('button', { name: 'Open navigation', exact: true }); await opener.focus(); await page.keyboard.press('Enter'); await expect(opener).toHaveAttribute('aria-expanded', 'true'); await page.locator('aside.rail').getByRole('link', { name: 'Jobs', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Jobs', exact: true })).toBeVisible(); await expect(opener).toHaveAttribute('aria-expanded', 'false'); await expect(page.locator('aside.rail')).toHaveAttribute('inert', ''); await expect(opener).toBeFocused(); const newJob = page.getByRole('button', { name: 'New job', exact: true }); await newJob.focus(); await page.keyboard.press('Enter'); let dialog = selectors.dialog(page, 'New job'); await dialogFocus(dialog); await page.keyboard.press('Tab'); await dialogFocus(dialog); await page.keyboard.press('Shift+Tab'); await dialogFocus(dialog); await page.keyboard.press('Escape'); await expect(dialog).not.toBeVisible(); await expect(newJob).toBeFocused(); expect(mutations).toHaveLength(0)
  const account = page.getByLabel('Account', { exact: true }).filter({ visible: true }); await account.focus(); await page.keyboard.press('Enter'); await expect(page.locator('.details-menu')).toHaveAttribute('open', ''); await page.keyboard.press('Tab'); const profileLink = page.locator('.details-menu').getByRole('link', { name: 'Profile', exact: true }); await expect(profileLink).toBeFocused(); await page.keyboard.press('Enter'); await expect(page.getByRole('heading', { name: 'Profile', exact: true })).toBeVisible(); const password = page.getByRole('button', { name: 'Change password', exact: true }); await password.focus(); await page.keyboard.press('Enter'); dialog = selectors.dialog(page, 'Change password'); await dialogFocus(dialog); await page.keyboard.press('Escape'); await expect(dialog).not.toBeVisible(); await expect(password).toBeFocused(); expect(mutations).toHaveLength(0); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  await observation(info, 'UI-029', 'menu-narrow', { actualViewport: 390, nativeMenuEnterAndActualJobsNavigation: true, newJobFormActuallyOpenedAndCancelled: true, backgroundInertRestored: true, businessMutationRequests: mutations })
  await observation(info, 'UI-035', 'keyboard-workspace-partial', { actualTabShiftTabEnterEscape: true, nativeJobAndPasswordDialogsFocusContainedAndReturnedToTriggers: true, nativeAccountMenuEnterTabProfileNavigation: true, allDomainKeyboardCoverage: 'NOT_CLAIMED', businessMutationRequests: mutations })
})

test('native keyboard authentication · actual Tab order and password toggle, registration Escape preserves masking without creation', async ({ page }, info) => {
  page.setDefaultTimeout(15_000); await page.goto('/#/powerjobLogin'); const form = page.locator('form').filter({ has: page.getByRole('button', { name: 'Sign in', exact: true }) }); const username = form.getByLabel('Username', { exact: true }); const password = form.getByLabel('Password', { exact: true }); let mutations = 0; page.on('request', request => { if (['/auth/thirdPartyLoginDirect', '/pwjbUser/create'].some(path => new URL(request.url()).pathname.endsWith(path))) mutations++ })
  await username.focus(); await page.keyboard.press('Tab'); await expect(password).toBeFocused(); await page.keyboard.press('Shift+Tab'); await expect(username).toBeFocused(); await secretFill(password, 'Keyboard-synthetic-value'); await password.focus(); await page.keyboard.press('Tab'); const show = form.getByRole('button', { name: 'Show password', exact: true }); await expect(show).toBeFocused(); await page.keyboard.press('Enter'); await expect(password).toHaveAttribute('type', 'text'); await expect(password).toHaveValue('Keyboard-synthetic-value'); await page.keyboard.press('Enter'); await expect(password).toHaveAttribute('type', 'password'); await expect(password).toHaveValue('Keyboard-synthetic-value')
  const create = page.getByRole('button', { name: 'Create an account', exact: true }); await create.focus(); await page.keyboard.press('Enter'); let dialog = selectors.dialog(page, 'Create an account'); await dialogFocus(dialog); await dialog.getByLabel('Username', { exact: true }).fill(ownedName('keyboard_cancelled')); await secretFill(dialog.getByLabel('Password', { exact: true }).filter({ visible: true }), 'Registration-keyboard-synthetic'); await page.keyboard.press('Tab'); await dialogFocus(dialog); await page.keyboard.press('Shift+Tab'); await dialogFocus(dialog); await page.keyboard.press('Escape'); await expect(dialog).not.toBeVisible(); await expect(create).toBeFocused(); await page.keyboard.press('Enter'); dialog = selectors.dialog(page, 'Create an account'); await expect(dialog.getByLabel('Username', { exact: true }).filter({ visible: true })).toHaveValue(''); await expect(dialog.getByLabel('Password', { exact: true }).filter({ visible: true })).toHaveAttribute('type', 'password'); await expect(dialog.getByLabel('Password', { exact: true }).filter({ visible: true })).toHaveValue(''); await page.keyboard.press('Escape'); await expect(create).toBeFocused(); expect(mutations).toBe(0)
  await observation(info, 'UI-035', 'keyboard-auth-partial', { realTabShiftTabUsernamePasswordOrder: true, realPasswordToggleEnterPreservedValue: true, registrationEscapeRestoredTriggerAndReopenClearedMaskedFields: true, businessMutationRequests: mutations })
})

test('native password cancellation · all three filled password fields are discarded, masked on reopen and never submitted', async ({ page, backend: _backend }, info) => {
  page.setDefaultTimeout(15_000); await page.goto('/#/admin/personal'); const open = page.getByRole('button', { name: 'Change password', exact: true }); await expect(open).toBeEnabled(); await open.click(); let dialog = selectors.dialog(page, 'Change password'); let requests = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/pwjbUser/changePassword')) requests++ }); for (const label of ['Old password', 'New password', 'Confirm new password']) { await secretFill(dialog.getByLabel(label, { exact: true }).filter({ visible: true }), 'Cancelled-synthetic-' + label); const field = dialog.getByLabel(label, { exact: true }).filter({ visible: true }); await field.locator('..').getByRole('button', { name: 'Show password', exact: true }).click(); await expect(field).toHaveAttribute('type', 'text') } await dialog.getByRole('button', { name: 'Cancel', exact: true }).click(); await expect(dialog).not.toBeVisible(); await expect(open).toBeFocused(); await open.click(); dialog = selectors.dialog(page, 'Change password'); for (const label of ['Old password', 'New password', 'Confirm new password']) { await expect(dialog.getByLabel(label, { exact: true }).filter({ visible: true })).toHaveValue(''); await expect(dialog.getByLabel(label, { exact: true }).filter({ visible: true })).toHaveAttribute('type', 'password') } await dialog.getByRole('button', { name: 'Cancel', exact: true }).click(); expect(requests).toBe(0); await observation(info, 'UI-008', 'password-cancel', { allThreePasswordInputsFilledAndShownBeforeCancel: true, allThreeEmptyAndMaskedAfterReopen: true, nativeFocusRestoredToTrigger: true, actualChangePasswordRequests: requests, businessWrites: 0 })
})
