import crypto from 'node:crypto'
import { test, expect, selectors, fill, choose, secretFill, clickAndResponse, cancelDialog, confirmDialog, login, enterApplication, observation, ownedName, id, type ID, type RecordDTO, type PageDTO } from './helpers'
import { AdminFixtures, emptyRoles, sameIDs } from './admin-fixtures'
import type { Page, Locator } from '@playwright/test'

const roleEntries = [['observer', 'Observer', 'OBSERVER'], ['qa', 'QA', 'QA'], ['developer', 'Developer', 'DEVELOPER'], ['admin', 'Administrator', 'ADMIN']] as const
async function logout(page: Page) { await page.getByLabel('Account', { exact: true }).filter({ visible: true }).click(); await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await expect(page).toHaveURL(/#\/loginHomepage$/) }
async function appQuery(page: Page, name: string, all = false) { if (all) await page.getByLabel('Related to me', { exact: true }).filter({ visible: true }).uncheck(); await fill(page, 'Application name', name); const response = await clickAndResponse<PageDTO<RecordDTO>>(page, '/appInfo/list', () => page.getByRole('button', { name: 'Query', exact: true }).click(), value => value.request().postDataJSON()?.appNameLike === name); expect(response.success).toBe(true); await expect(selectors.row(page, name)).toHaveCount(1) }
async function appRead(backend: AdminFixtures['backend'], app: RecordDTO) { const page = await backend.call<PageDTO<RecordDTO>>('/appInfo/list', { method: 'POST', data: { appId: app.id, showMyRelated: false, index: 0, pageSize: 10 } }); expect(page.data).toHaveLength(1); expect(page.data[0].appName).toBe(app.appName); return page.data[0] }
async function spaceRead(backend: AdminFixtures['backend'], space: RecordDTO) { const rows = (await backend.call<PageDTO<RecordDTO>>('/namespace/list', { method: 'POST', data: { codeLike: space.code, index: 0, pageSize: 100 } })).data.filter(row => id(row.id) === id(space.id)); expect(rows).toHaveLength(1); expect(rows[0].code).toBe(space.code); return rows[0] }
async function chooseRole(dialog: Locator, role: string, account: { origin: string }, checked: boolean) { await fill(dialog, 'Search users', account.origin); const column = dialog.locator('.role-column').filter({ has: dialog.page().getByRole('heading', { name: role, exact: true }) }); const option = column.getByRole('checkbox', { name: new RegExp(account.origin) }); await expect(option).toHaveCount(1); await option.setChecked(checked) }

// Each role belongs to a distinct account. UI acceptance never substitutes a prepared API role assignment for a page save.
test('admin roles · four distinct accounts, namespace/app field and role roundtrip, observer rejection and unique administrator rescue', async ({ page, backend, credentials }, info) => {
  page.setDefaultTimeout(15_000)
  const fixtures = new AdminFixtures(backend)
  try {
    const accounts = []
    for (const [key] of roleEntries) accounts.push(await fixtures.user('matrix_' + key))
    const rescue = await fixtures.user('matrix_rescue')
    const code = ownedName('matrix_namespace'); const name = ownedName('matrix_namespace_label')
    await page.goto('/#/admin/namespace'); await page.reload(); await page.getByRole('button', { name: 'New namespace', exact: true }).click(); let dialog = selectors.dialog(page, 'New namespace')
    await fill(dialog, 'Code', code); await fill(dialog, 'Name', name); await fill(dialog, 'Tags', 'four-role-namespace'); await fill(dialog, 'Extra configuration', '{"future":false,"count":0}')
    for (const [, label] of roleEntries) await chooseRole(dialog, label, accounts[roleEntries.findIndex(value => value[1] === label)], true)
    const createdSpace = await clickAndResponse<RecordDTO>(page, '/namespace/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(createdSpace.success).toBe(true); const space = fixtures.trackSpace(createdSpace.data); let savedSpace = await spaceRead(backend, space); expect(savedSpace).toMatchObject({ code, name, tags: 'four-role-namespace', extra: '{"future":false,"count":0}' })
    for (let index = 0; index < roleEntries.length; index++) expect((savedSpace.componentUserRoleInfo as Record<string, ID[]>)[roleEntries[index][0]].map(String)).toContain(accounts[index].id)
    const appName = ownedName('matrix_app'); await page.goto('/#/admin/app'); await page.getByRole('button', { name: 'New application', exact: true }).click(); dialog = selectors.dialog(page, 'New application'); await choose(dialog, 'Namespace', name + '(' + code + ')'); await fill(dialog, 'Application name', appName); await secretFill(dialog.getByLabel('Application password', { exact: true }).filter({ visible: true }), 'App-' + crypto.randomUUID()); await fill(dialog, 'Description', 'Four distinct roles'); await fill(dialog, 'Tags', 'four-role-app'); await fill(dialog, 'Extra configuration', '{"future":false}')
    for (let index = 0; index < roleEntries.length; index++) await chooseRole(dialog, roleEntries[index][1], accounts[index], true)
    const createdApp = await clickAndResponse<RecordDTO>(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(createdApp.success).toBe(true); const app = fixtures.trackApp(createdApp.data); const saved = await appRead(backend, app)
    expect(saved.appName).toBe(appName); expect(id(saved.namespaceId)).toBe(id(space.id)); expect(saved.title).toBe('Four distinct roles'); expect(saved.tags).toBe('four-role-app'); expect(saved.extra).toBe('{"future":false}')
    for (let index = 0; index < roleEntries.length; index++) expect((saved.componentUserRoleInfo as Record<string, ID[]>)[roleEntries[index][0]].map(String)).toContain(accounts[index].id)
    // Distinct normal logins verify actual server entitlements and readable job pages; no Worker execution is claimed.
    for (let index = 0; index < roleEntries.length; index++) { await logout(page); await login(page, { ...credentials, admin_username: accounts[index].origin, admin_password: accounts[index].password }); await page.goto('/#/admin/personal'); await page.getByText('View assigned permissions', { exact: true }).click(); const entitlement = page.locator('.entitlement-row').filter({ has: page.locator('.badge').filter({ hasText: new RegExp('^' + roleEntries[index][2] + '$') }) }); await expect(entitlement.filter({ hasText: appName })).toHaveCount(1); await expect(entitlement.filter({ hasText: name })).toHaveCount(1); await enterApplication(page, appName); const read = await clickAndResponse(page, '/job/list', () => page.getByRole('link', { name: 'Jobs', exact: true }).click()); expect(read.success).toBe(true); await expect(page.getByRole('heading', { name: 'Jobs', exact: true })).toBeVisible() }
    await logout(page); await login(page, { ...credentials, admin_username: accounts[0].origin, admin_password: accounts[0].password }); await appQuery(page, appName); await selectors.row(page, appName).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit application'); await fill(dialog, 'Description', 'Forbidden observer edit'); const rejectedSave = await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(rejectedSave.success).toBe(false); await expect(dialog.getByRole('alert')).toBeVisible(); expect((await appRead(backend, app)).title).toBe('Four distinct roles'); const rejectedDelete = await clickAndResponse(page, '/appInfo/delete', async () => { await dialog.getByRole('button', { name: 'Delete', exact: true }).click(); await confirmDialog(page) }); expect(rejectedDelete.success).toBe(false); await expect(dialog.getByRole('alert')).toBeVisible(); await expect(page.getByRole('status').filter({ hasText: 'Application deleted' })).toHaveCount(0); expect(id((await appRead(backend, app)).id)).toBe(id(app.id)); await cancelDialog(page, 'Edit application')
    await logout(page); await login(page, credentials); await appQuery(page, appName); await selectors.row(page, appName).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit application'); for (let index = 0; index < roleEntries.length; index++) await chooseRole(dialog, roleEntries[index][1], accounts[index], false); const removed = await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(removed.success).toBe(true); const removedRoles = (await appRead(backend, app)).componentUserRoleInfo as Record<string, ID[]>; for (let index = 0; index < roleEntries.length; index++) expect(removedRoles[roleEntries[index][0]].map(String)).not.toContain(accounts[index].id)
    // App assignments are gone; the four remaining explicit namespace roles still confer the old Server's inherited READ access.
    for (let index = 0; index < roleEntries.length; index++) {
      await logout(page); await login(page, { ...credentials, admin_username: accounts[index].origin, admin_password: accounts[index].password }); await page.goto('/#/admin/personal'); await page.getByText('View assigned permissions', { exact: true }).click()
      await expect(page.locator('.entitlement-row').filter({ hasText: appName })).toHaveCount(0)
      const inherited = page.locator('.entitlement-row').filter({ has: page.locator('.badge').filter({ hasText: new RegExp('^' + roleEntries[index][2] + '$') }) }); await expect(inherited.filter({ hasText: name })).toHaveCount(1)
      await page.goto('/#/admin/app'); await fill(page, 'Application name', appName)
      const explicitlyRelated = await clickAndResponse<PageDTO<RecordDTO>>(page, '/appInfo/list', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => response.request().postDataJSON()?.appNameLike === appName && response.request().postDataJSON()?.showMyRelated === true); expect(explicitlyRelated.success).toBe(true); expect(explicitlyRelated.data.data.some(row => id(row.id) === id(app.id))).toBe(false)
      const allVisible = await clickAndResponse<PageDTO<RecordDTO>>(page, '/appInfo/list', () => page.getByLabel('Related to me', { exact: true }).filter({ visible: true }).uncheck(), response => response.request().postDataJSON()?.appNameLike === appName && response.request().postDataJSON()?.showMyRelated === false); expect(allVisible.success).toBe(true); expect(allVisible.data.data.filter(row => id(row.id) === id(app.id))).toHaveLength(1)
      await selectors.row(page, appName).getByRole('button', { name: 'Enter', exact: true }).click(); await expect(page).toHaveURL(/#\/oms\/home$/); const inheritedRead = await clickAndResponse(page, '/job/list', () => page.getByRole('link', { name: 'Jobs', exact: true }).click()); expect(inheritedRead.success).toBe(true); await expect(page.getByRole('heading', { name: 'Jobs', exact: true })).toBeVisible()
    }
    await logout(page); await login(page, credentials)
    await page.goto('/#/admin/namespace'); await fill(page, 'Code', code); await clickAndResponse(page, '/namespace/list', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => response.request().postDataJSON()?.codeLike === code); await selectors.row(page, code).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit namespace'); await expect(dialog.getByLabel('Code', { exact: true }).filter({ visible: true })).toHaveAttribute('readonly', '')
    await expect(dialog.getByLabel('Access token', { exact: true }).filter({ visible: true })).toHaveAttribute('readonly', '')
    await expect(dialog.getByLabel('Access token', { exact: true }).filter({ visible: true })).toHaveAttribute('type', 'password')
    expect(await dialog.getByLabel('Access token', { exact: true }).filter({ visible: true }).inputValue() === String(savedSpace.token), 'Masked read-only token matches the actual owned namespace').toBe(true)
    await fill(dialog, 'Name', ownedName('matrix_edited')); await fill(dialog, 'Tags', 'edited-role-namespace'); await fill(dialog, 'Extra configuration', '{"edited":{"zero":0,"off":false}}'); await chooseRole(dialog, 'Observer', accounts[0], false); await chooseRole(dialog, 'Administrator', rescue, true); const editedSpace = await clickAndResponse(page, '/namespace/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(editedSpace.success).toBe(true); await page.reload(); await fill(page, 'Code', code); await clickAndResponse(page, '/namespace/list', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => response.request().postDataJSON()?.codeLike === code); await selectors.row(page, code).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit namespace'); await expect(dialog.getByLabel('Name', { exact: true }).filter({ visible: true })).toHaveValue(ownedName('matrix_edited')); await expect(dialog.getByLabel('Tags', { exact: true }).filter({ visible: true })).toHaveValue('edited-role-namespace'); await expect(dialog.getByLabel('Extra configuration', { exact: true }).filter({ visible: true })).toHaveValue('{"edited":{"zero":0,"off":false}}'); const namespaceBeforeEdit = savedSpace; savedSpace = await spaceRead(backend, space); expect(savedSpace.code).toBe(code); expect(savedSpace.token === namespaceBeforeEdit.token, 'Editing the namespace must preserve its original token').toBe(true); await expect(dialog.getByLabel('Code', { exact: true }).filter({ visible: true })).toHaveAttribute('readonly', ''); await expect(dialog.getByLabel('Access token', { exact: true }).filter({ visible: true })).toHaveAttribute('readonly', ''); await expect(dialog.getByLabel('Access token', { exact: true }).filter({ visible: true })).toHaveAttribute('type', 'password'); expect(await dialog.getByLabel('Access token', { exact: true }).filter({ visible: true }).inputValue() === String(namespaceBeforeEdit.token), 'Reopened token is unchanged').toBe(true); expect((savedSpace.componentUserRoleInfo as Record<string, ID[]>).observer.map(String)).not.toContain(accounts[0].id); expect((savedSpace.componentUserRoleInfo as Record<string, ID[]>).admin.map(String)).toContain(rescue.id); await cancelDialog(page, 'Edit namespace')
    // Formal 5.1.6 adds the creator automatically. Normalize only the owned precondition before testing exact single explicit ADMIN removal.
    await backend.call('/namespace/save', { method: 'POST', namespaceId: id(space.id), data: { ...savedSpace, componentUserRoleInfo: { ...emptyRoles(), admin: [rescue.id] } } }); await backend.call('/appInfo/save', { method: 'POST', appId: id(app.id), data: { ...(await appRead(backend, app)), componentUserRoleInfo: { ...emptyRoles(), admin: [accounts[3].id] } } }); expect(((await appRead(backend, app)).componentUserRoleInfo as Record<string, ID[]>).admin.map(String)).toEqual([accounts[3].id])
    await logout(page); await login(page, { ...credentials, admin_username: accounts[3].origin, admin_password: accounts[3].password }); await appQuery(page, appName); await selectors.row(page, appName).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit application'); await expect(dialog.locator('.role-chip')).toHaveCount(1); await dialog.locator('.role-chip').click(); const emptied = await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(emptied.success).toBe(true); expect(Object.values((await appRead(backend, app)).componentUserRoleInfo as Record<string, ID[]>).every(values => values.length === 0)).toBe(true)
    await logout(page); await login(page, { ...credentials, admin_username: rescue.origin, admin_password: rescue.password }); await appQuery(page, appName, true); await selectors.row(page, appName).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit application'); await fill(dialog, 'Description', 'Inherited namespace rescue'); await chooseRole(dialog, 'Administrator', accounts[3], true); const restored = await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(restored.success).toBe(true); expect((await appRead(backend, app)).title).toBe('Inherited namespace rescue'); expect(((await appRead(backend, app)).componentUserRoleInfo as Record<string, ID[]>).admin.map(String)).toEqual([accounts[3].id])
    for (const [caseId, variants] of Object.entries({ 'UI-005': ['assign-four-roles', 'remove-roles', 'unauthorized-change', 'delete-business-failure', 'last-admin'], 'UI-006': ['create-all-fields', 'edit-roundtrip'] })) for (const variant of variants) await observation(info, caseId, variant, { appId: id(app.id), namespaceId: id(space.id), fourDistinctAccountIDs: accounts.map(account => account.id), distinctNamespaceRescueAccountID: rescue.id, fourSeparateNormalLoginsAndREADPages: true, fourPostRemovalFreshProfilesWithoutExplicitAppRoleAndInheritedNamespaceReadPreserved: true, originalRelatedFilterExcludesNamespaceOnlyAccessAndAllModePermitsInheritedRead: true, namespaceCodeAndMaskedReadonlyTokenPreserved: true, observerSaveAndDeleteOriginalServerRejected: true, exactSingleExplicitAppAdminBeforeRemoval: true, namespaceRescueRestoredThatAdministrator: true, globalAdminLockoutGuard: 'SEPARATE_BOUNDARY_GROUP', noSharedMetadataChanged: true })
  } finally { await fixtures.cleanup(info) }
})

test('admin permissions · revoked live user switch rejects without mutation, real status retry recovers and nonglobal lists stay denied', async ({ page, backend, credentials }, info) => {
  page.setDefaultTimeout(15_000)
  const fixtures = new AdminFixtures(backend); const original = await backend.call<ID[]>('/auth/listGlobalAdmin'); let operatorID = ''
  try {
    const operator = await fixtures.user('toggle_operator'); operatorID = operator.id; const target = await fixtures.user('toggle_target'); await backend.call('/auth/saveGlobalAdmin', { method: 'POST', data: { admin: [...original, operator.id] } }); await logout(page); await login(page, { ...credentials, admin_username: operator.origin, admin_password: operator.password }); await page.goto('/#/admin/user'); await fill(page, 'User ID', target.id); const query = await clickAndResponse(page, '/user/query', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => String(response.request().postDataJSON()?.userIdEq) === target.id); expect(query.success).toBe(true); const switcher = selectors.row(page, 'PWJB_' + target.origin).getByRole('switch'); await expect(switcher).toHaveAttribute('aria-checked', 'true')
    await backend.call('/auth/saveGlobalAdmin', { method: 'POST', data: { admin: original } }); const refused = await clickAndResponse(page, '/user/disable', () => switcher.click()); expect(refused.success).toBe(false); await expect(switcher).toHaveAttribute('aria-checked', 'true'); await expect(page.getByRole('status').filter({ hasText: 'User disabled' })).toHaveCount(0); expect((await backend.call<RecordDTO[]>('/user/query', { method: 'POST', data: { userIdEq: target.id } }))[0].enable).toBe(true)
    const deniedQuery = await clickAndResponse(page, '/user/query', () => page.getByRole('button', { name: 'Query', exact: true }).click()); expect(deniedQuery.success).toBe(false); await expect(page.locator('.error-banner[role=alert]')).toBeVisible(); await page.reload(); await expect(page.locator('.error-banner[role=alert]')).toBeVisible(); await expect(page.locator('.data-table tbody tr')).toHaveCount(0)
    await backend.call('/auth/saveGlobalAdmin', { method: 'POST', data: { admin: [...original, operator.id] } }); const recoveredQuery = await clickAndResponse(page, '/user/query', () => page.getByRole('button', { name: 'Retry', exact: true }).click()); expect(recoveredQuery.success).toBe(true); await fill(page, 'User ID', target.id); await clickAndResponse(page, '/user/query', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => String(response.request().postDataJSON()?.userIdEq) === target.id); const recovered = selectors.row(page, 'PWJB_' + target.origin).getByRole('switch'); const disabled = await clickAndResponse(page, '/user/disable', () => recovered.click()); expect(disabled.success).toBe(true); await expect(recovered).toHaveAttribute('aria-checked', 'false'); expect((await backend.call<RecordDTO[]>('/user/query', { method: 'POST', data: { userIdEq: target.id } }))[0].enable).toBe(false); const enabled = await clickAndResponse(page, '/user/enable', () => recovered.click()); expect(enabled.success).toBe(true); await expect(recovered).toHaveAttribute('aria-checked', 'true'); expect((await backend.call<RecordDTO[]>('/user/query', { method: 'POST', data: { userIdEq: target.id } }))[0].enable).toBe(true)
    await backend.call('/auth/saveGlobalAdmin', { method: 'POST', data: { admin: original } }); expect(sameIDs(await backend.call<ID[]>('/auth/listGlobalAdmin'), original)).toBe(true)
    for (const [caseId, variants] of Object.entries({ 'UI-003': ['revoked-role'], 'UI-007': ['permission-error-toggle', 'status-error-recovery'] })) for (const variant of variants) await observation(info, caseId, variant, { operatorID, targetID: target.id, grantThenRevokeOnlyOwnedGlobalRole: true, originalServerQueryAndDisableDenied: true, ariaCheckedAndIndependentBackendEnableUnchanged: true, successfulUIRetryDisableAndEnableReadBack: true, originalAdministratorSetRestored: true })
  } finally { const current = await backend.call<ID[]>('/auth/listGlobalAdmin'); const expected = operatorID ? current.filter(value => id(value) !== operatorID) : current; if (!sameIDs(expected, original)) throw new Error('Unrelated administrator set changed; refusing restoration'); if (!sameIDs(current, original)) await backend.call('/auth/saveGlobalAdmin', { method: 'POST', data: { admin: original } }); await fixtures.cleanup(info) }
})

test('admin account access · wrong and opted-out application passwords deny, correct password grants and survives fresh normal login', async ({ page, backend, credentials }, info) => {
  page.setDefaultTimeout(15_000)
  const fixtures = new AdminFixtures(backend)
  try {
    const account = await fixtures.user('grant_account'); const space = await fixtures.space('grant_namespace'); const app = await fixtures.app('grant_app', id(space.id)); const optedOut = await fixtures.app('grant_optout', id(space.id), { extra: '{"allowedBecomeAdminByPassword":false}' }); const normal = await appRead(backend, app); const deniedApp = await appRead(backend, optedOut)
    await logout(page); await login(page, { ...credentials, admin_username: account.origin, admin_password: account.password }); await page.goto('/#/admin/personal'); await fill(page, 'Application name', String(app.appName)); await secretFill(page.getByLabel('Application password', { exact: true }).filter({ visible: true }), 'Incorrect-' + crypto.randomUUID()); const wrong = await clickAndResponse(page, '/appInfo/becomeAdmin', () => page.getByRole('button', { name: 'Get access', exact: true }).click()); expect(wrong.success).toBe(false); await expect(page.locator('.grant-panel').getByRole('alert')).toBeVisible(); expect(((await appRead(backend, app)).componentUserRoleInfo as Record<string, ID[]>).admin.map(String)).not.toContain(account.id)
    await fill(page, 'Application name', String(optedOut.appName)); await secretFill(page.getByLabel('Application password', { exact: true }).filter({ visible: true }), String(deniedApp.password)); const refused = await clickAndResponse(page, '/appInfo/becomeAdmin', () => page.getByRole('button', { name: 'Get access', exact: true }).click()); expect(refused.success).toBe(false); await expect(page.locator('.grant-panel').getByRole('alert')).toBeVisible(); expect(((await appRead(backend, optedOut)).componentUserRoleInfo as Record<string, ID[]>).admin.map(String)).not.toContain(account.id)
    await fill(page, 'Application name', String(app.appName)); await secretFill(page.getByLabel('Application password', { exact: true }).filter({ visible: true }), String(normal.password)); const granted = await clickAndResponse(page, '/appInfo/becomeAdmin', () => page.getByRole('button', { name: 'Get access', exact: true }).click()); expect(granted.success).toBe(true); await expect(page.getByRole('status').filter({ hasText: 'Application administration granted' })).toBeVisible(); await expect(page.getByLabel('Application password', { exact: true }).filter({ visible: true })).toHaveValue(''); expect(((await appRead(backend, app)).componentUserRoleInfo as Record<string, ID[]>).admin.map(String)).toContain(account.id); await page.reload(); await page.getByText('View assigned permissions', { exact: true }).click(); await expect(page.locator('.entitlement-row').filter({ hasText: app.appName as string })).toContainText('ADMIN'); await logout(page); await login(page, { ...credentials, admin_username: account.origin, admin_password: account.password }); await appQuery(page, String(app.appName)); await selectors.row(page, String(app.appName)).getByRole('button', { name: 'Edit', exact: true }).click(); const dialog = selectors.dialog(page, 'Edit application'); await fill(dialog, 'Description', 'Granted administrator real write'); const saved = await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(saved.success).toBe(true); expect((await appRead(backend, app)).title).toBe('Granted administrator real write')
    for (const variant of ['become-admin-success', 'become-admin-denied']) await observation(info, 'UI-008', variant, { accountID: account.id, applicationID: id(app.id), optoutApplicationID: id(optedOut.id), realWrongPasswordAndOptoutRefusedWithoutRoleGrant: true, correctAppPasswordGrantedAndFreshLoginCouldEdit: true, currentApplicationPasswordCleared: true })
  } finally { await fixtures.cleanup(info) }
})
