import crypto from 'node:crypto'
import { test, expect, selectors, fill, choose, secretFill, clickAndResponse, cancelDialog, confirmDialog, enterApplication, observation, ownedName, id, type RecordDTO, type PageDTO } from './helpers'
import { AdminFixtures } from './admin-fixtures'
import type { Page } from '@playwright/test'

async function query(page: Page, endpoint: string) {
  const labels = endpoint === '/namespace/list' ? { Code: 'codeLike', Name: 'nameLike', Tags: 'tagLike' } : { 'Application ID': 'appId', 'Application name': 'appNameLike', Tags: 'tagLike', Namespace: 'namespaceId' }
  const expected = Object.fromEntries(await Promise.all(Object.entries(labels).map(async ([label, key]) => [key, await page.getByLabel(label, { exact: true }).filter({ visible: true }).inputValue()])))
  const result = await clickAndResponse<PageDTO<RecordDTO>>(page, endpoint, () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => { const body = response.request().postDataJSON(); return body?.index === 0 && Object.entries(expected).every(([key, value]) => String(body[key] || '') === value) })
  expect(result.success).toBe(true); return result.data
}
async function reset(page: Page, endpoint: string) { const result = await clickAndResponse(page, endpoint, () => page.getByRole('button', { name: 'Reset', exact: true }).click(), response => { const body = response.request().postDataJSON(); return body?.index === 0 && ['appId', 'namespaceId', 'appNameLike', 'codeLike', 'nameLike', 'tagLike'].every(key => !body[key]) }); expect(result.success).toBe(true) }

test('admin filters · exact ID/name/tag/namespace axes, related toggle and real 0/1/10/11 pagination plus array user reset', async ({ page, backend }, info) => {
  const fixtures = new AdminFixtures(backend)
  page.setDefaultTimeout(15_000)
  try {
    const spaces: RecordDTO[] = []; const apps: RecordDTO[] = []; const users: Awaited<ReturnType<AdminFixtures['user']>>[] = []
    const tag = ownedName('filter_tag'); const phone = '100' + String(Date.now()).slice(-8)
    for (let index = 0; index < 11; index++) spaces.push(await fixtures.space('filter_space_' + index, { tags: tag }))
    for (let index = 0; index < 11; index++) apps.push(await fixtures.app('filter_app_' + index, id(spaces[0].id), { tags: tag }))
    for (let index = 0; index < 11; index++) users.push(await fixtures.user('filter_user_' + index, { phone: phone + String(index).padStart(2, '0') }))
    await page.goto('/#/admin/app'); await page.reload(); await fill(page, 'Application ID', id(apps[0].id)); let result = await query(page, '/appInfo/list'); expect(result.data.map(value => id(value.id))).toEqual([id(apps[0].id)]); await reset(page, '/appInfo/list'); await expect(page.getByLabel('Application ID', { exact: true }).filter({ visible: true })).toHaveValue(''); await expect(page.getByLabel('Related to me', { exact: true }).filter({ visible: true })).toBeChecked()
    await fill(page, 'Application name', String(apps[0].appName)); result = await query(page, '/appInfo/list'); expect(result.data.map(value => id(value.id))).toEqual([id(apps[0].id)]); await reset(page, '/appInfo/list')
    await choose(page, 'Namespace', String(spaces[0].name) + '(' + String(spaces[0].code) + ')'); result = await query(page, '/appInfo/list'); expect(Number(result.totalItems)).toBe(11); expect(result.data.every(row => id(row.namespaceId) === id(spaces[0].id))).toBe(true); await reset(page, '/appInfo/list')
    await fill(page, 'Tags', tag); result = await query(page, '/appInfo/list'); expect(Number(result.totalItems)).toBe(11); await expect(page.locator('.data-table tbody tr')).toHaveCount(10); const firstIds = result.data.map(value => id(value.id))
    let next = await clickAndResponse<PageDTO<RecordDTO>>(page, '/appInfo/list', () => page.getByRole('button', { name: 'Next', exact: true }).click(), value => value.request().postDataJSON()?.index === 1); expect(next.success).toBe(true); expect(next.data.data).toHaveLength(1); expect(firstIds).not.toContain(id(next.data.data[0].id)); await expect(page.locator('.pagination')).toContainText('2 / 2'); await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeDisabled()
    const related = await clickAndResponse<PageDTO<RecordDTO>>(page, '/appInfo/list', () => page.getByLabel('Related to me', { exact: true }).filter({ visible: true }).uncheck(), value => value.request().postDataJSON()?.showMyRelated === false && value.request().postDataJSON()?.index === 0); expect(related.success).toBe(true); await expect(page.locator('.pagination')).toContainText('1 / 2')
    await fill(page, 'Application name', ownedName('no_app')); result = await query(page, '/appInfo/list'); expect(result.data).toHaveLength(0); await expect(page.locator('.data-table tbody tr')).toHaveCount(0); await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeDisabled(); await reset(page, '/appInfo/list')
    // A real ten-item boundary and a one-item boundary, without replacing responses.
    for (let index = 1; index < apps.length; index++) await backend.call('/appInfo/save', { method: 'POST', appId: id(apps[index].id), data: { ...(await backend.call<PageDTO<RecordDTO>>('/appInfo/list', { method: 'POST', data: { appId: apps[index].id, showMyRelated: false, index: 0, pageSize: 10 } })).data[0], tags: tag + '_ten' } })
    await fill(page, 'Tags', tag + '_ten'); result = await query(page, '/appInfo/list'); expect(Number(result.totalItems)).toBe(10); await expect(page.locator('.data-table tbody tr')).toHaveCount(10); await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeDisabled(); await reset(page, '/appInfo/list'); await fill(page, 'Application ID', id(apps[0].id)); result = await query(page, '/appInfo/list'); expect(Number(result.totalItems)).toBe(1); await expect(page.locator('.data-table tbody tr')).toHaveCount(1)
    await page.goto('/#/admin/namespace'); for (const [label, value] of [['Code', String(spaces[0].code)], ['Name', String(spaces[0].name)], ['Tags', tag]]) { await fill(page, label, value); result = await query(page, '/namespace/list'); expect(Number(result.totalItems)).toBe(label === 'Tags' ? 11 : 1); await reset(page, '/namespace/list'); await expect(page.getByLabel(label, { exact: true }).filter({ visible: true })).toHaveValue('') }
    await fill(page, 'Tags', tag); result = await query(page, '/namespace/list'); const firstSpaceIds = result.data.map(value => id(value.id)); await expect(page.locator('.data-table tbody tr')).toHaveCount(10); next = await clickAndResponse<PageDTO<RecordDTO>>(page, '/namespace/list', () => page.getByRole('button', { name: 'Next', exact: true }).click(), value => value.request().postDataJSON()?.index === 1); expect(next.success).toBe(true); expect(next.data.data).toHaveLength(1); expect(firstSpaceIds).not.toContain(id(next.data.data[0].id)); await reset(page, '/namespace/list'); await expect(page.locator('.pagination')).toContainText('1 /')
    await page.goto('/#/admin/user'); for (const [label, value, key] of [['User ID', users[0].id, 'userIdEq'], ['Nickname', users[0].origin, 'nickLike'], ['Phone', phone + '00', 'phoneLike']]) { await fill(page, label, value); const response = await clickAndResponse<RecordDTO[]>(page, '/user/query', () => page.getByRole('button', { name: 'Query', exact: true }).click(), response => String(response.request().postDataJSON()?.[key]) === String(value)); expect(response.success).toBe(true); expect(response.data.map(value => id(value.id))).toEqual([users[0].id]); await clickAndResponse(page, '/user/query', () => page.getByRole('button', { name: 'Reset', exact: true }).click()); await expect(page.getByLabel(label, { exact: true }).filter({ visible: true })).toHaveValue('') }
    await fill(page, 'Nickname', ownedName('filter_user_')); const array = await clickAndResponse<RecordDTO[]>(page, '/user/query', () => page.getByRole('button', { name: 'Query', exact: true }).click()); expect(array.success).toBe(true); expect(array.data).toHaveLength(11); await expect(page.locator('.data-table tbody tr')).toHaveCount(10); await page.getByRole('button', { name: 'Next', exact: true }).click(); await expect(page.locator('.data-table tbody tr')).toHaveCount(1); await expect(page.locator('.pagination')).toContainText('2 / 2'); await clickAndResponse(page, '/user/query', () => page.getByRole('button', { name: 'Reset', exact: true }).click()); await expect(page.locator('.pagination')).toContainText('1 /'); await expect(page.getByLabel('Nickname', { exact: true }).filter({ visible: true })).toHaveValue('')
    for (const [caseId, variants] of Object.entries({ 'UI-004': ['filter-id', 'filter-code-tag-namespace', 'my-related-toggle', 'pagination-boundary'], 'UI-006': ['filters-reset', 'pagination', 'namespace-app-filter'], 'UI-007': ['user-id-nick-phone', 'user-pagination-reset'] })) for (const variant of variants) await observation(info, caseId, variant, { realUIQueryAndReset: true, originalServerResponses: true, exactFixtureApps: apps.map(row => id(row.id)), exactFixtureNamespaces: spaces.map(row => id(row.id)), pageIndicesActuallyChecked: [0, 1], appBoundariesActuallyChecked: [0, 1, 10, 11], userArrayContract: true })
  } finally { await fixtures.cleanup(info) }
})

test('admin drafts · duplicate create recovery, edit/cancel/new isolation, all-field reopen, real offline save recovery and confirmed deletion refresh', async ({ page, backend }, info) => {
  const fixtures = new AdminFixtures(backend)
  page.setDefaultTimeout(15_000)
  try {
    const space = await fixtures.space('draft_space', { tags: 'before', extra: '{"legacy":0}' }); const app = await fixtures.app('draft_app', id(space.id), { title: 'Before', tags: 'before', extra: '{"legacy":false}' })
    const appList = async () => (await backend.call<PageDTO<RecordDTO>>('/appInfo/list', { method: 'POST', data: { appId: app.id, showMyRelated: false, index: 0, pageSize: 10 } })).data[0]
    await page.goto('/#/admin/app'); await page.reload(); await fill(page, 'Application ID', id(app.id)); await query(page, '/appInfo/list'); await selectors.row(page, String(app.appName)).getByRole('button', { name: 'Edit', exact: true }).click(); let dialog = selectors.dialog(page, 'Edit application'); await fill(dialog, 'Description', 'Discarded'); await fill(dialog, 'Tags', 'discarded'); await cancelDialog(page, 'Edit application'); expect(await appList()).toMatchObject({ title: 'Before', tags: 'before' }); await page.reload(); await fill(page, 'Application ID', id(app.id)); await query(page, '/appInfo/list'); await selectors.row(page, String(app.appName)).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit application')
    const savedFields = { title: 'Saved 😀 &+', tags: ownedName('changed_tags'), extra: '{"future":{"enabled":false,"count":0}}' }; await fill(dialog, 'Description', savedFields.title); await fill(dialog, 'Tags', savedFields.tags); await fill(dialog, 'Extra configuration', savedFields.extra); await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); await expect(dialog).not.toBeVisible(); await page.reload(); await fill(page, 'Application ID', id(app.id)); await query(page, '/appInfo/list'); await selectors.row(page, String(app.appName)).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit application'); for (const [label, value] of [['Description', savedFields.title], ['Tags', savedFields.tags], ['Extra configuration', savedFields.extra]]) await expect(dialog.getByLabel(label, { exact: true }).filter({ visible: true })).toHaveValue(value); expect(await appList()).toMatchObject(savedFields)
    await fill(dialog, 'Description', 'Offline draft preserved'); await page.context().setOffline(true); await dialog.getByRole('button', { name: 'Save', exact: true }).click(); await expect(dialog.getByRole('alert')).toBeVisible(); await expect(dialog.getByLabel('Description', { exact: true }).filter({ visible: true })).toHaveValue('Offline draft preserved'); expect((await appList()).title).toBe(savedFields.title); await page.context().setOffline(false); const retried = await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(retried.success).toBe(true); expect((await appList()).title).toBe('Offline draft preserved')
    await page.getByRole('button', { name: 'New application', exact: true }).click(); dialog = selectors.dialog(page, 'New application'); await expect(dialog.locator('.role-chip')).toHaveCount(0); await expect(dialog.getByLabel('Application name', { exact: true }).filter({ visible: true })).toHaveValue(''); await choose(dialog, 'Namespace', String(space.name) + '(' + String(space.code) + ')'); await fill(dialog, 'Application name', String(app.appName)); await secretFill(dialog.getByLabel('Application password', { exact: true }).filter({ visible: true }), 'Duplicate-' + crypto.randomUUID()); await fill(dialog, 'Description', 'New separate app'); const duplicate = await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(duplicate.success).toBe(false); await expect(dialog.getByRole('alert')).toBeVisible(); await expect(dialog.getByLabel('Description', { exact: true }).filter({ visible: true })).toHaveValue('New separate app'); const otherName = ownedName('draft_other_app'); await fill(dialog, 'Application name', otherName); const created = await clickAndResponse<RecordDTO>(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(created.success).toBe(true); const otherApp = fixtures.trackApp(created.data); expect(id(otherApp.id)).not.toBe(id(app.id)); expect((await appList()).title).toBe('Offline draft preserved')
    const workerHeaders: string[] = []; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/system/listWorker')) workerHeaders.push(request.headers().appid || '') }); for (const target of [app, otherApp, app]) { await enterApplication(page, String(target.appName)); await expect(page.getByRole('link', { name: 'Switch application', exact: true })).toContainText(String(target.appName)); await expect(page.getByText('No Workers connected', { exact: true })).toBeVisible(); expect(workerHeaders).toContain(id(target.id)) }
    await page.goto('/#/admin/namespace'); await fill(page, 'Code', String(space.code)); await query(page, '/namespace/list'); await selectors.row(page, String(space.code)).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit namespace'); await fill(dialog, 'Name', 'Discarded namespace'); await fill(dialog, 'Tags', 'discarded'); await cancelDialog(page, 'Edit namespace'); const before = (await backend.call<PageDTO<RecordDTO>>('/namespace/list', { method: 'POST', data: { codeLike: space.code, index: 0, pageSize: 10 } })).data[0]; expect(before).toMatchObject({ name: space.name, tags: 'before', extra: '{"legacy":0}' })
    await page.getByRole('button', { name: 'New namespace', exact: true }).click(); dialog = selectors.dialog(page, 'New namespace'); await expect(dialog.getByLabel('Code', { exact: true }).filter({ visible: true })).toHaveValue(''); await expect(dialog.locator('.role-chip')).toHaveCount(0); await fill(dialog, 'Code', String(space.code)); await fill(dialog, 'Name', 'Retained namespace draft'); const duplicateSpace = await clickAndResponse(page, '/namespace/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(duplicateSpace.success).toBe(false); await expect(dialog.getByRole('alert')).toBeVisible(); const otherCode = ownedName('draft_other_space'); await fill(dialog, 'Code', otherCode); const createdSpace = await clickAndResponse<RecordDTO>(page, '/namespace/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(createdSpace.success).toBe(true); const otherSpace = fixtures.trackSpace(createdSpace.data)
    await fill(page, 'Code', String(space.code)); await query(page, '/namespace/list'); await selectors.row(page, String(space.code)).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit namespace'); await fill(dialog, 'Name', ownedName('updated_space')); await fill(dialog, 'Tags', 'updated'); await fill(dialog, 'Extra configuration', '{"future":false}'); const savedSpace = await clickAndResponse(page, '/namespace/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click()); expect(savedSpace.success).toBe(true); await page.reload(); await fill(page, 'Code', String(space.code)); await query(page, '/namespace/list'); await selectors.row(page, String(space.code)).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit namespace'); await expect(dialog.getByLabel('Code', { exact: true }).filter({ visible: true })).toHaveValue(String(space.code)); await expect(dialog.getByLabel('Name', { exact: true }).filter({ visible: true })).toHaveValue(ownedName('updated_space')); const savedReadback = (await backend.call<PageDTO<RecordDTO>>('/namespace/list', { method: 'POST', data: { codeLike: space.code, index: 0, pageSize: 10 } })).data[0]; expect(savedReadback).toMatchObject({ tags: 'updated', extra: '{"future":false}', token: before.token }); await cancelDialog(page, 'Edit namespace')
    await page.goto('/#/admin/app'); await fill(page, 'Application ID', id(otherApp.id)); await query(page, '/appInfo/list'); await selectors.row(page, String(otherApp.appName)).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page, 'Edit application'); let appDeletes = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/appInfo/delete')) appDeletes++ }); await dialog.getByRole('button', { name: 'Delete', exact: true }).click(); await confirmDialog(page, false); expect(appDeletes).toBe(0); expect((await backend.call<PageDTO<RecordDTO>>('/appInfo/list', { method: 'POST', data: { appId: otherApp.id, showMyRelated: false, index: 0, pageSize: 10 } })).data).toHaveLength(1); const deleted = await clickAndResponse(page, '/appInfo/delete', async () => { await dialog.getByRole('button', { name: 'Delete', exact: true }).click(); await confirmDialog(page) }); expect(deleted.success).toBe(true); await page.reload(); await fill(page, 'Application ID', id(otherApp.id)); const absent = await query(page, '/appInfo/list'); expect(absent.data).toHaveLength(0)
    await page.goto('/#/admin/namespace'); await fill(page, 'Code', String(otherSpace.code)); await query(page, '/namespace/list'); let spaceDeletes = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/namespace/delete')) spaceDeletes++ }); await selectors.row(page, String(otherSpace.code)).getByRole('button', { name: 'Delete', exact: true }).click(); await confirmDialog(page, false); expect(spaceDeletes).toBe(0); await page.reload(); await fill(page, 'Code', String(otherSpace.code)); const retained = await query(page, '/namespace/list'); expect(retained.data.map(row => id(row.id))).toEqual([id(otherSpace.id)])
    for (const [caseId, variants] of Object.entries({ 'UI-004': ['edit-cancel', 'edit-save-reopen', 'edit-then-create', 'duplicate-create', 'enter-switch-app'], 'UI-005': ['delete-cancel', 'delete-confirm'], 'UI-006': ['cancel-isolation', 'delete-empty-cancel'], 'UI-030': ['network-recovery'] })) for (const variant of variants) await observation(info, caseId, variant, { actualNetworkOfflineAndRecovery: true, originalServerBusinessDuplicateErrors: true, draftPersistedAndRetried: true, browserRefreshReadback: true, exactOwnedAppIds: [id(app.id), id(otherApp.id)], exactOwnedNamespaceIds: [id(space.id), id(otherSpace.id)], zeroRequestDeleteCancellationChecked: true })
  } finally { await page.context().setOffline(false); await fixtures.cleanup(info) }
})
