import fs from 'node:fs/promises'
import crypto from 'node:crypto'
import { test, expect, selectors, fill, clickAndResponse, cancelDialog, confirmDialog, enterSamples, id, ownedName, fileHash, observation, type RecordDTO } from './helpers'
import { OwnedResources } from './owned'
import { bothWorkersAtVersion } from './container-ui'
import { zipEntries, zipEntry } from './zip-oracle'

test.use({ actionTimeout: 15_000 })

test('UI-026 · native template fields, Java 8/11 real ZIP bytes and invalid package recovery', async ({ page, backend, credentials }, info) => {
  await enterSamples(page, credentials)
  await page.goto('/#/oms/template')
  let generatedRequests = 0
  let downloads = 0
  page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/container/downloadContainerTemplate')) generatedRequests++ })
  page.on('download', () => downloads++)
  await page.getByRole('button', { name: 'Generate & download', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Complete all required fields')
  expect(generatedRequests).toBe(0)
  expect(downloads).toBe(0)
  await observation(info, 'UI-026', 'template-missing-fields', { nativeEmptySubmitRejected: true, zeroTemplateRequestsAndDownloads: true })
  const packageName = 'com.example.处理器_$'
  for (const [label, value] of [['Group', 'com.example.fixture'], ['Artifact', 'fev3-processors'], ['Name', ownedName('template')], ['Package name', packageName]]) await fill(page, label, value)
  const files: RecordDTO[] = []
  for (const version of ['8', '11']) {
    await page.getByLabel('Java Version', { exact: true }).selectOption(version)
    const waiting = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Generate & download', exact: true }).click()
    const file = info.outputPath(`native-java-${version}.zip`)
    await (await waiting).saveAs(file)
    const bytes = await fs.readFile(file)
    expect(bytes.subarray(0, 2).toString()).toBe('PK')
    const listing = zipEntries(file)
    const pomName = listing.find(entry => entry.endsWith('/pom.xml') || entry === 'pom.xml')
    expect(pomName).toBeTruthy()
    const pom = zipEntry(file, pomName!).toString('utf8')
    expect(pom).toContain('<groupId>com.example.fixture</groupId>')
    expect(pom).toContain('<artifactId>fev3-processors</artifactId>')
    expect(pom).toContain(ownedName('template'))
    expect(pom).toMatch(new RegExp(`<maven.compiler.source>(?:1\\.)?${version}<`))
    expect(pom).toMatch(new RegExp(`<maven.compiler.target>(?:1\\.)?${version}<`))
    expect(listing.some(entry => entry.includes(packageName.replaceAll('.', '/')))).toBe(true)
    files.push({ java: version, bytes: bytes.length, sha256: await fileHash(file), compileStatus: 'NOT_RUN_IN_THIS_ZIP_STRUCTURE_TEST' })
  }
  await observation(info, 'UI-026', 'template-java-versions', { actualNativeSelections: ['8', '11'], originalServerGeneratedZIPsAndSourceTarget: files })
  await observation(info, 'UI-026', 'template-all-fields', { actualGroupArtifactNameAndUnicodePackageInDownloadedZIP: true, files, independentCompilation: 'NOT_RUN_IN_THIS_TEST' })
  await page.getByLabel('Java Version', { exact: true }).selectOption('11')
  const beforeRequests = generatedRequests
  const beforeDownloads = downloads
  const invalidNames = ['wrong package', '9start.name', 'a..b', 'class.example', 'a._.b']
  for (const invalid of invalidNames) {
    await fill(page, 'Package name', invalid)
    await page.getByRole('button', { name: 'Generate & download', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Enter a valid package name')
    await expect(page.getByLabel('Package name', { exact: true })).toHaveValue(invalid)
    expect(generatedRequests).toBe(beforeRequests)
    expect(downloads).toBe(beforeDownloads)
  }
  await fill(page, 'Package name', packageName)
  const correctedDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Generate & download', exact: true }).click()
  const corrected = info.outputPath('corrected-package.zip')
  await (await correctedDownload).saveAs(corrected)
  expect((await fs.readFile(corrected)).subarray(0, 2).toString()).toBe('PK')
  await observation(info, 'UI-026', 'template-invalid-identifiers', { invalidNames, allRejectedWithoutNetworkOrDownload: true, retainedDrafts: true, correctedUnicodePackageNativeZIP: await fileHash(corrected) })
})

test('UI-027 · fresh native JAR upload, hard reopen, real WS dispatch, two Worker readback and EXTERNAL success', async ({ page, backend, credentials }, info) => {
  test.setTimeout(180_000)
  const fixture = process.env.POWERJOB_E2E_CONTAINER_JAR
  const processor = process.env.POWERJOB_E2E_CONTAINER_PROCESSOR
  test.skip(!fixture || !processor, 'BLOCKED: configure the trusted isolated JAR and its deterministic Processor class')
  await fs.access(fixture!)
  const ledger = new OwnedResources(backend)
  const name = ownedName('jar_container')
  const jobName = ownedName('external_job')
  try {
    await enterSamples(page, credentials)
    const initialWorkers = await backend.call<RecordDTO[]>('/system/listWorker', { query: { appId: backend.appId } })
    expect(initialWorkers.length).toBeGreaterThanOrEqual(2)
    const workerAddresses = initialWorkers.map(value => String(value.address))
    await page.goto('/#/oms/containermanage')
    await page.getByRole('button', { name: 'New container', exact: true }).click()
    let dialog = selectors.dialog(page, 'New container')
    await fill(dialog, 'Container name', name)
    await dialog.getByLabel('Container type', { exact: true }).selectOption('FatJar')
    const upload = await clickAndResponse<string>(page, '/container/jarUpload', () => dialog.getByLabel('Upload JAR', { exact: true }).setInputFiles(fixture!))
    expect(upload.success).toBe(true)
    expect(upload.data).toBe(crypto.createHash('md5').update(await fs.readFile(fixture!)).digest('hex'))
    expect((await clickAndResponse(page, '/container/save', () => dialog.getByRole('button', { name: 'Save container', exact: true }).click())).success).toBe(true)
    await expect(dialog).not.toBeVisible()
    const container = (await backend.containers()).find(value => value.containerName === name)!
    const containerId = ledger.track('container', id(container.id), name)
    expect(container.sourceInfo).toBe(upload.data)
    const storedJar = await backend.file('/container/downloadJar', { version: upload.data })
    expect(storedJar.sha256).toBe(await fileHash(fixture!))
    await observation(info, 'UI-027', 'jar-upload-create', { containerId, actualNativeMultipartUploadAndSave: true, originalServerMD5: upload.data, storedJARSHA256: storedJar.sha256 })
    await page.reload()
    const row = selectors.row(page, name)
    await row.getByRole('button', { name: 'Edit', exact: true }).click()
    dialog = selectors.dialog(page, 'Edit container')
    await expect(dialog.getByLabel('Container type', { exact: true })).toHaveValue('FatJar')
    await expect(dialog).toContainText('The existing JAR is retained')
    const renamed = name + '_edited'
    await fill(dialog, 'Container name', renamed)
    expect((await clickAndResponse(page, '/container/save', () => dialog.getByRole('button', { name: 'Save container', exact: true }).click())).success).toBe(true)
    await expect(dialog).not.toBeVisible()
    await page.reload()
    const renamedRow = selectors.row(page, renamed)
    await renamedRow.getByRole('button', { name: 'Edit', exact: true }).click()
    dialog = selectors.dialog(page, 'Edit container')
    await expect(dialog.getByLabel('Container name', { exact: true })).toHaveValue(renamed)
    await cancelDialog(page, 'Edit container')
    expect((await backend.containers()).find(value => id(value.id) === containerId)?.sourceInfo).toBe(upload.data)
    await observation(info, 'UI-027', 'jar-edit-reopen', { containerId, nativeRenameThenHardReloadReopen: true, originalJARSourceInfoPreserved: true })
    await renamedRow.getByRole('button', { name: 'Deploy', exact: true }).click()
    const deployment = selectors.dialog(page, `Deploy container · ${renamed}`)
    await expect(deployment.locator('[data-status="success"]')).toContainText('Deployment was submitted', { timeout: 120_000 })
    await expect(deployment.locator('pre')).toContainText('deploy finished, congratulations!')
    await deployment.getByRole('button', { name: 'Close', exact: true }).click()
    await expect(deployment).not.toBeVisible()
    let deployed = ''
    await expect.poll(async () => {
      await renamedRow.getByRole('button', { name: 'More', exact: true }).click()
      await selectors.dialog(page, renamed).getByRole('button', { name: 'Deployed Workers', exact: true }).click()
      const workers = selectors.dialog(page, `Deployed Workers · ${renamed}`)
      await expect(workers.locator('pre')).not.toHaveText('Waiting for logs…')
      deployed = await workers.locator('pre').innerText()
      await workers.getByRole('button', { name: 'Close', exact: true }).click()
      await expect(workers).not.toBeVisible()
      return bothWorkersAtVersion(deployed, upload.data, initialWorkers)
    }, { timeout: 120_000, intervals: [1000, 2000], message: 'Dispatch completion is insufficient: both real Worker addresses and the uploaded version must be visible' }).toBe(true)
    const actualDeployed = await backend.call<string>('/container/listDeployedWorker', { query: { containerId } })
    for (const address of workerAddresses) expect(actualDeployed).toContain(address)
    expect(bothWorkersAtVersion(actualDeployed, upload.data, initialWorkers)).toBe(true)
    await observation(info, 'UI-027', 'jar-deploy-two-workers', { containerId, realWSDispatch: true, dispatchedLabelAccurate: true, realTwoWorkerReadback: actualDeployed, uploadedVersion: upload.data, noMultiHostHAClaim: true })
    await page.goto('/#/oms/job')
    await page.getByRole('button', { name: 'New job', exact: true }).click()
    dialog = selectors.dialog(page, 'New job')
    await fill(dialog, 'Job name', jobName)
    await dialog.getByLabel('Processor type', { exact: true }).selectOption('EXTERNAL')
    await fill(dialog, 'Processor', `${containerId}#${processor}`)
    await fill(dialog, 'Job parameters', process.env.POWERJOB_E2E_CONTAINER_PARAMS || '{"sql":"SELECT 1 AS id WHERE 1=0","showResult":true}')
    expect((await clickAndResponse(page, '/job/save', () => dialog.getByRole('button', { name: 'Save job', exact: true }).click())).success).toBe(true)
    await expect(dialog).not.toBeVisible()
    const job = (await backend.listJobs(jobName)).data.find(value => value.jobName === jobName)!
    ledger.track('job', id(job.id), jobName)
    expect(job.processorType).toBe('EXTERNAL')
    await page.reload()
    await fill(page, 'Keyword', jobName)
    expect((await clickAndResponse(page, '/job/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === jobName)).success).toBe(true)
    await selectors.row(page, jobName).getByRole('button', { name: 'Edit', exact: true }).click()
    dialog = selectors.dialog(page, 'Edit job')
    await expect(dialog.getByLabel('Processor type', { exact: true })).toHaveValue('EXTERNAL')
    await expect(dialog.getByLabel('Processor', { exact: true })).toHaveValue(`${containerId}#${processor}`)
    await cancelDialog(page, 'Edit job')
    const run = await clickAndResponse(page, '/job/run', () => selectors.row(page, jobName).getByRole('button', { name: 'Run', exact: true }).click())
    expect(run.success).toBe(true)
    const instanceId = ledger.trackInstance(id(run.data), id(job.id))
    const instance = await backend.waitInstance(instanceId, [5])
    await observation(info, 'UI-012', 'processorType-external', { containerId, actualUploadedDeployedProcessor: processor, hardReloadNativeReopen: true, exactInstanceId: instanceId, actualWorkerStatus: instance.status })
    await observation(info, 'UI-027', 'jar-processor-run', { containerId, jobId: id(job.id), exactInstanceId: instanceId, actualWorkerStatus: instance.status, result: instance.result })
    await observation(info, 'UI-027', 'root-context-path', { actualFormalServerRootContextUploadDispatchTwoWorkerReadbackAndExternalRun: true, sourceJARSHA256: storedJar.sha256, instanceId })
    // Remove the owned job through its exact ledger before testing UI container deletion; no reference can be hidden.
    await backend.call('/job/delete', { query: { jobId: id(job.id) } })
    await page.goto('/#/oms/containermanage')
    let deletes = 0
    page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/container/delete')) deletes++ })
    await renamedRow.getByRole('button', { name: 'More', exact: true }).click()
    await selectors.dialog(page, renamed).getByRole('button', { name: 'Delete container', exact: true }).click()
    await confirmDialog(page, false)
    expect(deletes).toBe(0)
    await expect(renamedRow).toHaveCount(1)
    await observation(info, 'UI-027', 'jar-delete-cancel', { zeroNativeDeleteRequests: true, realOwnedContainerStillActive: true })
    await renamedRow.getByRole('button', { name: 'More', exact: true }).click()
    await selectors.dialog(page, renamed).getByRole('button', { name: 'Delete container', exact: true }).click()
    expect((await clickAndResponse(page, '/container/delete', () => confirmDialog(page))).success).toBe(true)
    expect(deletes).toBe(1)
    await expect(renamedRow).toHaveCount(0)
    expect((await backend.containers()).some(value => id(value.id) === containerId)).toBe(false)
    await observation(info, 'UI-027', 'jar-delete-confirm', { realNativeDeleteAndActiveServerListAbsence: true, exactContainerId: containerId })
  } finally { await ledger.cleanup(info) }
})
