import fs from 'node:fs/promises'
import { test, expect, selectors, fill, clickAndResponse, confirmDialog, enterSamples, id, ownedName, processors, observation, fileHash, type RecordDTO } from './helpers'
import { createJob, editJob, saveJob } from './job-ui'
import { OwnedResources } from './owned'

test.use({ actionTimeout: 15_000 })

test('UI-016/017/019 · exact instance filters, real detail, late online logs and original authenticated download bytes', async ({ page, backend, credentials }, info) => {
  test.setTimeout(180_000)
  const ledger = new OwnedResources(backend)
  const name = ownedName('instance_read')
  const marker = ownedName('log_marker_CN')
  try {
    await enterSamples(page, credentials)
    const job = await createJob(page, backend, ledger, name, processors.simple, marker)
    const run = await clickAndResponse(page, '/job/run', () => selectors.row(page, name).getByRole('button', { name: 'Run', exact: true }).click())
    expect(run.success).toBe(true)
    const instanceId = ledger.trackInstance(id(run.data), id(job.id))
    const actual = await backend.waitInstance(instanceId, [5])
    await page.goto('/#/oms/instance?jobId=' + id(job.id))
    await expect(page.getByLabel('Job ID', { exact: true })).toHaveValue(id(job.id))
    await fill(page, 'Instance ID', instanceId)
    await page.getByLabel('Status', { exact: true }).selectOption('SUCCEED')
    const query = await clickAndResponse(page, '/instance/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.instanceId === instanceId)
    expect(query.success).toBe(true)
    const row = selectors.row(page, instanceId)
    await expect(row).toHaveCount(1)
    await expect(row).toContainText(name)
    await expect(row).toContainText('Succeeded')
    await observation(info, 'UI-016', 'instance-id-filters', { jobId: id(job.id), instanceId, actualFilterRequestAndRealRow: true })
    await observation(info, 'UI-016', 'status-filters', { actualStatusQuery: 'SUCCEED', exactRealSucceededRow: true })
    const detail = await clickAndResponse<RecordDTO>(page, '/instance/detailPlus', () => row.getByRole('button', { name: 'Details', exact: true }).click(), response => response.request().postDataJSON()?.instanceId === instanceId)
    expect(detail.success).toBe(true)
    const dialog = selectors.dialog(page, `Instance details #${instanceId}`)
    await expect(dialog).toContainText(instanceId)
    await expect(dialog).toContainText(String(actual.result))
    await expect(dialog.getByRole('button', { name: 'Refresh details', exact: true })).toBeVisible()
    await observation(info, 'UI-017', 'detail-normal-finished', { instanceId, actualWorkerStatus: actual.status, actualDetailRequest: true, realResultVisible: actual.result })
    const logs = await clickAndResponse(page, '/instance/log', () => dialog.getByRole('button', { name: 'Logs', exact: true }).click(), response => new URL(response.url()).searchParams.get('instanceId') === instanceId)
    expect(logs.success).toBe(true)
    const region = dialog.getByRole('region', { name: 'Online logs', exact: true })
    await expect.poll(async () => {
      const response = await clickAndResponse<{ data: string }>(page, '/instance/log', () => region.getByRole('button', { name: 'Refresh logs', exact: true }).click(), value => new URL(value.url()).searchParams.get('instanceId') === instanceId)
      expect(response.success).toBe(true)
      return response.data.data.includes(marker)
    }, { timeout: 90_000, intervals: [1000, 2000], message: 'The exact finished instance must archive its own Processor marker' }).toBe(true)
    await expect(region.locator('pre')).toContainText(marker)
    const original = await backend.file('/instance/downloadLog4Console', { instanceId })
    expect(original.bytes.toString('utf8')).toContain(marker)
    const waitingDownload = page.waitForEvent('download')
    await region.getByRole('button', { name: 'Download logs', exact: true }).click()
    const file = info.outputPath('actual-instance.log')
    await (await waitingDownload).saveAs(file)
    expect(await fileHash(file)).toBe(original.sha256)
    expect(await fs.readFile(file, 'utf8')).toContain(marker)
    await observation(info, 'UI-019', 'live-log-refresh', { instanceId, ownProcessorMarkerVisible: marker, realRefreshRequests: true })
    await observation(info, 'UI-019', 'archived-download', { instanceId, nativeDownloadMatchedOriginalAuthenticatedServerBytes: true, sha256: original.sha256, byteCount: original.bytes.length })
    let latePolls = 0
    await region.getByLabel('Auto refresh', { exact: true }).check()
    await dialog.getByRole('button', { name: 'Close', exact: true }).click()
    await expect(dialog).not.toBeVisible()
    page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/instance/log')) latePolls++ })
    await page.waitForTimeout(11_000)
    expect(latePolls).toBe(0)
    await observation(info, 'UI-038', 'log-poll-close', { exactInstanceId: instanceId, autoRefreshEnabledThenNativeDialogClosed: true, observedMilliseconds: 11000, subsequentLogRequests: 0 })
  } finally { await ledger.cleanup(info) }
})

test('UI-018 · real running instance Stop cancel makes zero writes and confirm reaches terminal state', async ({ page, backend, credentials }, info) => {
  test.setTimeout(180_000)
  const ledger = new OwnedResources(backend)
  const name = ownedName('instance_stop')
  try {
    await enterSamples(page, credentials)
    const job = await createJob(page, backend, ledger, name, processors.timeout, '60000')
    const run = await clickAndResponse(page, '/job/run', () => selectors.row(page, name).getByRole('button', { name: 'Run', exact: true }).click())
    expect(run.success).toBe(true)
    const instanceId = ledger.trackInstance(id(run.data), id(job.id))
    await backend.waitInstance(instanceId, [3])
    await page.goto('/#/oms/instance?jobId=' + id(job.id))
    await fill(page, 'Instance ID', instanceId)
    expect((await clickAndResponse(page, '/instance/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.instanceId === instanceId)).success).toBe(true)
    const row = selectors.row(page, instanceId)
    await expect(row).toContainText('Running')
    let stops = 0
    page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/instance/stop')) stops++ })
    await row.getByRole('button', { name: 'Stop', exact: true }).click()
    await confirmDialog(page, false)
    expect(stops).toBe(0)
    expect((await backend.instance(instanceId))?.status).toBe(3)
    await observation(info, 'UI-018', 'stop-cancel', { instanceId, actualRunningStatusBeforeAndAfterCancel: 3, zeroStopRequests: true })
    await row.getByRole('button', { name: 'Stop', exact: true }).click()
    expect((await clickAndResponse(page, '/instance/stop', () => confirmDialog(page), response => new URL(response.url()).searchParams.get('instanceId') === instanceId)).success).toBe(true)
    expect(stops).toBe(1)
    const stopped = await backend.waitInstance(instanceId, [10])
    await page.getByRole('button', { name: 'Refresh', exact: true }).click()
    await expect(row).toContainText('Stopped')
    await observation(info, 'UI-018', 'stop-running', { instanceId, actualWorkerTerminalStatus: stopped.status, oneExactNativeConfirmedRequest: true, realStoppedRowVisible: true })
  } finally { await ledger.cleanup(info) }
})

test('UI-018 · own failed Processor corrected through native editor retries its exact existing instance to real success', async ({ page, backend, credentials }, info) => {
  test.setTimeout(180_000)
  const ledger = new OwnedResources(backend)
  const name = ownedName('instance_retry')
  try {
    await enterSamples(page, credentials)
    const job = await createJob(page, backend, ledger, name, processors.simple, 'F')
    const run = await clickAndResponse(page, '/job/run', () => selectors.row(page, name).getByRole('button', { name: 'Run', exact: true }).click())
    expect(run.success).toBe(true)
    const instanceId = ledger.trackInstance(id(run.data), id(job.id))
    await backend.waitInstance(instanceId, [4])
    const editor = await editJob(page, name)
    // Formal 5.1.6 retries preserve the original instance jobParams. Change only the owned job Processor to one that accepts that snapshot.
    await fill(editor, 'Processor', processors.standalone)
    await saveJob(page)
    await page.goto('/#/oms/instance?jobId=' + id(job.id))
    await fill(page, 'Instance ID', instanceId)
    expect((await clickAndResponse(page, '/instance/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.instanceId === instanceId)).success).toBe(true)
    const row = selectors.row(page, instanceId)
    await expect(row).toContainText('Failed')
    expect((await clickAndResponse(page, '/instance/retry', () => row.getByRole('button', { name: 'Retry', exact: true }).click(), response => new URL(response.url()).searchParams.get('instanceId') === instanceId)).success).toBe(true)
    const succeeded = await backend.waitInstance(instanceId, [5])
    expect(Number(succeeded.runningTimes)).toBeGreaterThan(1)
    const snapshot = await backend.call<RecordDTO>('/instance/detailPlus', { method: 'POST', data: { instanceId, customQuery: 'status in (5, 6) order by last_modified_time desc' } })
    expect(snapshot.jobParams).toBe('F')
    await page.getByRole('button', { name: 'Refresh', exact: true }).click()
    await expect(row).toContainText('Succeeded')
    await observation(info, 'UI-018', 'retry-failed', { instanceId, failedThenNativeOwnedProcessorEditAndRetry: true, originalInstanceParameterSnapshotPreservedFromDetailPlus: snapshot.jobParams, actualFinalWorkerStatus: succeeded.status, actualRunCount: succeeded.runningTimes })
  } finally { await ledger.cleanup(info) }
})
