import { jobSection } from './job-ui'
import { test, expect, selectors, fill, check, clickAndResponse, cancelDialog, enterSamples, id, ownedName, processors, observation } from './helpers'
import { OwnedResources } from './owned'
import { cronCases, configureCron, validateCron } from './cron-oracle'

for (const rule of cronCases) {
  test(`UI-012 · fresh native Job CRON ${rule.key} builder, real Server calendar validation and hard-refresh persistence`, async ({ page, backend, credentials }, info) => {
    const ledger = new OwnedResources(backend)
    const name = ownedName(`cron_job_${rule.key}`)
    try {
      await enterSamples(page, credentials)
      await page.goto('/#/oms/job')
      await page.getByRole('button', { name: 'New job', exact: true }).click()
      const editor = selectors.dialog(page, 'New job')
      await fill(editor, 'Job name', name)
      await fill(editor, 'Processor', processors.simple)
      await check(editor, 'Enable job', false)
      await jobSection(editor, 'Schedule')
      await editor.getByLabel('Schedule type', { exact: true }).selectOption('CRON')
      const manual = '0 11 13 ? * MON#2 *'
      await fill(editor, 'Schedule expression', manual)
      const draft = await configureCron(page, editor, rule, false)
      expect(await editor.getByLabel('Schedule expression', { exact: true }).inputValue()).toBe(manual)
      await cancelDialog(page, 'CRON quick setup')
      await expect(editor.getByLabel('Schedule expression', { exact: true })).toHaveValue(manual)
      await expect(editor.getByRole('button', { name: 'Quick setup', exact: true })).toBeFocused()
      await configureCron(page, editor, rule)
      await expect(editor.getByLabel('Schedule expression', { exact: true })).toHaveValue(rule.expression)
      const dates = await validateCron(page, editor, backend, rule)
      // Opening a supported generated expression must restore that rule; complex expressions remain untouched until Apply.
      await editor.getByRole('button', { name: 'Quick setup', exact: true }).click()
      await expect(draft.getByLabel('Frequency', { exact: true })).toHaveValue(rule.frequency)
      for (const [label, value] of Object.entries(rule.fields)) await expect(draft.getByLabel(label, { exact: true })).toHaveValue(String(value))
      await draft.getByLabel('Frequency', { exact: true }).press('Escape')
      await expect(draft).not.toBeVisible()
      await expect(editor.getByRole('button', { name: 'Quick setup', exact: true })).toBeFocused()
      await expect(editor.getByLabel('Schedule expression', { exact: true })).toHaveValue(rule.expression)
      expect((await clickAndResponse(page, '/job/save', () => editor.getByRole('button', { name: 'Save job', exact: true }).click())).success).toBe(true)
      await expect(editor).not.toBeVisible()
      const saved = (await backend.listJobs(name)).data.find(job => job.jobName === name)!
      ledger.track('job', id(saved.id), name)
      expect(saved.timeExpressionType).toBe('CRON')
      expect(saved.timeExpression).toBe(rule.expression)
      expect(saved.enable).toBe(false)
      await page.reload()
      await fill(page, 'Keyword', name)
      expect((await clickAndResponse(page, '/job/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === name)).success).toBe(true)
      await selectors.row(page, name).getByRole('button', { name: 'Edit', exact: true }).click()
      const reopened = selectors.dialog(page, 'Edit job')
      await jobSection(reopened, 'Schedule')
      await expect(reopened.getByLabel('Schedule expression', { exact: true })).toHaveValue(rule.expression)
      await cancelDialog(page, 'Edit job')
      await observation(info, 'UI-012', `fev3-cron-job-${rule.key}`, { jobId: id(saved.id), expression: rule.expression, realNativeCreateAndReadback: true, realServerCalendar: dates, hardRefreshAndReopen: true, recognizedDraftRestored: true, cancelAndEscapePreservedManualOrGeneratedValue: true, disabledDefinitionNoScheduledSideEffects: true })
    } finally { await ledger.cleanup(info) }
  })
}

test.use({ actionTimeout: 15_000 })

test('UI-012 · all six native schedule modes, Daily first-fill/Tab and lifecycle clearing retain real DTO values', async ({ page, backend, credentials }, info) => {
  test.setTimeout(180_000)
  const ledger = new OwnedResources(backend)
  const name = ownedName('schedule_modes')
  try {
    await enterSamples(page, credentials)
    await page.goto('/#/oms/job')
    await page.getByRole('button', { name: 'New job', exact: true }).click()
    let editor = selectors.dialog(page, 'New job')
    await fill(editor, 'Job name', name)
    await fill(editor, 'Processor', processors.simple)
    await check(editor, 'Enable job', false)
    await jobSection(editor, 'Schedule')
    await fill(editor, 'Lifecycle start', '2032-01-01T01:02:03')
    await fill(editor, 'Lifecycle end', '2033-01-01T04:05:06')
    expect((await clickAndResponse(page, '/job/save', () => editor.getByRole('button', { name: 'Save job', exact: true }).click())).success).toBe(true)
    await expect(editor).not.toBeVisible()
    const job = (await backend.listJobs(name)).data.find(value => value.jobName === name)!
    ledger.track('job', id(job.id), name)
    const start = Date.parse('2032-01-01T01:02:03+08:00')
    const end = Date.parse('2033-01-01T04:05:06+08:00')
    expect(job.lifeCycle).toMatchObject({ start, end })
    for (const [type, expression] of [['API', ''], ['CRON', '0 0 9 * * ?'], ['FIXED_RATE', '10000'], ['FIXED_DELAY', '10000'], ['WORKFLOW', ''], ['DAILY_TIME_INTERVAL', '']] as const) {
      await fill(page, 'Keyword', name)
      expect((await clickAndResponse(page, '/job/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === name)).success).toBe(true)
      await selectors.row(page, name).getByRole('button', { name: 'Edit', exact: true }).click()
      editor = selectors.dialog(page, 'Edit job')
      await jobSection(editor, 'Schedule')
      await editor.getByLabel('Schedule type', { exact: true }).selectOption(type)
      if (type === 'DAILY_TIME_INTERVAL') {
        // Clear the prior numeric expression before opening the structured daily editor.
        await fill(editor, 'Schedule expression', '')
        await editor.getByRole('button', { name: 'Set daily interval', exact: true }).click()
        const daily = selectors.dialog(page, 'Daily interval')
        await fill(daily, 'Interval', 7)
        await daily.getByLabel('Unit', { exact: true }).selectOption('MINUTES')
        await fill(daily, 'Daily start time', '09:05:07')
        await daily.getByLabel('Daily start time', { exact: true }).press('Tab')
        await fill(daily, 'Daily end time', '18:23:45')
        await daily.getByLabel('Daily end time', { exact: true }).press('Tab')
        for (const day of ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']) await check(daily, day, day === 'Monday' || day === 'Wednesday')
        await daily.getByRole('button', { name: 'Apply configuration', exact: true }).click()
        await expect(daily).not.toBeVisible()
      } else if (expression) await fill(editor, 'Schedule expression', expression)
      expect((await clickAndResponse(page, '/job/save', () => editor.getByRole('button', { name: 'Save job', exact: true }).click())).success).toBe(true)
      await expect(editor).not.toBeVisible()
      const actual = (await backend.job(id(job.id)))!
      expect(actual.timeExpressionType).toBe(type)
      expect(actual.enable).toBe(false)
      expect(actual.lifeCycle).toMatchObject({ start, end })
      if (type === 'DAILY_TIME_INTERVAL') expect(JSON.parse(String(actual.timeExpression))).toMatchObject({ interval: 7, intervalUnit: 'MINUTES', startTimeOfDay: '09:05:07', endTimeOfDay: '18:23:45', daysOfWeek: [1, 3] })
      else if (expression) expect(actual.timeExpression).toBe(expression)
      await observation(info, 'UI-012', `timeExpressionType-${type.toLowerCase()}`, { jobId: id(job.id), nativeModeChangedAndSaved: true, actualType: actual.timeExpressionType, actualExpression: actual.timeExpression, actualLifecycle: actual.lifeCycle, disabledDefinition: true, actualSchedulingExecution: 'NOT_RUN_IN_THIS_ROUNDTRIP_TEST' })
    }
    await selectors.row(page, name).getByRole('button', { name: 'Edit', exact: true }).click()
    editor = selectors.dialog(page, 'Edit job')
    await jobSection(editor, 'Schedule')
    await fill(editor, 'Lifecycle start', '')
    await fill(editor, 'Lifecycle end', '')
    expect((await clickAndResponse(page, '/job/save', () => editor.getByRole('button', { name: 'Save job', exact: true }).click())).success).toBe(true)
    expect((await backend.job(id(job.id)))?.lifeCycle).toMatchObject({ start: null, end: null })
    await observation(info, 'UI-012', 'lifeCycle-valid', { realNativeEpochRoundtrip: { start, end }, browserTimezone: 'Asia/Shanghai' })
    await observation(info, 'UI-012', 'lifeCycle-unset', { realNativeClearingAndServerReadback: { start: null, end: null } })
  } finally { await ledger.cleanup(info) }
})

test('UI-012 · Daily first creation, reopen edits, cancellation and invalid range never overwrite the underlying draft', async ({ page, backend, credentials }, info) => {
  const ledger = new OwnedResources(backend)
  const name = ownedName('daily_first')
  try {
    await enterSamples(page, credentials)
    await page.goto('/#/oms/job')
    await page.getByRole('button', { name: 'New job', exact: true }).click()
    let editor = selectors.dialog(page, 'New job')
    await fill(editor, 'Job name', name)
    await fill(editor, 'Processor', processors.simple)
    await check(editor, 'Enable job', false)
    await jobSection(editor, 'Schedule')
    await editor.getByLabel('Schedule type', { exact: true }).selectOption('DAILY_TIME_INTERVAL')
    await editor.getByRole('button', { name: 'Set daily interval', exact: true }).click()
    let daily = selectors.dialog(page, 'Daily interval')
    await fill(daily, 'Interval', 8)
    await daily.getByLabel('Unit', { exact: true }).selectOption('MINUTES')
    await fill(daily, 'Daily start time', '08:15:16')
    await daily.getByLabel('Daily start time', { exact: true }).press('Tab')
    await fill(daily, 'Daily end time', '19:25:26')
    await daily.getByLabel('Daily end time', { exact: true }).press('Tab')
    for (const day of ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']) await check(daily, day, false)
    await daily.getByRole('button', { name: 'Apply configuration', exact: true }).click()
    expect((await clickAndResponse(page, '/job/save', () => editor.getByRole('button', { name: 'Save job', exact: true }).click())).success).toBe(true)
    await expect(editor).not.toBeVisible()
    const job = (await backend.listJobs(name)).data.find(value => value.jobName === name)!
    ledger.track('job', id(job.id), name)
    const first = JSON.parse(String(job.timeExpression))
    expect(first).toMatchObject({ interval: 8, intervalUnit: 'MINUTES', startTimeOfDay: '08:15:16', endTimeOfDay: '19:25:26', daysOfWeek: [] })
    await observation(info, 'UI-012', 'daily-first-create', { firstNativeCreationBeforeAnyPreviousJobSave: true, firstFillTabCommitted: true, realDailyConfig: first, emptyWeekdaysServerAllDays: true, disabledNoScheduleSideEffects: true })
    await fill(page, 'Keyword', name)
    expect((await clickAndResponse(page, '/job/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === name)).success).toBe(true)
    await selectors.row(page, name).getByRole('button', { name: 'Edit', exact: true }).click()
    editor = selectors.dialog(page, 'Edit job')
    await jobSection(editor, 'Schedule')
    const original = await editor.getByLabel('Schedule expression', { exact: true }).inputValue()
    await editor.getByRole('button', { name: 'Set daily interval', exact: true }).click()
    daily = selectors.dialog(page, 'Daily interval')
    await expect(daily.getByLabel('Daily start time', { exact: true })).toHaveValue('08:15:16')
    await fill(daily, 'Interval', 999)
    await cancelDialog(page, 'Daily interval')
    await expect(editor.getByLabel('Schedule expression', { exact: true })).toHaveValue(original)
    expect((await backend.job(id(job.id)))?.timeExpression).toBe(original)
    await observation(info, 'UI-012', 'daily-cancel', { originalRealServerExpressionAndEditorDraftUnchanged: true })
    await editor.getByRole('button', { name: 'Set daily interval', exact: true }).click()
    daily = selectors.dialog(page, 'Daily interval')
    await fill(daily, 'Daily start time', '20:00:00')
    await fill(daily, 'Daily end time', '10:00:00')
    await daily.getByRole('button', { name: 'Apply configuration', exact: true }).click()
    await expect(daily).toBeVisible()
    await expect(page.getByRole('alert').filter({ hasText: 'Enter a valid daily time range' })).toBeVisible()
    await expect(editor.getByLabel('Schedule expression', { exact: true })).toHaveValue(original)
    await observation(info, 'UI-012', 'daily-invalid-range', { actualInvertedDailyRangeRejected: true, underlyingExpressionAndRealServerValuePreserved: true, original })
    await fill(daily, 'Daily start time', '07:08:09')
    await fill(daily, 'Daily end time', '21:22:23')
    await fill(daily, 'Interval', 4)
    await check(daily, 'Sunday', true)
    await daily.getByRole('button', { name: 'Apply configuration', exact: true }).click()
    expect((await clickAndResponse(page, '/job/save', () => editor.getByRole('button', { name: 'Save job', exact: true }).click())).success).toBe(true)
    await expect(editor).not.toBeVisible()
    const edited = JSON.parse(String((await backend.job(id(job.id)))?.timeExpression))
    expect(edited).toMatchObject({ interval: 4, startTimeOfDay: '07:08:09', endTimeOfDay: '21:22:23', daysOfWeek: [7] })
    await page.reload()
    await fill(page, 'Keyword', name)
    expect((await clickAndResponse(page, '/job/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === name)).success).toBe(true)
    await selectors.row(page, name).getByRole('button', { name: 'Edit', exact: true }).click()
    editor = selectors.dialog(page, 'Edit job')
    await jobSection(editor, 'Schedule')
    expect(JSON.parse(await editor.getByLabel('Schedule expression', { exact: true }).inputValue())).toEqual(edited)
    await cancelDialog(page, 'Edit job')
    await observation(info, 'UI-012', 'daily-reopen-edit', { nativeEditAfterOriginalSaveAndHardReload: true, realEditedConfig: edited })
  } finally { await ledger.cleanup(info) }
})

test('UI-012 · real Server CRON invalid preview and invalid lifecycle retain native drafts without false save', async ({ page, backend, credentials }, info) => {
  const ledger = new OwnedResources(backend)
  const name = ownedName('schedule_invalid')
  try {
    await enterSamples(page, credentials)
    await page.goto('/#/oms/job')
    await page.getByRole('button', { name: 'New job', exact: true }).click()
    const editor = selectors.dialog(page, 'New job')
    await fill(editor, 'Job name', name)
    await fill(editor, 'Processor', processors.simple)
    await check(editor, 'Enable job', false)
    await jobSection(editor, 'Schedule')
    await editor.getByLabel('Schedule type', { exact: true }).selectOption('CRON')
    const valid = cronCases[0]
    await fill(editor, 'Schedule expression', valid.expression)
    const actualDates = await validateCron(page, editor, backend, valid)
    await observation(info, 'UI-012', 'cron-preview-valid', { realServerFutureDatesAndActualListMatched: actualDates })
    await fill(editor, 'Schedule expression', 'not a quartz cron')
    const invalid = await clickAndResponse<unknown>(page, '/validate/timeExpression', () => editor.getByRole('button', { name: 'Validate expression', exact: true }).click())
    expect(invalid.success).toBe(true)
    expect(Array.isArray(invalid.data)).toBe(true)
    const errorText = (invalid.data as string[]).join('\n')
    expect(errorText).not.toBe('')
    expect(errorText).not.toMatch(/^\d{4}-\d{2}-\d{2}/)
    const validation = selectors.dialog(page, 'Schedule validation')
    await expect(validation).toContainText(errorText)
    await expect(validation.getByRole('listitem')).toHaveCount(0)
    await validation.locator('footer').getByRole('button', { name: 'Close', exact: true }).click()
    await observation(info, 'UI-012', 'cron-preview-invalid', { originalServerSuccessEnvelopeWithErrorData: true, actualErrorDataVisible: errorText, zeroFakeFutureRows: true })
    await fill(editor, 'Schedule expression', valid.expression)
    await fill(editor, 'Lifecycle start', '2033-01-01T00:00')
    await fill(editor, 'Lifecycle end', '2032-01-01T00:00')
    let saves = 0
    page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/job/save')) saves++ })
    await editor.getByRole('button', { name: 'Save job', exact: true }).click()
    await expect(editor.getByRole('alert')).toContainText('Lifecycle start must not be after end')
    expect(saves).toBe(0)
    await expect(editor.getByLabel('Lifecycle start', { exact: true })).toHaveValue('2033-01-01T00:00')
    expect((await backend.listJobs(name)).data.some(value => value.jobName === name)).toBe(false)
    await observation(info, 'UI-012', 'lifeCycle-invalid', { nativeInvertedEpochDraftRetained: true, zeroServerWrites: true, noActiveJobDefinitionCreated: true })
    await cancelDialog(page, 'New job')
  } finally { await ledger.cleanup(info) }
})
