import type { Locator, Page, TestInfo } from '@playwright/test';
import fs from 'node:fs/promises';
import { test, expect, Backend, clickAndResponse, enterSamples, fill, id, observation, ownedName, parseResult, processors, selectors, type RecordDTO } from './helpers';
import { OwnedResources } from './owned';
import { configureCron, cronCases, validateCron } from './cron-oracle';

test.describe('fresh workflow operations against the real Server and Workers', () => {
  test.use({ actionTimeout: 15_000 });
  test.setTimeout(180_000);
  const receipts = new WeakMap<Page, { nodes: RecordDTO[]; requests: Promise<void>[] }>();
  const fixtureAttempts = new Map<string, { name: string; appId: string; status: string; jobId?: string; recoveryAttempts: number }[]>();
  test.beforeEach(async ({ page }, info) => { fixtureAttempts.set(info.testId, []); const ledger = { nodes: [] as RecordDTO[], requests: [] as Promise<void>[] }; receipts.set(page, ledger); page.on('response', response => { if (!new URL(response.url()).pathname.endsWith('/workflow/saveNode')) return; const reading = response.text().then(text => { const result = parseResult<RecordDTO[]>(text); if (result.success && Array.isArray(result.data)) ledger.nodes.push(...result.data); }).catch(() => {}); ledger.requests.push(reading); }); });
  test.afterEach(async ({ page }, info) => { const ledger = receipts.get(page); if (ledger) { await Promise.all(ledger.requests); const filename = info.outputPath('actual-node-response-ledger.json'); await fs.writeFile(filename, JSON.stringify({ status: 'ACTUAL_SAVE_NODE_RESPONSES_ONLY_NOT_AN_ORPHAN_DB_AUDIT', testTitle: info.title, nodes: ledger.nodes }, null, 2) + '\n'); await info.attach('actual-node-response-ledger', { path: filename, contentType: 'application/json' }); } const jobsFile = info.outputPath('fixture-job-write-ledger.json'); await fs.writeFile(jobsFile, JSON.stringify({ status: 'ATTEMPTED_API_FIXTURE_WRITES_AND_EXACT_ID_RECOVERY', testTitle: info.title, attempts: fixtureAttempts.get(info.testId) || [] }, null, 2) + '\n'); await info.attach('fixture-job-write-ledger', { path: jobsFile, contentType: 'application/json' }); fixtureAttempts.delete(info.testId); });

  async function fixtureJob(backend: Backend, owned: OwnedResources, suffix: string, params = 'success', processor: string = processors.standalone) {
    const name = ownedName(suffix), attempt = { name, appId: id(backend.appId), status: 'SAVE_ATTEMPTED', jobId: undefined as string | undefined, recoveryAttempts: 0 };
    fixtureAttempts.get(test.info().testId)!.push(attempt);
    async function exactPersistedID() {
      const matches = (await backend.listJobs(name, 0, 100)).data.filter(row => row.jobName === name);
      expect(matches, 'The exact newly created fixture name must resolve to one real persisted job').toHaveLength(1);
      const actual = matches[0]!; if (actual.appId != null) expect(id(actual.appId)).toBe(id(backend.appId));
      expect(actual.jobDescription).toBe('Synthetic workflow regression fixture'); expect(actual.processorInfo).toBe(processor);
      return id(actual.id);
    }
    try {
      // Locked d928 JobController.save returns ResultDTO<Void>; read back the exact persisted name for its ID.
      await backend.call<null>('/job/save', { method: 'POST', data: { appId: backend.appId, jobName: name, jobDescription: 'Synthetic workflow regression fixture', jobParams: params, timeExpressionType: 'API', timeExpression: '', executeType: 'STANDALONE', processorType: 'BUILT_IN', processorInfo: processor, enable: true, maxInstanceNum: 0, concurrency: 5, instanceRetryNum: 0, taskRetryNum: 0, notifyUserIds: [], lifeCycle: { start: null, end: null } } });
      attempt.status = 'SAVE_VOID_RETURNED'; const jobId = await exactPersistedID(); owned.track('job', jobId, name); attempt.jobId = jobId; attempt.status = 'EXACT_ID_TRACKED'; return { id: jobId, name };
    } catch (failure) {
      // A failed response/readback can follow a successful write; recover only this exact name/app/processor.
      for (let retry = 0; retry < 3 && !attempt.jobId; retry++) { attempt.recoveryAttempts++; try { const jobId = await exactPersistedID(); owned.track('job', jobId, name); attempt.jobId = jobId; attempt.status = 'EXACT_ID_RECOVERED_FOR_FINALLY_CLEANUP'; } catch { /* The attached attempted-write ledger retains an unresolved exact name. */ } }
      if (!attempt.jobId) attempt.status = 'WRITE_OUTCOME_UNRESOLVED_EXACT_NAME_REQUIRES_REVIEW'; throw failure;
    }
  }
  async function newWorkflow(page: Page, name: string) { await page.goto('/#/oms/workflow'); await page.getByRole('button', { name: '+ New workflow', exact: true }).click(); await fill(page, 'Workflow name', name); }
  async function importJobs(page: Page, jobIds: string[]) {
    if (jobIds.length !== 1) throw new Error('This exact-ID helper imports one job; the cross-page bulk test uses the real checkbox table');
    await page.locator('.flow-tools').getByRole('button', { name: '+ Jobs', exact: true }).click(); const dialog = selectors.dialog(page, 'Import jobs');
    for (const jobId of jobIds) { await fill(dialog, 'Job ID', jobId); await clickAndResponse(page, '/job/list', () => dialog.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.jobId === jobId); const row = dialog.getByRole('row').filter({ has: page.getByRole('cell', { name: jobId, exact: true }) }); await expect(row).toHaveCount(1); await row.getByRole('checkbox').check(); }
    // Searching intentionally clears a previous selection, so exact-ID imports are performed individually.
    const response = await clickAndResponse<RecordDTO[]>(page, '/workflow/saveNode', () => dialog.getByRole('button', { name: /^Import selected/ }).click()); expect(response.success).toBe(true); await expect(dialog).not.toBeVisible();
    return response.data.map(node => id(node.id));
  }
  async function importOne(page: Page, jobId: string) { return (await importJobs(page, [jobId]))[0]!; }
  async function save(page: Page, owned: OwnedResources, name: string) { const response = await clickAndResponse(page, '/workflow/save', () => page.getByRole('button', { name: 'Save workflow', exact: true }).click()); expect(response.success).toBe(true); const workflowId = id(response.data); owned.track('workflow', workflowId, name); await expect(page).toHaveURL(new RegExp(`workflowId=${workflowId}(?:&|$)`)); return workflowId; }
  async function saveExisting(page: Page) { const response = await clickAndResponse(page, '/workflow/save', () => page.getByRole('button', { name: 'Save workflow', exact: true }).click()); expect(response.success).toBe(true); return id(response.data); }
  async function connectNodes(page: Page, from: string, to: string) { await page.locator(`[data-node-id="${from}"]`).press('Enter'); await page.locator('.flow-tools').getByRole('button', { name: 'Connect', exact: true }).click(); await page.locator(`[data-node-id="${to}"]`).press('Enter'); }
  async function selectNode(page: Page, nodeId: string) { await page.locator(`[data-node-id="${nodeId}"]`).press('Enter'); return page.locator('.node-inspector'); }
  async function setCode(page: Page, inspector: Locator, value: string) { const editor = inspector.locator('.monaco-editor'); await expect(editor).toBeVisible(); await editor.click(); await page.keyboard.press('ControlOrMeta+A'); if (value) await page.keyboard.insertText(value); else await page.keyboard.press('Backspace'); }
  async function saveNode(page: Page, inspector: Locator) { const response = await clickAndResponse<RecordDTO[]>(page, '/workflow/saveNode', () => inspector.getByRole('button', { name: 'Save node', exact: true }).click()); expect(response.success).toBe(true); return response.data[0]!; }
  async function execute(page: Page, owned: OwnedResources, workflowId: string, parameters?: string) {
    await page.goto('/#/oms/workflow'); await fill(page, 'Workflow ID', workflowId); const listed = await clickAndResponse<{data:RecordDTO[]}>(page, '/workflow/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.workflowId === workflowId); expect(listed.success).toBe(true); expect(listed.data.data.map(row => id(row.id))).toEqual([workflowId]); const row = page.locator('.workflow-table tbody tr'); await expect(row).toHaveCount(1);
    let response;
    if (parameters !== undefined) { await row.getByRole('button', { name: 'Run with parameters', exact: true }).click(); const dialog = selectors.dialog(page, 'Run with parameters'); await fill(dialog, 'Initial parameters', parameters); response = await clickAndResponse(page, '/workflow/run', () => dialog.getByRole('button', { name: 'Run workflow', exact: true }).click()); }
    else response = await clickAndResponse(page, '/workflow/run', () => row.getByRole('button', { name: 'Run', exact: true }).click());
    expect(response.success).toBe(true); const instanceId = id(response.data); owned.trackInstance(instanceId, workflowId, 'WF_INSTANCE'); return instanceId;
  }
  function nodes(value: RecordDTO) { return (value.peworkflowDAG as { nodes: RecordDTO[] }).nodes; }
  function recordChildren(owned: OwnedResources, value: RecordDTO) { for (const node of nodes(value)) if (node.instanceId && Number(node.nodeType) === 1) owned.trackInstance(id(node.instanceId), id(node.jobId), 'WORKFLOW'); }
  async function proof(info: TestInfo, variant: string, actual: RecordDTO, caseId = 'UI-021') { await observation(info, caseId, variant, actual); }

  test('workflow CRUD, metadata, copy, enable, exact filters and disjoint pagination', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const job = await fixtureJob(backend, owned, 'list_job'); const definitions: string[] = [];
      for (let index = 0; index < 11; index++) { const name = ownedName(`list_${index}`); await newWorkflow(page, name); await importOne(page, job.id); definitions.push(await save(page, owned, name)); }
      await page.goto('/#/oms/workflow'); await fill(page, 'Name', ownedName('list')); await clickAndResponse(page, '/workflow/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === ownedName('list')); await expect(page.locator('.workflow-table tbody tr')).toHaveCount(10); const first = await page.locator('.workflow-table tbody tr').allTextContents(); await page.getByRole('button', { name: 'Next', exact: true }).click(); await expect(page.locator('.workflow-table tbody tr')).toHaveCount(1); const second = await page.locator('.workflow-table tbody tr').allTextContents(); expect(second.some(row => first.includes(row))).toBe(false);
      await fill(page, 'Workflow ID', definitions[0]!); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.locator('.workflow-table tbody tr')).toHaveCount(1); const row = page.locator('.workflow-table tbody tr');
      await clickAndResponse(page, '/workflow/disable', () => row.getByRole('switch').uncheck()); expect((await backend.workflow(definitions[0]!)).enable).toBe(false); await clickAndResponse(page, '/workflow/enable', () => row.getByRole('switch').check()); expect((await backend.workflow(definitions[0]!)).enable).toBe(true);
      await row.getByText('More', { exact: true }).click(); const copied = await clickAndResponse(page, '/workflow/copy', () => row.getByRole('button', { name: 'Copy', exact: true }).click()); expect(copied.success).toBe(true); const copiedId = id(copied.data); owned.track('workflow', copiedId, ownedName('list_0') + '_COPY'); await expect(page).toHaveURL(new RegExp(`workflowId=${copiedId}`)); const copiedMeta = await backend.workflow(copiedId); await expect(page.getByRole('heading', {name: String(copiedMeta.wfName),exact:true})).toBeVisible(); expect(nodes(copiedMeta).map(n => id(n.nodeId))).not.toEqual(nodes(await backend.workflow(definitions[0]!)).map(n => id(n.nodeId)));
      await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await fill(page, 'Description', '中文参数\n保留原值'); await fill(page, 'Maximum parallel instances', '3'); await fill(page, 'Lifecycle start', '2020-01-01T00:00'); await saveExisting(page); const before = await backend.workflow(copiedId);
      await page.reload(); await expect(page.getByRole('heading', { name: String(before.wfName), exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await fill(page, 'Workflow name', ownedName('list_renamed')); await saveExisting(page); const after = await backend.workflow(copiedId); for (const key of ['wfDescription', 'maxWfInstanceNum', 'enable', 'timeExpressionType', 'timeExpression', 'notifyUserIds', 'lifeCycle']) expect(after[key]).toEqual(before[key]);
      await page.goto('/#/oms/workflow'); await fill(page, 'Workflow ID', copiedId); await clickAndResponse(page, '/workflow/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.workflowId === copiedId); await expect(page.locator('.workflow-table tbody tr')).toHaveCount(1); await expect(page.locator('.workflow-table tbody tr')).toContainText(ownedName('list_renamed')); await page.locator('.workflow-table tbody tr').getByText('More', { exact: true }).click(); let requests = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/workflow/delete')) requests++; }); await page.getByRole('button', { name: 'Delete', exact: true }).click(); await selectors.dialog(page).getByRole('button', { name: 'Cancel', exact: true }).click(); expect(requests).toBe(0); expect((await backend.workflow(copiedId)).wfName).toBe(ownedName('list_renamed'));
      await page.getByRole('button', { name: 'Delete', exact: true }).click(); const deleted = await clickAndResponse(page, '/workflow/delete', () => selectors.dialog(page).getByRole('button', { name: /Confirm|Continue|Delete/, exact: false }).click()); expect(deleted.success).toBe(true); await expect(page.locator('.workflow-table tbody tr')).toHaveCount(0); await page.reload(); await fill(page, 'Workflow ID', copiedId); await clickAndResponse(page, '/workflow/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.workflowId === copiedId); await expect(page.locator('.workflow-table tbody tr')).toHaveCount(0);
      await page.getByRole('button', { name: 'Reset', exact: true }).click(); await expect(page.getByLabel('Workflow ID', { exact: true })).toHaveValue('');
      await proof(info, 'workflow-crud-list-copy-metadata', { createdWorkflowIds: definitions, copiedId, pageCounts: [10, 1], canceledDeletes: 0, copiedNodeIds: nodes(copiedMeta).map(n => id(n.nodeId)), metadataBefore: before, metadataAfter: after }, 'UI-020');
    } finally { await owned.cleanup(info); }
  });

  test('condition Y/N branches execute, disabled branches remain visible, and parameters reach the workflow', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const yesJob = await fixtureJob(backend, owned, 'branch_yes'), noJob = await fixtureJob(backend, owned, 'branch_no'); const name = ownedName('branch_flow'); await newWorkflow(page, name); const yes = await importOne(page, yesJob.id), no = await importOne(page, noJob.id); const condition = await clickAndResponse<RecordDTO[]>(page, '/workflow/saveNode', () => page.locator('.flow-tools').getByRole('button', { name: 'Condition', exact: true }).click()); expect(condition.success).toBe(true); const conditionId = id(condition.data[0]!.id);
      await connectNodes(page, conditionId, yes); await connectNodes(page, conditionId, no); await expect(page.locator('.flow-edge')).toHaveCount(2); const workflowId = await save(page, owned, name);
      const params = '中文 & + ? = {"unicode":"调度"}'; const trueId = await execute(page, owned, workflowId, params), trueInfo = await backend.waitWorkflowInstance(trueId); recordChildren(owned, trueInfo); expect(trueInfo.wfInitParams).toBe(params); expect(nodes(trueInfo).find(n => id(n.nodeId) === conditionId)?.result).toBe('true'); expect(nodes(trueInfo).find(n => id(n.nodeId) === yes)?.status).toBe(5); expect(nodes(trueInfo).find(n => id(n.nodeId) === no)?.disableByControlNode).toBe(true);
      await page.goto(`/#/oms/workflowEditor?workflowId=${workflowId}`); const inspector = await selectNode(page, conditionId); await setCode(page, inspector, 'false'); await saveNode(page, inspector); await saveExisting(page); const falseId = await execute(page, owned, workflowId), falseInfo = await backend.waitWorkflowInstance(falseId); recordChildren(owned, falseInfo); expect(nodes(falseInfo).find(n => id(n.nodeId) === conditionId)?.result).toBe('false'); expect(nodes(falseInfo).find(n => id(n.nodeId) === no)?.status).toBe(5); expect(nodes(falseInfo).find(n => id(n.nodeId) === yes)?.disableByControlNode).toBe(true);
      await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${falseId}`); await page.locator(`[data-node-id="${conditionId}"]`).press('Enter'); await expect(page.locator('.condition-script')).toHaveText('false');
      let refreshRequests = 0; const refreshListener = (request: { url(): string }) => { const url = new URL(request.url()); if (url.pathname.endsWith('/wfInstance/info') && url.searchParams.get('wfInstanceId') === falseId) refreshRequests++; }; page.on('request', refreshListener);
      const refreshToggle = page.getByLabel('Auto refresh', { exact: true }), exactRefresh = (response: { url(): string }) => new URL(response.url()).searchParams.get('wfInstanceId') === falseId;
      const firstPoll = await clickAndResponse<RecordDTO>(page, '/wfInstance/info', () => refreshToggle.check(), exactRefresh); expect(firstPoll.success).toBe(true); expect(id(firstPoll.data.wfInstanceId)).toBe(falseId); expect(firstPoll.data.status).toBe(4); await expect(page.locator('.condition-script')).toHaveText('false'); expect(refreshRequests).toBe(1);
      await refreshToggle.uncheck(); await page.waitForTimeout(5500); expect(refreshRequests).toBe(1);
      const reopenedPoll = await clickAndResponse<RecordDTO>(page, '/wfInstance/info', () => refreshToggle.check(), exactRefresh); expect(reopenedPoll.success).toBe(true); expect(id(reopenedPoll.data.wfInstanceId)).toBe(falseId); expect(refreshRequests).toBe(2);
      await page.goto('/#/oms/workflow'); await expect(page.getByRole('heading', { name: 'Workflows', exact: true })).toBeVisible(); await page.waitForTimeout(5500); expect(refreshRequests).toBe(2); page.off('request', refreshListener);
      await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${falseId}`); await page.reload(); await expect(page.getByRole('heading', { name })).toBeVisible(); await expect(page.getByLabel('Auto refresh', { exact: true })).not.toBeChecked();
      await proof(info, 'dag-condition-real-true-false', { workflowId, conditionId, trueInstance: trueInfo, falseInstance: falseInfo, parameterRoundtrip: params });
      await proof(info, 'workflow-parameter-run-details-refresh', { workflowId, trueId, falseId, currentURL: page.url() }, 'UI-023');
      await proof(info, 'workflow-detail-auto-refresh-lifecycle', { workflowId, falseId, firstPoll: firstPoll.data, reopenedPoll: reopenedPoll.data, exactOriginalHttpPolls: refreshRequests, disabledNoFurtherPollForMs: 5500, unmountedNoFurtherPollForMs: 5500, selectedConditionCodePreservedAfterRealPoll: true, defaultAutoRefreshOffAfterRemount: true }, 'UI-038');
    } finally { await owned.cleanup(info); }
  });

  test('graph import multiselect, pointer geometry, invalid topology, deletion, zoom and fullscreen', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const jobs: { id: string; name: string }[] = []; for (let index = 0; index < 10; index++) jobs.push(await fixtureJob(backend, owned, `graphjob_${index}`)); const name = ownedName('graph_flow'); await newWorkflow(page, name); await page.locator('.flow-tools').getByRole('button', { name: '+ Jobs', exact: true }).click(); const dialog = selectors.dialog(page, 'Import jobs'); await fill(dialog, 'Name', ownedName('graphjob')); const jobList = await clickAndResponse<{data:RecordDTO[]}>(page, '/job/list', () => dialog.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === ownedName('graphjob')); expect(jobList.success).toBe(true); expect(jobList.data.data.every(row => jobs.some(job => job.id === id(row.id)))).toBe(true); await expect(dialog.locator('tbody tr').first()).toContainText(ownedName('graphjob')); await expect(dialog.locator('tbody tr')).toHaveCount(8); const selectedJobIds = [(await dialog.locator('tbody tr').first().getByRole('cell').nth(2).innerText()).trim()]; await dialog.locator('tbody tr').first().getByRole('checkbox').check(); await dialog.getByRole('button', { name: 'Next', exact: true }).click(); await expect(dialog.locator('tbody tr')).toHaveCount(2); selectedJobIds.push((await dialog.locator('tbody tr').first().getByRole('cell').nth(2).innerText()).trim()); await dialog.locator('tbody tr').first().getByRole('checkbox').check(); const imported = await clickAndResponse<RecordDTO[]>(page, '/workflow/saveNode', () => dialog.getByRole('button', { name: 'Import selected (2)', exact: true }).click()); expect(imported.success).toBe(true); expect(imported.data).toHaveLength(2); expect(imported.data.map(node => id(node.jobId)).sort()).toEqual([...selectedJobIds].sort()); const [a, b] = imported.data.map(n => id(n.id));
      const first = page.locator(`[data-node-id="${a}"]`), second = page.locator(`[data-node-id="${b}"]`); const before = await first.getAttribute('transform'); const firstBox = await first.boundingBox(); if (!firstBox) throw new Error('The real SVG node has no pointer geometry'); await page.mouse.move(firstBox.x + firstBox.width / 2, firstBox.y + firstBox.height / 2); await page.mouse.down(); await page.mouse.move(firstBox.x + firstBox.width / 2 + 35, firstBox.y + firstBox.height / 2 + 45); await page.mouse.up(); expect(await first.getAttribute('transform')).not.toBe(before);
      const output = await first.locator('.port-output').boundingBox(), input = await second.locator('.port-input').boundingBox(); if (!output || !input) throw new Error('The real SVG connection ports are missing'); await page.mouse.move(output.x + output.width / 2, output.y + output.height / 2); await page.mouse.down(); await page.mouse.move(input.x + input.width / 2, input.y + input.height / 2, { steps: 8 }); await page.mouse.up(); await expect(page.locator('.flow-edge')).toHaveCount(1);
      const path = await page.locator('.edge-stroke').getAttribute('d'); expect(path).toMatch(/^M .+ C /); await first.press('Enter'); await second.press('Shift+Enter'); await expect(first).toHaveAttribute('aria-pressed', 'true'); await expect(second).toHaveAttribute('aria-pressed', 'true'); await expect(page.locator('.flow-tools').getByRole('button', { name: 'Delete (2)', exact: true })).toBeEnabled(); await connectNodes(page, a!, b!); await expect(page.locator('.flow-edge')).toHaveCount(1); await connectNodes(page, b!, a!); await expect(page.locator('.flow-edge')).toHaveCount(1); await connectNodes(page, a!, a!); await expect(page.locator('.flow-edge')).toHaveCount(1);
      await page.getByRole('button', { name: 'Zoom in', exact: true }).click(); await expect(page.getByRole('button', { name: 'Fit graph', exact: true })).not.toHaveText('100%'); await page.getByRole('button', { name: 'Arrange', exact: true }).click(); await page.getByRole('button', { name: 'Fullscreen', exact: true }).click(); await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(true); await page.keyboard.press('Escape'); await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(false);
      const workflowId = await save(page, owned, name); const topology = await backend.workflow(workflowId); await page.reload(); await expect(page.locator('.flow-edge')).toHaveCount(1); const restored = await backend.workflow(workflowId); expect(restored.peworkflowDAG).toEqual(topology.peworkflowDAG);
      await first.press('Enter'); await first.press('Delete'); await expect(page.locator('.flow-node')).toHaveCount(1); await expect(page.locator('.flow-edge')).toHaveCount(0); await saveExisting(page); expect(nodes(await backend.workflow(workflowId))).toHaveLength(1);
      const remainingJobId = id(imported.data.find(node => id(node.id) === b)!.jobId), remainingJob = jobs.find(job => job.id === remainingJobId)!; await page.locator('.flow-tools').getByRole('button', { name: '+ Jobs', exact: true }).click(); const duplicateDialog = selectors.dialog(page, 'Import jobs'); await fill(duplicateDialog, 'Name', remainingJob.name); const duplicateList = await clickAndResponse<{data:RecordDTO[]}>(page, '/job/list', () => duplicateDialog.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === remainingJob.name); expect(duplicateList.data.data.map(job => id(job.id))).toEqual([remainingJobId]); const duplicateImport = await clickAndResponse<RecordDTO[]>(page, '/workflow/saveNode', () => duplicateDialog.locator('tbody tr').getByRole('button', { name: 'Import', exact: true }).click()); expect(duplicateImport.success).toBe(true); const duplicateNodeId = id(duplicateImport.data[0]!.id); expect(duplicateNodeId).not.toBe(b); expect(id(duplicateImport.data[0]!.jobId)).toBe(remainingJobId); await saveExisting(page); const duplicateSaved = await backend.workflow(workflowId); expect(nodes(duplicateSaved).map(node => id(node.jobId))).toEqual([remainingJobId, remainingJobId]); expect(new Set(nodes(duplicateSaved).map(node => id(node.nodeId))).size).toBe(2);
      await proof(info, 'dag-native-pointer-controls-roundtrip', { workflowId, selectedJobIds, bulkNodeIds: imported.data.map(n => id(n.id)), importedNodes: imported.data, duplicateNodeId, duplicateSaved, duplicateBehavior: 'Importing an existing Job again intentionally creates a distinct workflow node, retaining the same exact Job ID.', pointerChangedTransform: true, edgePath: path, topology, restored, fullscreenEnteredAndExited: true }, 'UI-034');
    } finally { await owned.cleanup(info); }
  });

  test('nested workflow succeeds and opens its real child execution', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const job = await fixtureJob(backend, owned, 'nested_job'); const childName = ownedName('nested_child'); await newWorkflow(page, childName); await importOne(page, job.id); const childId = await save(page, owned, childName); const parentName = ownedName('nested_parent'); await newWorkflow(page, parentName); await page.locator('.flow-tools').getByRole('button', { name: 'Workflow', exact: true }).click(); const dialog = selectors.dialog(page, 'Import a workflow'); await fill(dialog, 'Workflow ID', childId); const childList = await clickAndResponse<{data:RecordDTO[]}>(page, '/workflow/list', () => dialog.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.workflowId === childId); expect(childList.success).toBe(true); expect(childList.data.data.map(row => id(row.id))).toEqual([childId]); await expect(dialog.locator('tbody tr')).toContainText(childName); await dialog.locator('tbody tr').getByRole('checkbox').check(); const imported = await clickAndResponse<RecordDTO[]>(page, '/workflow/saveNode', () => dialog.getByRole('button', { name: 'Import selected (1)', exact: true }).click()); expect(imported.success).toBe(true); const nodeId = id(imported.data[0]!.id); const parentId = await save(page, owned, parentName); const parentInstanceId = await execute(page, owned, parentId); const parent = await backend.waitWorkflowInstance(parentInstanceId); const childInstanceId = id(nodes(parent)[0]!.instanceId); owned.trackInstance(childInstanceId, childId, 'WF_INSTANCE'); const child = await backend.waitWorkflowInstance(childInstanceId); recordChildren(owned, child);
      await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${parentInstanceId}`); await page.locator(`[data-node-id="${nodeId}"]`).press('Enter'); await page.getByRole('button', { name: 'Open child workflow', exact: true }).click(); await expect(page).toHaveURL(new RegExp(`wfInstanceId=${childInstanceId}`)); await expect(page.getByRole('heading', { name: childName, exact: true })).toBeVisible(); await page.reload(); await expect(page.getByRole('heading', { name: childName, exact: true })).toBeVisible(); await page.goBack();
      await proof(info, 'workflow-nested-real-execution-child-navigation', { parentId, childId, parentInstanceId, childInstanceId, parent, child }, 'UI-025');
    } finally { await owned.cleanup(info); }
  });

  test('failed node mark-success changes only workflow state, then retry finishes the flow', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const job = await fixtureJob(backend, owned, 'marked_job', 'failed'); const name = ownedName('marked_flow'); await newWorkflow(page, name); const nodeId = await importOne(page, job.id); const workflowId = await save(page, owned, name); const instanceId = await execute(page, owned, workflowId), failed = await backend.waitWorkflowInstance(instanceId, [3]); recordChildren(owned, failed); const childId = id(nodes(failed)[0]!.instanceId); expect((await backend.waitInstance(childId, [4], 90_000, 'WORKFLOW')).status).toBe(4);
      await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${instanceId}`); await page.locator(`[data-node-id="${nodeId}"]`).press('Enter'); const marked = await clickAndResponse(page, '/wfInstance/markNodeAsSuccess', () => page.getByRole('button', { name: 'Mark node successful', exact: true }).click()); expect(marked.success).toBe(true); const markedInfo = await backend.workflowInstance(instanceId); expect(nodes(markedInfo)[0]!.status).toBe(5); expect((await backend.instance(childId, 'WORKFLOW'))!.status).toBe(4); const retried = await clickAndResponse(page, '/wfInstance/retry', () => page.getByRole('button', { name: 'Retry', exact: true }).click()); expect(retried.success).toBe(true); const finished = await backend.waitWorkflowInstance(instanceId);
      const refused = await clickAndResponse(page, '/wfInstance/retry', () => page.getByRole('button', { name: 'Retry', exact: true }).click()); expect(refused.success).toBe(false); expect((await backend.workflowInstance(instanceId)).status).toBe(4);
      await proof(info, 'workflow-failed-mark-retry-distinct-instance-result', { workflowId, instanceId, childId, failed, markedInfo, finished, successfulRetryRefused: true }, 'UI-025');
    } finally { await owned.cleanup(info); }
  });

  test('blank and invalid Groovy, lifecycle rejection before writes and no-ID editor reset', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const aJob = await fixtureJob(backend, owned, 'invalid_a'), bJob = await fixtureJob(backend, owned, 'invalid_b'); const name = ownedName('invalid_flow'); await newWorkflow(page, name); const a = await importOne(page, aJob.id), b = await importOne(page, bJob.id); const created = await clickAndResponse<RecordDTO[]>(page, '/workflow/saveNode', () => page.locator('.flow-tools').getByRole('button', { name: 'Condition', exact: true }).click()); expect(created.success).toBe(true); const c = id(created.data[0]!.id); await connectNodes(page, c, a); await connectNodes(page, c, b); const workflowId = await save(page, owned, name);
      await page.goto(`/#/oms/workflowEditor?workflowId=${workflowId}`); const inspector = await selectNode(page, c); await setCode(page, inspector, ''); let writes = 0; const listener = (request: { url(): string }) => { if (/\/workflow\/(?:save|saveNode)$/.test(new URL(request.url()).pathname)) writes++; }; page.on('request', listener); await inspector.getByRole('button', { name: 'Save node', exact: true }).click(); await expect(inspector.getByRole('alert')).toContainText('cannot be empty'); expect(writes).toBe(0);
      await setCode(page, inspector, 'this is not valid Groovy ???'); await saveNode(page, inspector); await saveExisting(page); const instanceId = await execute(page, owned, workflowId), failed = await backend.waitWorkflowInstance(instanceId, [3]); recordChildren(owned, failed); expect(failed.status).toBe(3);
      await page.goto(`/#/oms/workflowEditor?workflowId=${workflowId}`); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await fill(page, 'Lifecycle start', '2030-01-01T00:00'); await fill(page, 'Lifecycle end', '2020-01-01T00:00'); const changed = await selectNode(page, a); await fill(changed, 'Node name', ownedName('unsaved_node_change')); writes = 0; await page.getByRole('button', { name: 'Save workflow', exact: true }).click(); await expect(page.getByRole('alert').first()).toContainText('Invalid lifecycle'); expect(writes).toBe(0); page.off('request', listener);
      await page.goto('/#/oms/workflowEditor'); await expect(page.getByLabel('Workflow name', { exact: true })).toHaveValue(''); await expect(page.locator('.flow-node')).toHaveCount(0); expect((await backend.workflow(workflowId)).wfName).toBe(name);
      await proof(info, 'dag-script-invalid-and-lifecycle-prewrite-guard', { workflowId, instanceId, failed, blankScriptWrites: 0, invalidLifecycleWrites: 0, noIdClearedOldDraft: true });
    } finally { await owned.cleanup(info); }
  });

  test('stop confirmation expires across native route change and an old failed request cannot replace a new detail', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const job = await fixtureJob(backend, owned, 'race_job', '30000', processors.timeout), name = ownedName('race_flow'); await newWorkflow(page, name); await importOne(page, job.id); await fill(page, 'Maximum parallel instances', '3'); const workflowId = await save(page, owned, name); const a = await execute(page, owned, workflowId), b = await execute(page, owned, workflowId); await backend.waitWorkflowInstance(a, [2]); await backend.waitWorkflowInstance(b, [1, 2]);
      await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${a}`); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible(); let stops = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/wfInstance/stop')) stops++; }); await page.getByRole('button', { name: 'Stop', exact: true }).click(); await expect(selectors.dialog(page)).toBeVisible(); await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${b}`); await expect(selectors.dialog(page)).not.toBeVisible(); expect(stops).toBe(0); expect([1, 2]).toContain(Number((await backend.workflowInstance(a)).status)); expect([1, 2]).toContain(Number((await backend.workflowInstance(b)).status));
      let release!: () => void; const held = new Promise<void>(resolve => { release = resolve; }); let intercepted = false;
      await page.route('**/wfInstance/info?*', async route => { if (!intercepted && new URL(route.request().url()).searchParams.get('wfInstanceId') === a) { intercepted = true; await held; await route.abort('failed'); } else await route.continue(); }); await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${a}`); await expect.poll(() => intercepted).toBe(true); await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${b}`); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible(); release(); await expect(page).toHaveURL(new RegExp(`wfInstanceId=${b}`)); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible(); await page.unroute('**/wfInstance/info?*');
      await page.getByRole('button', { name: 'Stop', exact: true }).click(); const stop = await clickAndResponse(page, '/wfInstance/stop', () => selectors.dialog(page).getByRole('button', { name: /Confirm|Continue|Stop/, exact: false }).click()); expect(stop.success).toBe(true); await backend.waitWorkflowInstance(b, [10]); const childrenA = await backend.workflowInstance(a), childrenB = await backend.workflowInstance(b); recordChildren(owned, childrenA); recordChildren(owned, childrenB);
      await proof(info, 'workflow-detail-native-route-stop-and-old-network-error', { workflowId, a, b, expiredConfirmationRequests: 0, oldRequestAbortedWithoutNavigation: true, stoppedB: childrenB }, 'UI-025');
    } finally { await owned.cleanup(info); }
  });

  test('node edits preserve parameters, replace job ID and honor enabled/skip semantics in a real execution', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const good = await fixtureJob(backend, owned, 'flags_good'), failed = await fixtureJob(backend, owned, 'flags_failed', 'failed'); const name = ownedName('flags_flow'); await newWorkflow(page, name); const first = await importOne(page, good.id), disabled = await importOne(page, good.id), last = await importOne(page, good.id);
      const firstInspector = await selectNode(page, first); await fill(firstInspector, 'Find a job', failed.name); await expect(firstInspector.getByLabel('Job', { exact: true }).locator(`option[value="${failed.id}"]`)).toHaveCount(1); await firstInspector.getByLabel('Job', { exact: true }).selectOption(failed.id); await fill(firstInspector, 'Node name', ownedName('flags_alias')); await fill(firstInspector, 'Node parameters', 'failed'); await firstInspector.getByLabel('Continue after failure', { exact: true }).check(); await saveNode(page, firstInspector);
      const disabledInspector = await selectNode(page, disabled); await fill(disabledInspector, 'Node parameters', '中文节点参数 & +'); await disabledInspector.getByLabel('Enable node', { exact: true }).uncheck(); await saveNode(page, disabledInspector); await expect(page.locator(`[data-node-id="${first}"] .node-state`)).toHaveText('Skip on failure'); await expect(page.locator(`[data-node-id="${disabled}"] .node-state`)).toHaveText('Disabled'); await expect(page.locator(`[data-node-id="${disabled}"]`)).toHaveClass(/inactive/); await connectNodes(page, first, disabled); await connectNodes(page, disabled, last); const workflowId = await save(page, owned, name); const savedMetadata = await backend.workflow(workflowId); expect(id(nodes(savedMetadata).find(n => id(n.nodeId) === first)!.jobId)).toBe(failed.id); expect(nodes(savedMetadata).find(n => id(n.nodeId) === first)).toMatchObject({ nodeName: ownedName('flags_alias'), nodeParams: 'failed', skipWhenFailed: true }); expect(nodes(savedMetadata).find(n => id(n.nodeId) === disabled)).toMatchObject({ enable: false, nodeParams: '中文节点参数 & +' });
      const instanceId = await execute(page, owned, workflowId), actual = await backend.waitWorkflowInstance(instanceId); recordChildren(owned, actual); expect(nodes(actual).find(n => id(n.nodeId) === first)?.status).toBe(4); expect(nodes(actual).find(n => id(n.nodeId) === disabled)?.instanceId == null).toBe(true); expect(nodes(actual).find(n => id(n.nodeId) === last)?.status).toBe(5); await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${instanceId}`); await page.locator(`[data-node-id="${first}"]`).press('Enter'); await expect(page.getByRole('button', { name: 'Mark node successful', exact: true })).toBeDisabled();
      await proof(info, 'dag-node-all-fields-enabled-skip-real', { workflowId, instanceId, savedMetadata, actual });
    } finally { await owned.cleanup(info); }
  });

  test('workflow execution list has exact ID/status filters, disjoint pages, reset and list stop/retry actions', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const job = await fixtureJob(backend, owned, 'history_job'), name = ownedName('history_flow'); await newWorkflow(page, name); await importOne(page, job.id); await fill(page, 'Maximum parallel instances', '20'); const workflowId = await save(page, owned, name); const ids: string[] = [];
      for (let index = 0; index < 11; index++) ids.push(await execute(page, owned, workflowId));
      const actuals = []; for (const instanceId of ids) { const actual = await backend.waitWorkflowInstance(instanceId); recordChildren(owned, actual); actuals.push(actual); }
      await page.goto(`/#/oms/wfinstance?workflowId=${workflowId}`); await expect(page.locator('.data-table tbody tr')).toHaveCount(10); const first = await page.locator('.data-table tbody tr').allTextContents(); await page.getByRole('button', { name: 'Next', exact: true }).click(); await expect(page.locator('.data-table tbody tr')).toHaveCount(1); const second = await page.locator('.data-table tbody tr').allTextContents(); expect(first.some(row => second.includes(row))).toBe(false); await fill(page, 'Instance ID', ids[0]!); await page.getByLabel('Status', { exact: true }).selectOption('SUCCEED'); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.locator('.data-table tbody tr')).toHaveCount(1); const successfulRetry = await clickAndResponse(page, '/wfInstance/retry', () => page.locator('.data-table tbody tr').getByRole('button', { name: 'Retry', exact: true }).click()); expect(successfulRetry.success).toBe(false);
      // A delayed API-created execution is an explicit fixture for the UI WAITING and STOPPED status axes.
      const waitingId = id(await backend.call('/workflow/run', { query: { workflowId, delay: 600000 } })); owned.trackInstance(waitingId, workflowId, 'WF_INSTANCE'); await fill(page, 'Instance ID', waitingId); await page.getByLabel('Status', { exact: true }).selectOption('WAITING'); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.locator('.data-table tbody tr')).toHaveCount(1); let stops = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/wfInstance/stop')) stops++; }); await page.locator('.data-table tbody tr').getByRole('button', { name: 'Stop', exact: true }).click(); await selectors.dialog(page).getByRole('button', { name: 'Cancel', exact: true }).click(); expect(stops).toBe(0); expect((await backend.workflowInstance(waitingId)).status).toBe(1);
      await page.locator('.data-table tbody tr').getByRole('button', { name: 'Stop', exact: true }).click(); const stopped = await clickAndResponse(page, '/wfInstance/stop', () => selectors.dialog(page).getByRole('button', { name: 'Confirm', exact: true }).click()); expect(stopped.success).toBe(true); await backend.waitWorkflowInstance(waitingId, [10]); await page.getByLabel('Status', { exact: true }).selectOption('STOPPED'); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.locator('.data-table tbody tr')).toHaveCount(1); const retried = await clickAndResponse(page, '/wfInstance/retry', () => page.locator('.data-table tbody tr').getByRole('button', { name: 'Retry', exact: true }).click()); expect(retried.success).toBe(true); const finished = await backend.waitWorkflowInstance(waitingId); recordChildren(owned, finished);
      await page.getByRole('button', { name: 'Reset', exact: true }).click(); await expect(page.getByLabel('Workflow ID', { exact: true })).toHaveValue(''); await expect(page.getByLabel('Instance ID', { exact: true })).toHaveValue(''); await expect(page.getByLabel('Status', { exact: true })).toHaveValue('');
      await proof(info, 'workflow-instance-list-filters-pagination-stop-retry', { workflowId, instanceIds: ids, pageCounts: [10, 1], actuals, waitingFixture: { method: 'API delayed execution', waitingId }, canceledStopRequests: 0, finished, successfulRetryRefused: true }, 'UI-024');
    } finally { await owned.cleanup(info); }
  });

  test('all six workflow CRON presets validate real future dates and persist after reload without enabling schedules', async ({ page, backend, credentials }, info) => {
    const owned = new OwnedResources(backend);
    try {
      await enterSamples(page, credentials); const job = await fixtureJob(backend, owned, 'cron_job'), name = ownedName('cron_flow'); await newWorkflow(page, name); await importOne(page, job.id); const workflowId = await save(page, owned, name);
      await page.goto('/#/oms/workflow'); await fill(page, 'Workflow ID', workflowId); await page.getByRole('button', { name: 'Search', exact: true }).click(); await clickAndResponse(page, '/workflow/disable', () => page.locator('.workflow-table tbody tr').getByRole('switch').uncheck()); await page.goto(`/#/oms/workflowEditor?workflowId=${workflowId}`); await expect(page.getByRole('heading', {name,exact:true})).toBeVisible();
      for (const rule of cronCases) { await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await page.getByLabel('Schedule type', { exact: true }).selectOption('CRON'); await configureCron(page, page.locator('.workflow-settings'), rule); const validation = await validateCron(page, page.locator('.workflow-settings'), backend, rule); await saveExisting(page); const actual = await backend.workflow(workflowId); expect(actual.timeExpressionType).toBe('CRON'); expect(actual.timeExpression).toBe(rule.expression); expect(actual.enable).toBe(false); await page.reload(); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await expect(page.getByLabel('Schedule expression', { exact: true })).toHaveValue(rule.expression); await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await proof(info, `workflow-cron-${rule.key}-real-dates-reload`, { workflowId, rule: rule.expression, validation, actual }); }
    } finally { await owned.cleanup(info); }
  });
});
