import { test, expect, enterSamples, id, observation, ownedName } from './helpers';
import { WorkflowActions, workflowNodes } from './workflow-actions';

test.describe('fresh workflow condition failure presentation', () => {
  test.use({ actionTimeout: 15_000 }); test.setTimeout(90_000);
  test('blank Groovy produces zero writes and a saved malformed script visibly fails the real workflow without creating job children', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const job = await actions.job('condition_error_job'), name = ownedName('condition_error_flow'); await actions.create(name); const a = await actions.importJob(job.id), b = await actions.importJob(job.id), condition = await actions.condition(); await actions.connect(condition, a); await actions.connect(condition, b); const workflowId = await actions.save(name), inspector = await actions.select(condition); await actions.code(inspector, ''); let writes = 0; const listener = (request: { url(): string }) => { if (/\/workflow\/(?:save|saveNode)$/.test(new URL(request.url()).pathname)) writes++; }; page.on('request', listener); await inspector.getByRole('button', { name: 'Save node', exact: true }).click(); await expect(inspector.getByRole('alert')).toContainText('cannot be empty'); expect(writes).toBe(0); page.off('request', listener);
      const malformed = 'this is not valid Groovy ???'; await actions.code(inspector, malformed); const savedNode = await actions.nodeSave(inspector); expect(savedNode.nodeParams).toBe(malformed); await actions.save(); const instanceId = await actions.run(workflowId), failed = await backend.waitWorkflowInstance(instanceId, [3]); expect(failed.result).toBe("can't evaluate decision node!"); expect(workflowNodes(failed).every(node => node.instanceId == null)).toBe(true); await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${instanceId}`); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible(); await expect(page.locator('.run-title .badge')).toHaveText('Failed'); await page.getByText('Parameters, context and result', { exact: true }).click(); await expect(page.locator('.run-data>div').filter({ has: page.getByRole('heading', { name: 'Workflow result', exact: true }) }).locator('pre')).toHaveText(String(failed.result)); await page.locator(`[data-node-id="${condition}"]`).press('Enter'); await expect(page.locator('.condition-script')).toHaveText(malformed); await expect(page.locator('.run-inspector')).toContainText(id(condition));
      const row = await actions.list(workflowId); await row.getByRole('button', { name: 'Instances', exact: true }).click(); await expect(page.locator('tbody tr')).toHaveCount(1); await expect(page.locator('tbody tr')).toContainText(instanceId); await expect(page.locator('tbody tr .badge')).toHaveText('Failed'); await expect(page.locator('tbody tr')).toContainText(String(failed.result)); await observation(info, 'UI-021', 'dag-condition-invalid', { workflowId, instanceId, blankScriptWrites: 0, savedNode, malformed, failed, failureResultVisibleInDetailAndList: true, ordinaryJobChildrenCreated: 0, boundary: 'Nonempty malformed Groovy is saved by formal 5.1.6 and fails during Server condition evaluation. No invented precompilation or Worker task execution claim.' });
    } finally { await actions.cleanup(); }
  });
});
