import type { Page } from '@playwright/test';
import { test, expect, clickAndResponse, confirmDialog, enterApplication, enterSamples, fill, id, login, observation, ownedName, processors, selectors, type PageDTO, type RecordDTO } from './helpers';
import { AdminFixtures } from './admin-fixtures';
import { WorkflowActions, trackChildren, workflowEdges, workflowNodes } from './workflow-actions';

test.describe('fresh exact workflow parity assertions', () => {
  test.use({ actionTimeout: 15_000 });
  test.setTimeout(180_000);
  const time = (value: unknown) => { expect(String(value)).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/); return Date.parse(String(value).replace(' ', 'T') + '+08:00'); };
  async function fact(page: Page, label: string, expected: string) { await expect(page.locator('.instance-detail .facts').getByText(label, { exact: true }).locator('xpath=following-sibling::dd[1]')).toHaveText(expected); }

  test('parallel join uses both completed Worker branches and propagates exact JSON parameters to ordinary child details', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const left = await actions.job('join_left', '2000', processors.timeout), right = await actions.job('join_right', '4000', processors.timeout), tail = await actions.job('join_tail'); const name = ownedName('parallel_join'); await actions.create(name); const a = await actions.importJob(left.id), b = await actions.importJob(right.id), c = await actions.importJob(tail.id);
      const params = '{\n  "中文": "调度 🚀",\n  "quoted": "\\\" & + ? =",\n  "lines": "first\\nsecond"\n}'; const inspector = await actions.select(c); await fill(inspector, 'Node name', '长中文节点名称：等待两个并行分支完成后汇聚并执行最终任务'); await fill(inspector, 'Node parameters', params); await actions.nodeSave(inspector); await actions.connect(a, c); await actions.connect(b, c); const workflowId = await actions.save(name), saved = await backend.workflow(workflowId);
      await actions.edit(workflowId); expect(workflowEdges(saved).map(e => `${e.from}:${e.to}`).sort()).toEqual([`${a}:${c}`, `${b}:${c}`].sort()); await actions.select(c); await expect(page.getByLabel('Node parameters', { exact: true })).toHaveValue(params);
      const init = JSON.stringify({ '中文': '父上下文 🚀', escaped: '& + ? = "' }), instanceId = await actions.run(workflowId, init), actual = await backend.waitWorkflowInstance(instanceId); trackChildren(actions.owned, actual); const node = (nodeId: string) => workflowNodes(actual).find(n => id(n.nodeId) === nodeId)!;
      const details: RecordDTO[] = []; for (const nodeId of [a, b, c]) details.push(await backend.call<RecordDTO>('/instance/detailPlus', { method: 'POST', data: { instanceId: id(node(nodeId).instanceId) } }));
      expect(details.map(d => d.status)).toEqual([5, 5, 5]); expect(time(details[2]!.actualTriggerTime)).toBeGreaterThanOrEqual(Math.max(time(details[0]!.finishedTime), time(details[1]!.finishedTime))); expect(details[2]!.jobParams).toBe(params); expect(JSON.parse(String(details[2]!.instanceParams))).toEqual(JSON.parse(String(actual.wfContext))); expect(actual.wfInitParams).toBe(init);
      await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${instanceId}`); await page.locator(`[data-node-id="${c}"]`).press('Enter'); await fact(page, 'Instance ID', id(node(c).instanceId)); await fact(page, 'Job parameters', params); await fact(page, 'Instance parameters', String(details[2]!.instanceParams)); await fact(page, 'Result', String(details[2]!.result)); await expect(page.locator('.run-inspector>header .badge')).toHaveText('Succeeded');
      const definitionBefore = await backend.workflow(workflowId), readonlyNode = page.locator(`[data-node-id="${c}"]`), transform = await readonlyNode.getAttribute('transform'), box = await readonlyNode.boundingBox(); if (!box) throw new Error('Actual readonly SVG geometry is missing'); await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 60, box.y + box.height / 2 + 40, { steps: 6 }); await page.mouse.up(); await readonlyNode.press('Delete'); await expect(readonlyNode).toHaveAttribute('transform', transform!); await expect(page.locator('.flow-node')).toHaveCount(3); await expect(page.locator('.port-output')).toHaveCount(0); expect((await backend.workflow(workflowId)).peworkflowDAG).toEqual(definitionBefore.peworkflowDAG);
      for (const [caseId, variant] of [['UI-021','dag-parallel-join'],['UI-021','dag-json-params'],['UI-023','workflow-run'],['UI-023','workflow-run-params'],['UI-025','wfdetail-child-instance'],['UI-034','dag-view-readonly']]) await observation(info, caseId!, variant!, { workflowId, instanceId, saved, actual, details, exactNodeParams: params, readonlyDefinitionUnchanged: true });
    } finally { await actions.cleanup(); }
  });

  test('complete workflow metadata survives name-only edits, independent copy edits, hard refresh, history and new tabs', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const job = await actions.job('metadata_job'), name = ownedName('metadata_flow'); await actions.create(name); const nodeId = await actions.importJob(job.id); await fill(page, 'Description', '中文描述 🚀\n保留所有未编辑元数据'); await fill(page, 'Maximum parallel instances', '4'); await page.getByLabel('Schedule type', { exact: true }).selectOption('CRON'); await fill(page, 'Schedule expression', '0 0 0 1 1 ? 2030'); await fill(page, 'Lifecycle start', '2020-01-01T00:00'); await fill(page, 'Lifecycle end', '2031-01-01T00:00'); const contacts = page.getByLabel('Failure notifications', { exact: true }); await expect.poll(async () => contacts.locator('option').count()).toBeGreaterThan(0); const contactId = await contacts.locator('option').first().getAttribute('value'); expect(contactId).toBeTruthy(); await contacts.selectOption(contactId!); const workflowId = await actions.save(name), original = await backend.workflow(workflowId);
      expect(original).toMatchObject({ wfDescription: '中文描述 🚀\n保留所有未编辑元数据', maxWfInstanceNum: 4, timeExpressionType: 'CRON', timeExpression: '0 0 0 1 1 ? 2030' }); expect((original.notifyUserIds as unknown[]).map(id)).toEqual([contactId]); expect(original.lifeCycle).toEqual({ start: Date.parse('2020-01-01T00:00:00+08:00'), end: Date.parse('2031-01-01T00:00:00+08:00') });
      const row = await actions.list(workflowId); await row.getByRole('button', { name, exact: true }).click(); await page.reload(); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await expect(contacts).toHaveValues([contactId!]); await expect(page.getByLabel('Lifecycle start', { exact: true })).toHaveValue('2020-01-01T00:00'); await expect(page.getByLabel('Lifecycle end', { exact: true })).toHaveValue('2031-01-01T00:00');
      const renamed = ownedName('metadata_renamed'); await fill(page, 'Workflow name', renamed); expect(await actions.save()).toBe(workflowId); const edited = await backend.workflow(workflowId); for (const key of ['wfDescription','maxWfInstanceNum','timeExpressionType','timeExpression','notifyUserIds','lifeCycle','enable','peworkflowDAG']) expect(edited[key]).toEqual(original[key]);
      await page.getByRole('button', { name: 'Workflows', exact: true }).click(); await expect(page).toHaveURL(/#\/oms\/workflow$/); await expect(page.getByRole('heading', { name: 'Workflows', exact: true })).toBeVisible(); await page.goBack(); await expect(page.getByRole('heading', { name: renamed, exact: true })).toBeVisible(); await expect(page.locator(`[data-node-id="${nodeId}"]`)).toBeVisible(); await page.goForward(); await expect(page.getByRole('heading', { name: 'Workflows', exact: true })).toBeVisible(); await page.goBack(); await expect(page.getByRole('heading', { name: renamed, exact: true })).toBeVisible();
      const tab = await page.context().newPage(); try { await tab.goto(page.url()); await expect(tab.getByRole('heading', { name: renamed, exact: true })).toBeVisible(); await expect(tab.locator(`[data-node-id="${nodeId}"]`)).toBeVisible(); await tab.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await expect(tab.getByLabel('Failure notifications', { exact: true })).toHaveValues([contactId!]); } finally { await tab.close(); }
      const enabledRow = await actions.list(workflowId); await clickAndResponse(page, '/workflow/disable', () => enabledRow.getByRole('switch').uncheck()); await expect(enabledRow.getByRole('switch')).not.toBeChecked(); expect((await backend.workflow(workflowId)).enable).toBe(false); await clickAndResponse(page, '/workflow/enable', () => enabledRow.getByRole('switch').check()); await expect(enabledRow.getByRole('switch')).toBeChecked(); await page.reload(); const refreshedRow = await actions.list(workflowId); await expect(refreshedRow.getByRole('switch')).toBeChecked(); expect((await backend.workflow(workflowId)).enable).toBe(true); const sourceBeforeCopy = await backend.workflow(workflowId), sourceRow = await actions.list(workflowId); await sourceRow.getByText('More', { exact: true }).click(); const copied = await clickAndResponse(page, '/workflow/copy', () => sourceRow.getByRole('button', { name: 'Copy', exact: true }).click()); expect(copied.success).toBe(true); const copyId = id(copied.data), copyMeta = await backend.workflow(copyId); actions.owned.track('workflow', copyId, String(copyMeta.wfName)); await expect(page.getByRole('heading', { name: String(copyMeta.wfName), exact: true })).toBeVisible(); const copiedNode = id(workflowNodes(copyMeta)[0]!.nodeId); expect(copiedNode).not.toBe(nodeId); const copyInspector = await actions.select(copiedNode); await fill(copyInspector, 'Node name', ownedName('copy_only_alias')); await fill(copyInspector, 'Node parameters', '独立副本 🚀'); await actions.nodeSave(copyInspector); expect(await actions.save()).toBe(copyId); const sourceAfterCopy = await backend.workflow(workflowId); expect(sourceAfterCopy).toEqual(sourceBeforeCopy); expect(workflowNodes(await backend.workflow(copyId))[0]!.nodeParams).toBe('独立副本 🚀');
      for (const [caseId, variant] of [['UI-020','workflow-edit'],['UI-020','workflow-copy'],['UI-020','workflow-disable-enable'],['UI-021','dag-workflow-all-fields'],['UI-022','editor-hard-refresh'],['UI-022','editor-new-tab'],['UI-022','editor-history'],['UI-022','editor-first-save-id'],['UI-036','workflow-preserve-unknown']]) await observation(info, caseId!, variant!, { workflowId, copyId, original, edited, sourceBeforeCopy, sourceAfterCopy, boundary: 'Locked Java DTO fixed fields and null values are preserved; future unknown payload keys have a separate unit contract, not a fabricated Server readback.' });
    } finally { await actions.cleanup(); }
  });

  test('editor ID races, network save errors and missing or nonexistent deep links keep the correct draft and official model', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const job = await actions.job('routes_job'), nameA = ownedName('routes_a'), nameB = ownedName('routes_b'); await actions.create(nameA); await actions.importJob(job.id); const a = await actions.save(nameA); await actions.create(nameB); const bNode = await actions.importJob(job.id), b = await actions.save(nameB); await actions.edit(a); await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await fill(page, 'Description', 'Unsaved A draft must be discarded');
      let release!: () => void; const held = new Promise<void>(resolve => { release = resolve; }); let intercepted = false; await page.route('**/workflow/fetch?*', async route => { if (!intercepted && new URL(route.request().url()).searchParams.get('workflowId') === a) { intercepted = true; const original = await route.fetch(); await held; await route.fulfill({ response: original }); } else await route.continue(); }); await page.reload(); await expect.poll(() => intercepted).toBe(true); await page.goto(`/#/oms/workflowEditor?workflowId=${b}`); await expect(page.getByRole('heading', { name: nameB, exact: true })).toBeVisible(); release(); await expect(page.locator('.flow-node')).toHaveCount(1); await expect(page.locator(`[data-node-id="${bNode}"]`)).toBeVisible(); await page.unroute('**/workflow/fetch?*'); expect((await backend.workflow(a)).wfDescription).toBe('');
      await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); const official = await backend.workflow(b), draftName = ownedName('recoverable_draft'); await fill(page, 'Workflow name', draftName); await page.route('**/workflow/save', route => route.abort('failed')); await page.getByRole('button', { name: 'Save workflow', exact: true }).click(); await expect(page.locator('.error-banner[role="alert"]')).toBeVisible(); await expect(page.getByLabel('Workflow name', { exact: true })).toHaveValue(draftName); expect((await backend.workflow(b)).wfName).toBe(official.wfName); await page.unroute('**/workflow/save'); expect(await actions.save()).toBe(b); const recovered = await backend.workflow(b); expect(recovered.wfName).toBe(draftName); await page.reload(); await expect(page.getByRole('heading', { name: draftName, exact: true })).toBeVisible();
      const badRequests: string[] = []; page.on('request', request => { const url = new URL(request.url()); if (/\/workflow\/fetch|\/wfInstance\/info/.test(url.pathname) && /(?:=undefined|=null)(?:&|$)/.test(url.search)) badRequests.push(url.pathname); }); await page.goto('/#/oms/workflowEditor'); await expect(page.getByLabel('Workflow name', { exact: true })).toHaveValue(''); await expect(page.locator('.flow-node')).toHaveCount(0); await page.getByRole('button', { name: 'Save workflow', exact: true }).click(); await expect(page.locator('.error-banner[role="alert"]')).toContainText('Import at least one node'); await fill(page, 'Workflow name', ownedName('empty_graph')); let emptyWrites = 0; const listener = (request: { url(): string }) => { if (/\/workflow\/(?:save|saveNode)$/.test(new URL(request.url()).pathname)) emptyWrites++; }; page.on('request', listener); await page.getByRole('button', { name: 'Save workflow', exact: true }).click(); await expect(page.locator('.error-banner[role="alert"]')).toContainText('Import at least one node'); expect(emptyWrites).toBe(0); page.off('request', listener);
      await page.goto('/#/oms/workflowEditor?workflowId=999999999999999999'); await expect(page.locator('.error-banner[role="alert"]')).toBeVisible(); await expect(page.getByRole('button', { name: 'Reload', exact: true })).toBeVisible(); await expect(page.locator('.flow-node')).toHaveCount(0); await page.goto('/#/oms/wfInstanceDetail'); await expect(page.locator('.error-banner[role="alert"]')).toContainText('ID is missing'); await page.goto('/#/oms/wfInstanceDetail?wfInstanceId=999999999999999999'); await expect(page.locator('.error-banner[role="alert"]')).toBeVisible(); await expect(page.locator('.flow-node')).toHaveCount(0); expect(badRequests).toEqual([]);
      for (const [caseId, variant] of [['UI-022','editor-id-switch'],['UI-022','editor-no-id'],['UI-021','dag-empty-invalid'],['UI-025','wfdetail-no-id'],['UI-038','request-race-detail'],['UI-038','save-error-draft']]) await observation(info, caseId!, variant!, { a, b, official, recovered, heldOriginalAResponse: true, abortedRealSaveRequest: true, noUndefinedRequests: badRequests, emptyGraphWrites: emptyWrites });
    } finally { await actions.cleanup(); }
  });

  test('condition branches, Monaco keyboard isolation, long Chinese graph controls, edge deletion and repeated remounts retain topology', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const job = await actions.job('geometry_job'), name = ownedName('geometry_flow'); await actions.create(name); const a = await actions.importJob(job.id), b = await actions.importJob(job.id), c = await actions.importJob(job.id), condition = await actions.condition(); await actions.connect(condition, a); await actions.connect(condition, b); await actions.connect(condition, c); await expect(page.locator('.flow-edge')).toHaveCount(2); await expect(page.getByText('Conditions require exactly one Y and one N branch', { exact: true })).toBeVisible();
      const inspector = await actions.select(condition); await fill(inspector, 'Node name', '很长的中文条件名称：两个分支必须分别保持Y与N属性且不能误删除图节点'); await actions.code(inspector, 'true'); await page.keyboard.press('ControlOrMeta+A'); await page.keyboard.press('Delete'); await expect(page.locator('.flow-node')).toHaveCount(4); await page.keyboard.insertText('false'); await page.keyboard.press('Backspace'); await page.keyboard.press('ControlOrMeta+A'); await page.keyboard.insertText('true'); await actions.nodeSave(inspector); const workflowId = await actions.save(name), original = await backend.workflow(workflowId); expect(workflowEdges(original).map(e => e.property).sort()).toEqual(['false','true']); expect(workflowNodes(original).find(n => id(n.nodeId) === condition)!.nodeParams).toBe('true');
      await page.getByRole('button', { name: 'Zoom out', exact: true }).click(); await page.getByRole('button', { name: 'Zoom in', exact: true }).click(); await page.getByRole('button', { name: 'Fit graph', exact: true }).click(); await page.getByRole('button', { name: 'Arrange', exact: true }).click(); const layout1 = await page.locator('.flow-node').evaluateAll(items => items.map(item => [item.getAttribute('data-node-id'),item.getAttribute('transform')])); await page.getByRole('button', { name: 'Arrange', exact: true }).click(); expect(await page.locator('.flow-node').evaluateAll(items => items.map(item => [item.getAttribute('data-node-id'),item.getAttribute('transform')]))).toEqual(layout1);
      await page.getByRole('button', { name: 'Fullscreen', exact: true }).click(); await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(true); await page.setViewportSize({ width: 1024, height: 768 }); await expect(page.getByRole('button', { name: 'Arrange', exact: true })).toBeInViewport(); await page.locator('.flow-studio').press('Escape'); await expect.poll(() => page.evaluate(() => !!document.fullscreenElement)).toBe(false); await page.setViewportSize({ width: 1440, height: 900 }); await actions.select(condition); await expect(page.getByLabel('Node name', { exact: true })).toHaveValue(String(workflowNodes(original).find(n => id(n.nodeId) === condition)!.nodeName));
      await page.locator('.flow-edge').first().click(); await page.locator('.flow-studio').press('Delete'); await expect(page.locator('.flow-edge')).toHaveCount(1); await actions.connect(condition, c); await expect(page.locator('.flow-edge')).toHaveCount(2); expect(await actions.save()).toBe(workflowId); const replaced = await backend.workflow(workflowId); expect(workflowEdges(replaced).map(e => e.property).sort()).toEqual(['false','true']); expect(workflowEdges(replaced).some(e => id(e.to) === c)).toBe(true);
      let saves = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/workflow/save')) saves++; }); for (let i = 0; i < 3; i++) { await actions.edit(workflowId); const conditionInspector = await actions.select(condition); await expect(conditionInspector.locator('.monaco-editor')).toBeVisible(); await page.setViewportSize({ width: i % 2 ? 1024 : 1440, height: 900 }); await page.getByRole('button', { name: 'Arrange', exact: true }).click(); await page.getByRole('button', { name: 'Fit graph', exact: true }).click(); await page.goto('/#/oms/workflow'); } await actions.edit(workflowId); await expect(page.locator('.flow-node')).toHaveCount(4); const removable = await actions.select(a); await expect(removable).toBeVisible(); await page.locator(`[data-node-id="${a}"]`).press('Delete'); await expect(page.locator('.flow-node')).toHaveCount(3); const remainingBefore = workflowNodes(replaced).filter(n => id(n.nodeId) !== a); await actions.save(); expect(saves).toBe(1); const removed = await backend.workflow(workflowId); expect(workflowNodes(removed)).toEqual(remainingBefore); expect(workflowEdges(removed).every(e => id(e.to) !== a && id(e.from) !== a)).toBe(true); await page.reload(); await expect(page.locator('.flow-node')).toHaveCount(3);
      for (const [caseId, variant] of [['UI-021','dag-remove-node-edge'],['UI-034','dag-condition-edges'],['UI-034','dag-keyboard-editor'],['UI-034','dag-remove-keyboard'],['UI-034','dag-zoom-fit'],['UI-034','dag-fullscreen-resize'],['UI-034','dag-unmount-remount'],['UI-034','dag-layout-roundtrip'],['UI-038','dag-listener-lifecycle']]) await observation(info, caseId!, variant!, { workflowId, original, replaced, removed, layout1, remounts: 3, oneActualSaveRequestAfterRemount: saves, boundary: 'Coordinates are deterministic view state; no Server position-persistence claim. Native browser interaction plus separate listener cleanup unit contract.' });
    } finally { await page.setViewportSize({ width: 1440, height: 900 }); await actions.cleanup(); }
  });

  test('manual mark-success preserves the failed child and explicitly retries the previously unstarted downstream node', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const failedJob = await actions.job('marked_head', 'failed'), downstream = await actions.job('marked_downstream'), name = ownedName('mark_downstream_flow'); await actions.create(name); const a = await actions.importJob(failedJob.id), b = await actions.importJob(downstream.id); await actions.connect(a, b); const workflowId = await actions.save(name), instanceId = await actions.run(workflowId), failed = await backend.waitWorkflowInstance(instanceId, [3]); trackChildren(actions.owned, failed); const failedChildId = id(workflowNodes(failed).find(n => id(n.nodeId) === a)!.instanceId); expect(workflowNodes(failed).find(n => id(n.nodeId) === b)!.instanceId).toBeNull();
      await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${instanceId}`); await page.locator(`[data-node-id="${a}"]`).press('Enter'); await expect(page.locator('.run-inspector>header .badge')).toHaveText('Failed'); await fact(page, 'Instance ID', failedChildId); const marked = await clickAndResponse(page, '/wfInstance/markNodeAsSuccess', () => page.getByRole('button', { name: 'Mark node successful', exact: true }).click()); expect(marked.success).toBe(true); expect((await backend.instance(failedChildId, 'WORKFLOW'))!.status).toBe(4); const beforeRetry = await backend.workflowInstance(instanceId); expect(workflowNodes(beforeRetry).find(n => id(n.nodeId) === a)!.status).toBe(5); expect(workflowNodes(beforeRetry).find(n => id(n.nodeId) === b)!.instanceId).toBeNull(); const retried = await clickAndResponse(page, '/wfInstance/retry', () => page.getByRole('button', { name: 'Retry', exact: true }).click()); expect(retried.success).toBe(true); const finished = await backend.waitWorkflowInstance(instanceId); trackChildren(actions.owned, finished); const tail = workflowNodes(finished).find(n => id(n.nodeId) === b)!; expect(tail.status).toBe(5); const tailDetails = await backend.call<RecordDTO>('/instance/detailPlus', { method: 'POST', data: { instanceId: id(tail.instanceId) } }); expect(tailDetails.status).toBe(5); expect(String(tailDetails.result)).toContain('true'); expect((await backend.instance(failedChildId, 'WORKFLOW'))!.status).toBe(4);
      await page.getByRole('button', { name: 'Refresh', exact: true }).click(); await page.locator(`[data-node-id="${b}"]`).press('Enter'); await expect(page.locator('.run-inspector>header .badge')).toHaveText('Succeeded'); await fact(page, 'Instance ID', id(tail.instanceId)); await page.goto(`/#/oms/wfinstance?workflowId=${workflowId}`); await expect(page.locator('.data-table tbody tr')).toContainText(instanceId); await expect(page.locator('.data-table tbody tr .badge')).toHaveText('Succeeded');
      for (const variant of ['wfdetail-mark-success','wfdetail-retry-after-mark','wfdetail-stop-retry']) await observation(info, 'UI-025', variant, { workflowId, instanceId, failedChildId, failed, beforeRetry, finished, tailDetails, originalFailedChildStillFailed: true });
    } finally { await actions.cleanup(); }
  });

  test('running workflow stop cancellation continues the child, confirmed stop prevents its downstream, and failed list retry succeeds after explicit fixture repair', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const slow = await actions.job('stop_slow', '30000', processors.timeout), tailJob = await actions.job('stop_tail'), name = ownedName('stop_list_flow'); await actions.create(name); const slowNode = await actions.importJob(slow.id), tailNode = await actions.importJob(tailJob.id); await actions.connect(slowNode, tailNode); const workflowId = await actions.save(name), instanceId = await actions.run(workflowId); const running = await backend.waitWorkflowInstance(instanceId, [2]); trackChildren(actions.owned, running); await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${instanceId}`); await page.locator(`[data-node-id="${slowNode}"]`).press('Enter'); await expect(page.locator('.run-inspector>header .badge')).toHaveText('Running'); const runningChild = id(workflowNodes(running).find(n => id(n.nodeId) === slowNode)!.instanceId); await fact(page, 'Instance ID', runningChild);
      await page.goto(`/#/oms/wfinstance?workflowId=${workflowId}`); await fill(page, 'Instance ID', instanceId); await page.getByLabel('Status', { exact: true }).selectOption('RUNNING'); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.locator('.data-table tbody tr')).toHaveCount(1); let stopRequests = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/wfInstance/stop')) stopRequests++; }); await page.locator('tbody tr').getByRole('button', { name: 'Stop', exact: true }).click(); await confirmDialog(page, false); expect(stopRequests).toBe(0); const afterCancel = await backend.workflowInstance(instanceId); expect(afterCancel.status).toBe(2); expect((await backend.instance(runningChild, 'WORKFLOW'))!.status).toBe(2); await page.locator('tbody tr').getByRole('button', { name: 'Stop', exact: true }).click(); const stopped = await clickAndResponse(page, '/wfInstance/stop', () => selectors.dialog(page).getByRole('button', { name: 'Confirm', exact: true }).click()); expect(stopped.success).toBe(true); const terminal = await backend.waitWorkflowInstance(instanceId, [10]); expect(workflowNodes(terminal).find(n => id(n.nodeId) === tailNode)!.instanceId).toBeNull(); await page.getByLabel('Status', { exact: true }).selectOption('STOPPED'); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.locator('tbody tr .badge')).toHaveText('Stopped');
      const failJob = await actions.job('retry_head', 'failed'), retryName = ownedName('failed_list_retry'); await actions.create(retryName); const failNode = await actions.importJob(failJob.id), finalNode = await actions.importJob(tailJob.id); await actions.connect(failNode, finalNode); const retryWorkflow = await actions.save(retryName), failedId = await actions.run(retryWorkflow), failed = await backend.waitWorkflowInstance(failedId, [3]); trackChildren(actions.owned, failed); await page.goto(`/#/oms/wfinstance?workflowId=${retryWorkflow}`); await page.getByLabel('Status', { exact: true }).selectOption('FAILED'); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.locator('tbody tr')).toHaveCount(1);
      // Locked retry keeps the WF snapshot. Repair this owned Job processor fixture, not the frozen node params.
      const failedJobBeforeRepair = await backend.job(failJob.id); expect(failedJobBeforeRepair).toBeTruthy(); const repairedFixtureRequest = { ...failedJobBeforeRepair, processorInfo: processors.simple, alarmConfig: null, logConfig: null, advancedRuntimeConfig: null }; const repairedFixtureResponse = await backend.call<null>('/job/save', { method: 'POST', data: repairedFixtureRequest, allowFailure: true }); expect(repairedFixtureResponse.success, 'The isolated fixture repair must receive a real successful Void ResultDTO').toBe(true); const failedJobAfterRepair = await backend.job(failJob.id); expect(failedJobAfterRepair!.processorInfo).toBe(processors.simple); await page.goto(`/#/oms/wfinstance?workflowId=${retryWorkflow}`); await fill(page, 'Instance ID', failedId); await page.getByRole('button', { name: 'Search', exact: true }).click(); const retry = await clickAndResponse(page, '/wfInstance/retry', () => page.locator('tbody tr').getByRole('button', { name: 'Retry', exact: true }).click()); expect(retry.success).toBe(true); const recovered = await backend.waitWorkflowInstance(failedId); trackChildren(actions.owned, recovered); expect(workflowNodes(recovered).every(n => n.status === 5)).toBe(true); const repairedChild = await backend.call<RecordDTO>('/instance/detailPlus', { method: 'POST', data: { instanceId: id(workflowNodes(recovered).find(n => id(n.nodeId) === failNode)!.instanceId) } }); expect(repairedChild.status).toBe(5); expect(repairedChild.jobParams).toBe('failed'); expect(repairedChild.result).toBe('yeah!');
      for (const variant of ['wfinstance-stop-cancel','wfinstance-stop','wfinstance-retry']) await observation(info, 'UI-024', variant, { workflowId, instanceId, running, afterCancel, terminal, canceledStopRequests: 0, retryWorkflow, failedId, failed, recovered, repairedChild, failedJobBeforeRepair, failedJobAfterRepair, repairedFixtureRequest, repairedFixtureResponse, retryFixtureRepair: 'Own Job fixture processor changed through API from StandaloneProcessorDemo to SimpleProcessor before explicit UI list Retry. The existing WF instance snapshot and original failed node params remain unchanged. No fail-once or automatic-retry claim.' });
    } finally { await actions.cleanup(); }
  });

  test('nested workflow node parameters persist while the real child inherits parent context, with detail new-tab and back restoration', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const job = await actions.job('nested_parameters_job'), childName = ownedName('nested_child'), parentName = ownedName('nested_parent'); await actions.create(childName); const childJobNode = await actions.importJob(job.id), childId = await actions.save(childName); await actions.create(parentName); await page.locator('.flow-tools').getByRole('button', { name: 'Workflow', exact: true }).click(); const dialog = selectors.dialog(page, 'Import a workflow'); await fill(dialog, 'Workflow ID', childId); await clickAndResponse<PageDTO<RecordDTO>>(page, '/workflow/list', () => dialog.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.workflowId === childId); await dialog.locator('tbody tr').getByRole('checkbox').check(); const imported = await clickAndResponse<RecordDTO[]>(page, '/workflow/saveNode', () => dialog.getByRole('button', { name: 'Import selected (1)', exact: true }).click()); expect(imported.success).toBe(true); const nestedNode = id(imported.data[0]!.id); const inspector = await actions.select(nestedNode), nodeParams = '{\n"中文":"子节点配置 🚀",\n"reserved":"& + ? ="\n}'; await fill(inspector, 'Node parameters', nodeParams); await actions.nodeSave(inspector); const parentId = await actions.save(parentName); expect(workflowNodes(await backend.workflow(parentId))[0]!.nodeParams).toBe(nodeParams); await actions.edit(parentId); await actions.select(nestedNode); await expect(page.getByLabel('Node parameters', { exact: true })).toHaveValue(nodeParams);
      const init = '{"中文":"父上下文 🚀","reserved":"& + ? ="}', parentInstanceId = await actions.run(parentId, init), parent = await backend.waitWorkflowInstance(parentInstanceId), childInstanceId = id(workflowNodes(parent)[0]!.instanceId); actions.owned.trackInstance(childInstanceId, childId, 'WF_INSTANCE'); const child = await backend.waitWorkflowInstance(childInstanceId); trackChildren(actions.owned, child); expect(JSON.parse(String(child.wfInitParams))).toEqual(JSON.parse(String(parent.wfContext))); expect(child.wfContext).toEqual(parent.wfContext); expect(child.wfInitParams).not.toBe(nodeParams);
      await page.goto(`/#/oms/wfInstanceDetail?wfInstanceId=${parentInstanceId}`); await page.locator(`[data-node-id="${nestedNode}"]`).press('Enter'); await expect(page.locator('.run-inspector')).toContainText(nodeParams); await page.getByRole('button', { name: 'Open child workflow', exact: true }).click(); await expect(page).toHaveURL(new RegExp(`wfInstanceId=${childInstanceId}`)); await expect(page.getByRole('heading', { name: childName, exact: true })).toBeVisible(); await page.reload(); await expect(page.locator(`[data-node-id="${childJobNode}"]`)).toBeVisible(); const tab = await page.context().newPage(); try { await tab.goto(page.url()); await expect(tab.getByRole('heading', { name: childName, exact: true })).toBeVisible(); await expect(tab.locator(`[data-node-id="${childJobNode}"]`)).toBeVisible(); } finally { await tab.close(); } await page.goBack(); await expect(page).toHaveURL(new RegExp(`wfInstanceId=${parentInstanceId}`)); await expect(page.getByRole('heading', { name: parentName, exact: true })).toBeVisible(); await expect(page.locator(`[data-node-id="${nestedNode}"]`)).toBeVisible();
      for (const [caseId, variant] of [['UI-021','dag-subworkflow'],['UI-025','wfdetail-nested'],['UI-025','wfdetail-refresh-newtab'],['UI-025','wfdetail-id-switch']]) await observation(info, caseId!, variant!, { parentId, childId, parentInstanceId, childInstanceId, nodeParams, parent, child, childContextInheritanceVerified: true, nativeHistoryReturnedParent: true });
    } finally { await actions.cleanup(); }
  });

  test('observer receives real Server denials for workflow toggle, run, stop and retry without side effects', async ({ page, backend, credentials }, info) => {
    const admin = new AdminFixtures(backend); let resources: WorkflowActions | undefined;
    try {
      const space = await admin.space('wf_permission_space'), observer = await admin.user('wf_observer'), app = await admin.app('wf_permission_app', id(space.id), { componentUserRoleInfo: { observer: [observer.id], qa: [], developer: [], admin: [] } }), ownBackend = backend.forApp(id(app.id)), actions = resources = new WorkflowActions(page, ownBackend, info);
      await enterApplication(page, String(app.appName)); const job = await actions.job('permission_job'), name = ownedName('permission_flow'); await actions.create(name); await actions.importJob(job.id); const workflowId = await actions.save(name); const waitingId = id(await ownBackend.call('/workflow/run', { query: { workflowId, delay: 600000 } })); actions.owned.trackInstance(waitingId, workflowId, 'WF_INSTANCE'); const beforeInstances = await ownBackend.call<PageDTO<RecordDTO>>('/wfInstance/list', { method: 'POST', data: { appId: ownBackend.appId, workflowId, index: 0, pageSize: 100 } });
      await login(page, { ...credentials, admin_username: observer.origin, admin_password: observer.password }); await enterApplication(page, String(app.appName)); const row = await actions.list(workflowId); const toggled = await clickAndResponse(page, '/workflow/disable', () => row.getByRole('switch').uncheck()); expect(toggled.success).toBe(false); await expect(row.getByRole('switch')).toBeChecked(); await expect(page.locator('.error-banner[role="alert"]')).toBeVisible(); expect((await ownBackend.workflow(workflowId)).enable).toBe(true); const run = await clickAndResponse(page, '/workflow/run', () => row.getByRole('button', { name: 'Run', exact: true }).click()); expect(run.success).toBe(false); await expect(page.locator('.error-banner[role="alert"]')).toBeVisible(); const afterInstances = await ownBackend.call<PageDTO<RecordDTO>>('/wfInstance/list', { method: 'POST', data: { appId: ownBackend.appId, workflowId, index: 0, pageSize: 100 } }); expect(afterInstances.data.map(v => id(v.wfInstanceId))).toEqual(beforeInstances.data.map(v => id(v.wfInstanceId)));
      await page.goto(`/#/oms/wfinstance?workflowId=${workflowId}`); await expect(page.locator('tbody tr')).toHaveCount(1); await page.locator('tbody tr').getByRole('button', { name: 'Stop', exact: true }).click(); const stop = await clickAndResponse(page, '/wfInstance/stop', () => selectors.dialog(page).getByRole('button', { name: 'Confirm', exact: true }).click()); expect(stop.success).toBe(false); await expect(page.locator('.error-banner[role="alert"]')).toBeVisible(); expect((await ownBackend.workflowInstance(waitingId)).status).toBe(1); const retry = await clickAndResponse(page, '/wfInstance/retry', () => page.locator('tbody tr').getByRole('button', { name: 'Retry', exact: true }).click()); expect(retry.success).toBe(false); await expect(page.locator('.error-banner[role="alert"]')).toBeVisible(); expect((await ownBackend.workflowInstance(waitingId)).status).toBe(1);
      for (const [caseId, variant] of [['UI-020','workflow-status-fail'],['UI-023','workflow-run-fail'],['UI-024','wfinstance-permission']]) await observation(info, caseId!, variant!, { appId: id(app.id), observerId: observer.id, workflowId, waitingId, toggleDenied: true, switchRolledBack: true, runDeniedAndInstanceSetUnchanged: true, stopDeniedAndStateUnchanged: true, retryDeniedAndStateUnchanged: true, boundary: 'Independent app has no Workers; the delayed WAITING execution is an explicit API permission fixture, not a Worker-success claim.' });
    } finally { try { await resources?.cleanup(); } finally { await admin.cleanup(info); } }
  });
});
