import { test, expect, clickAndResponse, enterSamples, fill, id, observation, ownedName, processors, selectors, type PageDTO, type RecordDTO } from './helpers';
import { WorkflowActions, trackChildren, workflowNodes } from './workflow-actions';

test.describe('fresh remaining workflow boundary contracts', () => {
  test.use({ actionTimeout: 15_000 }); test.setTimeout(180_000);

  test('history entry, five exact status filters and eleven real workflow executions paginate, reset and refresh accurately', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const good = await actions.job('boundary_good'), name = ownedName('boundary_success'); await actions.create(name); const nodeId = await actions.importJob(good.id); await fill(page, 'Maximum parallel instances', '20'); const workflowId = await actions.save(name), successes: string[] = [];
      for (let i = 0; i < 11; i++) successes.push(await actions.run(workflowId));
      for (const instanceId of successes) trackChildren(actions.owned, await backend.waitWorkflowInstance(instanceId)); const sourceRow = await actions.list(workflowId); const history = await clickAndResponse<PageDTO<RecordDTO>>(page, '/wfInstance/list', () => sourceRow.getByRole('button', { name: 'Instances', exact: true }).click(), response => response.request().postDataJSON()?.workflowId === workflowId); expect(history.success).toBe(true); await expect(page).toHaveURL(new RegExp(`wfinstance\\?workflowId=${workflowId}`)); await expect(page.getByLabel('Workflow ID', { exact: true })).toHaveValue(workflowId); await expect(page.locator('.data-table tbody tr')).toHaveCount(10); const firstIDs = history.data.data.map(row => id(row.wfInstanceId)); const next = await clickAndResponse<PageDTO<RecordDTO>>(page, '/wfInstance/list', () => page.getByRole('button', { name: 'Next', exact: true }).click(), response => response.request().postDataJSON()?.index === 1); await expect(page.locator('.data-table tbody tr')).toHaveCount(1); const secondIDs = next.data.data.map(row => id(row.wfInstanceId)); expect([...firstIDs, ...secondIDs].sort()).toEqual([...successes].sort()); expect(secondIDs.some(value => firstIDs.includes(value))).toBe(false); const refreshed = await clickAndResponse<PageDTO<RecordDTO>>(page, '/wfInstance/list', () => page.getByRole('button', { name: 'Refresh', exact: true }).click(), response => response.request().postDataJSON()?.index === 1); expect(refreshed.data.data.map(row => id(row.wfInstanceId))).toEqual(secondIDs); await page.getByRole('button', { name: 'Reset', exact: true }).click(); await expect(page.getByLabel('Workflow ID', { exact: true })).toHaveValue(''); await expect(page.getByRole('button', { name: 'Previous', exact: true })).toBeDisabled();
      const failedJob = await actions.job('boundary_failed', 'failed'), failedName = ownedName('boundary_failure'); await actions.create(failedName); const failedNode = await actions.importJob(failedJob.id), failedWorkflow = await actions.save(failedName), failedId = await actions.run(failedWorkflow); const failed = await backend.waitWorkflowInstance(failedId, [3]); trackChildren(actions.owned, failed);
      const slowJob = await actions.job('boundary_running', '60000', processors.timeout), slowName = ownedName('boundary_running_flow'); await actions.create(slowName); const slowNode = await actions.importJob(slowJob.id), slowWorkflow = await actions.save(slowName), runningId = await actions.run(slowWorkflow); const running = await backend.waitWorkflowInstance(runningId, [2]); trackChildren(actions.owned, running);
      const waitingId = id(await backend.call('/workflow/run', { query: { workflowId, delay: 600000 } })); actions.owned.trackInstance(waitingId, workflowId, 'WF_INSTANCE'); const stoppedId = id(await backend.call('/workflow/run', { query: { workflowId, delay: 600000 } })); actions.owned.trackInstance(stoppedId, workflowId, 'WF_INSTANCE'); await page.goto(`/#/oms/wfinstance?workflowId=${workflowId}`); await fill(page, 'Instance ID', stoppedId); await clickAndResponse(page, '/wfInstance/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.wfInstanceId === stoppedId); await expect(page.locator('tbody tr')).toHaveCount(1); await page.locator('tbody tr').getByRole('button', { name: 'Stop', exact: true }).click(); await clickAndResponse(page, '/wfInstance/stop', () => selectors.dialog(page).getByRole('button', { name: 'Confirm', exact: true }).click()); await backend.waitWorkflowInstance(stoppedId, [10]);
      const axes = [{ status: 'RUNNING', numeric: 2, instanceId: runningId, definitionId: slowWorkflow, badge: 'Running', nodeId: slowNode },{ status: 'WAITING', numeric: 1, instanceId: waitingId, definitionId: workflowId, badge: 'Waiting' },{ status: 'STOPPED', numeric: 10, instanceId: stoppedId, definitionId: workflowId, badge: 'Stopped' },{ status: 'FAILED', numeric: 3, instanceId: failedId, definitionId: failedWorkflow, badge: 'Failed', nodeId: failedNode },{ status: 'SUCCEED', numeric: 4, instanceId: successes[0]!, definitionId: workflowId, badge: 'Succeeded', nodeId }]; const actualAxes: RecordDTO[] = [];
      for (const axis of axes) { await page.goto(`/#/oms/wfinstance?workflowId=${axis.definitionId}`); await fill(page, 'Instance ID', axis.instanceId); await page.getByLabel('Status', { exact: true }).selectOption(axis.status); const response = await clickAndResponse<PageDTO<RecordDTO>>(page, '/wfInstance/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), value => { const body = value.request().postDataJSON(); return body?.workflowId === axis.definitionId && body?.wfInstanceId === axis.instanceId && body?.status === axis.status; }); expect(response.success).toBe(true); expect(response.data.data.map(row => id(row.wfInstanceId))).toEqual([axis.instanceId]); expect(response.data.data[0]!.status).toBe(axis.numeric); await expect(page.locator('tbody tr')).toHaveCount(1); await expect(page.locator('tbody tr .badge')).toHaveText(axis.badge); const independent = await backend.workflowInstance(axis.instanceId); expect(independent.status).toBe(axis.numeric); actualAxes.push({ ...axis, independent, returned: response.data }); if (axis.nodeId) { await page.locator('tbody tr').getByRole('button', { name: 'Details', exact: true }).click(); await expect(page).toHaveURL(new RegExp(`wfInstanceId=${axis.instanceId}`)); await page.locator(`[data-node-id="${axis.nodeId}"]`).press('Enter'); await expect(page.locator('.run-inspector>header .badge')).toHaveText(axis.badge); const childId = id(workflowNodes(independent).find(n => id(n.nodeId) === axis.nodeId)!.instanceId); await expect(page.locator('.instance-detail .facts').getByText('Instance ID', { exact: true }).locator('xpath=following-sibling::dd[1]')).toHaveText(childId); const childDetails = await backend.call<RecordDTO>('/instance/detailPlus', { method: 'POST', data: { instanceId: childId } }); expect(childDetails.status).toBe(axis.status === 'FAILED' ? 4 : axis.status === 'SUCCEED' ? 5 : 2); await expect(page.locator('.instance-detail .facts').getByText('Result', { exact: true }).locator('xpath=following-sibling::dd[1]')).toHaveText(String(childDetails.result ?? '—')); actualAxes[actualAxes.length - 1]!.childDetails = childDetails; await page.goBack(); await expect(page).toHaveURL(new RegExp(`workflowId=${axis.definitionId}`)); } }
      for (const [caseId, variant] of [['UI-023','workflow-run-history'],['UI-024','wfinstance-filters'],['UI-024','wfinstance-pagination'],['UI-025','wfdetail-node-statuses']]) await observation(info, caseId!, variant!, { workflowId, successes, firstIDs, secondIDs, refreshExactSecondPage: true, axes: actualAxes, delayedWaitingStoppedBoundary: 'Two explicit delayed API fixtures establish deterministic WAITING/STOPPED status rows; all eleven Success plus Running/Failed were triggered through the page and actual Workers.' });
    } finally { await actions.cleanup(); }
  });

  test('cycle, duplicate and self edges visibly fail without replacing the persisted graph; single lifecycle bounds and explicit clearing remain exact', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const job = await actions.job('cycle_job'), name = ownedName('cycle_boundaries'); await actions.create(name); const a = await actions.importJob(job.id), b = await actions.importJob(job.id); await actions.connect(a, b); const workflowId = await actions.save(name), official = await backend.workflow(workflowId); await actions.connect(b, a); await expect(page.getByText('This connection would create a cycle', { exact: true })).toBeVisible(); await expect(page.locator('.flow-edge')).toHaveCount(1); await actions.connect(a, b); await expect(page.getByText('This connection already exists', { exact: true })).toBeVisible(); await actions.connect(a, a); await expect(page.getByText('A node cannot connect to itself', { exact: true })).toBeVisible(); expect((await backend.workflow(workflowId)).peworkflowDAG).toEqual(official.peworkflowDAG); expect(await actions.save()).toBe(workflowId); expect((await backend.workflow(workflowId)).peworkflowDAG).toEqual(official.peworkflowDAG);
      await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await fill(page, 'Lifecycle end', '2031-01-01T00:00'); await actions.save(); const endOnly = await backend.workflow(workflowId); expect(endOnly.lifeCycle).toEqual({ start: null, end: Date.parse('2031-01-01T00:00:00+08:00') }); await page.reload(); await expect(page.getByRole('heading', { name, exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Workflow settings', exact: true }).click(); await expect(page.getByLabel('Lifecycle start', { exact: true })).toHaveValue(''); await expect(page.getByLabel('Lifecycle end', { exact: true })).toHaveValue('2031-01-01T00:00'); await fill(page, 'Lifecycle end', ''); await fill(page, 'Lifecycle start', '2020-01-01T00:00'); await actions.save(); const startOnly = await backend.workflow(workflowId); expect(startOnly.lifeCycle).toEqual({ start: Date.parse('2020-01-01T00:00:00+08:00'), end: null }); await fill(page, 'Lifecycle start', ''); await actions.save(); const cleared = await backend.workflow(workflowId); expect(cleared.lifeCycle).toEqual({ start: null, end: null });
      await observation(info, 'UI-021', 'dag-cycle-reject', { workflowId, official, rejectedEdgesVisible: ['cycle','duplicate','self'], formalGraphUnchanged: true }); await observation(info, 'UI-039', 'dates-locale-format', { workflowId, timezone: 'Asia/Shanghai', endOnly, startOnly, cleared, nativeInputsCanonicalizedMinutes: true });
    } finally { await actions.cleanup(); }
  });
});
