import { test, expect, clickAndResponse, enterSamples, fill, id, observation, ownedName, parseResult, selectors, type PageDTO, type RecordDTO } from './helpers';
import { WorkflowActions } from './workflow-actions';

test.describe('fresh workflow regressions corresponding to upstream PR 63', () => {
  test.use({ actionTimeout: 15_000 }); test.setTimeout(180_000);
  test('definition query/reset always use page zero and a late real list response cannot replace the newer filter', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const job = await actions.job('upstream_list_job'), definitions: string[] = [];
      for (let i = 0; i < 11; i++) { const name = ownedName(`upstream_list_${i}`); await actions.create(name); await actions.importJob(job.id); definitions.push(await actions.save(name)); }
      await page.goto('/#/oms/workflow'); await fill(page, 'Name', ownedName('upstream_list')); const first = await clickAndResponse<PageDTO<RecordDTO>>(page, '/workflow/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === ownedName('upstream_list')); expect(first.success).toBe(true); await expect(page.locator('tbody tr')).toHaveCount(10); const second = await clickAndResponse<PageDTO<RecordDTO>>(page, '/workflow/list', () => page.getByRole('button', { name: 'Next', exact: true }).click(), response => response.request().postDataJSON()?.index === 1); await expect(page.locator('tbody tr')).toHaveCount(1); expect([...first.data.data,...second.data.data].map(row => id(row.id)).sort()).toEqual([...definitions].sort());
      await fill(page, 'Workflow ID', definitions[0]!); const exact = await clickAndResponse<PageDTO<RecordDTO>>(page, '/workflow/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => { const body = response.request().postDataJSON(); return body?.workflowId === definitions[0] && body.index === 0; }); expect(exact.data.data.map(row => id(row.id))).toEqual([definitions[0]]); await expect(page.getByRole('button', { name: 'Previous', exact: true })).toBeDisabled(); const reset = await clickAndResponse<PageDTO<RecordDTO>>(page, '/workflow/list', () => page.getByRole('button', { name: 'Reset', exact: true }).click(), response => { const body = response.request().postDataJSON(); return body?.index === 0 && !body.keyword && !body.workflowId; }); expect(reset.success).toBe(true); await expect(page.getByLabel('Name', { exact: true })).toHaveValue(''); await expect(page.getByLabel('Workflow ID', { exact: true })).toHaveValue(''); await expect(page.getByRole('button', { name: 'Previous', exact: true })).toBeDisabled();
      const nameA = ownedName('upstream_race_a'), nameB = ownedName('upstream_race_b'); await actions.create(nameA); await actions.importJob(job.id); const a = await actions.save(nameA); await actions.create(nameB); await actions.importJob(job.id); const b = await actions.save(nameB); await page.goto('/#/oms/workflow'); let release!: () => void; const held = new Promise<void>(resolve => { release = resolve; }); let intercepted = false; await page.route('**/workflow/list', async route => { if (!intercepted && route.request().postDataJSON()?.keyword === nameA) { intercepted = true; const original = await route.fetch(); await held; await route.fulfill({ response: original }); } else await route.continue(); }); await fill(page, 'Name', nameA); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect.poll(() => intercepted).toBe(true); await fill(page, 'Name', nameB); const newer = await clickAndResponse<PageDTO<RecordDTO>>(page, '/workflow/list', () => page.getByRole('button', { name: 'Search', exact: true }).click(), response => response.request().postDataJSON()?.keyword === nameB); expect(newer.data.data.map(row => id(row.id))).toEqual([b]); await expect(page.locator('tbody tr')).toHaveCount(1); await expect(page.locator('tbody tr')).toContainText(nameB); const delayed = page.waitForResponse(response => new URL(response.url()).pathname.endsWith('/workflow/list') && response.request().postDataJSON()?.keyword === nameA).then(async response => parseResult<PageDTO<RecordDTO>>(await response.text())); release(); const old = await delayed; expect(old.data.data.map(row => id(row.id))).toEqual([a]); await expect(page.locator('tbody tr')).toHaveCount(1); await expect(page.locator('tbody tr')).toContainText(nameB); await page.unroute('**/workflow/list');
      await observation(info, 'UI-020', 'workflow-page-reset', { definitions, pages: [first.data,second.data], queryIndexZero: true, resetIndexZero: true, previousDisabledAfterBoth: true }); await observation(info, 'UI-020', 'workflow-list-late-response', { a, b, old: old.data, newer: newer.data, visibleOnlyB: true, originalServerResponsesHeldWithoutFabricatedBusinessBody: true });
    } finally { await actions.cleanup(); }
  });

  test('run-parameter dialog close resets draft and switching condition nodes shows each real Monaco value without optional Job controls', async ({ page, backend, credentials }, info) => {
    const actions = new WorkflowActions(page, backend, info);
    try {
      await enterSamples(page, credentials); const job = await actions.job('upstream_code_job'), name = ownedName('upstream_code_flow'); await actions.create(name); const a = await actions.importJob(job.id), b = await actions.importJob(job.id), c1 = await actions.condition(), c2 = await actions.condition(); const firstCode = 'return true // alpha-node', secondCode = 'return false // beta-node'; const firstInspector = await actions.select(c1); await actions.code(firstInspector, firstCode); await actions.nodeSave(firstInspector); const secondInspector = await actions.select(c2); await actions.code(secondInspector, secondCode); await actions.nodeSave(secondInspector); await actions.connect(c1, a); await actions.connect(c1, b); await actions.connect(c2, a); await actions.connect(c2, b); const workflowId = await actions.save(name);
      for (const [nodeId, code] of [[c1,firstCode],[c2,secondCode],[c1,firstCode],[c2,secondCode]]) { const inspector = await actions.select(nodeId!); await expect(inspector.locator('.monaco-editor .view-lines')).toContainText(code!); await expect(inspector.locator('.node-flags')).toHaveCount(0); await expect(inspector.getByLabel('Job', { exact: true })).toHaveCount(0); await expect(inspector.getByLabel('Enable node', { exact: true })).toHaveCount(0); await expect(inspector.getByLabel('Continue after failure', { exact: true })).toHaveCount(0); }
      const actual = await backend.workflow(workflowId); expect(workflowNodesOf(actual).filter(n => Number(n.nodeType) === 2).map(n => n.jobId)).toEqual([null,null]); expect(workflowNodesOf(actual).filter(n => Number(n.nodeType) === 2).map(n => n.nodeParams)).toEqual([firstCode,secondCode]); const row = await actions.list(workflowId); let requests = 0; page.on('request', request => { if (new URL(request.url()).pathname.endsWith('/workflow/run')) requests++; }); await row.getByRole('button', { name: 'Run with parameters', exact: true }).click(); const dialog = selectors.dialog(page, 'Run with parameters'); await fill(dialog, 'Initial parameters', 'Discarded 中文 🚀 & +'); await dialog.getByRole('button', { name: 'Close', exact: true }).click(); await expect(dialog).not.toBeVisible(); await row.getByRole('button', { name: 'Run with parameters', exact: true }).click(); await expect(dialog.getByLabel('Initial parameters', { exact: true })).toHaveValue(''); await fill(dialog, 'Initial parameters', 'Second draft is also discarded'); await dialog.getByRole('button', { name: 'Cancel', exact: true }).click(); await row.getByRole('button', { name: 'Run with parameters', exact: true }).click(); await expect(dialog.getByLabel('Initial parameters', { exact: true })).toHaveValue(''); await dialog.getByRole('button', { name: 'Cancel', exact: true }).click(); expect(requests).toBe(0); const instances = await backend.call<PageDTO<RecordDTO>>('/wfInstance/list', { method: 'POST', data: { appId: backend.appId, workflowId, index: 0, pageSize: 10 } }); expect(instances.data).toHaveLength(0);
      await observation(info, 'UI-023', 'workflow-run-parameter-cancel-reset', { workflowId, canceledRuns: requests, noHiddenInstances: true, closedAndCanceledDraftsDiscarded: true }); await observation(info, 'UI-034', 'dag-code-prop-node-switch', { workflowId, nodes: actual.peworkflowDAG, codePropSwitches: 4, emptyJobReferences: [null,null], optionalJobControlsAbsent: true });
    } finally { await actions.cleanup(); }
  });
});
function workflowNodesOf(value: RecordDTO) { return (value.peworkflowDAG as { nodes: RecordDTO[] }).nodes; }
