<script setup lang="ts">
import { computed,ref,watch } from 'vue'
import { api } from '../../core/api'
import { useLatestRequest } from '../../core/request'
import type { Entity } from '../../core/session'
import { t,formatTime,instanceStatus } from '../../core/ui'
import Logs from './Logs.vue'
import Field from '../../shared/Field.vue'
const props=defineProps<{instanceId:string}>()
const detail=ref<Entity>({}),tab=ref('details'),error=ref(''),predicate=ref('status in (5, 6) order by last_modified_time desc')
const request=useLatestRequest(),{loading}=request
const columns=computed(()=>[{key:'taskId',label:'Task ID'},{key:'taskName',label:t('任务名称','Task name')},{key:'taskContent',label:t('任务内容','Task content')},{key:'processorAddress',label:t('处理器地址','Processor address')},{key:'failedCnt',label:t('失败次数','Failures')},{key:'statusStr',label:t('状态','Status')},{key:'createdTimeStr',label:t('创建时间','Created')},{key:'lastModifiedTimeStr',label:t('更新时间','Updated')},{key:'lastReportTimeStr',label:t('上报时间','Reported')},{key:'result',label:t('结果','Result')}])
const fields=computed(()=>[
 [t('实例 ID','Instance ID'),props.instanceId],[t('状态','Status'),instanceStatus(detail.value.status)],
 [t('运行次数','Run count'),detail.value.runningTimes],[t('TaskTracker 地址','TaskTracker address'),detail.value.taskTrackerAddress],
 [t('计划触发时间','Expected start'),formatTime(detail.value.expectedTriggerTime)],[t('实际触发时间','Started'),formatTime(detail.value.actualTriggerTime||detail.value.startTime)],
 [t('结束时间','Finished'),formatTime(detail.value.finishedTime)],[t('任务参数','Job parameters'),detail.value.jobParams??detail.value.nodeParams],
 [t('实例参数','Instance parameters'),detail.value.instanceParams],[t('执行结果','Result'),detail.value.result],
 ...(detail.value.taskDetail?[[t('子任务统计','Task summary'),detail.value.taskDetail]]:[]),
])
async function load(){if(!props.instanceId)return;const current=request.begin();try{const data=await api<Entity>('/instance/detailPlus',{body:{instanceId:props.instanceId,customQuery:predicate.value},signal:current.signal,quiet:true});if(current.current()){detail.value=data||{};error.value=''}}catch(e){if(current.current()&&!current.signal.aborted)error.value=(e as Error).message}finally{current.end()}}
watch(()=>props.instanceId,()=>{detail.value={};error.value='';predicate.value='status in (5, 6) order by last_modified_time desc';tab.value='details';load()},{immediate:true})
</script>
<template><section class="instance-detail" :aria-busy="loading"><div class="detail-controls"><div class="tabs"><button type="button" :class="{active:tab==='details'}" @click="tab='details'">{{t('详情','Details')}}</button><button type="button" :class="{active:tab==='logs'}" @click="tab='logs'">{{t('日志','Logs')}}</button></div><button type="button" class="btn" :disabled="loading" @click="load">{{t('刷新详情','Refresh details')}}</button></div><p v-if="error" class="error-banner" role="alert">{{error}}</p><template v-if="tab==='details'"><dl class="facts"><template v-for="field in fields" :key="String(field[0])"><dt>{{field[0]}}</dt><dd><pre class="detail-text">{{field[1]??'—'}}</pre></dd></template></dl><slot/><template v-if="detail.subInstanceDetails?.length"><h3 class="detail-subtitle">{{t('高频任务执行记录','High frequency runs')}}</h3><div class="table-scroll"><table class="data-table"><thead><tr><th>{{t('子实例 ID','Sub-instance ID')}}</th><th>{{t('开始时间','Started')}}</th><th>{{t('结束时间','Finished')}}</th><th>{{t('状态','Status')}}</th><th>{{t('结果','Result')}}</th></tr></thead><tbody><tr v-for="item in detail.subInstanceDetails" :key="item.subInstanceId"><td>{{item.subInstanceId}}</td><td>{{formatTime(item.startTime)}}</td><td>{{formatTime(item.finishedTime)}}</td><td>{{instanceStatus(item.status)}}</td><td>{{item.result||'—'}}</td></tr></tbody></table></div></template><template v-if="Array.isArray(detail.queriedTaskDetailInfoList)"><h3 class="detail-subtitle">{{t('子任务查询','Task query')}}</h3><form class="task-query" @submit.prevent="load"><Field :label="t('查询条件','Query predicate')" :hint="'select * from task_info where … limit 10'"><input v-model="predicate" class="code"/></Field><button class="btn btn-primary" :disabled="loading">{{t('查询','Search')}}</button></form><div class="table-scroll"><table class="data-table"><thead><tr><th v-for="column in columns" :key="column.key">{{column.label}}</th></tr></thead><tbody><tr v-for="(item,index) in detail.queriedTaskDetailInfoList" :key="item.taskId||index"><td v-for="column in columns" :key="column.key" :title="String(item[column.key]??'')">{{item[column.key]??'—'}}</td></tr></tbody></table></div><p v-if="!detail.queriedTaskDetailInfoList.length" class="muted">{{t('没有匹配的子任务','No matching tasks')}}</p></template></template><Logs v-else :instance-id="instanceId"/></section></template>
<style scoped>.detail-controls{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px;gap:12px;flex-wrap:wrap}.detail-text{margin:0;font:inherit;white-space:pre-wrap;overflow-wrap:anywhere}.detail-subtitle{margin:24px 0 15px}.task-query{display:flex;align-items:flex-end;gap:12px;margin-bottom:16px}.task-query .field{flex:1}@media(max-width:640px){.task-query{flex-direction:column;align-items:stretch}}</style>
