import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Alert, App, Button, Drawer, Empty, Form, Input, Modal, Popconfirm, Radio, Select, Space, Switch, Table, Typography, Upload, type UploadFile, type UploadProps } from 'antd';
import { Download, Package, Pencil, Play, Plus, RefreshCw, Server, Trash2, UploadCloud } from 'lucide-react';
import { ApiError, api, downloadBlob, websocketUrl, type DataRecord } from '../lib/api';
import { useConsole } from '../lib/console';
import { useSessionQuery, useSessionScope } from '../lib/sessionScope';
import { EnumTag, enumLabel } from '../lib/enums';
import { ErrorState, PageHeader, Panel, RefreshButton, formatTime } from '../components/ui';
import { assertZipDownload, containerPayload, deploymentStateFromLine, deploymentStateOnClose, maskDeploymentLog, parseContainerSource, uploadJarFile, type DeployState } from '../features/workflow/transport';
import { useRequestScope } from '../features/workflow/requestScope';
import '../features/workflow/workflow.css';

export function ContainerTemplate() {
  const { t } = useConsole(); const session = useSessionScope(); const { message } = App.useApp(); const [form] = Form.useForm(); const [busy, setBusy] = useState(false);
  useEffect(() => { setBusy(false); form.resetFields(); }, [session]);
  const generate = async () => { if (!session.current()) return; const values = await form.validateFields().catch(() => undefined); if (!values || !session.current()) return; setBusy(true); try { const file = await api.post<Blob>('/container/downloadContainerTemplate', values, { ...session.options, responseType: 'blob', timeout: 60000 }); if (!session.current()) return; const archive = await assertZipDownload(file); if (session.current()) downloadBlob(archive, `${values.artifact || 'template'}.zip`); } catch (error) { if (session.current() && !(error instanceof ApiError) && (error as Error).name !== 'AbortError') void message.error((error as Error).message); } finally { if (session.current()) setBusy(false); } };
  return <><PageHeader title={t('容器开发模板', 'Container starter project')} description={t('生成可独立构建的 Java 任务项目，部署到 Worker 动态运行。', 'Generate a Java job project that can be built independently and deployed to workers.')} /><Panel title={t('项目设置', 'Project settings')}><Form name="containerTemplate" form={form} layout="vertical" className="container-template-form" initialValues={{ javaVersion: 8 }}><div className="workflow-fields two"><Form.Item label="Group ID" name="group" rules={[{ required: true, whitespace: true, message: t('请输入 Group ID', 'Enter a Group ID') }]}><Input placeholder="com.example"/></Form.Item><Form.Item label="Artifact ID" name="artifact" rules={[{ required: true, message: t('请输入 Artifact ID', 'Enter an Artifact ID') }, { pattern: /^[A-Za-z0-9_.-]+$/, message: t('使用字母、数字、点、下划线或连字符', 'Use letters, digits, dots, underscores or hyphens') }]}><Input placeholder="powerjob-tasks"/></Form.Item><Form.Item label={t('项目名称', 'Project name')} name="name" rules={[{ required: true, whitespace: true, message: t('请输入项目名称', 'Enter a project name') }]}><Input placeholder="PowerJob Tasks"/></Form.Item><Form.Item label={t('Java 包名', 'Java package')} name="packageName" rules={[{ required: true, whitespace: true, message: t('请输入 Java 包名', 'Enter a Java package') }]}><Input placeholder="com.example.tasks"/></Form.Item><Form.Item label={t('Java 版本', 'Java version')} name="javaVersion" rules={[{ required: true }]}><Radio.Group options={[{ value: 8, label: 'Java 8' }, { value: 11, label: 'Java 11' }]}/></Form.Item></div><Button type="primary" icon={<Download size={16}/>} loading={busy} onClick={() => void generate()}>{t('生成并下载 ZIP', 'Generate and download ZIP')}</Button></Form></Panel></>;
}

function ContainerManager() {
  const navigate = useNavigate();
  const { appId, language, t } = useConsole(); const { message } = App.useApp(); const session = useSessionScope(); const scope = useRequestScope(appId, session); const editorScope = useRequestScope(appId, session); const workerScope = useRequestScope(appId, session); const [form] = Form.useForm(); const [editing, setEditing] = useState<DataRecord>(); const [editOpen, setEditOpen] = useState(false); const [busy, setBusy] = useState(false); const [jarSource, setJarSource] = useState(''); const [files, setFiles] = useState<UploadFile[]>([]); const [uploading, setUploading] = useState(false);
  const [deployment, setDeployment] = useState<DataRecord>(); const [logs, setLogs] = useState<string[]>([]); const [deployState, setDeployState] = useState<DeployState>('closed'); const [workersFor, setWorkersFor] = useState<DataRecord>(); const [workerLog, setWorkerLog] = useState(''); const [workerBusy, setWorkerBusy] = useState(false); const [workerError, setWorkerError] = useState<Error>(); const [actionId, setActionId] = useState(''); const socket = useRef<WebSocket | undefined>(undefined); const socketSequence = useRef(0); const uploadSequence = useRef(0); const uploadController = useRef<AbortController | undefined>(undefined); const logEnd = useRef<HTMLDivElement>(null);
  const list = useSessionQuery(session, () => api.get<DataRecord[]>('/container/list', { appId }, session.options), [appId]); const sourceType = Form.useWatch('sourceType', form);
  useEffect(() => { ++uploadSequence.current; uploadController.current?.abort(); setUploading(false); ++socketSequence.current; socket.current?.close(); socket.current = undefined; setDeployment(undefined); setLogs([]); setWorkersFor(undefined); setWorkerLog(''); setWorkerBusy(false); setWorkerError(undefined); setEditOpen(false); setEditing(undefined); setBusy(false); setActionId(''); setJarSource(''); setFiles([]); setDeployState('closed'); form.resetFields(); return () => { ++uploadSequence.current; uploadController.current?.abort(); ++socketSequence.current; socket.current?.close(); }; }, [appId, session]);
  useEffect(() => { logEnd.current?.scrollIntoView({ block: 'nearest' }); }, [logs]);
  const closeEditor = () => { editorScope.invalidate(); setBusy(false); ++uploadSequence.current; uploadController.current?.abort(); setUploading(false); setEditOpen(false); };
  const openEditor = (row?: DataRecord) => { if (!session.current()) return; editorScope.invalidate(); setBusy(false); ++uploadSequence.current; uploadController.current?.abort(); setUploading(false); setEditing(row); setFiles([]); setJarSource(row?.sourceType === 'FatJar' ? row.sourceInfo || '' : ''); form.resetFields(); form.setFieldsValue({ containerName: row?.containerName || '', sourceType: row?.sourceType || 'Git', status: row?.status || 'ENABLE', repo: '', branch: '', username: '', password: '', ...(row ? parseContainerSource(row) : {}) }); setEditOpen(true); };
  const save = async () => { const token = editorScope.capture(); const appToken = scope.capture(); const values = await form.validateFields().catch(() => undefined); if (!values || !editorScope.current(token)) return; if (values.sourceType === 'FatJar' && !jarSource) { void message.warning(t('请先上传 JAR 文件', 'Upload a JAR file first')); return; } setBusy(true); try { await api.post('/container/save', containerPayload(values, appId, jarSource, editing?.id), { ...session.options, headers: { AppId: appId } }); if (!editorScope.current(token)) { if (scope.current(appToken)) void list.refresh(); return; } setEditOpen(false); setJarSource(''); setFiles([]); void message.success(t('容器已保存', 'Container saved')); await list.refresh(); } catch {} finally { if (editorScope.current(token)) setBusy(false); } };
  const upload: UploadProps['customRequest'] = async options => { const token = editorScope.capture(); if (!editorScope.current(token)) return; const generation = ++uploadSequence.current; uploadController.current?.abort(); const controller = new AbortController(); uploadController.current = controller; const abort = () => controller.abort(); session.options.signal.addEventListener('abort', abort, { once: true }); setUploading(true); try { const source = await uploadJarFile(options.file as File, appId, controller.signal); if (!editorScope.current(token) || generation !== uploadSequence.current) return; setJarSource(source); options.onSuccess?.({ success: true, data: source }); void message.success(t('JAR 已上传', 'JAR uploaded')); } catch (error) { if (editorScope.current(token) && generation === uploadSequence.current && !controller.signal.aborted) { options.onError?.(error as Error); if (!(error instanceof ApiError)) void message.error((error as Error).message); } } finally { session.options.signal.removeEventListener('abort', abort); if (editorScope.current(token) && generation === uploadSequence.current) setUploading(false); } };
  const remove = async (row: DataRecord) => { const token = scope.capture(); if (!scope.current(token)) return; setActionId(String(row.id)); try { await api.get('/container/delete', { appId, containerId: row.id }, { ...session.options, headers: { AppId: appId } }); if (!scope.current(token)) return; void message.success(t('容器已删除', 'Container deleted')); await list.refresh(); } catch {} finally { if (scope.current(token)) setActionId(''); } };
  const switchStatus = async (row: DataRecord, enable: boolean) => { const token = scope.capture(); if (!scope.current(token)) return; setActionId(String(row.id)); try { await api.post('/container/save', { id: row.id, appId, containerName: row.containerName, sourceType: row.sourceType, sourceInfo: row.sourceInfo, status: enable ? 'ENABLE' : 'DISABLE' }, { ...session.options, headers: { AppId: appId } }); if (scope.current(token)) await list.refresh(); } catch {} finally { if (scope.current(token)) setActionId(''); } };
  const closeDeployment = () => { ++socketSequence.current; socket.current?.close(); socket.current = undefined; setDeployment(undefined); setLogs([]); setDeployState('closed'); if (session.current()) void list.refresh(); };
  const deploy = (row: DataRecord) => {
    const token = scope.capture(); if (!scope.current(token)) return;
    ++socketSequence.current; socket.current?.close(); const generation = socketSequence.current; setLogs([]); setDeployState('connecting'); setDeployment(row); const source = parseContainerSource(row);
    try { const connection = new WebSocket(websocketUrl(`/container/deploy/${row.id}`)); socket.current = connection; connection.onopen = () => { if (scope.current(token) && generation === socketSequence.current) setDeployState('running'); }; connection.onmessage = event => { if (!scope.current(token) || generation !== socketSequence.current) return; const line = maskDeploymentLog(String(event.data), source); setLogs(current => [...current, line]); setDeployState(current => deploymentStateFromLine(current, line)); }; connection.onerror = () => { if (scope.current(token) && generation === socketSequence.current) { setDeployState('failed'); setLogs(current => [...current, t('连接失败，请检查服务连接后重试。', 'Connection failed. Check the server connection and retry.')]); } }; connection.onclose = () => { if (scope.current(token) && generation === socketSequence.current) { setDeployState(deploymentStateOnClose); socket.current = undefined; void list.refresh(); } }; } catch { setDeployState('failed'); setLogs([t('无法建立部署连接，请检查服务地址。', 'Unable to open the deployment connection. Check the server URL.')]); }
  };
  const closeWorkers = () => { workerScope.invalidate(); setWorkersFor(undefined); setWorkerLog(''); setWorkerError(undefined); setWorkerBusy(false); };
  const loadWorkers = async (row: DataRecord) => { if (!session.current()) return; workerScope.invalidate(); const token = workerScope.capture(); setWorkersFor(row); setWorkerLog(''); setWorkerBusy(true); setWorkerError(undefined); try { const result = await api.get<string>('/container/listDeployedWorker', { appId, containerId: row.id }, { ...session.options, headers: { AppId: appId } }); if (!workerScope.current(token)) return; setWorkerLog(result || t('暂无部署信息', 'No deployment information yet')); } catch (error) { if (workerScope.current(token)) setWorkerError(error as Error); } finally { if (workerScope.current(token)) setWorkerBusy(false); } };
  const deploymentLabel = enumLabel('containerDeployment', deployState, language);
  return <><PageHeader title={t('容器管理', 'Containers')} description={t('将独立任务代码部署到 Worker，无需重启应用。', 'Deploy standalone job code to workers without restarting applications.')} actions={<Space><RefreshButton loading={list.loading} onClick={() => void list.refresh()}/><Button icon={<Download size={16}/>} onClick={() => navigate('/oms/template')}>{t('开发模板', 'Starter template')}</Button><Button type="primary" icon={<Plus size={16}/>} onClick={() => openEditor()}>{t('新建容器', 'Create container')}</Button></Space>}/><Panel><ErrorState error={list.error} retry={() => void list.refresh()}/><Table rowKey={row => String(row.id)} dataSource={list.data || []} loading={list.loading} scroll={{ x: 1100 }} pagination={false} columns={[
    { title: t('容器', 'Container'), width: 250, render: (_, row) => <Space><Package size={18}/><div><div className="workflow-table-title">{row.containerName}</div><div className="workflow-table-description">#{row.id}</div></div></Space> }, { title: t('来源', 'Source'), dataIndex: 'sourceType', width: 140, render: (type: string) => <EnumTag kind="containerType" value={type}/> }, { title: t('版本', 'Version'), dataIndex: 'version', width: 230, render: (version: string) => version ? <Typography.Text className="container-version" copyable title={version}>{version}</Typography.Text> : '—' }, { title: t('最近部署', 'Last deployed'), dataIndex: 'lastDeployTime', width: 170, render: formatTime }, { title: t('启用', 'Enabled'), width: 85, render: (_, row) => <Switch checked={row.status === 'ENABLE'} loading={actionId === String(row.id)} onChange={enable => void switchStatus(row, enable)}/> }, { title: t('操作', 'Actions'), width: 340, render: (_, row) => <Space size={2}><Button type="text" icon={<Play size={14}/>} onClick={() => deploy(row)}>{t('部署', 'Deploy')}</Button><Button type="text" icon={<Pencil size={14}/>} onClick={() => openEditor(row)}>{t('编辑', 'Edit')}</Button><Button type="text" icon={<Server size={14}/>} onClick={() => void loadWorkers(row)}>{t('已部署 Worker', 'Deployed workers')}</Button><Popconfirm title={t('删除这个容器？', 'Delete this container?')} description={row.containerName} onConfirm={() => void remove(row)}><Button type="text" danger icon={<Trash2 size={14}/>} aria-label={t('删除容器', 'Delete container')} disabled={!!actionId}/></Popconfirm></Space> }
  ]}/></Panel>
  <Modal title={editing ? t('编辑容器', 'Edit container') : t('新建容器', 'Create container')} open={editOpen} width={620} onCancel={closeEditor} onOk={() => void save()} confirmLoading={busy} okButtonProps={{ disabled: uploading }} okText={t('保存容器', 'Save container')}><Form name="containerEditor" form={form} layout="vertical"><Form.Item label={t('容器名称', 'Container name')} name="containerName" rules={[{ required: true, whitespace: true, message: t('请输入容器名称', 'Enter a container name') }]}><Input/></Form.Item><Form.Item label={t('代码来源', 'Code source')} name="sourceType"><Radio.Group options={['Git', 'FatJar'].map(value => ({ value, label: enumLabel('containerType', value, language) }))}/></Form.Item>
    {sourceType === 'Git' ? <><Form.Item label={t('Git 仓库地址', 'Git repository URL')} name="repo" rules={[{ required: true, whitespace: true, message: t('请输入仓库地址', 'Enter a repository URL') }]}><Input placeholder="https://git.example.com/team/tasks.git"/></Form.Item><Form.Item label={t('分支名称', 'Branch')} name="branch"><Input placeholder="main"/></Form.Item><div className="workflow-fields two"><Form.Item label={t('用户名（可选）', 'Username (optional)')} name="username"><Input autoComplete="off"/></Form.Item><Form.Item label={t('密码（可选）', 'Password (optional)')} name="password"><Input.Password autoComplete="new-password"/></Form.Item></div></> : <Form.Item label={t('JAR 文件', 'JAR file')}><Upload.Dragger accept=".jar" maxCount={1} customRequest={upload} fileList={files} onChange={info => setFiles(info.fileList)} onRemove={() => { ++uploadSequence.current; uploadController.current?.abort(); setUploading(false); setJarSource(''); return true; }}><UploadCloud size={30} color="#617084" style={{ margin: '10px auto' }}/><p>{t('选择或拖入 JAR 文件', 'Choose or drop a JAR file')}</p><Typography.Text type="secondary">{t('上传包含独立任务 Processor 的 Fat JAR。', 'Upload a Fat JAR containing standalone job processors.')}</Typography.Text></Upload.Dragger>{jarSource && <Typography.Paragraph type="secondary" style={{ marginTop: 10, marginBottom: 0 }}>{t('当前制品', 'Current artifact')}: <Typography.Text code>{jarSource}</Typography.Text></Typography.Paragraph>}</Form.Item>}
    <Form.Item label={t('容器状态', 'Container status')} name="status"><Select options={['ENABLE', 'DISABLE'].map(value => ({ value, label: enumLabel('containerStatus', value, language) }))}/></Form.Item></Form></Modal>
  <Drawer title={`${t('部署容器', 'Deploy container')} / ${deployment?.containerName || ''}`} open={!!deployment} onClose={closeDeployment} size="large" extra={<EnumTag kind="containerDeployment" value={deployState}/>}><Alert showIcon type={deployState === 'failed' ? 'error' : 'info'} title={deployState === 'finished' ? t('部署请求已发送。请核对 Worker 上加载的版本。', 'Deployment requests sent. Check the version loaded on each worker.') : deploymentLabel} style={{ marginBottom: 16 }}/><div className="container-log" role="log" aria-label={t('部署日志', 'Deployment logs')}>{logs.length ? logs.map((line, index) => <div key={index}>{line}</div>) : t('等待服务端部署日志…', 'Waiting for server deployment logs…')}<div ref={logEnd}/></div><Space style={{ marginTop: 18 }} wrap><Button icon={<RefreshCw size={15}/>} onClick={() => deployment && void loadWorkers(deployment)}>{t('查看已部署 Worker', 'View deployed workers')}</Button>{['failed', 'closed'].includes(deployState) && <Button type="primary" icon={<Play size={15}/>} onClick={() => deployment && deploy(deployment)}>{t('重新部署', 'Redeploy')}</Button>}<Button onClick={closeDeployment}>{t('关闭', 'Close')}</Button></Space></Drawer>
  <Modal title={`${t('已部署 Worker', 'Deployed workers')} / ${workersFor?.containerName || ''}`} open={!!workersFor} width={800} onCancel={closeWorkers} footer={<Space><Button icon={<RefreshCw size={15}/>} loading={workerBusy} onClick={() => workersFor && void loadWorkers(workersFor)}>{t('刷新', 'Refresh')}</Button><Button onClick={closeWorkers}>{t('关闭', 'Close')}</Button></Space>}><ErrorState error={workerError} retry={() => workersFor && void loadWorkers(workersFor)}/>{workerLog ? <pre className="workflow-context" style={{ maxHeight: 450 }}>{workerLog}</pre> : <Empty description={workerBusy ? t('读取部署信息…', 'Loading deployment information…') : t('暂无部署信息', 'No deployment information yet')}/>}</Modal></>;
}

export default function Containers({ template = false }: { template?: boolean }) { const location = useLocation(); return template || location.pathname.endsWith('/template') ? <ContainerTemplate/> : <ContainerManager/>; }
