import { useEffect, useRef, useState } from 'react';
import { App, Button, Input, Segmented, Select, Space, Table, Tooltip } from 'antd';
import { useSearchParams } from 'react-router-dom';
import { api, type DataRecord, type PageResult } from '../lib/api';
import { useConsole } from '../lib/console';
import { useQuery } from '../lib/hooks';
import { ErrorState, PageHeader, Panel, QueryBar, RefreshButton, StatusTag } from '../components/ui';
import InstanceDetail, {LogViewer} from '../features/jobs/InstanceDetail';
import { instanceActions } from '../features/jobs/instanceActions';
import { createAppRequestScope } from '../lib/appRequestScope';

export default function Instances(){
  const {appId,t}=useConsole();const {message,modal}=App.useApp();const [search]=useSearchParams(); const initial={jobId:search.get('jobId')||undefined,instanceId:search.get('instanceId')||undefined,wfInstanceId:search.get('wfInstanceId')||undefined,status:search.get('status')||'',type:search.get('wfInstanceId')?'WORKFLOW':'NORMAL',index:0,pageSize:10};
  const token=localStorage.getItem('PowerJwt');const scopeRef=useRef<ReturnType<typeof createAppRequestScope>|undefined>(undefined);
  if(!scopeRef.current||scopeRef.current.appId!==appId||scopeRef.current.token!==token){scopeRef.current?.dispose();scopeRef.current=createAppRequestScope(appId,token);}
  const scope=scopeRef.current;const confirmations=useRef(new Set<ReturnType<typeof modal.confirm>>());
  useEffect(()=>()=>{scope.dispose();for(const confirmation of confirmations.current)confirmation.destroy();confirmations.current.clear();},[scope]);
  const [filters,setFilters]=useState<DataRecord>(initial);const [query,setQuery]=useState<DataRecord>(initial);const [detail,setDetail]=useState<string>();const [log,setLog]=useState<string>();
  const instances=useQuery(()=>api.post<PageResult>('/instance/list',{...query,appId:scope.appId},scope.options),[query,scope]);
  useEffect(()=>{const q={...initial};setFilters(q);setQuery(q);setDetail(undefined);setLog(undefined);},[search,appId]);
  const action=(kind:string,row:DataRecord)=>{
    if(!scope.current())return;const allowed=instanceActions(row,query.type);if(kind==='stop'?!allowed.canStop:!allowed.canRetry)return;
    const confirmation=modal.confirm({title:kind==='stop'?t('停止实例？','Stop instance?'):t('重新执行实例？','Retry instance?'),content:String(row.instanceId),okText:t('确认','Confirm'),okButtonProps:{danger:kind==='stop'},afterClose:()=>confirmations.current.delete(confirmation),onOk:async()=>{if(!scope.current())return;await api.get('/instance/'+kind,{instanceId:row.instanceId,appId:scope.appId},scope.options);if(!scope.current())return;void message.success(t('请求已提交','Request submitted'));await instances.refresh();}});
    confirmations.current.add(confirmation);
  };
  const statuses=['WAITING_DISPATCH','WAITING_WORKER_RECEIVE','RUNNING','FAILED','SUCCEED','CANCELED','STOPPED'];const labels=[t('待派发','Waiting dispatch'),t('待接收','Waiting receive'),t('运行中','Running'),t('失败','Failed'),t('成功','Succeeded'),t('已取消','Canceled'),t('已停止','Stopped')];
  return <><PageHeader title={t('任务实例','Job instances')} description={t('追踪每次执行，查看结果、分片与运行日志。','Track executions, inspect results, shards and logs.')} actions={<RefreshButton loading={instances.loading} onClick={instances.refresh}/>}/><Panel><div className="panel-tabs"><Segmented value={query.type} options={[{label:t('普通实例','Standalone instances'),value:'NORMAL'},{label:t('工作流任务实例','Workflow job instances'),value:'WORKFLOW'}]} onChange={type=>{setFilters({...filters,type});setQuery({...filters,type,index:0});}}/></div><QueryBar>{['jobId','instanceId',...(query.type==='WORKFLOW'?['wfInstanceId']:[])].map((k,i)=><Input key={k} style={{width:i===0?150:210}} aria-label={[t('任务 ID','Job ID'),t('实例 ID','Instance ID'),t('工作流实例 ID','Workflow instance ID')][i]} placeholder={[t('任务 ID','Job ID'),t('实例 ID','Instance ID'),t('工作流实例 ID','Workflow instance ID')][i]} value={filters[k]||''} onChange={e=>setFilters({...filters,[k]:e.target.value})} onPressEnter={()=>setQuery({...filters,index:0})}/>)}<Select style={{width:150}} aria-label={t('实例状态','Instance status')} value={filters.status} options={[{value:'',label:t('全部状态','All statuses')},...statuses.map((s,i)=>({value:s,label:labels[i]}))]} onChange={s=>setFilters({...filters,status:s})}/><Button type="primary" onClick={()=>setQuery({...filters,index:0})}>{t('查询','Search')}</Button><Button onClick={()=>{const q={type:query.type,index:0,pageSize:10,status:''};setFilters(q);setQuery(q);}}>{t('重置','Reset')}</Button></QueryBar><ErrorState error={instances.error} retry={instances.refresh}/><Table<DataRecord> rowKey="instanceId" dataSource={instances.data?.data||[]} loading={instances.loading} scroll={{x:1300}} pagination={{current:query.index+1,pageSize:query.pageSize,total:instances.data?.totalItems||0,showSizeChanger:true,onChange:(p,s)=>setQuery({...query,index:p-1,pageSize:s})}} columns={[
    {title:t('任务 / 实例','Job / instance'),key:'name',width:280,render:(_,r)=><div className="entity-cell"><button className="text-link" onClick={()=>setDetail(String(r.instanceId))}>{r.jobName}</button><code>{r.instanceId}</code></div>},{title:t('任务 ID','Job ID'),dataIndex:'jobId',width:100},...(query.type==='WORKFLOW'?[{title:t('工作流实例','Workflow instance'),dataIndex:'wfInstanceId',width:180}]:[]),{title:t('状态','Status'),dataIndex:'status',width:120,render:s=><StatusTag status={s}/>},{title:t('开始时间','Started'),dataIndex:'actualTriggerTime',width:170},{title:t('完成时间','Finished'),dataIndex:'finishedTime',width:170},{title:t('操作','Actions'),key:'actions',fixed:'right',width:255,render:(_,r)=>{const actions=instanceActions(r,query.type);const retryHint=actions.retryReason==='workflow'?t('请在工作流实例中操作该任务。','Manage this job from its workflow instance.'):actions.retryReason==='unfinished'?t('实例结束后可以重跑。','Retry becomes available after the instance finishes.'):actions.retryReason?t('请刷新以获取当前实例状态。','Refresh to load the current instance status.'):undefined;const stopHint=actions.stopReason==='finished'?t('实例已结束，无需停止。','This instance has already finished.'):actions.stopReason?t('请刷新以获取当前实例状态。','Refresh to load the current instance status.'):undefined;return <Space size={0}><Button type="text" onClick={()=>setDetail(String(r.instanceId))}>{t('详情','Details')}</Button><Button type="text" onClick={()=>setLog(String(r.instanceId))}>{t('日志','Logs')}</Button><Tooltip title={retryHint}><span><Button type="text" disabled={!actions.canRetry} onClick={()=>action('retry',r)}>{t('重跑','Retry')}</Button></span></Tooltip><Tooltip title={stopHint}><span><Button type="text" danger disabled={!actions.canStop} onClick={()=>action('stop',r)}>{t('停止','Stop')}</Button></span></Tooltip></Space>;}}
  ]}/></Panel>{detail&&<InstanceDetail instanceId={detail} onClose={()=>setDetail(undefined)}/>} {log&&<LogViewer instanceId={log} open onClose={()=>setLog(undefined)}/>}</>;
}
