import { useEffect, useRef, useState } from 'react';
import { App, Alert, Button, Checkbox, Collapse, DatePicker, Drawer, Dropdown, Form, Input, InputNumber, Modal, Select, Space, Switch, Table } from 'antd';
import { Copy, Download, History, MoreHorizontal, Pencil, Play, Plus, Search, SlidersHorizontal, Trash2, Upload } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api, type DataRecord, type PageResult } from '../lib/api';
import { useConsole } from '../lib/console';
import { useQuery } from '../lib/hooks';
import { ErrorState, JsonModal, PageHeader, Panel, QueryBar, RefreshButton } from '../components/ui';
import { dailyRule, jobPayload, jobToForm, newJob } from '../features/jobs/model';
import { createAppRequestScope } from '../lib/appRequestScope';
import { schedulePreview, type SchedulePreview } from '../lib/schedule';
import { EnumTag, enumOptions, type EnumKind } from '../lib/enums';

export default function Jobs() {
  const { appId, t, language } = useConsole(); const navigate = useNavigate(); const { message, modal } = App.useApp();
  const scopeRef = useRef<ReturnType<typeof createAppRequestScope> | undefined>(undefined); const token = localStorage.getItem('PowerJwt');
  if (!scopeRef.current || scopeRef.current.appId !== appId || scopeRef.current.token !== token) { scopeRef.current?.dispose(); scopeRef.current = createAppRequestScope(appId, token); }
  const scope = scopeRef.current; const editorVersion = useRef(0);
  useEffect(() => () => scope.dispose(), [scope]);
  const [filters, setFilters] = useState<DataRecord>({}); const [query, setQuery] = useState<DataRecord>({index:0,pageSize:10});
  const jobs = useQuery(() => api.post<PageResult>('/job/list',{...query,appId},scope.options),[scope,query]);
  const users = useQuery(() => api.get<DataRecord[]>('/user/list',undefined,scope.options),[scope]);
  const [editing, setEditing] = useState<DataRecord>(); const [saving,setSaving] = useState(false); const [form] = Form.useForm();
  const schedule = Form.useWatch('timeExpressionType',form); const processor = Form.useWatch('processorType',form); const dispatch = Form.useWatch('dispatchStrategy',form); const logType = Form.useWatch(['logConfig','type'],form);
  const [run, setRun] = useState<DataRecord>(); const [params,setParams] = useState(''); const [running,setRunning]=useState(false);
  const [exported,setExported]=useState<any>(); const [importing,setImporting]=useState(false); const [preview,setPreview]=useState<SchedulePreview>(); const [scheduleBusy,setScheduleBusy]=useState(false);
  const [daily,setDaily]=useState<DataRecord>(); const [dailyError,setDailyError]=useState('');
  const dailyUnit = daily?.intervalUnit == null || daily.intervalUnit === '' ? 'SECONDS' : String(daily.intervalUnit);
  const dailyUnits = enumOptions('timeUnit', language);
  if (!dailyUnits.some(unit=>unit.value===dailyUnit)) dailyUnits.push({value:dailyUnit,label:dailyUnit});
  useEffect(()=>{++editorVersion.current;setEditing(undefined);setRun(undefined);setExported(undefined);setPreview(undefined);setDaily(undefined);setImporting(false);setSaving(false);setRunning(false);setScheduleBusy(false);setFilters({});setQuery({index:0,pageSize:10});},[scope]);
  const closeEditor = () => { ++editorVersion.current; setEditing(undefined); setPreview(undefined); setDaily(undefined); };
  const edit = (job:DataRecord) => { if(!scope.current())return; ++editorVersion.current; setPreview(undefined); setDaily(undefined);setEditing(structuredClone(job));form.resetFields();form.setFieldsValue(jobToForm(job)); };
  const save = async () => {
    if(saving||!editing||!scope.current())return;
    const version=editorVersion.current; const original=structuredClone(editing);setSaving(true);
    try { const validated = await form.validateFields(); if(!scope.current()||version!==editorVersion.current)return;const values = {...form.getFieldsValue(true),...validated};await api.post('/job/save',jobPayload(original,values,scope.appId),scope.options);if(!scope.current())return;void message.success(t('任务已保存','Job saved'));if(version===editorVersion.current)closeEditor();await jobs.refresh(); } catch {} finally {if(scope.current())setSaving(false);}
  };
  const trigger = async (job:DataRecord, instanceParams?:string) => {
    if(running||!scope.current())return;setRunning(true);
    try {const id=await api.get('/job/run',{jobId:job.id,appId:scope.appId,instanceParams},scope.options);if(!scope.current())return;void message.success(t('已提交执行','Execution submitted'));setRun(undefined);setParams('');if(id)navigate('/oms/instance?instanceId='+encodeURIComponent(String(id)));}catch{}finally{if(scope.current())setRunning(false);}
  };
  const toggle = async (job:DataRecord) => {if(!scope.current())return;try{if(job.enable)await api.get('/job/disable',{jobId:job.id},scope.options);else await api.post('/job/save',{...job,appId:scope.appId,enable:true},scope.options);if(scope.current())await jobs.refresh();}catch{}};
  const more = async (key:string, job:DataRecord) => {
    if(!scope.current())return;const version=editorVersion.current;
    try {if(key==='params'){setParams('');setRun(job);}if(key==='history')navigate('/oms/instance?jobId='+encodeURIComponent(job.id));if(key==='copy'){const copy=await api.post('/job/copy',undefined,{...scope.options,params:{jobId:job.id}});if(scope.current()&&version===editorVersion.current)edit(copy);}if(key==='export'){const result=await api.get('/job/export',{jobId:job.id},scope.options);if(scope.current())setExported(result);}if(key==='delete')modal.confirm({title:t('删除任务？','Delete job?'),content:job.jobName,okText:t('删除','Delete'),okButtonProps:{danger:true},onOk:async()=>{if(!scope.current())return;await api.get('/job/delete',{jobId:job.id},scope.options);if(scope.current())await jobs.refresh();}});}catch{}
  };
  const checkSchedule = async () => {
    if(scheduleBusy||!scope.current())return;const version=editorVersion.current;const values=form.getFieldsValue(true);setScheduleBusy(true);setPreview(undefined);
    try {const result=await api.get('/validate/timeExpression',{timeExpressionType:values.timeExpressionType,timeExpression:values.timeExpression,startTime:values.dateRange?.[0]?.valueOf(),endTime:values.dateRange?.[1]?.valueOf()},scope.options);if(scope.current()&&version===editorVersion.current)setPreview(schedulePreview(result));}catch(error){if(scope.current()&&version===editorVersion.current)setPreview({times:[],error:(error as Error).message});}finally{if(scope.current())setScheduleBusy(false);}
  };
  const required = [{required:true,message:t('请填写此项','This field is required')}];
  const select = (name:string|string[], label:string, kind:EnumKind, rules?:any[]) => { const options=enumOptions(kind,language); const current=form.getFieldValue(name); if(current!=null&&!options.some(option=>option.value===current))options.push(...enumOptions(kind,language,[current])); return <Form.Item name={name} label={label} rules={rules}><Select options={options} optionRender={option=><EnumTag kind={kind} value={option.value}/>}/></Form.Item>; };
  const numeric = (name:string|string[],label:string) => <Form.Item name={name} label={label}><InputNumber style={{width:'100%'}}/></Form.Item>;
  const submitQuery = () => setQuery({...filters,index:0,pageSize:query.pageSize});
  return <><PageHeader title={t('任务管理','Jobs')} description={t('配置调度规则，控制每一次任务执行。','Configure schedules and control every execution.')} actions={<><Button icon={<Upload size={16}/>} onClick={()=>setImporting(true)}>{t('导入任务','Import')}</Button><Button type="primary" icon={<Plus size={17}/>} onClick={()=>edit(newJob(appId))}>{t('新建任务','New job')}</Button></>}/>
    <Panel><QueryBar><Input aria-label={t('任务 ID','Job ID')} placeholder={t('任务 ID','Job ID')} value={filters.jobId||''} onChange={e=>setFilters({...filters,jobId:e.target.value})} onPressEnter={submitQuery} style={{width:160}}/><Input aria-label={t('搜索任务','Search jobs')} prefix={<Search size={16}/>} placeholder={t('搜索任务名称或描述','Search name or description')} value={filters.keyword||''} onChange={e=>setFilters({...filters,keyword:e.target.value})} onPressEnter={submitQuery} style={{width:280}}/><Button type="primary" onClick={submitQuery}>{t('查询','Search')}</Button><Button onClick={()=>{setFilters({});setQuery({index:0,pageSize:10});}}>{t('重置','Reset')}</Button><span className="query-spacer"/><RefreshButton onClick={jobs.refresh} loading={jobs.loading}/></QueryBar><ErrorState error={jobs.error} retry={jobs.refresh}/>
    <Table<DataRecord> rowKey={r=>String(r.id)} loading={jobs.loading} dataSource={jobs.data?.data||[]} scroll={{x:1080}} pagination={{current:query.index+1,pageSize:query.pageSize,total:jobs.data?.totalItems||0,showSizeChanger:true,onChange:(p,s)=>setQuery({...query,index:p-1,pageSize:s})}} columns={[
      {title:t('任务','Job'),key:'job',width:280,render:(_,r)=><div className="entity-cell"><button className="text-link" onClick={()=>edit(r)}>{r.jobName}</button><span>{r.jobDescription||t('暂无描述','No description')} <code>#{r.id}</code></span></div>},
      {title:t('调度规则','Schedule'),key:'schedule',width:225,render:(_,r)=><div className="entity-cell"><EnumTag kind="schedule" value={r.timeExpressionType}/><code className="truncate" title={r.timeExpression}>{r.timeExpression||t('按需触发','On demand')}</code></div>},
      {title:t('执行方式','Execution'),dataIndex:'executeType',width:180,render:v=><EnumTag kind="execution" value={v}/>},
      {title:t('处理器','Processor'),dataIndex:'processorType',width:110,render:v=><EnumTag kind="processor" value={v}/>},
      {title:t('启用','Enabled'),key:'enable',width:84,render:(_,r)=><Switch size="small" aria-label={`${r.jobName} ${t('启用','enabled')}`} checked={r.enable} onChange={()=>void toggle(r)}/>},
      {title:t('操作','Actions'),key:'actions',width:230,fixed:'right',render:(_,r)=><Space size={4}><Button type="text" icon={<Pencil size={14}/>} onClick={()=>edit(r)}>{t('编辑','Edit')}</Button><Button type="text" icon={<Play size={14}/>} onClick={()=>void trigger(r)} disabled={running}>{t('运行','Run')}</Button><Dropdown menu={{items:[{key:'params',label:t('参数运行','Run with parameters'),icon:<SlidersHorizontal size={14}/>},{key:'history',label:t('执行历史','Execution history'),icon:<History size={14}/>},{key:'copy',label:t('复制任务','Copy job'),icon:<Copy size={14}/>},{key:'export',label:t('导出任务','Export'),icon:<Download size={14}/>},{type:'divider'},{key:'delete',label:t('删除','Delete'),icon:<Trash2 size={14}/>,danger:true}],onClick:({key})=>void more(key,r)}} trigger={['click']}><Button type="text" aria-label={t('更多操作','More actions')} icon={<MoreHorizontal size={18}/>}/></Dropdown></Space>}
    ]}/></Panel>
    <Drawer title={editing?.id?t('编辑任务','Edit job'):t('新建任务','New job')} open={!!editing} onClose={closeEditor} size={820} mask={{closable:false}} extra={<Space><Button onClick={closeEditor}>{t('取消','Cancel')}</Button><Button type="primary" loading={saving} onClick={save}>{t('保存任务','Save job')}</Button></Space>}>
      <Form name="job-editor" form={form} layout="vertical" preserve><Form.Item name="jobName" label={t('任务名称','Job name')} rules={required}><Input autoFocus/></Form.Item><Form.Item name="jobDescription" label={t('任务描述','Description')}><Input/></Form.Item><div className="form-grid">{select('timeExpressionType',t('调度类型','Schedule type'),'schedule',required)}<Form.Item label={t('调度表达式','Schedule expression')}><Space.Compact style={{width:'100%'}}><Form.Item name="timeExpression" noStyle><Input readOnly={schedule==='DAILY_TIME_INTERVAL'} placeholder={schedule==='CRON'?'0 0/5 * * * ?':t('时间间隔（毫秒）','Interval in milliseconds')}/></Form.Item>{schedule==='DAILY_TIME_INTERVAL'&&<Button onClick={()=>{try{setDaily(dailyRule(form.getFieldValue('timeExpression')));setDailyError('');}catch(e){setDailyError((e as Error).message);setDaily({});}}}>{t('编辑','Edit')}</Button>}<Button loading={scheduleBusy} onClick={()=>void checkSchedule()}>{t('校验','Validate')}</Button></Space.Compact></Form.Item></div><Form.Item name="dateRange" label={t('生效时间范围','Active time range')}><DatePicker.RangePicker allowEmpty={[true,true]} showTime style={{width:'100%'}}/></Form.Item><div className="form-grid">{select('executeType',t('执行方式','Execution mode'),'execution',required)}{select('processorType',t('处理器类型','Processor type'),'processor',required)}</div><Form.Item name="processorInfo" label={t('处理器信息','Processor information')} rules={required}><Input className="code-input" placeholder={processor==='EXTERNAL'?'containerId#className':'tech.powerjob.samples.processors.StandaloneProcessorDemo'}/></Form.Item><Form.Item name="jobParams" label={t('任务参数','Job parameters')}><Input.TextArea className="code-input" rows={3}/></Form.Item>
      <Collapse defaultActiveKey={['runtime']} items={[
        {key:'runtime',label:t('运行与重试','Runtime and retries'),children:<><div className="form-grid three">{select('dispatchStrategy',t('派发策略','Dispatch strategy'),'dispatch')}{numeric('maxInstanceNum',t('最大实例数（≤0 为不限）','Max instances (≤0 = unlimited)'))}{numeric('concurrency',t('线程并发数（≤0 使用 1）','Concurrency (≤0 uses 1)'))}</div>{dispatch==='SPECIFY'&&<Form.Item name="dispatchStrategyConfig" label={t('指定派发配置','Dispatch configuration')}><Input/></Form.Item>}<div className="form-grid three">{numeric('instanceTimeLimit',t('实例超时（毫秒，≤0 不限）','Timeout (ms; ≤0 = unlimited)'))}{numeric('instanceRetryNum',t('实例重试次数','Instance retries'))}{numeric('taskRetryNum',t('子任务重试次数','Task retries'))}</div></>},
        {key:'workers',label:t('Worker 资源与集群','Worker resources and cluster'),children:<><div className="form-grid three">{numeric('minCpuCores',t('最少 CPU 核数','Min CPU cores'))}{numeric('minMemorySpace',t('最少内存（GB）','Min memory (GB)'))}{numeric('minDiskSpace',t('最少磁盘（GB）','Min disk (GB)'))}</div><Form.Item name="designatedWorkers" label={t('指定 Worker 地址','Designated Workers')}><Input placeholder={t('多个地址用逗号分隔，留空则不限','Comma-separated addresses; empty = all')}/></Form.Item>{numeric('maxWorkerCount',t('最多 Worker 数（≤0 为不限）','Max Workers (≤0 = unlimited)'))}</>},
        {key:'alarm',label:t('告警与通知','Alerts and notifications'),children:<><Form.Item name="notifyUserIds" label={t('通知用户','Notify users')}><Select mode="multiple" showSearch optionFilterProp="label" options={(users.data||[]).map(u=>({value:String(u.id),label:u.showName||u.username}))}/></Form.Item><div className="form-grid three">{numeric(['alarmConfig','alertThreshold'],t('告警阈值','Alert threshold'))}{numeric(['alarmConfig','statisticWindowLen'],t('统计窗口（秒）','Statistics window (s)'))}{numeric(['alarmConfig','silenceWindowLen'],t('静默窗口（秒）','Silence window (s)'))}</div></>},
        {key:'logging',label:t('日志与高级配置','Logging and advanced configuration'),children:<><div className="form-grid">{select(['logConfig','type'],t('日志方式','Log destination'),'logType')}{select(['logConfig','level'],t('日志级别','Log level'),'logLevel')}</div>{[2,4].includes(logType)&&<Form.Item name={['logConfig','loggerName']} label={t('日志记录器名称','Logger name')}><Input/></Form.Item>}{select(['advancedRuntimeConfig','taskTrackerBehavior'],t('协调节点行为','TaskTracker behavior'),'taskTracker')}<Form.Item name="enable" label={t('启用任务','Enable job')} valuePropName="checked"><Switch/></Form.Item></>}
      ]}/></Form>
    </Drawer>
    <Modal title={t('参数运行','Run with parameters')} open={!!run} onCancel={()=>setRun(undefined)} onOk={()=>void trigger(run!,params)} confirmLoading={running} okText={t('运行任务','Run job')}><p>{run?.jobName}</p><Input.TextArea aria-label={t('运行参数','Instance parameters')} rows={5} value={params} onChange={e=>setParams(e.target.value)}/></Modal>
    <Modal title={t('表达式校验结果','Schedule validation')} open={!!preview} onCancel={()=>setPreview(undefined)} footer={<Button onClick={()=>setPreview(undefined)}>{t('关闭','Close')}</Button>}>{preview?.error?<Alert type="error" showIcon title={t('调度表达式无效','Invalid schedule expression')} description={preview.error}/>:preview?.message?<Alert type="info" showIcon title={t('表达式有效，但当前没有后续触发时间。','The expression is valid, but has no future trigger times.')}/>:<ol>{preview?.times.map((time,i)=><li key={i}>{time}</li>)}</ol>}</Modal>
    <Modal title={t('每日固定间隔','Daily interval')} open={!!daily} onCancel={()=>setDaily(undefined)} onOk={()=>{if(dailyError)return;form.setFieldValue('timeExpression',JSON.stringify(daily));setDaily(undefined);}}>{dailyError?<Alert type="error" title={dailyError} action={<Button onClick={()=>{setDaily(dailyRule());setDailyError('');}}>{t('重置','Reset')}</Button>}/>:<div className="daily-editor"><label>{t('执行间隔','Interval')}<InputNumber aria-label={t('每日执行间隔','Daily interval value')} min={1} value={daily?.interval} onChange={v=>setDaily({...daily,interval:v})}/></label><label>{t('时间单位','Time unit')}<Select aria-label={t('每日间隔单位','Daily interval unit')} style={{width:180}} value={dailyUnit} options={dailyUnits} onChange={unit=>setDaily({...daily,intervalUnit:unit})}/></label><label>{t('开始时间','Start time')}<Input type="time" step="1" value={daily?.startTimeOfDay} onChange={e=>setDaily({...daily,startTimeOfDay:e.target.value})}/></label><label>{t('结束时间','End time')}<Input type="time" step="1" value={daily?.endTimeOfDay} onChange={e=>setDaily({...daily,endTimeOfDay:e.target.value})}/></label><Checkbox.Group options={enumOptions('weekday',language)} value={daily?.daysOfWeek||[]} onChange={v=>setDaily({...daily,daysOfWeek:v})}/></div>}</Modal>
    <JsonModal title={t('导出任务','Export job')} open={exported!==undefined} value={exported} onCancel={()=>setExported(undefined)}/><JsonModal title={t('导入任务','Import job')} open={importing} onCancel={()=>setImporting(false)} onImport={async value=>{if(!scope.current())return;await api.post('/job/save',{...value,appId:scope.appId},scope.options);if(!scope.current())return;void message.success(t('任务已导入','Job imported'));await jobs.refresh();}}/>
  </>;
}
