import { useState } from 'react';
import { ArrowUpRight, CircleCheck, Cpu, Layers, Timer, TriangleAlert } from 'lucide-react';
import { Progress, Table, Tag } from 'antd';
import { Link } from 'react-router-dom';
import { api,type DataRecord } from '../lib/api';
import { useConsole } from '../lib/console';
import { useQuery } from '../lib/hooks';
import { ErrorState,formatTime,PageHeader,Panel,RefreshButton } from '../components/ui';
import { resourcePercent } from '../features/overview/resources';
import { OverviewClock } from '../features/overview/OverviewClock';

export default function Overview(){const {appId,appName,t}=useConsole();const [clockRefreshKey,setClockRefreshKey]=useState(0);const overview=useQuery(()=>api.get<DataRecord>('/system/overview',{appId}),[appId]);const workers=useQuery(()=>api.get<DataRecord[]>('/system/listWorker',{appId}),[appId]);const data=overview.data;const rows=[...(workers.data||[])].sort((a,b)=>a.status-b.status);const online=rows.filter(w=>w.status!==9999).length;const refresh=()=>{void overview.refresh();void workers.refresh();setClockRefreshKey(key=>key+1);};
  const metrics=[{label:t('任务总数','Total jobs'),value:data?.jobCount,icon:Layers,link:'/oms/job'},{label:t('运行中实例','Running instances'),value:data?.runningInstanceCount,icon:Timer,link:'/oms/instance?status=RUNNING'},{label:t('近期失败实例','Recent failures'),value:data?.failedInstanceCount,icon:TriangleAlert,link:'/oms/instance?status=FAILED',warning:true},{label:t('在线 Worker','Online Workers'),value:workers.data?online:undefined,icon:Cpu,link:undefined}];
  const load=(v:any)=>{if(v===null||v===undefined)return '—';const percent=resourcePercent(v);return percent!==undefined?<div className="resource-load"><Progress percent={percent} size="small" showInfo={false} strokeColor={percent>80?'#d45a46':'#7794ef'}/><span>{v}</span></div>:String(v);};
  return <><PageHeader title={t('运行概览','Overview')} description={t('掌握调度状态与集群运行情况。','Monitor scheduling activity and cluster health.')} actions={<RefreshButton onClick={refresh} loading={overview.loading||workers.loading}/>}/><ErrorState error={overview.error} retry={overview.refresh}/><div className="overview-band overview-band-with-clocks"><div className="overview-app"><div className="scope-icon"><Layers size={24}/></div><div><span>{t('当前应用','Current application')}</span><h2>{data?.appName||appName||'—'}</h2><code>App ID {appId}</code></div></div><div className="overview-server"><span>{t('调度节点','Scheduler')}</span><strong>{data?.scheduleServerInfo?.ip||'—'}</strong><small>{t('启动于','Started')} {formatTime(data?.scheduleServerInfo?.bornTime)}</small></div><OverviewClock appId={appId} refreshKey={clockRefreshKey}/></div><div className="metrics-strip">{metrics.map(m=>{const content=<><div className="metric-label"><m.icon size={17}/>{m.label}<ArrowUpRight size={14}/></div><strong>{m.value??'—'}</strong><span>{t('查看详情','View details')}</span></>;return m.link?<Link key={m.label} to={m.link} className={`metric ${m.warning&&Number(m.value)>0?'metric-alert':''}`}>{content}</Link>:<button key={m.label} type="button" className="metric" style={{background:'transparent',border:0,textAlign:'left',font:'inherit'}} onClick={()=>document.getElementById('worker-cluster')?.scrollIntoView({behavior:'smooth',block:'start'})}>{content}</button>;})}</div><div id="worker-cluster" style={{scrollMarginTop:90}}><Panel title={t('Worker 集群','Worker cluster')} actions={<Tag icon={<CircleCheck size={13}/>} color={online?'success':'default'}>{online} {t('在线','online')}</Tag>}><ErrorState error={workers.error} retry={workers.refresh}/><Table<DataRecord> rowKey="address" dataSource={rows} loading={workers.loading} pagination={rows.length>10?{pageSize:10}:false} scroll={{x:1000}} columns={[{title:t('Worker 地址','Worker address'),dataIndex:'address',width:240,render:v=><code>{v}</code>},{title:t('状态','Status'),dataIndex:'status',width:100,render:v=><Tag color={v===1?'success':v===9999?'default':'warning'}>{v===1?t('健康','Healthy'):v===9999?t('离线','Offline'):t('繁忙','Busy')}</Tag>},{title:'CPU',dataIndex:'cpuLoad',width:145,render:load},{title:t('内存','Memory'),dataIndex:'memoryLoad',width:145,render:load},{title:t('磁盘','Disk'),dataIndex:'diskLoad',width:145,render:load},{title:t('标签','Tag'),dataIndex:'tag',width:100},{title:t('最近活跃','Last active'),dataIndex:'lastActiveTime',width:185,render:formatTime}]}/></Panel></div></>;
}
