import { useEffect, useState } from 'react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { App, Button, Descriptions, Empty, Form, Input, Popconfirm, Select, Space, Spin, Table, Typography } from 'antd';
import { ArrowLeft, CheckCheck, Eye, FileText, RotateCw, Square } from 'lucide-react';
import { api, type DataRecord, type PageResult } from '../lib/api';
import { useConsole } from '../lib/console';
import { useQuery } from '../lib/hooks';
import { EnumTag, enumLabel } from '../lib/enums';
import { ErrorState, PageHeader, Panel, QueryBar, RefreshButton } from '../components/ui';
import InstanceDetail, { LogViewer } from '../features/jobs/InstanceDetail';
import WorkflowGraph from '../features/workflow/WorkflowGraph';
import CodeEditor from '../features/workflow/CodeEditor';
import { normalizeDag } from '../features/workflow/model';
import { formatWorkflowContext, workflowNodeStartTime } from '../features/workflow/transport';
import { useRequestScope } from '../features/workflow/requestScope';
import '../features/workflow/workflow.css';


function WorkflowInstanceView({ instanceId }: { instanceId: string }) {
  const { appId, t } = useConsole(); const { message } = App.useApp(); const navigate = useNavigate(); const scope = useRequestScope(`${appId}:${instanceId}`); const [selectedId, setSelectedId] = useState<string>(); const [jobInstanceId, setJobInstanceId] = useState<string>(); const [jobLogId, setJobLogId] = useState<string>(); const [busy, setBusy] = useState(false);
  const detail = useQuery(() => api.get<DataRecord>('/wfInstance/info', { appId, wfInstanceId: instanceId }), [instanceId, appId]); const data = detail.data; const dag = normalizeDag(data || {}); const selected = dag.nodes.find(node => node.nodeId === selectedId);
  const nodeInstanceId = selected?.nodeType === 1 ? selected.instanceId : undefined;
  const execution = useQuery(() => nodeInstanceId && !selected?.startTime ? api.get<DataRecord>('/instance/detail', { appId, instanceId: nodeInstanceId }).then(value => ({ ...value, instanceId: nodeInstanceId })) : Promise.resolve<DataRecord>({}), [nodeInstanceId, selected?.startTime, selected?.status, appId]);
  const refresh = () => { void detail.refresh(); void execution.refresh(); };
  useEffect(() => { setSelectedId(undefined); setJobInstanceId(undefined); setJobLogId(undefined); }, [instanceId, appId]);
  useEffect(() => { if (!data || ![1, 2].includes(data.status)) return; const timer = window.setInterval(refresh, 5000); return () => window.clearInterval(timer); }, [data?.status, instanceId, appId]);
  const operate = async (operation: string, nodeId?: string) => { const token = scope.capture(); setBusy(true); try { await api.get(`/wfInstance/${operation}`, { appId, wfInstanceId: instanceId, nodeId }, { headers: { AppId: appId } }); if (!scope.current(token)) return; void message.success(t('操作已完成', 'Operation completed')); await detail.refresh(); } catch {} finally { if (scope.current(token)) setBusy(false); } };
  const running = data && [1, 2].includes(data.status); const retryable = data && [3, 10].includes(data.status); const canMark = selected && !running && selected.status === 4 && !!selected.instanceId && !selected.skipWhenFailed;
  return <><PageHeader contextual title={data?.workflowName || t('工作流实例', 'Workflow instance')} description={`${t('实例', 'Instance')} #${instanceId}`} actions={<Space wrap><Button icon={<ArrowLeft size={15}/>} onClick={() => navigate('/oms/wfinstance')}>{t('实例列表', 'All instances')}</Button><RefreshButton loading={detail.loading} onClick={refresh}/><Button disabled={!retryable} loading={busy} icon={<RotateCw size={15}/>} onClick={() => void operate('retry')}>{t('重新运行', 'Retry')}</Button><Popconfirm title={t('停止这个工作流实例？', 'Stop this workflow instance?')} onConfirm={() => void operate('stop')}><Button danger disabled={!running} loading={busy} icon={<Square size={14}/>} >{t('停止', 'Stop')}</Button></Popconfirm></Space>}/>
    <ErrorState error={detail.error} retry={() => void detail.refresh()}/><Spin spinning={detail.loading && !data}>{data && <><Panel className="workflow-summary"><Descriptions column={{ xs: 1, sm: 2, lg: 3 }} items={[
      { key: 'status', label: t('状态', 'Status'), children: <EnumTag kind="workflowStatus" value={data.status}/> }, { key: 'workflow', label: t('工作流 ID', 'Workflow ID'), children: <Button type="link" style={{ padding: 0 }} onClick={() => navigate(`/oms/workflowEditor?workflowId=${data.workflowId}`)}>{data.workflowId}</Button> }, { key: 'instance', label: t('实例 ID', 'Instance ID'), children: <Typography.Text copyable>{data.wfInstanceId}</Typography.Text> },
      { key: 'expected', label: t('预计触发时间', 'Expected trigger'), children: data.expectedTriggerTime || '—' }, { key: 'actual', label: t('实际触发时间', 'Actual trigger'), children: data.actualTriggerTime || '—' }, { key: 'finished', label: t('完成时间', 'Finished'), children: data.finishedTime || '—' }, { key: 'params', label: t('初始参数', 'Initial parameters'), span: 'filled', children: <Typography.Text style={{ whiteSpace: 'pre-wrap' }}>{data.wfInitParams || '—'}</Typography.Text> }, { key: 'result', label: t('执行结果', 'Result'), span: 'filled', children: <Typography.Text style={{ whiteSpace: 'pre-wrap' }}>{data.result || '—'}</Typography.Text> }
    ]}/>{data.wfContext && <><Typography.Title level={5}>{t('工作流上下文', 'Workflow context')}</Typography.Title><pre className="workflow-context">{formatWorkflowContext(data.wfContext)}</pre></>}</Panel>
    <div className="workflow-editor-grid"><WorkflowGraph nodes={dag.nodes} edges={dag.edges} selectedId={selectedId} onSelect={node => setSelectedId(node?.nodeId)} actions={<RefreshButton loading={detail.loading} onClick={refresh}/>}/><aside className="workflow-inspector"><h3>{t('节点详情', 'Node details')}</h3>{selected ? <><Typography.Title level={5}>{selected.nodeName}</Typography.Title><EnumTag kind="nodeType" value={selected.nodeType}/>{selected.status != null && <EnumTag kind="instanceStatus" value={selected.status}/>}<Descriptions size="small" column={1} style={{ marginTop: 20 }} items={[
      { key: 'nodeId', label: t('节点 ID', 'Node ID'), children: selected.nodeId }, ...(selected.jobId ? [{ key: 'jobId', label: selected.nodeType === 3 ? t('工作流 ID', 'Workflow ID') : t('任务 ID', 'Job ID'), children: selected.jobId }] : []), ...(selected.instanceId ? [{ key: 'instanceId', label: t('实例 ID', 'Instance ID'), children: selected.instanceId }] : []), { key: 'startTime', label: t('开始时间', 'Started'), children: workflowNodeStartTime(selected, execution.data) }, { key: 'finishedTime', label: t('完成时间', 'Finished'), children: selected.finishedTime || '—' }, ...(selected.nodeType !== 2 ? [{ key: 'enable', label: t('启用', 'Enabled'), children: selected.enable ? t('是', 'Yes') : t('否', 'No') }, { key: 'skipWhenFailed', label: t('失败跳过', 'Skip on failure'), children: selected.skipWhenFailed ? t('是', 'Yes') : t('否', 'No') }] : []), { key: 'result', label: t('节点结果', 'Node result'), children: selected.result || '—' }
    ]}/><ErrorState error={execution.error} retry={() => void execution.refresh()}/><Typography.Title level={5}>{selected.nodeType === 2 ? t('判断表达式', 'Decision expression') : t('节点参数', 'Node parameters')}</Typography.Title>{selected.nodeType === 2 ? <CodeEditor value={selected.nodeParams} readOnly/> : <pre className="workflow-context">{selected.nodeParams || '—'}</pre>}<Space direction="vertical" style={{ width: '100%' }}>
      {selected.instanceId && selected.nodeType === 1 && <><Button block type="primary" icon={<Eye size={15}/>} onClick={() => setJobInstanceId(selected.instanceId)}>{t('查看任务实例', 'View job instance')}</Button><Button block icon={<FileText size={15}/>} onClick={() => setJobLogId(selected.instanceId)}>{t('查看运行日志', 'View execution log')}</Button></>}
      {selected.instanceId && selected.nodeType === 3 && <Button block type="primary" icon={<Eye size={15}/>} onClick={() => navigate(`/oms/wfInstanceDetail?wfInstanceId=${selected.instanceId}`)}>{t('查看子工作流实例', 'View nested workflow instance')}</Button>}
      {!selected.instanceId && selected.nodeType !== 2 && <Typography.Text type="secondary">{t('该节点尚未创建执行实例', 'This node has no execution instance yet')}</Typography.Text>}
      {canMark && <Popconfirm title={t('将这个节点标记为成功？', 'Mark this node as successful?')} description={t('原任务实例保持失败。标记后可重新运行工作流。', 'The job instance remains failed. Retry the workflow after marking this node.')} onConfirm={() => void operate('markNodeAsSuccess', selected.nodeId)}><Button block icon={<CheckCheck size={15}/>} loading={busy}>{t('标记成功', 'Mark successful')}</Button></Popconfirm>}
    </Space></> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t('选择节点查看执行详情', 'Select a node to inspect its execution')}/>}</aside></div></>}</Spin>{jobInstanceId && <InstanceDetail instanceId={jobInstanceId} open onClose={() => setJobInstanceId(undefined)}/>} {jobLogId && <LogViewer instanceId={jobLogId} open onClose={() => setJobLogId(undefined)}/>}</>;
}

export default function WorkflowInstances() {
  const { appId, language, t } = useConsole(); const { message } = App.useApp(); const navigate = useNavigate(); const location = useLocation(); const [params] = useSearchParams(); const [searchForm] = Form.useForm(); const [query, setQuery] = useState<DataRecord>({ index: 0, pageSize: 10, status: '' }); const [busyId, setBusyId] = useState('');
  const instanceId = params.get('wfInstanceId') || ''; const scope = useRequestScope(`${appId}:${location.pathname}:${instanceId}`); const isDetail = location.pathname.toLowerCase().includes('wfinstancedetail') || !!instanceId;
  const list = useQuery(() => api.post<PageResult>('/wfInstance/list', { ...query, appId }), [query, appId, location.pathname, instanceId]);
  if (isDetail) return instanceId ? <WorkflowInstanceView instanceId={instanceId}/> : <><PageHeader contextual title={t('缺少工作流实例 ID', 'Workflow instance ID is missing')}/><Button type="primary" onClick={() => navigate('/oms/wfinstance')}>{t('返回实例列表', 'Back to instances')}</Button></>;
  const operate = async (row: DataRecord, operation: string) => { const token = scope.capture(); setBusyId(row.wfInstanceId); try { await api.get(`/wfInstance/${operation}`, { appId, wfInstanceId: row.wfInstanceId }, { headers: { AppId: appId } }); if (!scope.current(token)) return; void message.success(t('操作已完成', 'Operation completed')); await list.refresh(); } catch {} finally { if (scope.current(token)) setBusyId(''); } };
  const statuses = [{ value: '', label: t('全部状态', 'All statuses') }, ...['WAITING', 'RUNNING', 'FAILED', 'SUCCEED', 'STOPPED'].map(value => ({ value, label: enumLabel('workflowStatus', value, language) }))];
  return <><PageHeader title={t('工作流实例', 'Workflow instances')} description={t('追踪每个流程的执行状态、节点结果与上下文。', 'Inspect flow execution, node results and context.')} actions={<RefreshButton loading={list.loading} onClick={() => void list.refresh()}/>}/><Panel><QueryBar><Form name="workflowInstanceQuery" form={searchForm} layout="inline" initialValues={{ status: '' }} onFinish={values => setQuery(current => ({ ...current, ...values, index: 0 }))}><Form.Item name="workflowId"><Input aria-label={t('工作流 ID', 'Workflow ID')} placeholder={t('工作流 ID', 'Workflow ID')} allowClear/></Form.Item><Form.Item name="wfInstanceId"><Input aria-label={t('实例 ID', 'Instance ID')} placeholder={t('实例 ID', 'Instance ID')} allowClear/></Form.Item><Form.Item name="status"><Select aria-label={t('状态', 'Status')} style={{ width: 155 }} options={statuses}/></Form.Item><Space><Button type="primary" htmlType="submit">{t('查询', 'Search')}</Button><Button onClick={() => { searchForm.resetFields(); setQuery({ index: 0, pageSize: query.pageSize, status: '' }); }}>{t('重置', 'Reset')}</Button></Space></Form></QueryBar><ErrorState error={list.error} retry={() => void list.refresh()}/><Table rowKey="wfInstanceId" loading={list.loading} dataSource={list.data?.data || []} scroll={{ x: 1000 }} columns={[
    { title: t('工作流', 'Workflow'), width: 220, render: (_, row) => <><span className="workflow-table-title">{row.workflowName}</span><div className="workflow-table-description">#{row.workflowId}</div></> }, { title: t('实例 ID', 'Instance ID'), dataIndex: 'wfInstanceId', render: (id: string) => <Button type="link" style={{ padding: 0 }} onClick={() => navigate(`/oms/wfInstanceDetail?wfInstanceId=${id}`)}>{id}</Button> }, { title: t('状态', 'Status'), width: 110, render: (_, row) => <EnumTag kind="workflowStatus" value={row.status}/> }, { title: t('触发时间', 'Triggered'), dataIndex: 'actualTriggerTime', width: 170 }, { title: t('完成时间', 'Finished'), dataIndex: 'finishedTime', width: 170 }, { title: t('操作', 'Actions'), width: 260, render: (_, row) => <Space size={2}><Button type="text" icon={<Eye size={14}/>} onClick={() => navigate(`/oms/wfInstanceDetail?wfInstanceId=${row.wfInstanceId}`)}>{t('详情', 'Details')}</Button><Popconfirm title={t('停止这个工作流实例？', 'Stop this workflow instance?')} onConfirm={() => void operate(row, 'stop')}><Button type="text" danger icon={<Square size={14}/>} disabled={![1, 2].includes(row.status)} loading={busyId === row.wfInstanceId}>{t('停止', 'Stop')}</Button></Popconfirm><Button type="text" icon={<RotateCw size={14}/>} disabled={![3, 10].includes(row.status)} loading={busyId === row.wfInstanceId} onClick={() => void operate(row, 'retry')}>{t('重试', 'Retry')}</Button></Space> }
  ]} pagination={{ current: query.index + 1, pageSize: query.pageSize, total: list.data?.totalItems || 0, showSizeChanger: true, onChange: (page, pageSize) => setQuery(current => ({ ...current, index: page - 1, pageSize })) }}/></Panel></>;
}
