import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { Alert, App, Button, DatePicker, Empty, Form, Input, InputNumber, Modal, Popconfirm, Select, Space, Spin, Switch, Table, Typography } from 'antd';
import { ArrowLeft, Copy, GitBranch, Link2, Pencil, Play, Plus, Save, SlidersHorizontal, Trash2, Workflow } from 'lucide-react';
import dayjs from 'dayjs';
import { ApiError, api, type DataRecord, type PageResult } from '../lib/api';
import { useConsole } from '../lib/console';
import { useQuery } from '../lib/hooks';
import { EnumTag, enumLabel } from '../lib/enums';
import { ErrorState, PageHeader, Panel, QueryBar, RefreshButton } from '../components/ui';
import WorkflowGraph from '../features/workflow/WorkflowGraph';
import CodeEditor from '../features/workflow/CodeEditor';
import { connectionError, dagErrors, normalizeDag, type WorkflowEdge, type WorkflowNode } from '../features/workflow/model';
import { WorkflowSaveError, nodePayload, persistWorkflow, responseId, scheduleResultType } from '../features/workflow/transport';
import { useRequestScope } from '../features/workflow/requestScope';
import '../features/workflow/workflow.css';

function NodeInspector({ node, onChange, onSave, onRemove, busy, disabled = false }: { node?: WorkflowNode; onChange: (node: WorkflowNode) => void; onSave: () => Promise<void>; onRemove: () => void; busy: boolean; disabled?: boolean }) {
  const { appId, t } = useConsole(); const [form] = Form.useForm(); const [options, setOptions] = useState<DataRecord[]>([]); const [searching, setSearching] = useState(false); const requestSequence = useRef(0);
  useEffect(() => { ++requestSequence.current; setSearching(false); form.resetFields(); if (node) { form.setFieldsValue(node); setOptions(node.jobId ? [{ id: node.jobId, jobName: node.nodeName, wfName: node.nodeName }] : []); } }, [node?.nodeId]);
  const search = async (keyword: string) => { if (!node || node.nodeType === 2) return; const generation = ++requestSequence.current; setSearching(true); try { const page = await api.post<PageResult>(node.nodeType === 3 ? '/workflow/list' : '/job/list', { appId, keyword, index: 0, pageSize: 30 }); if (generation === requestSequence.current) setOptions(page.data); } catch {} finally { if (generation === requestSequence.current) setSearching(false); } };
  if (!node) return <aside className="workflow-inspector"><h3>{t('节点配置', 'Node settings')}</h3><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t('选择画布中的节点', 'Select a node on the canvas')}/><p className="workflow-empty-hint">{t('从任务或子工作流添加节点，再连接它们。判断节点需要成立和不成立两条分支。', 'Add jobs or nested workflows, then connect them. Decision nodes need both True and False branches.')}</p></aside>;
  return <aside className="workflow-inspector"><h3>{t('节点配置', 'Node settings')}<span style={{ marginLeft: 10 }}><EnumTag kind="nodeType" value={node.nodeType}/></span></h3><Form name="workflowNode" form={form} layout="vertical" disabled={disabled} onValuesChange={(_, values) => { if (!disabled) onChange({ ...node, ...values }); }}>
    {node.nodeType !== 2 && <Form.Item label={node.nodeType === 3 ? t('关联工作流', 'Linked workflow') : t('关联任务', 'Linked job')} name="jobId" rules={[{ required: true, message: t('请选择关联对象', 'Select a linked object') }]}><Select showSearch filterOption={false} loading={searching} onSearch={search} onOpenChange={open => { if (open) void search(''); }} options={options.map(item => ({ value: String(item.id), label: `${item.jobName || item.wfName} #${item.id}` }))}/></Form.Item>}
    <Form.Item label={t('节点名称', 'Node name')} name="nodeName" rules={[{ required: true, message: t('请输入节点名称', 'Enter a node name') }]}><Input/></Form.Item>
    <Form.Item label={node.nodeType === 2 ? t('Groovy 判断表达式', 'Groovy decision expression') : t('节点参数', 'Node parameters')} extra={node.nodeType === 2 ? t("通过 context 读取工作流上下文，例如 context.get('route') == 'true'。", "Read workflow context with context, e.g. context.get('route') == 'true'.") : undefined} name="nodeParams" rules={node.nodeType === 2 ? [{ required: true, message: t('请输入判断表达式', 'Enter a decision expression') }] : []}>{node.nodeType === 2 ? <CodeEditor readOnly={disabled}/> : <Input.TextArea rows={5}/>}</Form.Item>
    {node.nodeType !== 2 && <><Form.Item label={t('启用节点', 'Enable node')} name="enable" valuePropName="checked"><Switch/></Form.Item><Form.Item label={t('失败时跳过', 'Skip on failure')} name="skipWhenFailed" valuePropName="checked"><Switch/></Form.Item></>}
    <Space wrap><Button type="primary" icon={<Save size={14}/>} loading={busy} onClick={() => void form.validateFields().then(onSave).catch(() => {})}>{t('保存节点', 'Save node')}</Button><Popconfirm title={t('移除这个节点及其连接？', 'Remove this node and its connections?')} onConfirm={onRemove}><Button danger icon={<Trash2 size={14}/>}>{t('移除', 'Remove')}</Button></Popconfirm></Space>
  </Form></aside>;
}

function WorkflowEditor() {
  const { appId, language, t } = useConsole(); const { message } = App.useApp(); const navigate = useNavigate(); const [params] = useSearchParams(); const workflowId = params.get('workflowId') || ''; const scope = useRequestScope(`${appId}:${workflowId}`);
  const [form] = Form.useForm(); const [connectForm] = Form.useForm(); const [nodes, setNodes] = useState<WorkflowNode[]>([]); const [edges, setEdges] = useState<WorkflowEdge[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [busy, setBusy] = useState(false); const [nodeBusy, setNodeBusy] = useState(false); const [validation, setValidation] = useState<string[]>([]);
  const [importType, setImportType] = useState<1 | 3>(); const [importQuery, setImportQuery] = useState({ keyword: '', resourceId: '', index: 0, pageSize: 8 }); const [importKeys, setImportKeys] = useState<React.Key[]>([]); const [importRows, setImportRows] = useState<DataRecord[]>([]); const [connectOpen, setConnectOpen] = useState(false); const [scheduleResults, setScheduleResults] = useState<string[]>(); const [scheduleBusy, setScheduleBusy] = useState(false);
  const detail = useQuery(() => workflowId ? api.get<DataRecord>('/workflow/fetch', { workflowId, appId }) : Promise.resolve<DataRecord>({ enable: true, maxWfInstanceNum: 1, timeExpressionType: 'API', notifyUserIds: [] }), [workflowId, appId]);
  const editorLocked = detail.loading || busy || nodeBusy || !!detail.error;
  const users = useQuery(() => api.get<DataRecord[]>('/user/list'), [appId]);
  const imported = useQuery(() => importType ? api.post<PageResult>(importType === 3 ? '/workflow/list' : '/job/list', { ...importQuery, appId, [importType === 3 ? 'workflowId' : 'jobId']: importQuery.resourceId || undefined }) : Promise.resolve<PageResult>({ data: [], totalItems: 0, pageSize: 8 }), [importType, importQuery, appId]);
  useEffect(() => { setNodes([]); setEdges([]); setSelectedId(undefined); setImportType(undefined); setImportKeys([]); setImportRows([]); setBusy(false); setNodeBusy(false); setScheduleBusy(false); setScheduleResults(undefined); setConnectOpen(false); connectForm.resetFields(); form.resetFields(); }, [workflowId, appId]);
  useEffect(() => { if (!detail.data) return; const dag = normalizeDag(detail.data); setNodes(dag.nodes); setEdges(dag.edges); setSelectedId(undefined); setValidation([]); form.resetFields(); form.setFieldsValue({ ...detail.data, notifyUserIds: (detail.data.notifyUserIds || []).map(String), lifeCycle: detail.data.lifeCycle && (detail.data.lifeCycle.start || detail.data.lifeCycle.end) ? [detail.data.lifeCycle.start ? dayjs(detail.data.lifeCycle.start) : null, detail.data.lifeCycle.end ? dayjs(detail.data.lifeCycle.end) : null] : null }); }, [detail.data]);
  const selected = nodes.find(n => n.nodeId === selectedId);
  const saveNode = async (node: WorkflowNode) => { await api.post('/workflow/saveNode', [nodePayload(node, appId)], { headers: { AppId: appId } }); };
  const persistSelected = async () => { if (!selected || editorLocked) return; const token = scope.capture(); setNodeBusy(true); try { await saveNode(selected); if (!scope.current(token)) return; void message.success(t('节点已保存', 'Node saved')); } catch {} finally { if (scope.current(token)) setNodeBusy(false); } };
  const removeSelected = () => { if (editorLocked) return; setNodes(current => current.filter(n => n.nodeId !== selectedId)); setEdges(current => current.filter(e => e.from !== selectedId && e.to !== selectedId)); setSelectedId(undefined); };
  const addNodes = async (rows: DataRecord[], type: number) => {
    if (!rows.length || editorLocked) return; const token = scope.capture(); setNodeBusy(true); try { const saved = await api.post<DataRecord[]>('/workflow/saveNode', rows.map(item => ({ appId, type, jobId: type === 2 ? undefined : String(item.id), nodeName: type === 2 ? t('判断条件', 'Decision') : item.jobName || item.wfName, nodeParams: type === 2 ? 'true' : item.jobParams || '', enable: item.enable !== false, skipWhenFailed: item.skipWhenFailed ?? false })), { headers: { AppId: appId } }); if (!scope.current(token)) return; const added = normalizeDag({ nodes: saved, edges: [] }).nodes; setNodes(current => [...current, ...added]); setSelectedId(added[0]?.nodeId); setImportType(undefined); setImportKeys([]); setImportRows([]); } catch {} finally { if (scope.current(token)) setNodeBusy(false); }
  };
  const save = async () => {
    if (editorLocked) return;
    const token = scope.capture(); const values = await form.validateFields().catch(() => undefined); if (!values || !scope.current(token)) return;
    const errors = dagErrors(nodes, edges); const labels: Record<string, string> = { empty: t('至少添加一个节点', 'Add at least one node'), cycle: t('连接不能形成循环', 'Connections cannot form a cycle'), duplicate: t('请移除重复连接', 'Remove duplicate connections'), missing: t('连接引用了不存在的节点', 'A connection references a missing node'), branch: t('判断分支必须为独立的成立和不成立连接', 'Decision branches must have distinct True and False connections'), decision: t('每个判断节点需要成立和不成立两条出口', 'Each decision node needs both True and False outputs') };
    if (errors.length) { setValidation(errors.map(error => labels[error])); return; }
    if (nodes.some(n => !n.nodeName?.trim() || n.nodeType !== 2 && !n.jobId || n.nodeType === 2 && !n.nodeParams?.trim())) { setValidation([t('请填写所有节点的名称、关联对象和判断参数', 'Complete node names, linked objects and decision parameters')]); return; }
    setValidation([]); setBusy(true); try {
      const id = await persistWorkflow(values, nodes, edges, workflowId, appId);
      if (!scope.current(token)) return; void message.success(t('工作流已保存', 'Workflow saved')); if (!workflowId) navigate(`/oms/workflowEditor?workflowId=${id}`, { replace: true }); else await detail.refresh();
    } catch (error) { if (!scope.current(token)) return; if (error instanceof WorkflowSaveError) setValidation([t('节点配置已保存，工作流保存失败。请修正问题后再次保存。', 'Node settings were saved, but the workflow save failed. Correct the issue and save again.'), error.message]); else if (!(error instanceof ApiError) && (error as Error).name !== 'AbortError') void message.error((error as Error).message); } finally { if (scope.current(token)) setBusy(false); }
  };
  const checkSchedule = async () => { if (editorLocked) return; const token = scope.capture(); const values = form.getFieldsValue(); setScheduleBusy(true); try { const results = await api.get<string[]>('/validate/timeExpression', { timeExpressionType: values.timeExpressionType, timeExpression: values.timeExpression || '', startTime: values.lifeCycle?.[0]?.valueOf(), endTime: values.lifeCycle?.[1]?.valueOf() }, { headers: { AppId: appId } }); if (scope.current(token)) setScheduleResults(results); } catch {} finally { if (scope.current(token)) setScheduleBusy(false); } };
  const addConnection = async () => { if (editorLocked) return; const value = await connectForm.validateFields().catch(() => undefined); if (!value) return; const source = nodes.find(n => n.nodeId === value.from); const property = source?.nodeType === 2 ? value.property : undefined; if (connectionError(nodes, edges, value.from, value.to, property)) { void message.warning(t('连接无效：检查循环、重复连接和判断分支', 'Invalid connection: check cycles, duplicates and decision branches')); return; } setEdges(current => [...current, { from: value.from, to: value.to, ...(property ? { property } : {}) }]); setConnectOpen(false); connectForm.resetFields(); };
  return <><PageHeader title={workflowId ? t('编辑工作流', 'Edit workflow') : t('新建工作流', 'Create workflow')} description={t('组合任务与判断分支，构建可观察的自动化流程。', 'Compose jobs and decision branches into observable automation.')} actions={<Space wrap><Button icon={<ArrowLeft size={15}/>} onClick={() => navigate('/oms/workflow')}>{t('工作流列表', 'All workflows')}</Button><Button type="primary" loading={busy} disabled={editorLocked} icon={<Save size={15}/>} onClick={() => void save()}>{t('保存工作流', 'Save workflow')}</Button></Space>}/>
    <ErrorState error={detail.error} retry={() => void detail.refresh()}/><Spin spinning={detail.loading}><Panel><Form name="workflowGlobal" form={form} layout="vertical" className="workflow-fields" disabled={editorLocked}>
      <Form.Item label={t('工作流名称', 'Workflow name')} name="wfName" rules={[{ required: true, whitespace: true, message: t('请输入工作流名称', 'Enter a workflow name') }]}><Input placeholder={t('例如：每日数据处理', 'For example: Daily data pipeline')}/></Form.Item>
      <Form.Item label={t('最大并发实例', 'Concurrent instances')} name="maxWfInstanceNum" extra={t('0 或负数表示不限', '0 or a negative value means unlimited')} rules={[{ required: true }]}><InputNumber precision={0} style={{ width: '100%' }}/></Form.Item><Form.Item label={t('启用工作流', 'Enable workflow')} name="enable" valuePropName="checked"><Switch/></Form.Item>
      <Form.Item className="full" label={t('说明', 'Description')} name="wfDescription"><Input.TextArea rows={2}/></Form.Item>
      <Form.Item label={t('调度方式', 'Schedule')} name="timeExpressionType" rules={[{ required: true }]}><Select options={['API', 'CRON'].map(value => ({ value, label: enumLabel('schedule', value, language) }))}/></Form.Item>
      <Form.Item label={t('时间表达式', 'Time expression')} name="timeExpression"><Input placeholder="0 0 2 * * ?"/></Form.Item><Form.Item label={t('调度预览', 'Schedule preview')}><Button loading={scheduleBusy} onClick={() => void checkSchedule()}>{t('校验时间表达式', 'Validate expression')}</Button></Form.Item>
      <Form.Item label={t('生效时间范围', 'Active period')} name="lifeCycle"><DatePicker.RangePicker showTime allowEmpty={[true, true]} style={{ width: '100%' }}/></Form.Item><Form.Item label={t('失败通知', 'Failure notifications')} name="notifyUserIds"><Select mode="multiple" showSearch optionFilterProp="label" options={(users.data || []).map(user => ({ value: String(user.id), label: user.username || user.nick }))}/></Form.Item>
    </Form></Panel>
    {!!validation.length && <Alert type="error" showIcon title={t('工作流尚未保存', 'Workflow has not been saved')} description={validation.join('；')} style={{ marginTop: 16 }}/>}<fieldset disabled={editorLocked} style={{ border: 0, padding: 0, margin: 0, minWidth: 0 }}><div className="workflow-editor-grid"><WorkflowGraph nodes={nodes} edges={edges} editable={!editorLocked} selectedId={selectedId} onSelect={node => { if (!editorLocked) setSelectedId(node?.nodeId); }} onChange={(nextNodes, nextEdges) => { if (editorLocked) return; setNodes(nextNodes); setEdges(nextEdges); }} actions={<><Button disabled={editorLocked} icon={<Plus size={14}/>} onClick={() => { setImportType(1); setImportQuery({ keyword: '', resourceId: '', index: 0, pageSize: 8 }); }}>{t('添加任务', 'Add jobs')}</Button><Button disabled={editorLocked} icon={<GitBranch size={14}/>} loading={nodeBusy} onClick={() => void addNodes([{}], 2)}>{t('判断', 'Decision')}</Button><Button disabled={editorLocked} icon={<Workflow size={14}/>} onClick={() => { setImportType(3); setImportQuery({ keyword: '', resourceId: '', index: 0, pageSize: 8 }); }}>{t('子工作流', 'Nested flow')}</Button><Button disabled={editorLocked || nodes.length < 2} icon={<Link2 size={14}/>} onClick={() => setConnectOpen(true)}>{t('连接节点', 'Connect')}</Button></>}/><NodeInspector node={selected} onChange={node => setNodes(current => current.map(n => n.nodeId === node.nodeId ? node : n))} onSave={persistSelected} onRemove={removeSelected} busy={nodeBusy} disabled={editorLocked}/></div>
    <Panel title={t('连接关系', 'Connections')} className="workflow-connection-list">{edges.length ? edges.map((edge, index) => <div className="workflow-connection-row" key={`${edge.from}-${edge.to}-${index}`}><span>{nodes.find(n => n.nodeId === edge.from)?.nodeName} → {nodes.find(n => n.nodeId === edge.to)?.nodeName} {edge.property && <EnumTag kind="decisionBranch" value={edge.property}/>}</span><Button size="small" danger aria-label={t('删除连接', 'Delete connection')} icon={<Trash2 size={14}/>} disabled={editorLocked} onClick={() => { if (!editorLocked) setEdges(current => current.filter((_, i) => i !== index)); }}/></div>) : <Typography.Text type="secondary">{t('拖动节点连接点，或使用“连接节点”建立关系。', 'Drag node handles, or use Connect to add a connection.')}</Typography.Text>}</Panel></fieldset></Spin>
    <Modal title={importType === 3 ? t('添加子工作流', 'Add nested workflows') : t('添加任务节点', 'Add job nodes')} open={!!importType} width={850} onCancel={() => { setImportType(undefined); setImportKeys([]); setImportRows([]); }} onOk={() => void addNodes(importRows, importType!)} confirmLoading={nodeBusy} okButtonProps={{ disabled: editorLocked || !importRows.length }} okText={t(`添加 ${importRows.length} 个节点`, `Add ${importRows.length} nodes`)}><QueryBar><Input.Search aria-label={t('搜索名称', 'Search names')} placeholder={t('搜索名称', 'Search names')} allowClear onSearch={keyword => setImportQuery(current => ({ ...current, keyword, index: 0 }))}/><Input.Search aria-label="ID" placeholder="ID" allowClear onSearch={resourceId => setImportQuery(current => ({ ...current, resourceId, index: 0 }))}/></QueryBar><ErrorState error={imported.error} retry={() => void imported.refresh()}/><Table rowKey={row => String(row.id)} loading={imported.loading} dataSource={(imported.data?.data || []).filter(row => importType !== 3 || String(row.id) !== workflowId)} rowSelection={{ selectedRowKeys: importKeys, preserveSelectedRowKeys: true, onChange: (keys, rows) => { setImportKeys(keys); setImportRows(rows); } }} columns={[{ title: 'ID', dataIndex: 'id', width: 110 }, { title: t('名称', 'Name'), render: (_, row) => row.jobName || row.wfName }, { title: t('调度', 'Schedule'), render: (_, row) => <Space><EnumTag kind="schedule" value={row.timeExpressionType}/><span>{row.timeExpression || '—'}</span></Space> }]} pagination={{ current: importQuery.index + 1, pageSize: importQuery.pageSize, total: imported.data?.totalItems, showSizeChanger: false, onChange: page => setImportQuery(current => ({ ...current, index: page - 1 })) }}/></Modal>
    <Modal title={t('连接节点', 'Connect nodes')} open={connectOpen} onCancel={() => setConnectOpen(false)} onOk={() => void addConnection()} okButtonProps={{ disabled: editorLocked }}><Form name="workflowConnect" form={connectForm} layout="vertical" disabled={editorLocked}><Form.Item name="from" label={t('来源节点', 'Source node')} rules={[{ required: true }]}><Select options={nodes.map(n => ({ value: n.nodeId, label: n.nodeName }))}/></Form.Item><Form.Item name="to" label={t('目标节点', 'Target node')} rules={[{ required: true }]}><Select options={nodes.map(n => ({ value: n.nodeId, label: n.nodeName }))}/></Form.Item><Form.Item noStyle shouldUpdate={(before, after) => before.from !== after.from}>{({ getFieldValue }) => nodes.find(n => n.nodeId === getFieldValue('from'))?.nodeType === 2 ? <Form.Item name="property" label={t('判断分支', 'Decision branch')} rules={[{ required: true }]}><Select options={['true', 'false'].map(value => ({ value, label: enumLabel('decisionBranch', value, language) }))}/></Form.Item> : null}</Form.Item></Form></Modal>
    <Modal title={t('调度校验结果', 'Schedule validation')} open={!!scheduleResults} onCancel={() => setScheduleResults(undefined)} footer={<Button onClick={() => setScheduleResults(undefined)}>{t('关闭', 'Close')}</Button>}>{scheduleResults?.length ? scheduleResults.map((item, i) => <Alert key={i} type={scheduleResultType(item)} title={scheduleResultType(item) === 'info' ? t('校验通过，此调度不生成定时触发列表。', 'Valid schedule. This schedule has no timed trigger list.') : item} style={{ marginBottom: 10 }}/>) : <Empty description={t('此调度方式由 API 手动触发', 'This schedule is triggered through the API')}/>}</Modal>
  </>;
}

export default function Workflows() {
  const { appId, t } = useConsole(); const { message } = App.useApp(); const navigate = useNavigate(); const location = useLocation(); const [params] = useSearchParams(); const [searchForm] = Form.useForm(); const [query, setQuery] = useState<DataRecord>({ index: 0, pageSize: 10 }); const scope = useRequestScope(`${appId}:${location.pathname}:${params.get('edit') || ''}`); const [runRow, setRunRow] = useState<DataRecord>(); const [runParams, setRunParams] = useState(''); const [delay, setDelay] = useState(0); const [actionId, setActionId] = useState(''); const [running, setRunning] = useState(false);
  const list = useQuery(() => api.post<PageResult>('/workflow/list', { ...query, appId }), [query, appId, location.pathname, params.get('edit')]);
  useEffect(() => { setRunRow(undefined); setRunParams(''); setDelay(0); setRunning(false); setActionId(''); }, [appId, location.pathname, params.get('edit')]);
  if (location.pathname.toLowerCase().includes('workfloweditor') || params.get('edit') === '1') return <WorkflowEditor/>;
  const operate = async (row: DataRecord, operation: string) => { const token = scope.capture(); setActionId(String(row.id)); try { const id = operation === 'copy' ? responseId(await api.post('/workflow/copy', undefined, { params: { workflowId: row.id, appId }, headers: { AppId: appId } })) : await api.get(`/workflow/${operation}`, { workflowId: row.id, appId }, { headers: { AppId: appId } }); if (!scope.current(token)) return; void message.success(t('操作已完成', 'Operation completed')); if (operation === 'copy') navigate(`/oms/workflowEditor?workflowId=${id}`); else void list.refresh(); } catch (error) { if (!(error instanceof ApiError) && (error as Error).name !== 'AbortError') void message.error((error as Error).message); } finally { if (scope.current(token)) setActionId(''); } };
  const run = async (row: DataRecord, parameters?: string, runDelay = 0) => { const token = scope.capture(); setRunning(true); try { const id = responseId(await api.get('/workflow/run', { workflowId: row.id, appId, initParams: parameters, delay: runDelay }, { headers: { AppId: appId } })); if (!scope.current(token)) return; setRunRow(undefined); setRunParams(''); setDelay(0); void message.success(t('工作流已提交运行', 'Workflow run submitted')); navigate(`/oms/wfInstanceDetail?wfInstanceId=${id}`); } catch (error) { if (!(error instanceof ApiError) && (error as Error).name !== 'AbortError') void message.error((error as Error).message); } finally { if (scope.current(token)) setRunning(false); } };
  return <><PageHeader title={t('工作流', 'Workflows')} description={t('让多个任务按依赖协同运行。', 'Coordinate jobs through dependencies.')} actions={<Button type="primary" icon={<Plus size={16}/>} onClick={() => navigate('/oms/workflowEditor')}>{t('新建工作流', 'Create workflow')}</Button>}/><Panel><QueryBar><Form name="workflowQuery" form={searchForm} layout="inline" onFinish={values => setQuery({ ...query, ...values, index: 0 })}><Form.Item name="workflowId"><Input placeholder={t('工作流 ID', 'Workflow ID')} aria-label={t('工作流 ID', 'Workflow ID')} allowClear/></Form.Item><Form.Item name="keyword"><Input placeholder={t('搜索名称', 'Search names')} aria-label={t('搜索名称', 'Search names')} allowClear/></Form.Item><Space><Button type="primary" htmlType="submit">{t('查询', 'Search')}</Button><Button onClick={() => { searchForm.resetFields(); setQuery({ index: 0, pageSize: query.pageSize }); }}>{t('重置', 'Reset')}</Button></Space></Form><RefreshButton loading={list.loading} onClick={() => void list.refresh()}/></QueryBar><ErrorState error={list.error} retry={() => void list.refresh()}/><Table rowKey={row => String(row.id)} loading={list.loading} dataSource={list.data?.data || []} scroll={{ x: 920 }} columns={[
    { title: t('工作流', 'Workflow'), key: 'name', width: 300, render: (_, row) => <div><Button className="workflow-table-title" type="link" style={{ padding: 0 }} onClick={() => navigate(`/oms/workflowEditor?workflowId=${row.id}`)}>{row.wfName}</Button><div className="workflow-table-description">#{row.id}{row.wfDescription && ` / ${row.wfDescription}`}</div></div> }, { title: t('调度', 'Schedule'), render: (_, row) => <Space direction="vertical" size={0}><EnumTag kind="schedule" value={row.timeExpressionType}/><Typography.Text type="secondary">{row.timeExpression || '—'}</Typography.Text></Space> }, { title: t('启用', 'Enabled'), width: 90, render: (_, row) => <Switch checked={row.enable} loading={actionId === String(row.id)} onChange={value => void operate(row, value ? 'enable' : 'disable')}/> }, { title: t('操作', 'Actions'), width: 400, render: (_, row) => <Space size={2}><Button type="text" icon={<Pencil size={14}/>} onClick={() => navigate(`/oms/workflowEditor?workflowId=${row.id}`)}>{t('编辑', 'Edit')}</Button><Button type="text" icon={<Copy size={14}/>} disabled={!!actionId} onClick={() => void operate(row, 'copy')}>{t('复制', 'Copy')}</Button><Button type="text" icon={<Play size={14}/>} disabled={running} onClick={() => void run(row)}>{t('运行', 'Run')}</Button><Button type="text" icon={<SlidersHorizontal size={14}/>} onClick={() => { setRunRow(row); setRunParams(''); setDelay(0); }}>{t('参数运行', 'Run with params')}</Button><Popconfirm title={t('删除这个工作流？', 'Delete this workflow?')} description={row.wfName} onConfirm={() => void operate(row, 'delete')}><Button type="text" danger aria-label={t('删除工作流', 'Delete workflow')} icon={<Trash2 size={14}/>}/></Popconfirm></Space> }
  ]} pagination={{ current: query.index + 1, pageSize: query.pageSize, total: list.data?.totalItems || 0, showSizeChanger: true, onChange: (page, pageSize) => setQuery(current => ({ ...current, index: page - 1, pageSize })) }}/></Panel><Modal title={t('运行工作流', 'Run workflow')} open={!!runRow} onCancel={() => setRunRow(undefined)} confirmLoading={running} okText={t('运行', 'Run')} onOk={() => runRow && void run(runRow, runParams, delay)}><Typography.Paragraph>{runRow?.wfName}</Typography.Paragraph><Form name="workflowRun" layout="vertical"><Form.Item label={t('初始参数', 'Initial parameters')} htmlFor="workflowRun_initParams"><Input.TextArea id="workflowRun_initParams" aria-label={t('初始参数', 'Initial parameters')} rows={5} value={runParams} onChange={e => setRunParams(e.target.value)}/></Form.Item><Form.Item label={t('延迟运行（毫秒）', 'Delay (milliseconds)')} htmlFor="workflowRun_delay"><InputNumber id="workflowRun_delay" aria-label={t('延迟运行（毫秒）', 'Delay (milliseconds)')} min={0} value={delay} onChange={value => setDelay(value ?? 0)} style={{ width: '100%' }}/></Form.Item></Form></Modal></>;
}
