server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location / { try_files $uri $uri/ =404; }
    location = /config.js { add_header Cache-Control "no-store"; }
    location = /index.html { add_header Cache-Control "no-cache"; }
}
