<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { api } from '../../core/api'
import { useLatestRequest } from '../../core/request'
import { t, toast, clone } from '../../core/ui'
import type { Entity } from '../../core/session'
import Field from '../../shared/Field.vue'
import Modal from '../../shared/Modal.vue'
import Icon from '../../shared/Icon.vue'
import { schedules, cronExpression, dailyExpression, draftFromCron } from './model'
const props=withDefaults(defineProps<{type:string;expression:string;lifeCycle:Entity|null;types?:string[]}>(),{types:()=>schedules})
const emit=defineEmits<{'update:type':[value:string];'update:expression':[value:string];'update:lifeCycle':[value:Entity|null]}>()
const quick=ref(false),daily=ref(false),validation=ref(false),checking=ref(false)
const validationRequest=useLatestRequest()
const triggers=ref<string[]>([]),validationError=ref(''),notice=ref('')
const preset=reactive({kind:'minutes',step:5,hour:9,minute:0,weekday:2,day:1})
const generated=computed(()=>{try{return cronExpression(preset)}catch{return ''}})
const dailyValue=ref<Entity>({interval:60,intervalUnit:'SECONDS',startTimeOfDay:'09:00:00',endTimeOfDay:'18:00:00',daysOfWeek:[1,2,3,4,5]})
const names=computed(()=>({API:t('手动 / API','Manual / API'),CRON:'CRON',FIXED_RATE:t('固定频率','Fixed rate'),FIXED_DELAY:t('固定延迟','Fixed delay'),WORKFLOW:t('工作流触发','Workflow triggered'),DAILY_TIME_INTERVAL:t('每日固定间隔','Daily interval')}))
const presets=computed(()=>[{value:'minutes',label:t('每隔几分钟','Every N minutes')},{value:'hours',label:t('每隔几小时','Every N hours')},{value:'daily',label:t('每天','Every day')},{value:'weekdays',label:t('工作日','Weekdays')},{value:'weekly',label:t('每周','Every week')},{value:'monthly',label:t('每月','Every month')}])
function openQuick(){Object.assign(preset,draftFromCron(props.expression));quick.value=true}
function applyQuick(){try{emit('update:expression',cronExpression(preset));quick.value=false}catch(error){toast((error as Error).message,'error')}}
function openDaily(){
  try{const parsed=props.expression?JSON.parse(props.expression):{};if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();dailyValue.value={interval:60,intervalUnit:'SECONDS',startTimeOfDay:'09:00:00',endTimeOfDay:'18:00:00',daysOfWeek:[1,2,3,4,5],...parsed};if(parsed.daysOfWeek)dailyValue.value.daysOfWeek=parsed.daysOfWeek.map(Number);daily.value=true}catch{toast(t('每日间隔不是有效 JSON，请先修正表达式','The daily interval is invalid JSON. Correct the expression.'),'error')}
}
function applyDaily(){try{emit('update:expression',dailyExpression(dailyValue.value));daily.value=false}catch(error){toast((error as Error).message,'error')}}
function dateValue(value:unknown){if(value==null)return '';const date=new Date(Number(value));if(!Number.isFinite(date.getTime()))return '';return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,19)}
function updateDate(key:string,value:string){const next=clone(props.lifeCycle||{start:null,end:null});next[key]=value?new Date(value).getTime():null;emit('update:lifeCycle',next)}
async function validate(){
  validation.value=true;checking.value=true;triggers.value=[];validationError.value='';notice.value=''
  const type=props.type,expression=props.expression
  const request=validationRequest.begin()
  try{const result=await api<string[]>('/validate/timeExpression',{query:{timeExpressionType:type,timeExpression:expression},quiet:true,signal:request.signal});if(!request.current()||!validation.value||props.type!==type||props.expression!==expression)return
    if(Array.isArray(result)&&result.every(value=>/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}/.test(value)))triggers.value=result
    else if(result?.join('\n')==='It is valid, but has not trigger time list!')notice.value=t('表达式有效，此调度类型不返回触发时间。','The expression is valid; this schedule has no trigger-time list.')
    else validationError.value=Array.isArray(result)?result.join('\n'):t('无法验证表达式','Unable to validate this expression')
  }catch(error){if(request.current()&&!request.signal.aborted)validationError.value=(error as Error).message}finally{if(request.current())checking.value=false;request.end()}
}
</script>
<template><div class="schedule-grid"><Field :label="t('调度方式','Schedule type')"><select :value="type" @change="emit('update:type',($event.target as HTMLSelectElement).value)"><option v-for="item in types" :key="item" :value="item">{{(names as Record<string,string>)[item]||item}}</option></select></Field><Field v-if="!['API','WORKFLOW'].includes(type)" :label="t('调度表达式','Schedule expression')" class="schedule-expression"><input class="code" :value="expression" @input="emit('update:expression',($event.target as HTMLInputElement).value)"/></Field><div class="schedule-actions"><button v-if="type==='CRON'" type="button" class="btn" @click="openQuick"><Icon name="clock"/>{{t('快速配置','Quick setup')}}</button><button v-if="type==='DAILY_TIME_INTERVAL'" type="button" class="btn" @click="openDaily">{{t('配置每日间隔','Set daily interval')}}</button><button type="button" class="btn btn-quiet" @click="validate">{{t('验证表达式','Validate expression')}}</button></div></div><div class="form-grid lifecycle-grid"><Field :label="t('生效开始时间','Lifecycle start')" :hint="t('留空表示没有开始限制；按浏览器时区输入。','Leave empty for no start limit; enter in browser timezone.')"><input type="datetime-local" step="1" :value="dateValue(lifeCycle?.start)" @input="updateDate('start',($event.target as HTMLInputElement).value)"/></Field><Field :label="t('生效结束时间','Lifecycle end')"><input type="datetime-local" step="1" :value="dateValue(lifeCycle?.end)" @input="updateDate('end',($event.target as HTMLInputElement).value)"/></Field></div>
<Modal v-model="quick" :title="t('CRON 快速配置','CRON quick setup')"><div class="form-grid"><Field class="full" :label="t('执行周期','Frequency')"><select v-model="preset.kind"><option v-for="item in presets" :key="item.value" :value="item.value">{{item.label}}</option></select></Field><Field v-if="['minutes','hours'].includes(preset.kind)" :label="t('间隔','Interval')"><input v-model.number="preset.step" type="number" min="1" :max="preset.kind==='minutes'?59:23"/></Field><Field v-if="preset.kind!=='minutes' && preset.kind!=='hours'" :label="t('小时','Hour')"><input v-model.number="preset.hour" type="number" min="0" max="23"/></Field><Field v-if="preset.kind!=='minutes'" :label="t('分钟','Minute')"><input v-model.number="preset.minute" type="number" min="0" max="59"/></Field><Field v-if="preset.kind==='weekly'" :label="t('星期','Weekday')"><select v-model.number="preset.weekday"><option v-for="(day,index) in [t('星期日','Sunday'),t('星期一','Monday'),t('星期二','Tuesday'),t('星期三','Wednesday'),t('星期四','Thursday'),t('星期五','Friday'),t('星期六','Saturday')]" :key="index" :value="index+1">{{day}}</option></select></Field><Field v-if="preset.kind==='monthly'" :label="t('日期','Day of month')"><input v-model.number="preset.day" type="number" min="1" max="31"/></Field><div class="cron-preview full"><span>{{t('生成的表达式','Generated expression')}}</span><code>{{generated||t('请修正输入值','Correct the input values')}}</code></div><p class="field-hint full">{{t('实际触发时间使用 Server 时区。步长在自然小时/日重新开始；不存在的月日期会跳过。复杂规则仍可直接编辑。','Execution uses the Server timezone. Steps reset at hour/day boundaries; nonexistent month dates are skipped. Complex expressions remain editable.')}}</p></div><template #footer><button type="button" class="btn" @click="quick=false">{{t('取消','Cancel')}}</button><button type="button" class="btn btn-primary" :disabled="!generated" @click="applyQuick">{{t('应用表达式','Apply expression')}}</button></template></Modal>
<Modal v-model="daily" :title="t('每日固定间隔','Daily interval')"><div class="form-grid"><Field :label="t('间隔','Interval')"><input v-model.number="dailyValue.interval" type="number" min="1"/></Field><Field :label="t('单位','Unit')"><select v-model="dailyValue.intervalUnit"><option value="SECONDS">{{t('秒','Seconds')}}</option><option value="MINUTES">{{t('分钟','Minutes')}}</option><option value="HOURS">{{t('小时','Hours')}}</option></select></Field><Field :label="t('每天开始时间','Daily start time')"><input v-model="dailyValue.startTimeOfDay" type="time" step="1"/></Field><Field :label="t('每天结束时间','Daily end time')"><input v-model="dailyValue.endTimeOfDay" type="time" step="1"/></Field><div class="full"><span class="field-label">{{t('星期范围','Weekdays')}}</span><div class="checkboxes"><label v-for="(day,index) in [t('星期一','Monday'),t('星期二','Tuesday'),t('星期三','Wednesday'),t('星期四','Thursday'),t('星期五','Friday'),t('星期六','Saturday'),t('星期日','Sunday')]" :key="day" class="check-label"><input v-model="dailyValue.daysOfWeek" type="checkbox" :value="index+1"/>{{day}}</label></div><small class="muted">{{t('全部不选按 Server 规则表示每天。','An empty selection means every day in the Server contract.')}}</small></div></div><template #footer><button type="button" class="btn" @click="daily=false">{{t('取消','Cancel')}}</button><button type="button" class="btn btn-primary" @click="applyDaily">{{t('应用配置','Apply configuration')}}</button></template></Modal>
<Modal v-model="validation" :title="t('调度验证','Schedule validation')"><p v-if="checking">{{t('正在验证…','Validating…')}}</p><div v-else-if="validationError" class="error-banner">{{validationError}}</div><div v-else-if="notice" class="info-banner">{{notice}}</div><ol v-else class="trigger-list"><li v-for="trigger in triggers" :key="trigger">{{trigger}}</li></ol><template #footer><button type="button" class="btn" @click="validate">{{t('重新验证','Retry validation')}}</button><button type="button" class="btn btn-primary" @click="validation=false">{{t('关闭','Close')}}</button></template></Modal>
</template>
<style scoped>.schedule-grid{display:flex;align-items:flex-end;gap:12px;flex-wrap:wrap}.schedule-grid>.field{min-width:180px;flex:0 1 220px}.schedule-expression{flex:1 1 280px!important}.schedule-actions{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.lifecycle-grid{margin-top:18px}.cron-preview{padding:15px;border-radius:9px;background:#f4f7fe;display:flex;flex-direction:column;gap:8px}.cron-preview span{font-size:12px;color:var(--muted)}.cron-preview code{font-size:16px;color:var(--blue);font-weight:650}.checkboxes{margin-top:10px}.trigger-list{padding-left:22px;line-height:2.4;color:var(--blue);font-variant-numeric:tabular-nums}</style>
