import { useEffect, useState } from 'react';
import { Avatar, Button, Drawer, Dropdown, Input, Modal, Select, Tooltip } from 'antd';
import { Activity, ArrowLeftRight, BellRing, Boxes, ChevronDown, Command, GitBranch, Globe, Layers, ListChecks, LogOut, Menu, Search, Settings, Shield, User, Users, Zap } from 'lucide-react';
import { Link, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { api,type DataRecord,type PageResult } from '../lib/api';
import { useConsole } from '../lib/console';
import { useQuery } from '../lib/hooks';

export default function Shell(){
  const {appId,appName,user,refreshSession,setApp,language,setLanguage,t,logout}=useConsole();const navigate=useNavigate();const location=useLocation();const [mobile,setMobile]=useState(false);const [command,setCommand]=useState(false);const [search,setSearch]=useState('');
  const apps=useQuery(()=>api.post<PageResult>('/appInfo/list',{showMyRelated:true,index:0,pageSize:1000}),[appId,location.pathname]);
  useEffect(()=>{void refreshSession().catch(()=>{});},[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommand(c=>!c);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  useEffect(()=>setMobile(false),[location.pathname]);
  const operations=[{path:'/oms/home',zh:'运行概览',en:'Overview',icon:Activity},{path:'/oms/job',zh:'任务管理',en:'Jobs',icon:ListChecks},{path:'/oms/instance',zh:'任务实例',en:'Job instances',icon:Layers},{path:'/oms/workflow',zh:'工作流',en:'Workflows',icon:GitBranch},{path:'/oms/wfinstance',zh:'工作流实例',en:'Workflow instances',icon:BellRing},{path:'/oms/containermanage',zh:'容器管理',en:'Containers',icon:Boxes}];
  const management=[{path:'/admin/app',zh:'应用管理',en:'Applications',icon:Boxes},{path:'/admin/namespace',zh:'命名空间',en:'Namespaces',icon:Shield},{path:'/admin/user',zh:'用户管理',en:'Users',icon:Users},{path:'/admin/settings',zh:'系统设置',en:'System settings',icon:Settings}];
  const availableApps=[...(apps.data?.data||[])];if(appId&&!availableApps.some(a=>String(a.id)===appId))availableApps.unshift({id:appId,appName:appName||appId});
  const all=[...operations,...management,{path:'/oms/template',zh:'容器开发模板',en:'Container starter project',icon:Boxes},{path:'/admin/personal',zh:'个人设置',en:'My profile',icon:User}];const active=all.find(n=>n.path===location.pathname)||(location.pathname==='/oms/workflowEditor'?operations[3]:location.pathname==='/oms/wfInstanceDetail'?operations[4]:undefined);
  const nav=<><Link className="brand" to={appId?'/oms/home':'/admin/app'}><div className="brand-mark"><Zap size={22} fill="currentColor"/></div><span>PowerJob<small>{t('分布式任务调度','Distributed scheduling')}</small></span></Link><div className="nav-scroll"><div className="nav-section-title">{t('工作区','Workspace')}</div><nav>{operations.map(n=><Link aria-current={active?.path===n.path?'page':undefined} className={`nav-item ${active?.path===n.path?'active':''} ${!appId?'inactive':''}`} to={appId?n.path:'/admin/app'} key={n.path}><n.icon size={18}/><span>{t(n.zh,n.en)}</span></Link>)}</nav><div className="nav-section-title">{t('组织管理','Organization')}</div><nav>{management.map(n=><Link aria-current={active?.path===n.path?'page':undefined} className={`nav-item ${active?.path===n.path?'active':''}`} to={n.path} key={n.path}><n.icon size={18}/><span>{t(n.zh,n.en)}</span></Link>)}</nav></div><div className="nav-footer"><button onClick={()=>{setCommand(true);setSearch('');}}><Command size={16}/><span>{t('快捷导航','Quick navigation')}</span><kbd>⌘ K</kbd></button><span className="nav-version">PowerJob Console</span></div></>;
  return <div className="app-shell"><a className="skip-link" href="#main-content" onClick={event=>{event.preventDefault();const main=document.getElementById('main-content');main?.focus({preventScroll:true});main?.scrollIntoView({behavior:'smooth',block:'start'});}}>{t('跳到主内容','Skip to content')}</a><aside className="sidebar">{nav}</aside><Drawer placement="left" size={250} open={mobile} onClose={()=>setMobile(false)} styles={{body:{padding:0}}} className="mobile-nav">{nav}</Drawer><div className="workspace"><header className="topbar"><Button className="mobile-menu" type="text" aria-label={t('打开导航','Open navigation')} icon={<Menu size={20}/>} onClick={()=>setMobile(true)}/><div className="breadcrumb">{location.pathname.startsWith('/admin')?t('组织管理','Organization'):t('工作区','Workspace')}<span>/</span><strong>{active?t(active.zh,active.en):t('项目模板','Project template')}</strong></div><div className="topbar-controls"><div className="app-switcher"><Layers size={16}/><Select aria-label={t('当前应用','Current application')} value={appId||undefined} placeholder={t('选择应用','Select application')} variant="borderless" popupMatchSelectWidth={300} showSearch optionFilterProp="label" options={availableApps.map(a=>({value:String(a.id),label:a.appName}))} onChange={id=>{const selected=availableApps.find(a=>String(a.id)===id);if(selected){setApp(selected);navigate('/oms/home');}}}/></div><Tooltip title={t('切换语言','Change language')}><Button type="text" aria-label={t('切换语言','Change language')} icon={<Globe size={18}/>} onClick={()=>setLanguage(language==='en'?'cn':'en')}/></Tooltip><Dropdown trigger={['click']} menu={{items:[{key:'profile',label:t('个人设置','My profile'),icon:<User size={15}/>},{type:'divider'},{key:'logout',label:t('退出登录','Sign out'),icon:<LogOut size={15}/> }],onClick:({key})=>key==='logout'?logout():navigate('/admin/personal')}}><button className="user-menu"><Avatar size={30} style={{background:'#e9edfb',color:'#315ae8'}}>{(user?.nick||user?.username||'P').slice(0,1)}</Avatar><span>{user?.nick||user?.username||t('我的账户','Account')}</span><ChevronDown size={13}/></button></Dropdown></div></header><main id="main-content" tabIndex={-1} className="main-content" style={{scrollMarginTop:90}}><Outlet key={appId}/></main></div><Modal title={t('快捷导航','Quick navigation')} open={command} onCancel={()=>setCommand(false)} footer={null}><Input autoFocus prefix={<Search size={17}/>} aria-label={t('搜索页面','Search pages')} placeholder={t('输入页面名称…','Type a page name…')} value={search} onChange={e=>setSearch(e.target.value)}/><div className="command-list">{all.filter(n=>(n.zh+n.en).toLowerCase().includes(search.toLowerCase())).map(n=><button key={n.path} onClick={()=>{navigate(n.path);setCommand(false);}}><n.icon size={18}/>{t(n.zh,n.en)}<ArrowLeftRight size={14}/></button>)}</div></Modal></div>;
}
