import { type ReactNode, useState } from 'react';
import { Alert, Button, Empty, Input, Modal, Space, Tag, type ModalProps } from 'antd';
import { RefreshCw } from 'lucide-react';
import { useConsole } from '../lib/console';
import { EnumTag } from '../lib/enums';
import { downloadBlob, parseJson, stringifyJson } from '../lib/api';
export function PageHeader({ title, description, actions, contextual = false }: { title: string; description?: string; actions?: ReactNode; contextual?: boolean }) { return <header className={`page-header ${contextual ? 'page-header-contextual' : 'page-header-compact'}`}><div className={contextual ? undefined : 'sr-only'}><h1>{title}</h1>{contextual && description && <p>{description}</p>}</div>{actions && <div className="page-actions">{actions}</div>}</header>; }
export function Panel({ children, title, actions, className = '' }: { children: ReactNode; title?: ReactNode; actions?: ReactNode; className?: string }) { return <section className={`panel ${className}`}>{(title || actions) && <div className="panel-header"><h2>{title}</h2>{actions}</div>}{children}</section>; }
export function QueryBar({ children }: { children: ReactNode }) { return <div className="query-bar">{children}</div>; }
export function RefreshButton({ onClick, loading }: { onClick: () => void; loading?: boolean }) { const { t } = useConsole(); return <Button icon={<RefreshCw size={15}/>} loading={loading} onClick={onClick}>{t('刷新', 'Refresh')}</Button>; }
export function ErrorState({ error, retry }: { error?: Error; retry: () => void }) { const { t } = useConsole(); return error ? <Alert type="error" showIcon title={error.message} action={<Button onClick={retry}>{t('重试','Retry')}</Button>}/> : null; }
export function EmptyState({ description }: { description?: string }) { const { t } = useConsole(); return <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={description || t('暂无数据', 'No data yet')}/>; }
export function StatusTag({ status, workflow = false }: { status: string | number; workflow?: boolean }) { return <EnumTag kind={workflow ? 'workflowStatus' : 'instanceStatus'} value={status}/>; }
export const formatTime = (value: any) => { if (!value || value === 'N/A') return '—'; if (typeof value === 'string' && !/^\d+$/.test(value)) return value; const time = new Date(Number(value)); return Number(value) < 10000 || isNaN(time.valueOf()) ? '—' : time.toLocaleString('sv-SE'); };
export function JsonModal({ title, open, onCancel, value, onImport, filename = 'powerjob.json' }: { title: string; open: boolean; onCancel: () => void; value?: unknown; onImport?: (value: any) => Promise<void>; filename?: string }) { const { t } = useConsole(); const [text, setText] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async () => { setError(''); setBusy(true); try { const parsed = parseJson(text); if (!parsed || Array.isArray(parsed) || typeof parsed !== 'object') throw new Error(t('请输入 JSON 对象','Enter a JSON object')); await onImport?.(parsed); onCancel(); setText(''); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }; return <Modal title={title} open={open} onCancel={onCancel} width={760} footer={onImport ? <Space><Button onClick={onCancel}>{t('取消','Cancel')}</Button><Button type="primary" loading={busy} onClick={submit}>{t('导入','Import')}</Button></Space> : <Button type="primary" onClick={() => downloadBlob(new Blob([stringifyJson(value,2)],{type:'application/json'}),filename)}>{t('下载 JSON','Download JSON')}</Button>}><Input.TextArea aria-label="JSON" className="code-input" autoSize={{minRows:12,maxRows:24}} value={onImport ? text : stringifyJson(value,2)} readOnly={!onImport} onChange={e=>setText(e.target.value)}/>{error && <Alert type="error" title={error} style={{marginTop:12}}/>}</Modal>; }
export function Confirm({ children, ...props }: ModalProps & { children?: ReactNode }) { return <Modal {...props}>{children}</Modal>; }
