<script setup lang="ts">
import { computed, onMounted, ref, onScopeDispose } from 'vue'
import { api } from '../../core/api'
import { session,type Entity } from '../../core/session'
import { t,toast } from '../../core/ui'
import Field from '../../shared/Field.vue'
import ScheduleFields from '../schedule/ScheduleFields.vue'
import { editJob,jobPayload } from './model'
const props=defineProps<{job:Entity;formId:string}>()
const emit=defineEmits<{saved:[]}>()
const controller=new AbortController()
onScopeDispose(()=>controller.abort())
const draft=ref(editJob(props.job,session.appId)),section=ref('basic'),saving=ref(false),error=ref(''),users=ref<Entity[]>([])
const sections=computed(()=>[{key:'basic',label:t('任务信息','Job information'),description:t('名称、处理器与执行参数','Identity, processor and parameters')},{key:'schedule',label:t('调度计划','Schedule'),description:t('触发方式与生效时间','Trigger and lifecycle')},{key:'runtime',label:t('运行控制','Runtime'),description:t('并发、重试与 Worker 资源','Concurrency, retries and resources')},{key:'notifications',label:t('告警与日志','Alerts & logs'),description:t('通知对象与日志记录','Recipients and logging')}])
const numeric=computed(()=>[
 {key:'maxInstanceNum',zh:'最大实例数',en:'Max instances',hint:t('0 表示不限制','0 means unlimited')},
 {key:'concurrency',zh:'线程并发度',en:'Thread concurrency'},{key:'instanceTimeLimit',zh:'实例超时（ms）',en:'Instance timeout (ms)'},
 {key:'instanceRetryNum',zh:'实例重试次数',en:'Instance retries'},{key:'taskRetryNum',zh:'子任务重试次数',en:'Task retries'},
 {key:'minCpuCores',zh:'最小 CPU 核数',en:'Min CPU cores'},{key:'minMemorySpace',zh:'最小内存（GB）',en:'Min memory (GB)'},
 {key:'minDiskSpace',zh:'最小磁盘（GB）',en:'Min disk (GB)'},{key:'maxWorkerCount',zh:'最大 Worker 数量',en:'Max Worker count'},
])
async function save(){
 if(saving.value)return
 error.value=''
 let body:Entity
 try{body=jobPayload(draft.value)}catch(e){error.value=(e as Error).message;return}
 saving.value=true
 try{await api('/job/save',{body,signal:controller.signal});if(controller.signal.aborted)return;toast(t('任务已保存','Job saved'),'success');emit('saved')}catch(e){if(!controller.signal.aborted)error.value=(e as Error).message}finally{saving.value=false}
}
onMounted(async()=>{try{const data=await api<Entity[]>('/user/list',{signal:controller.signal});if(!controller.signal.aborted)users.value=data}catch{/* Central request feedback. */}})
defineExpose({saving})
</script>
<template><form :id="formId" @submit.prevent="save"><div class="job-editor"><nav class="editor-sections" :aria-label="t('任务配置分区','Job configuration sections')"><button v-for="item in sections" :key="item.key" type="button" :class="{active:section===item.key}" @click="section=item.key"><span>{{item.label}}</span><small>{{item.description}}</small></button></nav><div class="editor-fields"><div v-show="section==='basic'" class="form-grid"><Field class="full" :label="t('任务名称','Job name')" required><input v-model="draft.jobName" maxlength="255" autocomplete="off"/></Field><Field class="full" :label="t('任务描述','Description')"><textarea v-model="draft.jobDescription" rows="2"/></Field><Field :label="t('执行模式','Execution mode')"><select v-model="draft.executeType"><option value="STANDALONE">{{t('单机','Standalone')}}</option><option value="BROADCAST">{{t('广播','Broadcast')}}</option><option value="MAP">Map</option><option value="MAP_REDUCE">MapReduce</option></select></Field><Field :label="t('处理器类型','Processor type')"><select v-model="draft.processorType"><option value="BUILT_IN">{{t('内置','Built-in')}}</option><option value="EXTERNAL">{{t('外置','External')}}</option></select></Field><Field class="full" :label="t('处理器','Processor')" required :hint="draft.processorType==='EXTERNAL'?t('容器 ID # 处理器类全名','Container ID # processor class'):t('Java 处理器类全名','Fully qualified Java processor class')"><input v-model="draft.processorInfo" class="code" :placeholder="draft.processorType==='EXTERNAL'?'1#tech.powerjob.samples.processors.StandaloneProcessorDemo':'tech.powerjob.samples.processors.StandaloneProcessorDemo'"/></Field><Field class="full" :label="t('任务参数','Job parameters')"><textarea v-model="draft.jobParams" class="code" rows="4"/></Field><label class="check-label"><input v-model="draft.enable" type="checkbox"/>{{t('启用任务','Enable job')}}</label></div>
<div v-show="section==='schedule'"><ScheduleFields v-model:type="draft.timeExpressionType" v-model:expression="draft.timeExpression" v-model:life-cycle="draft.lifeCycle"/></div>
<div v-show="section==='runtime'" class="form-grid"><Field :label="t('派发策略','Dispatch strategy')"><select v-model="draft.dispatchStrategy"><option value="HEALTH_FIRST">HEALTH_FIRST</option><option value="RANDOM">RANDOM</option><option value="SPECIFY">SPECIFY</option></select></Field><Field v-if="draft.dispatchStrategy==='SPECIFY'" :label="t('派发策略配置','Dispatch strategy config')"><input v-model="draft.dispatchStrategyConfig"/></Field><Field v-for="field in numeric" :key="field.key" :label="t(field.zh,field.en)" :hint="field.hint"><input v-model.number="draft[field.key]" type="number" min="0" :step="['minCpuCores','minMemorySpace','minDiskSpace'].includes(field.key)?'any':1"/></Field><Field class="full" :label="t('指定 Worker 地址','Designated Workers')" :hint="t('可按原 Server 格式输入多个地址','Enter addresses in the existing Server format')"><input v-model="draft.designatedWorkers" placeholder="127.0.0.1:27777"/></Field><Field :label="t('TaskTracker 行为','TaskTracker behavior')"><select v-model.number="draft.advancedRuntimeConfig.taskTrackerBehavior"><option :value="1">NORMAL</option><option :value="11">PADDLING</option></select></Field></div>
<div v-show="section==='notifications'" class="form-grid"><Field class="full" :label="t('通知对象','Notification recipients')" :hint="t('按住 Ctrl / Command 可选择多个用户','Hold Ctrl / Command to select multiple users')"><select v-model="draft.notifyUserIds" multiple size="4"><option v-for="user in users" :key="user.id" :value="String(user.id)">{{user.username}}</option></select></Field><Field :label="t('告警阈值','Alert threshold')"><input v-model.number="draft.alarmConfig.alertThreshold" type="number" min="0"/></Field><Field :label="t('统计窗口（s）','Statistics window (s)')"><input v-model.number="draft.alarmConfig.statisticWindowLen" type="number" min="0"/></Field><Field :label="t('静默窗口（s）','Silence window (s)')"><input v-model.number="draft.alarmConfig.silenceWindowLen" type="number" min="0"/></Field><Field :label="t('日志类型','Log type')"><select v-model.number="draft.logConfig.type"><option v-for="item in [{value:1,label:'ONLINE'},{value:2,label:'LOCAL'},{value:3,label:'STDOUT'},{value:4,label:'LOCAL_AND_ONLINE'},{value:999,label:'NULL'}]" :key="item.value" :value="item.value">{{item.label}}</option></select></Field><Field :label="t('日志级别','Log level')"><select v-model.number="draft.logConfig.level"><option v-for="item in [{value:1,label:'DEBUG'},{value:2,label:'INFO'},{value:3,label:'WARN'},{value:4,label:'ERROR'},{value:99,label:'OFF'}]" :key="item.value" :value="item.value">{{item.label}}</option></select></Field><Field v-if="[2,4].includes(draft.logConfig.type)" :label="t('Logger 名称','Logger name')"><input v-model="draft.logConfig.loggerName"/></Field></div>
<div v-if="error" class="error-banner" role="alert">{{error}}</div></div></div></form></template>
<style scoped>.job-editor{display:grid;grid-template-columns:195px minmax(0,1fr);gap:25px;min-height:410px}.editor-sections{display:flex;flex-direction:column;gap:6px;border-right:1px solid var(--line);padding-right:17px}.editor-sections button{border:0;background:transparent;text-align:left;border-radius:8px;padding:13px 12px;display:flex;flex-direction:column;gap:5px}.editor-sections button span{font-size:13px;font-weight:700}.editor-sections button small{font-size:10px;color:var(--muted);line-height:1.6}.editor-sections button.active{background:var(--blue-soft);color:var(--blue)}.editor-fields{min-width:0}.editor-fields>.error-banner{margin-top:18px}@media(max-width:760px){.job-editor{grid-template-columns:1fr;gap:20px;min-height:0}.editor-sections{flex-direction:row;flex-wrap:wrap;border:0;padding:0}.editor-sections button{padding:8px}.editor-sections small{display:none}}</style>
