import {describe,expect,it} from 'vitest';
import dayjs from 'dayjs';
import {dailyRule,jobPayload,jobToForm,newJob} from './model';
describe('job form compatibility regressions',()=>{
  it('preserves lifecycle timestamps and does not mutate list rows on open/save',()=>{const job={...newJob('1'),id:'9223372036854775807',lifeCycle:{start:Date.UTC(2026,0,1),end:Date.UTC(2027,0,1)}};const original=structuredClone(job);const form=jobToForm(job);form.jobName='updated';const payload=jobPayload(job,form,'1');expect(payload.lifeCycle).toEqual(job.lifeCycle);expect(payload.id).toBe(job.id);expect(job).toEqual(original);expect('dateRange'in payload).toBe(false);});
  it('clears a lifecycle deliberately and preserves unknown backend extension fields',()=>{const job={...newJob('1'),extra:'opaque',tag:'tag',lifeCycle:{start:1,end:2}};expect(jobPayload(job,{dateRange:null},'2')).toMatchObject({extra:'opaque',tag:'tag',lifeCycle:null,appId:'2'});});
  it('starts each new job with independent nested settings',()=>{const a=newJob('1');a.alarmConfig.alertThreshold=100;expect(newJob('1').alarmConfig.alertThreshold).toBe(0);});
  it('normalizes notification user IDs to strings without precision loss',()=>{expect(jobToForm({...newJob('1'),notifyUserIds:['9223372036854775807',3]}).notifyUserIds).toEqual(['9223372036854775807','3']);});
  it('retains a server-provided lifecycle with only one bound when editing',()=>{for(const lifeCycle of [{start:Date.UTC(2026,0,1),end:null},{start:null,end:Date.UTC(2027,0,1)}]){const job={...newJob('1'),lifeCycle};expect(jobPayload(job,jobToForm(job),'1').lifeCycle).toEqual(lifeCycle);}const job={...newJob('1'),lifeCycle:{start:Date.UTC(2026,0,1),end:null}};expect(jobPayload(job,{jobName:'rename only'},'1').lifeCycle).toEqual(job.lifeCycle);});
  it('preserves hidden logger settings while changing the visible log level',()=>{const job={...newJob('1'),logConfig:{type:1,level:2,loggerName:'saved-logger'},advancedRuntimeConfig:{taskTrackerBehavior:11,extension:'keep'}};expect(jobPayload(job,{logConfig:{type:1,level:3},advancedRuntimeConfig:{taskTrackerBehavior:1}},'1')).toMatchObject({logConfig:{type:1,level:3,loggerName:'saved-logger'},advancedRuntimeConfig:{taskTrackerBehavior:1,extension:'keep'}});});
  it('rejects array daily rules rather than silently replacing the existing expression',()=>{expect(()=>dailyRule('[1,2]')).toThrow('Invalid daily interval');expect(()=>dailyRule('{"daysOfWeek":0}')).toThrow('Invalid daily interval');});
  it('keeps daily expression units and weekdays when editing',()=>{const expression={interval:2,intervalUnit:'MINUTES',startTimeOfDay:'00:00:00',endTimeOfDay:'23:59:59',daysOfWeek:[1,7]};expect(dailyRule(JSON.stringify(expression))).toEqual(expression);expect(()=>dailyRule('{broken')).toThrow();expect(dailyRule('0 0 * * * ?').intervalUnit).toBe('SECONDS');});
  it.each(['SECONDS','MINUTES','HOURS','DAYS','FUTURE_UNIT'])('retains %s and extension fields through opening, editing and saving a daily job',intervalUnit=>{const rule={interval:2,intervalUnit,startTimeOfDay:'00:00:00',endTimeOfDay:'23:59:59',daysOfWeek:[1,7],extension:{keep:true}};const job={...newJob('1'),timeExpressionType:'DAILY_TIME_INTERVAL',timeExpression:JSON.stringify(rule)};const form=jobToForm(job);const edited=dailyRule(form.timeExpression);edited.interval=3;form.timeExpression=JSON.stringify(edited);const payload=jobPayload(job,form,'1');expect(JSON.parse(payload.timeExpression)).toEqual({...rule,interval:3});expect(JSON.parse(job.timeExpression)).toEqual(rule);});
  it('keeps published non-positive unlimited values and the server concurrency fallback when editing',()=>{const settings={maxInstanceNum:-1,instanceTimeLimit:-1,maxWorkerCount:-1,concurrency:0};const job={...newJob('1'),...settings};const form=jobToForm(job);form.jobDescription='edited';expect(jobPayload(job,form,'1')).toMatchObject({...settings,jobDescription:'edited'});expect(job).toMatchObject(settings);});
});
