import { test, expect, Backend, selectors, runId, input, choose, login, secretFill, saveDialog, confirmDialog, clickAndResponse } from './support.js'

test('UI-001/003 · real password validation, Enter login, refresh and logout', async ({ page, credentials }) => {
  await page.goto('/#/loginHomepage')
  await page.getByRole('button', { name: /PWJB|PowerJob/i }).first().click()
  await page.getByRole('button', { name: 'Login', exact: true }).click()
  await expect(page.locator('.el-form-item__error').first()).toBeVisible()
  await secretFill(page.getByLabel('Username', { exact: true }), credentials.admin_username)
  await page.getByLabel('Password', { exact: true }).fill('synthetic-wrong-password')
  const failed = await clickAndResponse(page, '/auth/thirdPartyLoginDirect', () => page.getByRole('button', { name: 'Login', exact: true }).click())
  expect(failed.success).toBe(false)
  await expect(page).toHaveURL(/powerjobLogin/)
  await secretFill(page.getByLabel('Password', { exact: true }), credentials.admin_password)
  await page.getByLabel('Password', { exact: true }).press('Enter')
  await expect(page).toHaveURL(/admin\/app/)
  await page.reload()
  await expect(page.locator('.el-table')).toBeVisible()
  await page.locator('.account-button').hover()
  await page.getByRole('menuitem', { name: 'Logout', exact: true }).click()
  await expect(page).toHaveURL(/loginHomepage/)
  await page.goto('/#/oms/job')
  await expect(page).toHaveURL(/loginHomepage/)
  expect(await page.evaluate(() => localStorage.getItem('PowerJwt'))).toBeNull()
})

test('UI-002 · real registration, mismatch, duplicate and cancellation', async ({ page, credentials }) => {
  const account = `${runId}_register`
  const password = `Synthetic.${runId}.Only`
  await page.goto('/#/powerjobLogin')
  await page.getByRole('button', { name: 'User Registration', exact: true }).click()
  let dialog = selectors.dialog(page)
  await input(dialog, 'Username', account)
  await input(dialog, 'Nick', `${runId} 中文`)
  await input(dialog, 'Phone', '10000000000')
  await input(dialog, 'Email', 'fixture@example.invalid')
  await input(dialog, 'Webhook', 'https://example.invalid/synthetic')
  await input(dialog, 'New Password', password)
  await input(dialog, 'Check New Password', password + '.mismatch')
  await dialog.getByRole('button', { name: 'Register', exact: true }).click()
  await expect(dialog).toBeVisible()
  await expect(page.locator('.el-message').last()).toContainText(/match|consistent/i)
  await input(dialog, 'Check New Password', password)
  const created = await clickAndResponse(page, '/pwjbUser/create', () => dialog.getByRole('button', { name: 'Register', exact: true }).click())
  expect(created.success).toBe(true)
  await expect(dialog).not.toBeVisible()
  await login(page, { ...credentials, admin_username: account, admin_password: password })
  await page.goto('/#/admin/personal')
  await expect(page.getByLabel('Nick', { exact: true })).toHaveValue(`${runId} 中文`)
  await expect(page.getByLabel('Phone', { exact: true })).toHaveValue('10000000000')
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue('fixture@example.invalid')
  await expect(page.getByLabel('Webhook', { exact: true })).toHaveValue('https://example.invalid/synthetic')
  await page.locator('.account-button').hover()
  await page.getByRole('menuitem', { name: 'Logout', exact: true }).click()
  await page.goto('/#/powerjobLogin')
  await page.getByRole('button', { name: 'User Registration', exact: true }).click()
  dialog = selectors.dialog(page)
  await input(dialog, 'Username', account)
  await input(dialog, 'New Password', password)
  await input(dialog, 'Check New Password', password)
  const duplicate = await clickAndResponse(page, '/pwjbUser/create', () => dialog.getByRole('button', { name: 'Register', exact: true }).click())
  expect(duplicate.success).toBe(false)
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'User Registration', exact: true }).click()
  await expect(selectors.dialog(page).getByLabel('Username', { exact: true })).toHaveValue('')
  await selectors.dialog(page).getByRole('button', { name: 'Cancel', exact: true }).click()
  // Registered PWJB identities cannot be deleted by the published management API.
  // The unique synthetic identity remains confined to the disposable isolated DB.
})

test('UI-007/008 · isolated user enable/disable, profile/password full page roundtrip', async ({ page, backend, credentials }) => {
  test.setTimeout(240_000)
  const account = `${runId}_profile`
  const password = `Synthetic.${runId}.Original`
  const changed = `Synthetic.${runId}.Changed`
  await backend.call('/pwjbUser/create', { method: 'POST', data: { username: account, password } })
  const isolated = await page.context().browser().newContext({ baseURL: new URL(page.url()).origin })
  await isolated.addInitScript(() => localStorage.setItem('oms_lang', 'en'))
  const userPage = await isolated.newPage()
  try {
    await login(userPage, { ...credentials, admin_username: account, admin_password: password })
    const userBackend = new Backend(backend.request, backend.server, await userPage.evaluate(() => localStorage.getItem('PowerJwt')), credentials.app_id)
    const profile = await userBackend.call('/user/detail')
    await userPage.goto('/#/admin/personal')
    for (const [label, value] of [['Nick', `${runId} 测试`], ['Phone', '10000000001'], ['Email', 'changed@example.invalid'], ['Webhook', 'https://example.invalid/changed?text=%E4%B8%AD']]) await input(userPage.locator('.profile-card').first(), label, value)
    const changedProfile = await clickAndResponse(userPage, '/user/modify', () => userPage.locator('.profile-actions').getByRole('button', { name: 'Save', exact: true }).click())
    expect(changedProfile.success).toBe(true)
    await userPage.reload()
    await expect(userPage.getByLabel('Nick', { exact: true })).toHaveValue(`${runId} 测试`)
    expect(await userBackend.call('/user/detail')).toMatchObject({ nick: `${runId} 测试`, phone: '10000000001', email: 'changed@example.invalid', webHook: 'https://example.invalid/changed?text=%E4%B8%AD' })
    await userPage.getByRole('button', { name: 'Change Password', exact: true }).click()
    let dialog = selectors.dialog(userPage)
    await input(dialog, 'Old password', 'synthetic-wrong-old')
    await input(dialog, 'New Password', changed)
    await input(dialog, 'Check New Password', changed + '.mismatch')
    await dialog.getByRole('button', { name: 'Confirm', exact: true }).click()
    await expect(dialog).toBeVisible()
    await input(dialog, 'Check New Password', changed)
    const wrongOld = await clickAndResponse(userPage, '/pwjbUser/changePassword', () => dialog.getByRole('button', { name: 'Confirm', exact: true }).click())
    expect(wrongOld.success).toBe(false)
    await expect(dialog).toBeVisible()
    await input(dialog, 'Old password', password)
    const passwordResult = await clickAndResponse(userPage, '/pwjbUser/changePassword', () => dialog.getByRole('button', { name: 'Confirm', exact: true }).click())
    expect(passwordResult.success).toBe(true)
    await expect(userPage).toHaveURL(/loginHomepage|powerjobLogin/)
    await userPage.goto('/#/powerjobLogin')
    await input(userPage.locator('.login-card'), 'Username', account)
    await input(userPage.locator('.login-card'), 'Password', password)
    const oldLogin = await clickAndResponse(userPage, '/auth/thirdPartyLoginDirect', () => userPage.getByRole('button', { name: 'Login', exact: true }).click())
    expect(oldLogin.success).toBe(false)
    await input(userPage.locator('.login-card'), 'Password', changed)
    await userPage.getByRole('button', { name: 'Login', exact: true }).click()
    await expect(userPage).toHaveURL(/admin\/app/)

    await page.goto('/#/admin/user')
    await input(page.locator('main'), 'ID', profile.id)
    await page.getByRole('button', { name: 'Query', exact: true }).click()
    let row = selectors.row(page, String(profile.id))
    await row.locator('.el-switch').click()
    await expect.poll(async () => {
      const result = await backend.call('/user/query', { method: 'POST', data: { userIdEq: profile.id, index: 0, pageSize: 10 } })
      return result[0].enable
    }).toBe(false)
    await userPage.locator('.account-button').hover()
    await userPage.getByRole('menuitem', { name: 'Logout', exact: true }).click()
    await userPage.goto('/#/powerjobLogin')
    await input(userPage.locator('.login-card'), 'Username', account)
    await input(userPage.locator('.login-card'), 'Password', changed)
    const disabledLogin = await clickAndResponse(userPage, '/auth/thirdPartyLoginDirect', () => userPage.getByRole('button', { name: 'Login', exact: true }).click())
    expect(disabledLogin.success).toBe(false)
    row = selectors.row(page, String(profile.id))
    await row.locator('.el-switch').click()
    await expect.poll(async () => {
      const result = await backend.call('/user/query', { method: 'POST', data: { userIdEq: profile.id, index: 0, pageSize: 10 } })
      return result[0].enable
    }).toBe(true)
    await userPage.getByRole('button', { name: 'Login', exact: true }).click()
    await expect(userPage).toHaveURL(/admin\/app/)
  } finally { await isolated.close() }
})

test('UI-004/005/006 · page-created namespace/app full CRUD and delete cancellation', async ({ page, backend }) => {
  const code = `${runId}_admin`
  let namespaceId, appId
  try {
    await page.goto('/#/admin/namespace')
    await page.getByRole('button', { name: 'Add', exact: true }).click()
    await input(selectors.dialog(page), 'Code', code)
    await input(selectors.dialog(page), 'Name', `${code} 中文`)
    await input(selectors.dialog(page), 'Tag', 'vue3,synthetic')
    await input(selectors.dialog(page), 'Extra', 'extra 中文 &+%#')
    await saveDialog(page, '/namespace/save')
    let namespaces = await backend.call('/namespace/list', { method: 'POST', data: { codeLike: code, index: 0, pageSize: 10 } })
    expect(namespaces.data).toHaveLength(1)
    namespaceId = namespaces.data[0].id
    expect(namespaces.data[0].extra).toBe('extra 中文 &+%#')
    await input(page.locator('main'), 'Code', code)
    await page.getByRole('button', { name: 'Query', exact: true }).click()
    let row = selectors.row(page, code)
    await row.getByRole('button', { name: 'Edit', exact: true }).click()
    await expect(selectors.dialog(page).getByLabel('Code', { exact: true })).toBeDisabled()
    await input(selectors.dialog(page), 'Name', 'unsaved mutation')
    await selectors.dialog(page).getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(row).toContainText(`${code} 中文`)
    await row.getByRole('button', { name: 'Edit', exact: true }).click()
    await input(selectors.dialog(page), 'Name', `${code} edited`)
    await saveDialog(page, '/namespace/save')
    await page.reload()
    await input(page.locator('main'), 'Code', code)
    await page.getByRole('button', { name: 'Query', exact: true }).click()
    await expect(selectors.row(page, code)).toContainText(`${code} edited`)

    await page.goto('/#/admin/app')
    await page.getByRole('button', { name: 'Add', exact: true }).click()
    await choose(page, selectors.dialog(page), 'Namespace', new RegExp(code))
    await input(selectors.dialog(page), 'appName', code)
    await input(selectors.dialog(page), 'Name', `${code} title`)
    await input(selectors.dialog(page), 'Password', `Synthetic.${runId}`)
    await input(selectors.dialog(page), 'Tag', 'frontend,vue3')
    await input(selectors.dialog(page), 'Extra', 'app extra 中文 &+%#')
    await saveDialog(page, '/appInfo/save')
    const apps = await backend.call('/appInfo/list', { method: 'POST', data: { appNameLike: code, showMyRelated: false, index: 0, pageSize: 10 } })
    expect(apps.data).toHaveLength(1)
    appId = apps.data[0].id
    expect(apps.data[0].namespaceId).toBe(namespaceId)
    expect(apps.data[0].extra).toBe('app extra 中文 &+%#')
    await input(page.locator('main'), 'appName', code)
    await page.getByRole('button', { name: 'Query', exact: true }).click()
    row = selectors.row(page, code)
    await row.getByRole('button', { name: 'Edit', exact: true }).click()
    await input(selectors.dialog(page), 'Name', `${code} updated`)
    await saveDialog(page, '/appInfo/save')
    await page.reload()
    await input(page.locator('main'), 'appName', code)
    await page.getByRole('button', { name: 'Query', exact: true }).click()
    await expect(selectors.row(page, code)).toContainText(`${code} updated`)
    await selectors.row(page, code).getByRole('button', { name: 'Edit', exact: true }).click()
    await selectors.dialog(page).getByRole('button', { name: 'Delete', exact: true }).click()
    await confirmDialog(page, false)
    await expect(selectors.dialog(page)).toBeVisible()
    await selectors.dialog(page).getByRole('button', { name: 'Delete', exact: true }).click()
    const deleted = page.waitForResponse(response => response.url().includes('/appInfo/delete'))
    await confirmDialog(page)
    expect((await (await deleted).json()).success).toBe(true)
    await expect(selectors.dialog(page)).not.toBeVisible()
    appId = null
    await expect(selectors.row(page, code)).not.toBeVisible()

    await page.goto('/#/admin/namespace')
    await input(page.locator('main'), 'Code', code)
    await page.getByRole('button', { name: 'Query', exact: true }).click()
    row = selectors.row(page, code)
    await row.getByRole('button', { name: 'Delete', exact: true }).click()
    await confirmDialog(page, false)
    await expect(row).toBeVisible()
    await row.getByRole('button', { name: 'Delete', exact: true }).click()
    const nsDelete = page.waitForResponse(response => response.url().includes('/namespace/delete'))
    await confirmDialog(page)
    expect((await (await nsDelete).json()).success).toBe(true)
    namespaceId = null
    await expect(selectors.row(page, code)).not.toBeVisible()
  } finally {
    if (appId) await backend.call('/appInfo/delete?appId=' + appId, { method: 'POST', data: {}, appId })
    if (namespaceId) await backend.call('/namespace/delete?id=' + namespaceId, { method: 'DELETE', namespaceId })
  }
})

test('UI-007/008/009 · user filters, profile readback and settings safety', async ({ page, backend }) => {
  await page.goto('/#/admin/user')
  const profile = await backend.call('/user/detail')
  await input(page.locator('main'), 'ID', profile.id)
  await page.getByRole('button', { name: 'Query', exact: true }).click()
  await expect(page.locator('.el-table__body-wrapper tr')).toHaveCount(1)
  await expect(page.locator('.el-table__body-wrapper tr')).toContainText(String(profile.id))
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(page.locator('.el-table__body-wrapper tr').first()).toBeVisible()
  await page.goto('/#/admin/personal')
  await expect(page.locator('.account-label')).toContainText(String(profile.id))
  await expect(page.getByLabel('Username', { exact: true })).toBeDisabled()
  await expect(page.getByLabel('Nick', { exact: true })).toHaveValue(profile.nick || '')
  await page.goto('/#/admin/settings')
  const prior = await backend.call('/auth/listGlobalAdmin')
  await expect(page.locator('.el-select__selected-item').first()).toBeVisible()
  const saved = await clickAndResponse(page, '/auth/saveGlobalAdmin', () => page.getByRole('button', { name: 'Save', exact: true }).click())
  expect(saved.success).toBe(true)
  expect(await backend.call('/auth/listGlobalAdmin')).toEqual(prior)
  await page.reload()
  await expect(page.locator('.el-select__selected-item').first()).toBeVisible()
})
