import { test, expect, Backend, selectors, runId, input, choose, formItem, login, secretFill, saveDialog, confirmDialog } from './support.js'

// Live Chrome + released Server acceptance. API calls only create isolated fixtures,
// independently read back page actions, and restore those owned fixture resources.
const prefix = `${runId}_adminext`
const roles = ['observer', 'qa', 'developer', 'admin']

async function clickAndResponse(page, pathPart, action) {
  const initiated = new Set()
  const capture = req => { if (req.url().split('?')[0].endsWith(pathPart) && req.method() !== 'OPTIONS') initiated.add(req) }
  page.on('request', capture)
  try {
    const response = page.waitForResponse(res => initiated.has(res.request()))
    const [received] = await Promise.all([response, action()])
    const body = JSON.parse(await received.text())
    if (pathPart === '/job/list') { body.requestAppId = received.request().headers().appid; body.requestBodyAppId = received.request().postDataJSON().appId }
    return body
  } finally { page.off('request', capture) }
}

const secondaryErrors = []
test.beforeEach(async ({ page }, info) => { info.evidencePage = page; secondaryErrors.length = 0 })
test.afterEach(async () => { expect(secondaryErrors.flat(), 'No uncaught errors in secondary profile').toEqual([]) })
const emptyRoles = () => Object.fromEntries(roles.map(role => [role, []]))
async function evidence(info, caseId, variantId, steps, readback) {
  if (info.evidencePage && !info.evidencePage.isClosed()) {
    const filename = info.outputPath(`${caseId}-${variantId}-redacted.png`)
    await info.evidencePage.screenshot({ path: filename, fullPage: true, mask: [info.evidencePage.locator('input[type=\"password\"]'), info.evidencePage.locator('input[autocomplete=\"username\"]'), info.evidencePage.locator('input[autocomplete=\"new-password\"]'), info.evidencePage.locator('input[disabled]')] })
    await info.attach(`page-${caseId}-${variantId}`, { path: filename, contentType: 'image/png' })
  }
  await info.attach(`${variantId.endsWith('-detail') ? 'context' : 'variant'}-${caseId}-${variantId}`, { body: Buffer.from(JSON.stringify({ caseId, variantId, steps, readback })), contentType: 'application/json' })
}
async function logout(page) {
  await page.locator('.account-button').hover()
  await page.getByRole('menuitem', { name: 'Logout', exact: true }).click()
  await expect(page).toHaveURL(/loginHomepage/)
}
async function contextFor(page) {
  const context = await page.context().browser().newContext({ baseURL: new URL(page.url()).origin })
  await context.addInitScript(() => { if (/^https?:$/.test(location.protocol)) localStorage.setItem('oms_lang', 'en') })
  const errors = []
  context.on('page', opened => opened.on('pageerror', error => errors.push(error.message)))
  secondaryErrors.push(errors)
  return context
}
async function userFixture(backend, suffix) {
  const username = `${prefix}_${suffix}`
  const password = `Synthetic.${username}.Original`
  await backend.call('/pwjbUser/create', { method: 'POST', data: { username, password } })
  const auth = await backend.call('/auth/thirdPartyLoginDirect', { method: 'POST', data: { loginType: 'PWJB', originParams: JSON.stringify({ username, password, encryption: 'none' }) } })
  const own = new Backend(backend.request, backend.server, auth.jwtToken, backend.appId)
  const detail = await own.call('/user/detail')
  const nick = `${prefix}_${suffix}_nick`
  await own.call('/user/modify', { method: 'POST', data: { id: detail.id, nick, phone: `100${String(detail.id).slice(-8).padStart(8, '0')}`, email: `${suffix}@example.invalid`, webHook: 'https://example.invalid/fixture' } })
  return { ...(await own.call('/user/detail')), username, password, nick, id: detail.id, own }
}
async function ownLogin(page, credentials, user) {
  await page.goto('/#/powerjobLogin')
  await secretFill(page.getByLabel('Username', { exact: true }), user.username)
  await secretFill(page.getByLabel('Password', { exact: true }), user.password)
  await page.getByRole('button', { name: 'Login', exact: true }).click()
  await expect(page).toHaveURL(/admin\/app/)
  await expect(page.locator('.el-table')).toBeVisible()
}
async function roleSelect(page, dialog, role, nick) {
  const field = dialog.locator('.role-field').filter({ has: dialog.page().locator('label', { hasText: new RegExp(`^${role}$`, 'i') }) })
  await field.locator('.el-select').click()
  await field.locator('input').fill(nick)
  await page.locator('.el-select-dropdown:visible .el-select-dropdown__item:visible').filter({ hasText: nick }).click()
  await dialog.locator('.el-dialog__header').click()
}
async function query(page, endpoint, fields) {
  for (const [label, value] of fields) await input(page.locator('.filter-panel'), label, value)
  return clickAndResponse(page, endpoint, () => page.getByRole('button', { name: 'Query', exact: true }).click())
}
async function namespaceViaPage(page, backend, code, users = {}) {
  await page.goto('/#/admin/namespace')
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  const dialog = selectors.dialog(page)
  for (const [label, value] of [['Code', code], ['Name', `${code} 中文`], ['Tag', `${prefix}-tag`], ['Extra', 'extra 中文 &+%#']]) await input(dialog, label, value)
  for (const [role, user] of Object.entries(users)) await roleSelect(page, dialog, role, user.nick)
  await saveDialog(page, '/namespace/save')
  const result = await backend.call('/namespace/list', { method: 'POST', data: { codeLike: code, index: 0, pageSize: 100 } })
  const value = result.data.find(item => item.code === code)
  expect(value).toBeDefined()
  return value
}
async function appViaPage(page, backend, ns, name, users = {}) {
  await page.goto('/#/admin/app')
  await page.getByRole('button', { name: 'Add', exact: true }).click()
  const dialog = selectors.dialog(page)
  await choose(page, dialog, 'Namespace', new RegExp(ns.code))
  for (const [label, value] of [['appName', name], ['Name', `${name} title`], ['Password', `Synthetic.${name}`], ['Tag', `${prefix}-tag`], ['Extra', 'app extra 中文 &+%#']]) await input(dialog, label, value)
  for (const [role, user] of Object.entries(users)) await roleSelect(page, dialog, role, user.nick)
  await saveDialog(page, '/appInfo/save')
  const result = await backend.call('/appInfo/list', { method: 'POST', data: { appNameLike: name, showMyRelated: false, index: 0, pageSize: 100 } })
  const value = result.data.find(item => item.appName === name)
  expect(value).toBeDefined()
  return value
}
async function cleanupApp(backend, id) { if (id != null) await backend.call('/appInfo/delete?appId=' + encodeURIComponent(id), { method: 'POST', data: {}, appId: id }) }
async function cleanupNamespace(backend, id) { if (id != null) await backend.call('/namespace/delete?id=' + encodeURIComponent(id), { method: 'DELETE', namespaceId: id }) }

test('adminext auth · required-field combinations, password masks and registration error recovery', async ({ page, credentials, request }, info) => {
  test.setTimeout(180_000)
  const typesRequest = page.waitForResponse(response => response.url().endsWith('/auth/supportLoginTypes'))
  await page.goto('/#/')
  const typesResponse = await typesRequest
  const server = credentials.server_urls[0]
  const publicBackend = new Backend(request, server, '', null)
  const types = await publicBackend.call('/auth/supportLoginTypes')
  for (const type of types) await expect(page.getByRole('button', { name: type.name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: /PWJB|PowerJob/i }).first().click()
  await expect(page).toHaveURL(/powerjobLogin/)
  await evidence(info, 'UI-001', 'fresh-supported-types', ['fresh profile root; compare every supported Server type; choose PWJB'], { typeNames: types.map(type => type.name), selected: 'PWJB', liveResponse: Boolean(typesResponse) })
  let requests = 0
  page.on('request', req => { if (req.url().includes('/auth/thirdPartyLoginDirect')) requests++ })
  for (const [username, password] of [['', ''], ['', 'synthetic'], ['synthetic', '']]) {
    await input(page.locator('.login-card'), 'Username', username)
    await input(page.locator('.login-card'), 'Password', password)
    await page.getByRole('button', { name: 'Login', exact: true }).click()
    await expect(page.locator('.el-form-item__error').first()).toBeVisible()
  }
  expect(requests).toBe(0)
  await evidence(info, 'UI-001', 'empty-fields', ['submit both empty, username empty, password empty'], { directRequests: requests, route: 'powerjobLogin' })
  const loginPassword = page.getByLabel('Password', { exact: true })
  await loginPassword.fill('SyntheticMaskOnly')
  await expect(loginPassword).toHaveAttribute('type', 'password')
  await formItem(page.locator('.login-card'), 'Password').locator('.el-input__password').click()
  await expect(loginPassword).toHaveAttribute('type', 'text')
  await expect(loginPassword).toHaveValue('SyntheticMaskOnly')
  await page.getByRole('button', { name: 'User Registration', exact: true }).click()
  let dialog = selectors.dialog(page)
  for (const fields of [{}, { username: `${prefix}_missing` }, { password: 'SyntheticRequired', password2: 'SyntheticRequired' }]) {
    await input(dialog, 'Username', fields.username || '')
    await input(dialog, 'New Password', fields.password || '')
    await input(dialog, 'Check New Password', fields.password2 || '')
    await dialog.getByRole('button', { name: 'Register', exact: true }).click()
    await expect(dialog.locator('.el-form-item__error').first()).toBeVisible()
  }
  await evidence(info, 'UI-002', 'missing-required', ['registration empty, missing password, missing username'], { notCreated: true })
  const registerPassword = dialog.getByLabel('New Password', { exact: true })
  await registerPassword.fill('SyntheticMaskOnly')
  await expect(registerPassword).toHaveAttribute('type', 'password')
  await formItem(dialog, 'New Password').locator('.el-input__password').click()
  await expect(registerPassword).toHaveAttribute('type', 'text')
  await expect(registerPassword).toHaveValue('SyntheticMaskOnly')
  await evidence(info, 'UI-002', 'password-mask', ['login and register passwords masked; show-password preserves values'], { login: 'text', registration: 'text', valuePreserved: true })
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'User Registration', exact: true }).click()
  dialog = selectors.dialog(page)
  await expect(dialog.getByLabel('Username', { exact: true })).toHaveValue('')
  await expect(dialog.getByLabel('New Password', { exact: true })).toHaveValue('')
  await evidence(info, 'UI-002', 'register-cancel', ['fill then cancel and reopen'], { freshUsername: true, clearedPassword: true })
  await input(dialog, 'Username', credentials.admin_username)
  await input(dialog, 'Nick', `${prefix}_recover`)
  await input(dialog, 'New Password', 'SyntheticRecovery')
  await input(dialog, 'Check New Password', 'SyntheticRecovery')
  const duplicate = await clickAndResponse(page, '/pwjbUser/create', () => dialog.getByRole('button', { name: 'Register', exact: true }).click())
  expect(duplicate.success).toBe(false)
  await expect(dialog.getByLabel('Nick', { exact: true })).toHaveValue(`${prefix}_recover`)
  await expect(dialog).toBeVisible()
  await input(dialog, 'Username', `${prefix}_recover`)
  const recovery = await clickAndResponse(page, '/pwjbUser/create', () => dialog.getByRole('button', { name: 'Register', exact: true }).click())
  expect(recovery.success).toBe(true)
  await expect(dialog).not.toBeVisible()
  await login(page, { ...credentials, admin_username: `${prefix}_recover`, admin_password: 'SyntheticRecovery' })
  await page.goto('/#/admin/personal')
  await expect(page.getByLabel('Nick', { exact: true })).toHaveValue(`${prefix}_recover`)
  await evidence(info, 'UI-002', 'register-error-draft', ['duplicate failure preserves nickname; correct username; register; normal login; profile readback'], { recovered: true, nick: `${prefix}_recover` })
})

test('adminext user · ID/nickname/phone axes and 11-user pagination reset', async ({ page, backend }, info) => {
  test.setTimeout(240_000)
  const users = []
  for (let i = 0; i < 11; i++) users.push(await userFixture(backend, `page${i}`))
  await page.goto('/#/admin/user')
  for (const [label, value, field] of [['ID', users[0].id, 'userIdEq'], ['Nick', users[0].nick, 'nickLike'], ['Phone', users[0].phone, 'phoneLike']]) {
    await page.getByRole('button', { name: 'Reset', exact: true }).click()
    const result = await query(page, '/user/query', [[label, value]])
    expect(result.success).toBe(true)
    expect(result.data.map(user => String(user.id))).toEqual([String(users[0].id)])
    await expect(selectors.row(page, String(users[0].id))).toBeVisible()
    expect(Array.isArray(await backend.call('/user/query', { method: 'POST', data: { [field]: value } }))).toBe(true)
  }
  await evidence(info, 'UI-007', 'user-id-nick-phone', ['independent ID, nick and phone queries against controlled profile'], { id: users[0].id, responseShape: 'Array' })
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  const result = await query(page, '/user/query', [['Nick', `${prefix}_page`]])
  expect(result.data).toHaveLength(11)
  await expect(page.locator('.el-table__body-wrapper tr')).toHaveCount(10)
  const firstIds = await page.locator('.el-table__body-wrapper tr td:first-child').allTextContents()
  await page.locator('.el-pagination .btn-next').click()
  await expect(page.locator('.el-table__body-wrapper tr')).toHaveCount(1)
  const secondId = await page.locator('.el-table__body-wrapper tr td:first-child').textContent()
  expect(firstIds).not.toContain(secondId)
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(page.locator('.el-pager .is-active')).toHaveText('1')
  await expect(page.getByLabel('Nick', { exact: true })).toHaveValue('')
  await evidence(info, 'UI-007', 'user-pagination-reset', ['11 fixture profiles; page1 ten; page2 one distinct; reset filters/page'], { firstPageCount: 10, secondPageCount: 1, resetPage: 1, serverResponse: 'Array no new pagination request fields' })
})

test('adminext namespace/app · all fields, filter axes, cancel isolation and occupied deletion failure', async ({ page, backend }, info) => {
  test.setTimeout(240_000)
  const users = Object.fromEntries(await Promise.all(roles.map(async role => [role, await userFixture(backend, `ns${role}`)])))
  let ns, app, second
  try {
    ns = await namespaceViaPage(page, backend, `${prefix}_metadata`, users)
    expect(ns).toMatchObject({ name: `${ns.code} 中文`, tags: `${prefix}-tag`, extra: 'extra 中文 &+%#' })
    for (const role of roles) expect(ns.componentUserRoleInfo[role].map(String)).toContain(String(users[role].id))
    await evidence(info, 'UI-006', 'create-all-fields', ['page create namespace all editable fields and all four roles; independent readback'], { id: ns.id, roles: Object.fromEntries(roles.map(role => [role, ns.componentUserRoleInfo[role]])), fieldsPreserved: true })
    for (const [label, value] of [['Code', ns.code], ['Name', `${ns.code} 中文`], ['Tag', `${prefix}-tag`]]) {
      await page.getByRole('button', { name: 'Reset', exact: true }).click()
      const response = await query(page, '/namespace/list', [[label, value]])
      expect(response.data.data.map(item => String(item.id))).toContain(String(ns.id))
      await expect(selectors.row(page, ns.code)).toBeVisible()
    }
    await page.getByRole('button', { name: 'Reset', exact: true }).click()
    for (const label of ['Code', 'Name', 'Tag']) await expect(formItem(page.locator('.filter-panel'), label).locator('input')).toHaveValue('')
    await evidence(info, 'UI-006', 'filters-reset', ['code/name/tag query independently then reset all'], { allAxesFound: true, resetFiltersEmpty: true })
    await query(page, '/namespace/list', [['Code', ns.code]])
    await selectors.row(page, ns.code).getByRole('button', { name: 'Edit', exact: true }).click()
    let dialog = selectors.dialog(page)
    await expect(dialog.getByLabel('Code', { exact: true })).toBeDisabled()
    await expect(dialog.getByLabel('Token', { exact: true })).toBeDisabled()
    for (const [label, value] of [['Name', `${ns.code} edited`], ['Tag', `${prefix}-edited`], ['Extra', 'edited 中文 &+%#']]) await input(dialog, label, value)
    await roleSelect(page, dialog, 'observer', users.observer.nick)
    await saveDialog(page, '/namespace/save')
    await page.reload()
    await query(page, '/namespace/list', [['Code', ns.code]])
    await selectors.row(page, ns.code).getByRole('button', { name: 'Edit', exact: true }).click()
    dialog = selectors.dialog(page)
    await expect(dialog.getByLabel('Name', { exact: true })).toHaveValue(`${ns.code} edited`)
    await expect(dialog.getByLabel('Token', { exact: true })).toHaveValue(ns.token || '')
    const savedNS = (await backend.call('/namespace/list', { method: 'POST', data: { codeLike: ns.code, index: 0, pageSize: 10 } })).data[0]
    expect(savedNS).toMatchObject({ code: ns.code, token: ns.token, tags: `${prefix}-edited`, extra: 'edited 中文 &+%#' })
    expect(savedNS.componentUserRoleInfo.observer.map(String)).not.toContain(String(users.observer.id))
    await evidence(info, 'UI-006', 'edit-roundtrip', ['edit name/tags/extra/remove observer; save reload reopen; immutable code/token readback'], { id: ns.id, immutableFieldsPreserved: true, observerRemoved: true })
    await input(dialog, 'Name', 'UNSAVED')
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(selectors.row(page, ns.code)).toContainText(`${ns.code} edited`)
    await page.getByRole('button', { name: 'Add', exact: true }).click()
    dialog = selectors.dialog(page)
    await expect(dialog.getByLabel('Code', { exact: true })).toHaveValue('')
    await expect(dialog.getByLabel('Code', { exact: true })).toBeEnabled()
    await expect(dialog.locator('.el-select__selected-item .el-tag')).toHaveCount(0)
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await evidence(info, 'UI-006', 'cancel-isolation', ['mutate edit then cancel; fresh Add blank mutable code/roles'], { oldNamePreserved: true, newCodeBlank: true, newRolesEmpty: true })
    app = await appViaPage(page, backend, ns, `${prefix}_metadata_app`)
    expect(app).toMatchObject({ namespaceId: ns.id, title: `${app.appName} title`, password: `Synthetic.${app.appName}`, tags: `${prefix}-tag`, extra: 'app extra 中文 &+%#' })
    await evidence(info, 'UI-004', 'create-all-fields', ['page create app namespace/appName/title/password/tags/extra and empty roles; independent readback'], { id: app.id, allFieldsPreserved: true, roles: app.componentUserRoleInfo })
    for (const [label, value] of [['appName', app.appName], ['Tag', `${prefix}-tag`]]) {
      await page.getByRole('button', { name: 'Reset', exact: true }).click()
      const response = await query(page, '/appInfo/list', [[label, value]])
      expect(response.data.data.map(item => String(item.id))).toContain(String(app.id))
    }
    await page.getByRole('button', { name: 'Reset', exact: true }).click()
    await choose(page, page.locator('.filter-panel'), 'Namespace', new RegExp(ns.code))
    const namespaceFiltered = await query(page, '/appInfo/list', [])
    expect(namespaceFiltered.data.data.map(item => String(item.id))).toEqual([String(app.id)])
    await evidence(info, 'UI-004', 'filter-code-tag-namespace', ['independent appName/tag/namespace axes; Server and table compare'], { appId: app.id, namespaceId: ns.id, axes: 3 })
    await evidence(info, 'UI-006', 'namespace-app-filter', ['namespace fields/roles edited; app created selecting updated namespace; namespace filter returns exact owned app'], { namespaceId: ns.id, selectedAppId: app.id, filteredOnlyOwnedApp: true })
    await page.getByRole('button', { name: 'Reset', exact: true }).click()
    const idResult = await query(page, '/appInfo/list', [['ID', app.id]])
    expect(idResult.data.data.map(item => String(item.id))).toEqual([String(app.id)])
    await page.getByRole('button', { name: 'Reset', exact: true }).click()
    await expect(page.getByLabel('ID', { exact: true })).toHaveValue('')
    await expect(formItem(page.locator('.filter-panel'), 'ShowMyRelated').locator('.el-switch')).toHaveClass(/is-checked/)
    await evidence(info, 'UI-004', 'filter-id', ['exact ID query then reset restores my related'], { exactId: app.id, resetMyRelated: true })
    await query(page, '/appInfo/list', [['appName', app.appName]])
    await selectors.row(page, app.appName).getByRole('button', { name: 'Edit', exact: true }).click()
    dialog = selectors.dialog(page)
    await input(dialog, 'Name', 'UNSAVED')
    await input(dialog, 'Tag', 'UNSAVED')
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    expect((await backend.call('/appInfo/list', { method: 'POST', data: { appId: app.id, showMyRelated: false, index: 0, pageSize: 10 } })).data[0].title).toBe(app.title)
    await page.reload()
    await query(page, '/appInfo/list', [['ID', app.id]])
    await expect(selectors.row(page, app.appName)).toContainText(app.appName)
    await evidence(info, 'UI-004', 'edit-cancel', ['edit title/tags cancel; backend readback and hard refresh'], { originalTitle: app.title, originalTags: app.tags })
    await selectors.row(page, app.appName).getByRole('button', { name: 'Edit', exact: true }).click()
    dialog = selectors.dialog(page)
    for (const [label, value] of [['Name', `${prefix} edited app`], ['Tag', `${prefix}-edited`], ['Extra', 'edited app 中文 &+%#']]) await input(dialog, label, value)
    await saveDialog(page, '/appInfo/save')
    await page.reload()
    await query(page, '/appInfo/list', [['ID', app.id]])
    await selectors.row(page, app.appName).getByRole('button', { name: 'Edit', exact: true }).click()
    dialog = selectors.dialog(page)
    await expect(dialog.getByLabel('Name', { exact: true })).toHaveValue(`${prefix} edited app`)
    await expect(dialog.getByLabel('Extra', { exact: true })).toHaveValue('edited app 中文 &+%#')
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await evidence(info, 'UI-004', 'edit-save-reopen', ['save title/tag/extra; hard refresh; reopen exact fields'], { unchangedAppName: app.appName, unchangedNamespaceId: ns.id })
    second = await appViaPage(page, backend, ns, `${prefix}_metadata_second`)
    expect(String(second.id)).not.toBe(String(app.id))
    await evidence(info, 'UI-004', 'edit-then-create', ['after edit create another page app; independent distinct IDs'], { originalId: app.id, newId: second.id, originalPreserved: true })
    await page.getByRole('button', { name: 'Add', exact: true }).click()
    dialog = selectors.dialog(page)
    await choose(page, dialog, 'Namespace', new RegExp(ns.code))
    await input(dialog, 'appName', second.appName)
    await input(dialog, 'Password', 'SyntheticDuplicate')
    const duplicate = await clickAndResponse(page, '/appInfo/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click())
    expect(duplicate.success).toBe(false)
    await expect(dialog).toBeVisible()
    await expect(dialog.getByLabel('appName', { exact: true })).toHaveValue(second.appName)
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await evidence(info, 'UI-004', 'duplicate-create', ['duplicate page create gets business error; draft remains; independent one object'], { appId: second.id, success: false })
    await page.goto('/#/admin/namespace')
    await query(page, '/namespace/list', [['Code', ns.code]])
    await selectors.row(page, ns.code).getByRole('button', { name: 'Delete', exact: true }).click()
    const failed = await clickAndResponse(page, '/namespace/delete', () => confirmDialog(page))
    expect(failed.success).toBe(false)
    await expect(selectors.row(page, ns.code)).toBeVisible()
    expect((await backend.call('/appInfo/list', { method: 'POST', data: { appId: app.id, showMyRelated: false, index: 0, pageSize: 10 } })).data).toHaveLength(1)
    await evidence(info, 'UI-006', 'delete-occupied', ['confirm occupied namespace deletion; actual business refusal; namespace row and app remain'], { namespaceId: ns.id, appId: app.id, success: false })
  } finally { await cleanupApp(backend, second?.id); await cleanupApp(backend, app?.id); await cleanupNamespace(backend, ns?.id) }
})

test('adminext pagination · application 0/1/10/11 and namespace 11 distinct records', async ({ page, backend }, info) => {
  test.setTimeout(240_000)
  const namespaces = [], apps = []
  try {
    for (let i = 0; i < 11; i++) namespaces.push(await backend.call('/namespace/save', { method: 'POST', data: { code: `${prefix}_paging${i}`, name: `${prefix}_paging${i}`, tags: `${prefix}_paging`, componentUserRoleInfo: emptyRoles() } }))
    const nsRows = (await backend.call('/namespace/list', { method: 'POST', data: { codeLike: `${prefix}_paging`, index: 0, pageSize: 100 } })).data
    expect(nsRows).toHaveLength(11)
    for (let i = 0; i < 11; i++) apps.push(await backend.call('/appInfo/save', { method: 'POST', data: { namespaceId: nsRows[0].id, appName: `${prefix}_paging${i}`, password: 'SyntheticPaging', tags: `${prefix}_paging`, componentUserRoleInfo: emptyRoles() } }))
    const appRows = (await backend.call('/appInfo/list', { method: 'POST', data: { appNameLike: `${prefix}_paging`, showMyRelated: false, index: 0, pageSize: 100 } })).data
    expect(appRows).toHaveLength(11)
    await page.goto('/#/admin/namespace')
    const first = await query(page, '/namespace/list', [['Code', `${prefix}_paging`]])
    expect(first.data.index || 0).toBe(0)
    await expect(page.locator('.el-table__body-wrapper tr')).toHaveCount(10)
    const firstIds = await page.locator('.el-table__body-wrapper tr td:first-child').allTextContents()
    const next = await clickAndResponse(page, '/namespace/list', () => page.locator('.el-pagination .btn-next').click())
    expect(next.data.data).toHaveLength(1)
    expect(firstIds).not.toContain(String(next.data.data[0].id))
    await expect(page.locator('.el-pager .is-active')).toHaveText('2')
    await evidence(info, 'UI-006', 'pagination', ['11 isolated namespace fixtures; page1 10; page2 1; IDs distinct'], { firstPageCount: 10, secondPageCount: 1, firstIndex: 0, secondIndex: 1 })
    await page.goto('/#/admin/app')
    await query(page, '/appInfo/list', [['appName', `${prefix}_paging`]])
    await expect(page.locator('.el-table__body-wrapper tr')).toHaveCount(10)
    const firstAppIds = await page.locator('.el-table__body-wrapper tr td:first-child').allTextContents()
    const nextApps = await clickAndResponse(page, '/appInfo/list', () => page.locator('.el-pagination .btn-next').click())
    expect(nextApps.data.data).toHaveLength(1)
    expect(firstAppIds).not.toContain(String(nextApps.data.data[0].id))
    const switchItem = formItem(page.locator('.filter-panel'), 'ShowMyRelated').locator('.el-switch')
    const toggled = await clickAndResponse(page, '/appInfo/list', () => switchItem.click())
    expect(toggled.data.data).toHaveLength(10)
    await expect(page.locator('.el-pager .is-active')).toHaveText('1')
    await evidence(info, 'UI-004', 'my-related-toggle', ['page2 then toggle related off; request/list/page reset; toggle back'], { initialIndex: 1, toggleIndex: 0, showMyRelated: false })
    await clickAndResponse(page, '/appInfo/list', () => switchItem.click())
    await query(page, '/appInfo/list', [['appName', `${prefix}_no_matching_resource`]])
    await expect(page.locator('.el-table__empty-block')).toBeVisible()
    await query(page, '/appInfo/list', [['appName', `${prefix}_paging10`]])
    await expect(page.locator('.el-table__body-wrapper tr')).toHaveCount(1)
    await evidence(info, 'UI-004', 'pagination-boundary', ['11 fixtures page1 10/page2 1 distinct; query0/query1 resets stale page'], { total: 11, firstPage: 10, secondPage: 1, zero: 0, one: 1 })
  } finally {
    const ownedApps = (await backend.call('/appInfo/list', { method: 'POST', data: { appNameLike: `${prefix}_paging`, showMyRelated: false, index: 0, pageSize: 100 } })).data
    for (const app of ownedApps) await cleanupApp(backend, app.id)
    const ownedNamespaces = (await backend.call('/namespace/list', { method: 'POST', data: { codeLike: `${prefix}_paging`, index: 0, pageSize: 100 } })).data
    for (const ns of ownedNamespaces) await cleanupNamespace(backend, ns.id)
  }
})

test('adminext profile · password cancellation, wrong old/mismatch, successful change and restoration', async ({ page, backend, credentials }, info) => {
  test.setTimeout(240_000)
  const user = await userFixture(backend, 'password')
  const context = await contextFor(page), ownPage = await context.newPage()
  info.evidencePage = ownPage
  const changed = `${user.password}.Changed`
  try {
    await ownLogin(ownPage, credentials, user)
    await ownPage.goto('/#/admin/personal')
    for (const label of ['Username', 'Original username', 'Account type', 'Global roles']) await expect(ownPage.getByLabel(label, { exact: true })).toBeDisabled()
    for (const [label, value] of [['Nick', `${prefix} 修改中文`], ['Phone', '10099999999'], ['Email', 'modified@example.invalid'], ['Webhook', 'https://example.invalid/modified?text=%E4%B8%AD&x=+%25']]) await input(ownPage.locator('.profile-card').first(), label, value)
    const saved = await clickAndResponse(ownPage, '/user/modify', () => ownPage.locator('.profile-actions').getByRole('button', { name: 'Save', exact: true }).click())
    expect(saved.success).toBe(true)
    await ownPage.reload()
    await expect(ownPage.getByLabel('Nick', { exact: true })).toHaveValue(`${prefix} 修改中文`)
    const read = await user.own.call('/user/detail')
    expect(read).toMatchObject({ nick: `${prefix} 修改中文`, phone: '10099999999', email: 'modified@example.invalid', webHook: 'https://example.invalid/modified?text=%E4%B8%AD&x=+%25' })
    await evidence(info, 'UI-008', 'profile-all-fields', ['normal synthetic login; readonly identity fields; edit all profile fields; save reload independent readback'], { id: user.id, allFieldsPreserved: true, identityReadonly: true })
    let writes = 0
    ownPage.on('request', req => { if (req.url().includes('/pwjbUser/changePassword')) writes++ })
    await ownPage.getByRole('button', { name: 'Change Password', exact: true }).click()
    let dialog = selectors.dialog(ownPage)
    for (const [label, value] of [['Old password', user.password], ['New Password', changed], ['Check New Password', changed]]) await input(dialog, label, value)
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await ownPage.getByRole('button', { name: 'Change Password', exact: true }).click()
    dialog = selectors.dialog(ownPage)
    for (const label of ['Old password', 'New Password', 'Check New Password']) await expect(dialog.getByLabel(label, { exact: true })).toHaveValue('')
    expect(writes).toBe(0)
    await evidence(info, 'UI-008', 'password-cancel', ['fill all passwords cancel reopen; each secret blank; zero request'], { writes })
    for (const [label, value] of [['Old password', user.password], ['New Password', changed], ['Check New Password', `${changed}.mismatch`]]) await input(dialog, label, value)
    await dialog.getByRole('button', { name: 'Confirm', exact: true }).click()
    await expect(dialog).toBeVisible()
    expect(writes).toBe(0)
    await evidence(info, 'UI-008', 'password-mismatch', ['different new passwords Confirm; remains dialog; zero write'], { writes })
    await input(dialog, 'Old password', 'synthetic-wrong-old')
    await input(dialog, 'Check New Password', changed)
    const wrong = await clickAndResponse(ownPage, '/pwjbUser/changePassword', () => dialog.getByRole('button', { name: 'Confirm', exact: true }).click())
    expect(wrong.success).toBe(false)
    await expect(dialog).toBeVisible()
    const oldStill = await backend.call('/auth/thirdPartyLoginDirect', { method: 'POST', data: { loginType: 'PWJB', originParams: JSON.stringify({ username: user.originUsername, password: user.password, encryption: 'none' }) }, allowFailure: true })
    expect(oldStill.success).toBe(true)
    await evidence(info, 'UI-008', 'password-wrong-old', ['wrong old Confirm gets actual business failure; original credential remains valid'], { success: false, originalPasswordStillValid: true })
    await input(dialog, 'Old password', user.password)
    const success = await clickAndResponse(ownPage, '/pwjbUser/changePassword', () => dialog.getByRole('button', { name: 'Confirm', exact: true }).click())
    expect(success.success).toBe(true)
    await expect(ownPage).toHaveURL(/loginHomepage|powerjobLogin/)
    await ownPage.goto('/#/powerjobLogin')
    await input(ownPage.locator('.login-card'), 'Username', user.originUsername)
    await secretFill(ownPage.getByLabel('Password', { exact: true }), user.password)
    const failed = await clickAndResponse(ownPage, '/auth/thirdPartyLoginDirect', () => ownPage.getByRole('button', { name: 'Login', exact: true }).click())
    expect(failed.success).toBe(false)
    await secretFill(ownPage.getByLabel('Password', { exact: true }), changed)
    await ownPage.getByRole('button', { name: 'Login', exact: true }).click()
    await expect(ownPage).toHaveURL(/admin\/app/)
    await ownPage.goto('/#/admin/personal')
    await ownPage.getByRole('button', { name: 'Change Password', exact: true }).click()
    dialog = selectors.dialog(ownPage)
    for (const [label, value] of [['Old password', changed], ['New Password', user.password], ['Check New Password', user.password]]) await input(dialog, label, value)
    const restored = await clickAndResponse(ownPage, '/pwjbUser/changePassword', () => dialog.getByRole('button', { name: 'Confirm', exact: true }).click())
    expect(restored.success).toBe(true)
    await ownLogin(ownPage, credentials, { ...user, username: user.originUsername })
    await evidence(info, 'UI-008', 'password-success', ['change success; old normal login refuses; new normal login succeeds; restore via page; original normal login succeeds'], { oldRefused: true, newAccepted: true, originalRestored: true })
  } finally { await context.close() }
})

test('adminext settings · actual add/remove, empty rejection, revoked toggle rollback and recovery', async ({ page, backend, credentials }, info) => {
  test.setTimeout(240_000)
  const operator = await userFixture(backend, 'operator'), target = await userFixture(backend, 'toggle_target')
  const original = await backend.call('/auth/listGlobalAdmin')
  expect(original.length).toBeGreaterThan(0)
  const context = await contextFor(page), operatorPage = await context.newPage()
  const readAdmins = async () => (await backend.call('/auth/listGlobalAdmin')).map(String).sort()
  const setUI = async (user, select = true) => {
    const selectBox = page.locator('.settings-card .el-select')
    await selectBox.click()
    await selectBox.locator('input').fill(user.nick)
    const option = page.locator('.el-select-dropdown:visible .el-select-dropdown__item:visible').filter({ hasText: user.nick })
    if (select) await expect(option).not.toHaveClass(/is-selected/)
    else await expect(option).toHaveClass(/is-selected/)
    await option.click()
    await page.locator('.card-heading').click()
    const result = await clickAndResponse(page, '/auth/saveGlobalAdmin', () => page.getByRole('button', { name: 'Save', exact: true }).click())
    expect(result.success).toBe(true)
  }
  try {
    await page.goto('/#/admin/settings')
    await setUI(operator)
    await page.reload()
    expect(await readAdmins()).toEqual([...original.map(String), String(operator.id)].sort())
    await ownLogin(operatorPage, credentials, operator)
    await operatorPage.goto('/#/admin/settings')
    await expect(operatorPage.getByRole('button', { name: 'Save', exact: true })).toBeEnabled()
    const ownAdmins = await operator.own.call('/auth/listGlobalAdmin')
    expect(ownAdmins.map(String)).toContain(String(operator.id))
    await evidence(info, 'UI-009', 'add-admin', ['rescue membership retained; add unique operator through page; reload; operator normal login/settings'], { originalRetained: true, addedId: operator.id, canReadAdminList: true })
    await operatorPage.goto('/#/admin/user')
    await query(operatorPage, '/user/query', [['ID', target.id]])
    const row = selectors.row(operatorPage, String(target.id))
    await expect(row.locator('.el-switch')).toHaveClass(/is-checked/)
    await setUI(operator, false)
    expect(await readAdmins()).toEqual(original.map(String).sort())
    const refused = await clickAndResponse(operatorPage, '/user/disable', () => row.locator('.el-switch').click())
    expect(refused.success).toBe(false)
    await expect(row.locator('.el-switch')).toHaveClass(/is-checked/)
    expect((await backend.call('/user/query', { method: 'POST', data: { userIdEq: target.id } }))[0].enable).toBe(true)
    await expect(operatorPage.locator('.el-message').last()).toBeVisible()
    await evidence(info, 'UI-003', 'revoked-role', ['second rescue administrator revokes original operator role; stale real page status action refuses'], { noFakeSuccess: true, targetStillEnabled: true })
    await operatorPage.reload()
    await expect(operatorPage.locator('.el-table__empty-block')).toBeVisible()
    await evidence(info, 'UI-007', 'permission-error-toggle', ['non-global-admin stale control refuses and switch restores; hard refresh has no sensitive list'], { targetEnabled: true, emptyDeniedList: true })
    await page.reload()
    await setUI(operator)
    await operatorPage.reload()
    await query(operatorPage, '/user/query', [['ID', target.id]])
    let recoveredRow = selectors.row(operatorPage, String(target.id))
    const disabled = await clickAndResponse(operatorPage, '/user/disable', () => recoveredRow.locator('.el-switch').click())
    expect(disabled.success).toBe(true)
    await expect(recoveredRow.locator('.el-switch')).not.toHaveClass(/is-checked/)
    const enabled = await clickAndResponse(operatorPage, '/user/enable', () => recoveredRow.locator('.el-switch').click())
    expect(enabled.success).toBe(true)
    await expect(recoveredRow.locator('.el-switch')).toHaveClass(/is-checked/)
    await evidence(info, 'UI-007', 'status-error-recovery', ['previous actual denied mutation; restore operator authorization; retry disable then enable; independent final readback'], { refusedFirst: true, disableThenEnableSucceeded: true, finalEnabled: (await backend.call('/user/query', { method: 'POST', data: { userIdEq: target.id } }))[0].enable })
    await setUI(operator, false)
    await page.reload()
    expect(await readAdmins()).toEqual(original.map(String).sort())
    await operatorPage.goto('/#/admin/settings')
    await expect(operatorPage.getByRole('button', { name: 'Save', exact: true })).toBeEnabled()
    const denied = await clickAndResponse(operatorPage, '/auth/saveGlobalAdmin', () => operatorPage.getByRole('button', { name: 'Save', exact: true }).click())
    expect(denied.success).toBe(false)
    await evidence(info, 'UI-009', 'remove-admin', ['remove operator via page; restore exact original; revoked profile settings refuses'], { exactOriginalRestored: true, removedId: operator.id, rescueAvailable: true })
    await evidence(info, 'UI-009', 'unauthorized-settings', ['non-global-admin directly opens settings; original Server permits membership read; page Save refused; membership unchanged'], { saveRefused: true, noSideEffect: true })
    const selectBox = page.locator('.settings-card .el-select')
    await selectBox.click()
    await selectBox.locator('input').fill('')
    const selected = page.locator('.el-select-dropdown:visible .el-select-dropdown__item.is-selected')
    await expect(selected).toHaveCount(original.length)
    for (let count = original.length; count > 0; count--) { await selected.first().click(); await expect(selected).toHaveCount(count - 1) }
    await page.locator('.card-heading').click()
    const empty = await clickAndResponse(page, '/auth/saveGlobalAdmin', () => page.getByRole('button', { name: 'Save', exact: true }).click())
    expect(empty.success).toBe(false)
    await page.reload()
    expect(await readAdmins()).toEqual(original.map(String).sort())
    await evidence(info, 'UI-009', 'reject-empty-admins', ['deselect all real options Save; actual Server refusal; reload original members retained'], { success: false, originalsRetained: true })
  } finally {
    await backend.call('/auth/saveGlobalAdmin', { method: 'POST', data: { admin: original } })
    await backend.call('/user/enable?uid=' + encodeURIComponent(target.id), { method: 'POST' })
    await context.close()
    expect(await readAdmins()).toEqual(original.map(String).sort())
  }
})
test('adminext roles · four independent profiles, revoke all and observer Job/Workflow operation denial', async ({ page, backend, credentials }, info) => {
  test.setTimeout(360_000)
  const users = Object.fromEntries(await Promise.all(roles.map(async role => [role, await userFixture(backend, `app${role}`)])))
  let ns, app, jobId, workflowId, instanceId, wfInstanceId
  const contexts = [], roleInstances = []
  try {
    ns = await namespaceViaPage(page, backend, `${prefix}_roles`)
    app = await appViaPage(page, backend, ns, `${prefix}_roles_app`, users)
    for (const role of roles) expect(app.componentUserRoleInfo[role].map(String)).toContain(String(users[role].id))
    const appBackend = new Backend(backend.request, backend.server, backend.token, app.id)
    jobId = await appBackend.call('/job/save', { method: 'POST', data: { appId: app.id, jobName: `${prefix}_permission_job`, jobDescription: '', timeExpressionType: 'API', timeExpression: '', executeType: 'STANDALONE', processorType: 'BUILT_IN', processorInfo: 'tech.powerjob.samples.processors.SimpleProcessor', enable: false, maxInstanceNum: 0, concurrency: 1, instanceTimeLimit: 0, instanceRetryNum: 0, taskRetryNum: 0, minCpuCores: 0, minMemorySpace: 0, minDiskSpace: 0, dispatchStrategy: 'HEALTH_FIRST', maxWorkerCount: 0, notifyUserIds: [], lifeCycle: { start: null, end: null } } })
    jobId = (await appBackend.call('/job/list', { method: 'POST', data: { appId: app.id, keyword: `${prefix}_permission_job`, index: 0, pageSize: 10 } })).data[0].id
    const rolePages = {}
    for (const role of roles) {
      const context = await contextFor(page), rolePage = await context.newPage(); contexts.push(context); rolePages[role] = rolePage
      await ownLogin(rolePage, credentials, users[role])
      await query(rolePage, '/appInfo/list', [['ID', app.id]])
      await expect(selectors.row(rolePage, app.appName)).toBeVisible()
      await selectors.row(rolePage, app.appName).getByRole('button', { name: 'Enter', exact: true }).click()
      await expect(rolePage).toHaveURL(/oms\/home/)
      await rolePage.goto('/#/oms/job')
      await expect(selectors.row(rolePage, String(jobId))).toBeVisible()
      await selectors.row(rolePage, String(jobId)).getByRole('button', { name: 'Edit', exact: true }).click()
      const dialog = selectors.dialog(rolePage)
      await input(dialog, 'Job description', `${prefix} edited by ${role}`)
      const result = await clickAndResponse(rolePage, '/job/save', () => dialog.getByRole('button', { name: 'Save', exact: true }).click())
      expect(result.success, `role=${role}; business=${result.message || ''}`).toBe(role === 'admin' || role === 'developer')
      if (!result.success) { await expect(dialog).toBeVisible(); await dialog.getByRole('button', { name: 'Cancel', exact: true }).click() }
      else await expect(dialog).not.toBeVisible()
      const run = await clickAndResponse(rolePage, '/job/run', () => selectors.row(rolePage, String(jobId)).getByRole('button', { name: 'Run', exact: true }).click())
      expect(run.success, `OPS contract for ${role}`).toBe(role !== 'observer')
      if (run.success) roleInstances.push(run.data)
    }
    await evidence(info, 'UI-005', 'assign-four-roles', ['page assign all four IDs; four normal isolated profiles login/enter/list; admin/developer Job write succeed and QA/observer write refused'], { appId: app.id, roles: Object.fromEntries(roles.map(role => [role, users[role].id])), metadataWrite: { admin: true, developer: true, qa: false, observer: false }, operationRun: { admin: true, developer: true, qa: true, observer: false } })
    const observer = rolePages.observer
    info.evidencePage = observer
    await observer.goto('/#/admin/app')
    await query(observer, '/appInfo/list', [['ID', app.id]])
    await selectors.row(observer, app.appName).getByRole('button', { name: 'Edit', exact: true }).click()
    let appDialog = selectors.dialog(observer)
    await input(appDialog, 'Name', 'unauthorized app change')
    const deniedAppSave = await clickAndResponse(observer, '/appInfo/save', () => appDialog.getByRole('button', { name: 'Save', exact: true }).click())
    expect(deniedAppSave.success).toBe(false); await expect(appDialog).toBeVisible()
    await appDialog.getByRole('button', { name: 'Delete', exact: true }).click()
    const deniedAppDelete = await clickAndResponse(observer, '/appInfo/delete', () => confirmDialog(observer))
    expect(deniedAppDelete.success).toBe(false); await expect(appDialog).toBeVisible()
    await appDialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    const appRead = (await backend.call('/appInfo/list', { method: 'POST', data: { appId: app.id, showMyRelated: false, index: 0, pageSize: 10 } })).data[0]
    expect(appRead.title).toBe(app.title)
    await evidence(info, 'UI-005', 'unauthorized-change', ['observer real app Edit Save refused; Delete confirm refused; draft stays; independent original object'], { appId: app.id, saveRefused: true, deleteRefused: true })
    await evidence(info, 'UI-005', 'delete-business-failure', ['original role contract refuses observer confirmed app deletion; failure displayed; original object stays'], { appId: app.id, success: false, originalPreserved: true })
    await observer.goto('/#/oms/job')
    const jobRow = selectors.row(observer, String(jobId))
    const deniedEnable = await clickAndResponse(observer, '/job/save', () => jobRow.locator('.el-switch').click())
    expect(deniedEnable.success).toBe(false)
    await expect(jobRow.locator('.el-switch')).not.toHaveClass(/is-checked/)
    expect((await appBackend.call('/job/list', { method: 'POST', data: { appId: app.id, jobId, index: 0, pageSize: 10 } })).data[0].enable).toBe(false)
    await evidence(info, 'UI-014', 'status-error-rollback', ['observer page enables disabled controlled Job; actual permission refusal; visual rollback and independent enable false'], { jobId, enabled: false })
    const deniedRun = await clickAndResponse(observer, '/job/run', () => jobRow.getByRole('button', { name: 'Run', exact: true }).click())
    expect(deniedRun.success).toBe(false)
    await evidence(info, 'UI-015', 'run-permission-error', ['observer real Job Run button refused; no fake success'], { jobId, success: false })
    await jobRow.getByRole('button', { name: 'More', exact: true }).click()
    await observer.locator('.el-dropdown-menu:visible').getByRole('button', { name: 'Delete', exact: true }).click()
    const deniedDelete = await clickAndResponse(observer, '/job/delete', () => confirmDialog(observer))
    expect(deniedDelete.success).toBe(false)
    await expect(jobRow).toBeVisible()
    await evidence(info, 'UI-014', 'delete-permission-error', ['observer page Delete confirm actual permission refusal; controlled Job remains'], { jobId, success: false })
    // Page authoring for owner workflow; isolated API fixture avoids any shared Samples data.
    await page.goto('/#/admin/app')
    await query(page, '/appInfo/list', [['ID', app.id]])
    await selectors.row(page, app.appName).getByRole('button', { name: 'Enter', exact: true }).click()
    await page.goto('/#/oms/workflow')
    await page.getByRole('button', { name: 'New workflow', exact: true }).click()
    await input(page.locator('main'), 'Workflow name', `${prefix}_permission_workflow`)
    await page.locator('.canvas-toolbar').getByRole('button', { name: /Import job/ }).click()
    const drawer = selectors.dialog(page)
    await input(drawer, 'Keyword', `${prefix}_permission_job`)
    await drawer.getByRole('button', { name: 'Query', exact: true }).click()
    const imported = await clickAndResponse(page, '/workflow/saveNode', () => selectors.row(page, `${prefix}_permission_job`).getByRole('button', { name: 'Import', exact: true }).click())
    expect(imported.success).toBe(true)
    await expect(drawer).not.toBeVisible()
    const savedWF = await clickAndResponse(page, '/workflow/save', () => page.locator('.editor-heading').getByRole('button', { name: 'Save', exact: true }).click())
    expect(savedWF.success).toBe(true); workflowId = savedWF.data
    const wfBefore = await appBackend.call('/workflow/fetch?workflowId=' + encodeURIComponent(workflowId))
    await observer.goto('/#/oms/workflow')
    const wfRow = selectors.row(observer, String(workflowId)); await expect(wfRow).toBeVisible()
    const deniedWFStatus = await clickAndResponse(observer, '/workflow/' + (wfBefore.enable ? 'disable' : 'enable'), () => wfRow.locator('.el-switch').click())
    expect(deniedWFStatus.success).toBe(false)
    const wfAfter = await appBackend.call('/workflow/fetch?workflowId=' + encodeURIComponent(workflowId))
    expect(wfAfter.enable).toBe(wfBefore.enable)
    await evidence(info, 'UI-020', 'workflow-status-fail', ['observer real workflow status switch refused; rollback and independent unchanged status'], { workflowId, enable: wfAfter.enable })
    const deniedWFRun = await clickAndResponse(observer, '/workflow/run', () => wfRow.getByRole('button', { name: 'Run', exact: true }).click())
    expect(deniedWFRun.success).toBe(false)
    await evidence(info, 'UI-023', 'workflow-run-fail', ['observer real workflow Run refused; no fake success'], { workflowId, success: false })
    instanceId = await appBackend.call('/job/run?jobId=' + encodeURIComponent(jobId) + '&appId=' + encodeURIComponent(app.id))
    let instance
    await expect.poll(async () => {
      instance = (await appBackend.call('/instance/list', { method: 'POST', data: { appId: app.id, instanceId, type: 'NORMAL', index: 0, pageSize: 10 } })).data[0]
      return instance?.status
    }, { timeout: 30000, intervals: [500, 1000] }).toBeOneOf([4, 5, 10])
    await observer.goto('/#/oms/instance')
    const instanceRow = selectors.row(observer, String(instanceId)); await expect(instanceRow).toBeVisible()
    const retryDenied = await clickAndResponse(observer, '/instance/retry', () => instanceRow.getByRole('button', { name: 'Retry', exact: true }).click())
    expect(retryDenied.success).toBe(false)
    const instanceAfter = (await appBackend.call('/instance/list', { method: 'POST', data: { appId: app.id, instanceId, type: 'NORMAL', index: 0, pageSize: 10 } })).data[0]
    expect(instanceAfter.status).toBe(instance.status)
    await evidence(info, 'UI-018', 'retry-permission-error', ['owner isolated run reaches terminal; observer page Retry refused; independent status unchanged'], { instanceId, status: instanceAfter.status, retryRefused: true })
    wfInstanceId = await appBackend.call('/workflow/run?workflowId=' + encodeURIComponent(workflowId) + '&appId=' + encodeURIComponent(app.id))
    let wfInstance
    await expect.poll(async () => {
      wfInstance = await appBackend.call('/wfInstance/info?wfInstanceId=' + encodeURIComponent(wfInstanceId))
      return wfInstance.status
    }, { timeout: 30000, intervals: [500, 1000] }).toBeOneOf([3, 4, 10])
    await observer.goto('/#/oms/wfinstance')
    const wfInstanceRow = selectors.row(observer, String(wfInstanceId)); await expect(wfInstanceRow).toBeVisible()
    await wfInstanceRow.getByRole('button', { name: 'Stop', exact: true }).click()
    const stopDenied = await clickAndResponse(observer, '/wfInstance/stop', () => confirmDialog(observer))
    expect(stopDenied.success).toBe(false)
    const wfRetryDenied = await clickAndResponse(observer, '/wfInstance/retry', () => wfInstanceRow.getByRole('button', { name: 'Retry', exact: true }).click())
    expect(wfRetryDenied.success).toBe(false)
    const wfRead = await appBackend.call('/wfInstance/info?wfInstanceId=' + encodeURIComponent(wfInstanceId))
    expect(wfRead.status).toBe(wfInstance.status)
    await evidence(info, 'UI-024', 'wfinstance-permission', ['owner isolated Workflow run reaches terminal; observer page Stop confirm and Retry refused; independent status unchanged'], { wfInstanceId, status: wfRead.status, stopRefused: true, retryRefused: true })
    // Revoke roles on the owning app through the real editor. Namespace has no inherited grants.
    await page.goto('/#/admin/app')
    await query(page, '/appInfo/list', [['ID', app.id]])
    await selectors.row(page, app.appName).getByRole('button', { name: 'Edit', exact: true }).click()
    for (const role of roles) await roleSelect(page, selectors.dialog(page), role, users[role].nick)
    await saveDialog(page, '/appInfo/save')
    const revoked = (await backend.call('/appInfo/list', { method: 'POST', data: { appId: app.id, showMyRelated: false, index: 0, pageSize: 10 } })).data[0]
    for (const role of roles) expect(revoked.componentUserRoleInfo[role].map(String)).not.toContain(String(users[role].id))
    for (const role of roles) {
      const rolePage = rolePages[role]
      await rolePage.goto('/#/admin/app')
      const after = await query(rolePage, '/appInfo/list', [['ID', app.id]])
      expect(after.data.data).toHaveLength(0)
      await expect(rolePage.locator('.el-table__empty-block')).toBeVisible()
      const deniedRead = await clickAndResponse(rolePage, '/job/list', () => rolePage.goto('/#/oms/job'))
      expect(deniedRead.success).toBe(false)
      await expect(rolePage.locator('.el-table__empty-block')).toBeVisible()
    }
    await evidence(info, 'UI-005', 'remove-roles', ['real page deselect each role and save; each independent former-role profile query no related app; independent grants empty'], { appId: app.id, allFourRevoked: true, noInheritedNamespaceGrant: true })
  } finally {
    for (const context of contexts) await context.close()
    if (app) {
      const owner = new Backend(backend.request, backend.server, backend.token, app.id)
      for (const ownedInstance of roleInstances) await owner.call('/instance/stop?instanceId=' + encodeURIComponent(ownedInstance), { allowFailure: true })
      if (instanceId) await owner.call('/instance/stop?instanceId=' + encodeURIComponent(instanceId), { allowFailure: true })
      if (wfInstanceId) await owner.call('/wfInstance/stop?wfInstanceId=' + encodeURIComponent(wfInstanceId), { allowFailure: true })
      if (workflowId) await owner.call('/workflow/delete?workflowId=' + encodeURIComponent(workflowId))
      if (jobId) await owner.call('/job/delete?jobId=' + encodeURIComponent(jobId))
    }
    await cleanupApp(backend, app?.id); await cleanupNamespace(backend, ns?.id)
  }
})
test('adminext sessions · switch applications, refresh/history, legacy storage and shared-tab account/logout', async ({ page, backend, credentials }, info) => {
  test.setTimeout(240_000)
  let ns, first, second
  const user = await userFixture(backend, 'session')
  let otherTab
  try {
    ns = await namespaceViaPage(page, backend, `${prefix}_sessions`)
    first = await appViaPage(page, backend, ns, `${prefix}_session_a`)
    second = await appViaPage(page, backend, ns, `${prefix}_session_b`)
    for (const app of [first, second, first]) {
      await page.goto('/#/admin/app')
      await query(page, '/appInfo/list', [['ID', app.id]])
      await selectors.row(page, app.appName).getByRole('button', { name: 'Enter', exact: true }).click()
      await expect(page).toHaveURL(/oms\/home/)
      expect(await page.evaluate(() => localStorage.getItem('Power_appId'))).toBe(String(app.id))
      await expect(page.locator('.application-tag')).toContainText(app.appName)
      const list = await clickAndResponse(page, '/job/list', () => page.goto('/#/oms/job'))
      expect(list.success).toBe(true)
    }
    await evidence(info, 'UI-004', 'enter-switch-app', ['explicit enter A→B→A via applications; home nav; job live request each app'], { appIds: [first.id, second.id, first.id], storageAndNavbarMatch: true })
    const tokenBefore = await page.evaluate(() => localStorage.getItem('PowerJwt'))
    await page.reload()
    await expect(page.locator('.el-table')).toBeVisible()
    expect(await page.evaluate(() => localStorage.getItem('PowerJwt'))).toBe(tokenBefore)
    expect(await page.evaluate(() => localStorage.getItem('Power_appId'))).toBe(String(first.id))
    await page.goto('/#/admin/app'); await page.reload(); await expect(page.locator('.el-table')).toBeVisible()
    await evidence(info, 'UI-003', 'refresh-session', ['hard refresh application and Job page preserving legitimate session/app'], { tokenPreserved: true, appId: first.id })
    await page.goto('/#/oms/job'); await page.goto('/#/admin/personal'); await page.goBack(); await expect(page).toHaveURL(/oms\/job/); await page.goForward(); await expect(page).toHaveURL(/admin\/personal/)
    expect(await page.evaluate(() => localStorage.getItem('Power_appId'))).toBe(String(first.id))
    await evidence(info, 'UI-003', 'history-navigation', ['Job→profile browser Back/Forward; no context change'], { currentAppId: first.id, routes: ['oms/job', 'admin/personal'] })
    await page.evaluate(() => { localStorage.setItem('oms_lang', 'en') })
    await page.reload()
    await expect(page.getByRole('button', { name: 'Change Password', exact: true })).toBeVisible()
    expect(await page.evaluate(() => localStorage.getItem('Power_appId'))).toBe(String(first.id))
    expect(await page.evaluate(() => localStorage.getItem('PowerJwt'))).toBe(tokenBefore)
    await evidence(info, 'UI-003', 'legacy-storage', ['legitimate legacy PowerJwt/Power_appId/oms_lang remain; normal reload'], { language: 'en', tokenAndAppPreserved: true })
    await page.goto('/#/oms/job')
    otherTab = await page.context().newPage()
    await otherTab.goto('/#/admin/app')
    await query(otherTab, '/appInfo/list', [['ID', second.id]])
    const synchronized = await clickAndResponse(page, '/job/list', () => selectors.row(otherTab, second.appName).getByRole('button', { name: 'Enter', exact: true }).click())
    expect(synchronized.success).toBe(true)
    expect(String(synchronized.requestBodyAppId)).toBe(String(second.id))
    expect(synchronized.requestAppId).toBe(String(second.id))
    await expect(page.locator('.application-tag')).toContainText(second.appName)
    await expect(page).toHaveURL(/oms\/job/)
    await evidence(info, 'UI-003', 'multi-tab-app-context-detail', ['second shared tab same-account selects B; first Job remounts automatically; request body/header/navbar all B'], { appId: second.id, bodyAppId: synchronized.requestBodyAppId, headerAppId: synchronized.requestAppId })
    await ownLogin(otherTab, credentials, user)
    await expect(page).toHaveURL(/admin\/app/)
    await expect(page.locator('.profile-card')).toHaveCount(0)

    expect(await otherTab.evaluate(() => localStorage.getItem('Power_appId'))).toBeNull()
    await page.goto('/#/admin/personal')
    await expect(page.getByLabel('Nick', { exact: true })).toHaveValue(user.nick)
    await expect(page.locator('.application-tag')).not.toBeVisible()
    await logout(otherTab)
    await expect(page).toHaveURL(/loginHomepage/)
    await evidence(info, 'UI-003', 'multi-tab-account', ['same-account app switch synchronized body/header/view; second tab real other-account login; old tab automatically resets views and normal profile shows new account; second logout automatically updates first tab'], { newUserId: user.id, oldApplicationCleared: true, bothLoggedOut: true })
    await page.goto('/#/oms/job'); await expect(page).toHaveURL(/loginHomepage/)
    expect(await page.evaluate(() => localStorage.getItem('PowerJwt'))).toBeNull()
    expect(await page.evaluate(() => localStorage.getItem('Power_appId'))).toBeNull()
    await evidence(info, 'UI-003', 'logout-deep-link', ['real Logout then direct Job deep link refused'], { token: 'cleared', application: 'cleared', deepLink: 'loginHomepage' })
  } finally { await otherTab?.close(); await cleanupApp(backend, second?.id); await cleanupApp(backend, first?.id); await cleanupNamespace(backend, ns?.id) }
})

test('adminext personal · become-admin wrong password, opt-out and real successful grant', async ({ page, backend, credentials }, info) => {
  test.setTimeout(180_000)
  let ns, allowed, denied
  const user = await userFixture(backend, 'becomeadmin')
  const context = await contextFor(page), ownPage = await context.newPage()
  try {
    ns = await namespaceViaPage(page, backend, `${prefix}_becomeadmin`)
    const create = async (suffix, optout) => backend.call('/appInfo/save', { method: 'POST', data: { namespaceId: ns.id, appName: `${prefix}_${suffix}`, password: 'SyntheticGrant', extra: JSON.stringify({ allowedBecomeAdminByPassword: !optout }), componentUserRoleInfo: emptyRoles() } })
    allowed = (await create('grant_allowed', false)).id; denied = (await create('grant_denied', true)).id
    info.evidencePage = ownPage
    await ownLogin(ownPage, credentials, user)
    await ownPage.goto('/#/admin/personal')
    const form = ownPage.locator('.app-admin-card')
    for (const [name, password] of [[`${prefix}_grant_allowed`, 'SyntheticWrong'], [`${prefix}_grant_denied`, 'SyntheticGrant']]) {
      await input(form, 'appName', name); await input(form, 'Password', password)
      const failed = await clickAndResponse(ownPage, '/appInfo/becomeAdmin', () => form.getByRole('button', { name: 'Auth then become admin', exact: true }).click())
      expect(failed.success).toBe(false)
      const read = (await backend.call('/appInfo/list', { method: 'POST', data: { appNameLike: name, showMyRelated: false, index: 0, pageSize: 10 } })).data[0]
      expect(read.componentUserRoleInfo.admin.map(String)).not.toContain(String(user.id))
    }
    await evidence(info, 'UI-008', 'become-admin-denied', ['normal isolated user; page wrong app password and opt-out exact app; actual refusal; no grant readback'], { wrongPasswordRefused: true, optOutRefused: true, noRolesAdded: true })
    await input(form, 'appName', `${prefix}_grant_allowed`); await input(form, 'Password', 'SyntheticGrant')
    const granted = await clickAndResponse(ownPage, '/appInfo/becomeAdmin', () => form.getByRole('button', { name: 'Auth then become admin', exact: true }).click())
    expect(granted.success).toBe(true)
    await expect(form.getByLabel('Password', { exact: true })).toHaveValue('')
    await ownPage.goto('/#/admin/app')
    const related = await query(ownPage, '/appInfo/list', [['ID', allowed]])
    expect(related.data.data).toHaveLength(1)
    expect(related.data.data[0].componentUserRoleInfo.admin.map(String)).toContain(String(user.id))
    await selectors.row(ownPage, `${prefix}_grant_allowed`).getByRole('button', { name: 'Edit', exact: true }).click()
    await input(selectors.dialog(ownPage), 'Name', `${prefix} granted admin write`)
    const saved = await saveDialog(ownPage, '/appInfo/save')
    expect(String(saved.id)).toBe(String(allowed))
    await evidence(info, 'UI-008', 'become-admin-success', ['correct app password real grant; related app visible; admin metadata write succeeds'], { appId: allowed, userId: user.id, actualGranted: true })
  } finally { await context.close(); await cleanupApp(backend, denied); await cleanupApp(backend, allowed); await cleanupNamespace(backend, ns?.id) }
})
test('adminext deletion · empty app/namespace cancel zero requests and confirmed deletion survive refresh', async ({ page, backend }, info) => {
  test.setTimeout(180_000)
  let ns, app
  try {
    ns = await namespaceViaPage(page, backend, `${prefix}_delete`)
    app = await appViaPage(page, backend, ns, `${prefix}_delete_app`)
    await query(page, '/appInfo/list', [['ID', app.id]])
    await selectors.row(page, app.appName).getByRole('button', { name: 'Edit', exact: true }).click()
    let deleteRequests = 0
    page.on('request', req => { if (req.url().includes('/appInfo/delete')) deleteRequests++ })
    let dialog = selectors.dialog(page)
    await dialog.getByRole('button', { name: 'Delete', exact: true }).click(); await confirmDialog(page, false)
    expect(deleteRequests).toBe(0); await expect(dialog).toBeVisible()
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await page.reload(); await query(page, '/appInfo/list', [['ID', app.id]]); await expect(selectors.row(page, app.appName)).toBeVisible()
    await evidence(info, 'UI-005', 'delete-cancel', ['empty page-created app Delete then Cancel; zero delete requests; hard refresh still present'], { appId: app.id, deleteRequests })
    await selectors.row(page, app.appName).getByRole('button', { name: 'Edit', exact: true }).click(); dialog = selectors.dialog(page)
    await dialog.getByRole('button', { name: 'Delete', exact: true }).click()
    const deleted = await clickAndResponse(page, '/appInfo/delete', () => confirmDialog(page)); expect(deleted.success).toBe(true)
    const id = app.id, name = app.appName; app = null
    await expect(selectors.row(page, name)).not.toBeVisible()
    await page.reload(); const refreshed = await query(page, '/appInfo/list', [['ID', id]]); expect(refreshed.data.data).toHaveLength(0)
    await evidence(info, 'UI-005', 'delete-confirm', ['confirm empty app deletion; row gone; hard refresh exact ID absent'], { appId: id, success: true, absentAfterReload: true })
    await page.goto('/#/admin/namespace'); await query(page, '/namespace/list', [['Code', ns.code]])
    let nsDeletes = 0
    page.on('request', req => { if (req.url().includes('/namespace/delete')) nsDeletes++ })
    await selectors.row(page, ns.code).getByRole('button', { name: 'Delete', exact: true }).click(); await confirmDialog(page, false)
    expect(nsDeletes).toBe(0); await page.reload(); await query(page, '/namespace/list', [['Code', ns.code]]); await expect(selectors.row(page, ns.code)).toBeVisible()
    await evidence(info, 'UI-006', 'delete-empty-cancel', ['empty namespace Delete Cancel; zero request; hard refresh retained'], { namespaceId: ns.id, nsDeletes })
    await selectors.row(page, ns.code).getByRole('button', { name: 'Delete', exact: true }).click()
    const nsDeleted = await clickAndResponse(page, '/namespace/delete', () => confirmDialog(page)); expect(nsDeleted.success).toBe(true)
    const nsId = ns.id, code = ns.code; ns = null
    await expect(selectors.row(page, code)).not.toBeVisible(); await page.reload(); const absent = await query(page, '/namespace/list', [['Code', code]]); expect(absent.data.data).toHaveLength(0)
    await evidence(info, 'UI-006', 'delete-empty-confirm', ['confirm empty namespace deletion; row gone; hard refresh query absent'], { namespaceId: nsId, absentAfterReload: true })
  } finally { await cleanupApp(backend, app?.id); await cleanupNamespace(backend, ns?.id) }
})
