import { test, expect, selectors, runId, demoProcessor, timeoutProcessor, input, choose, formItem, enterSamples, saveDialog, clickAndResponse, confirmDialog, fileHash } from './support.js';
import fs from 'node:fs/promises';

async function variantProof(info, caseId, variantId, actual) {
  const result={caseId,variantId,status:'PASS',testTitle:info.title,actual};
  await fs.writeFile(info.outputPath(`variant-${caseId}-${variantId}.json`),JSON.stringify(result,null,2));
  await info.attach(`${caseId}/${variantId}`,{body:JSON.stringify(result),contentType:'application/json'});
}

async function createJob(page,backend,name,processor=demoProcessor,params='success') {
  await page.goto('/#/oms/job'); await page.getByRole('button',{name:'New job',exact:true}).click();
  const dialog=selectors.dialog(page);
  await input(dialog,'Job name',name); await input(dialog,'Job params',params);
  await choose(page,dialog,'Schedule info','API'); await choose(page,dialog,'Execution config','Standalone',0); await choose(page,dialog,'Execution config','BUILT_IN',1); await input(dialog,'Execution config',processor);
  await saveDialog(page,'/job/save'); const result=(await backend.listJobs(name)).data.find(job=>job.jobName===name); expect(result).toBeTruthy(); return String(result.id);
}
async function newWorkflow(page,name) {
  await page.goto('/#/oms/workflow'); await page.getByRole('button',{name:'New workflow',exact:true}).click();
  await expect(page).toHaveURL(/workflowEditor/); await input(page.locator('main'),'Workflow name',name);
}
async function importJob(page,name,jobId) {
  await page.locator('.canvas-toolbar').getByRole('button',{name:/Import job/}).click();
  const drawer=page.getByRole('dialog').filter({visible:true}).last();
  await input(drawer,'Job ID',jobId || '');await input(drawer,'Keyword',jobId ? '' : name); await drawer.getByRole('button',{name:'Query',exact:true}).click();
  const result=await clickAndResponse(page,'/workflow/saveNode',()=>selectors.row(page,name).getByRole('button',{name:'Import',exact:true}).click());
  expect(result.success).toBe(true); await expect(drawer).not.toBeVisible();
  const id=String(result.data[0].id); await expect(page.locator(`[data-node-id="${id}"]`)).toBeVisible(); return id;
}
async function saveWorkflow(page) {
  const result=await clickAndResponse(page,'/workflow/save',()=>page.locator('.editor-heading').getByRole('button',{name:'Save',exact:true}).click());
  expect(result.success).toBe(true); await expect(page).toHaveURL(/workflowId=/); return String(result.data);
}
async function node(page,id) { return page.locator(`[data-node-id="${id}"]`); }
async function connect(page,source,target,label) {
  const start=page.locator(`[data-node-id="${source}"] ${label==='Y'?'.branch-yes':label==='N'?'.branch-no':'.output-anchor'}`);
  const end=page.locator(`[data-node-id="${target}"] .node-shape`);
  await page.locator(`[data-node-id="${source}"]`).click(); await start.hover();
  const a=await start.boundingBox(), b=await end.boundingBox();
  expect(a).toBeTruthy(); expect(b).toBeTruthy();
  await page.mouse.move(a.x+a.width/2,a.y+a.height/2); await page.mouse.down(); await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:12}); await page.mouse.up();
}
async function editCondition(page,id,code,paste=false) {
  await (await node(page,id)).click();
  const editor=page.locator('.node-panel .monaco-editor'); await expect(editor).toBeVisible();
  await editor.click({position:{x:100,y:30}}); await page.keyboard.press('ControlOrMeta+A');if(paste){await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.evaluate(text=>navigator.clipboard.writeText(text),code);await page.keyboard.press('ControlOrMeta+V');}else await page.keyboard.insertText(code);
  const result=await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.node-panel').getByRole('button',{name:'Save',exact:true}).click()); expect(result.success).toBe(true);
}
async function findWorkflow(page,id) {
  await page.goto('/#/oms/workflow'); await input(page.locator('main'),'Workflow ID',id); await page.getByRole('button',{name:'Query',exact:true}).click(); const row=selectors.row(page,String(id)); await expect(row).toBeVisible(); return row;
}
async function workflowInfo(backend,id) { return backend.call('/workflow/fetch?workflowId='+encodeURIComponent(id)); }
async function waitWorkflow(backend,id,statuses) {
  let info;
  await expect.poll(async()=>{info=await backend.call('/wfInstance/info?wfInstanceId='+encodeURIComponent(id));return info.status;},{timeout:60_000,intervals:[500,1000,2000]}).toBeOneOf(statuses);
  return info;
}
async function runWorkflow(page,id,parameters) {
  const row=await findWorkflow(page,id);
  if (parameters !== undefined) {
    await row.locator('.el-dropdown').hover(); await page.locator('.el-dropdown-menu:visible').getByRole('button',{name:'Run by parameter',exact:true}).click();
    await selectors.dialog(page).locator('textarea').fill(parameters);
    const result=await clickAndResponse(page,'/workflow/run',()=>selectors.dialog(page).getByRole('button',{name:'Run',exact:true}).click()); expect(result.success).toBe(true); return String(result.data);
  }
  const result=await clickAndResponse(page,'/workflow/run',()=>row.getByRole('button',{name:'Run',exact:true}).click()); expect(result.success).toBe(true); return String(result.data);
}
async function clean(backend,workflows,jobs,instances=[]) {
  for(const instance of instances) await backend.call('/wfInstance/stop?wfInstanceId='+encodeURIComponent(instance),{allowFailure:true});
  for(const id of workflows.reverse()) { const info=await workflowInfo(backend,id); if (!info.wfName.startsWith(runId)) throw new Error('Refusing cleanup of another lane workflow'); await backend.call('/workflow/delete?workflowId='+encodeURIComponent(id)); }
  for(const id of jobs) await backend.deleteOwnedJob(id);
}

test('UI-020/021/034/039 · native DAG metadata, all node types, drag/connect/delete, zoom/layout/fullscreen and URL reload',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(240_000); await enterSamples(page,credentials); const jobs=[],workflows=[];
  try {
    const firstName=`${runId}_workflow_a`, secondName=`${runId}_workflow_b`;
    jobs.push(await createJob(page,backend,firstName)); jobs.push(await createJob(page,backend,secondName));
    await newWorkflow(page,`${runId}_workflow_child`); await importJob(page,firstName); const childId=await saveWorkflow(page); workflows.push(childId);
    await newWorkflow(page,`${runId}_workflow_allnodes`);
    await input(page.locator('main'),'Description','中文😀 workflow "quotes" &+%');
    await page.getByRole('combobox',{name:'Start time',exact:true}).fill('2026-10-01 00:00:00'); await page.getByRole('combobox',{name:'Start time',exact:true}).press('Enter');
    await page.getByRole('spinbutton',{name:'Max instance num',exact:true}).fill('2'); await page.getByRole('spinbutton',{name:'Max instance num',exact:true}).press('Tab');
    const first=await importJob(page,firstName), second=await importJob(page,secondName,jobs[1]);
    const conditionResult=await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.canvas-toolbar').getByRole('button',{name:/Condition/}).click()); expect(conditionResult.success).toBe(true); const condition=String(conditionResult.data[0].id);
    await editCondition(page,condition,'return true');
    await connect(page,condition,first,'Y'); await connect(page,condition,second,'N'); await expect(page.locator('.dag-edge')).toHaveCount(2);
    await connect(page,first,condition); await expect(page.locator('.dag-edge')).toHaveCount(2); await expect(page.locator('.el-message--warning').last()).toContainText(/cycles|循环/);
    const before=await (await node(page,first)).getAttribute('transform'); const box=await (await node(page,first)).boundingBox(); await page.mouse.move(box.x+40,box.y+30); await page.mouse.down(); await page.mouse.move(box.x+65,box.y+80,{steps:8}); await page.mouse.up(); expect(await (await node(page,first)).getAttribute('transform')).not.toBe(before);
    await page.locator('.canvas-toolbar').getByRole('button',{name:'Zoom In',exact:true}).click(); await expect(page.locator('.zoom-label')).not.toHaveText('100%'); await page.locator('.canvas-toolbar').getByRole('button',{name:'Zoom out',exact:true}).click();
    await page.locator('.canvas-toolbar').getByRole('button',{name:'Auto Fit',exact:true}).click();
    await page.locator('.canvas-toolbar').getByRole('button',{name:/Full Screen/}).click(); await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(true);await page.setViewportSize({width:1280,height:850});await expect(page.locator('.dag-node')).toHaveCount(3); await page.keyboard.press('Escape'); await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBe(false);await page.setViewportSize({width:1440,height:1000});
    await page.locator('.canvas-toolbar').getByRole('button',{name:/Subprocesses/}).click(); const drawer=page.getByRole('dialog').filter({visible:true}).last(); await input(drawer,'Workflow ID',childId); await drawer.getByRole('button',{name:'Query',exact:true}).click(); const nested=await clickAndResponse(page,'/workflow/saveNode',()=>selectors.row(page,`${runId}_workflow_child`).getByRole('button',{name:/Import|引入/,exact:true}).click()); expect(nested.success).toBe(true); const nestedId=String(nested.data[0].id); await expect(drawer).not.toBeVisible();
    await connect(page,first,nestedId); await expect(page.locator('.dag-edge')).toHaveCount(3);
    const extraResult=await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.canvas-toolbar').getByRole('button',{name:/Condition/}).click()); const extraId=String(extraResult.data[0].id); await (await node(page,extraId)).click(); await page.locator('.canvas-toolbar').getByRole('button',{name:'Delete',exact:true}).click(); await expect(page.locator(`[data-node-id="${extraId}"]`)).toHaveCount(0);
    const id=await saveWorkflow(page); workflows.push(id); const saved=await workflowInfo(backend,id); expect(saved.wfDescription).toBe('中文😀 workflow "quotes" &+%'); expect(saved.maxWfInstanceNum).toBe(2); expect(saved.lifeCycle.start).toBe(1790784000000); expect(saved.lifeCycle.end ?? null).toBeNull(); expect(saved.peworkflowDAG.nodes.map(n=>n.nodeType).sort()).toEqual([1,1,2,3]); expect(saved.peworkflowDAG.edges.filter(e=>String(e.from)===condition).map(e=>e.property).sort()).toEqual(['false','true']); expect(saved.peworkflowDAG.nodes.find(n=>String(n.nodeId)===condition).nodeParams).toBe('return true');
    await page.reload(); await expect(page.locator('.dag-node')).toHaveCount(4); await expect(page.locator('.dag-edge')).toHaveCount(3); await expect(page.locator('.editor-heading h2')).toContainText(`${runId}_workflow_allnodes`);
    await (await node(page,nestedId)).click(); await input(page.locator('.node-panel'),'Node name','alias 中文'); await page.locator('.node-panel').locator('.el-switch').nth(0).click(); await page.locator('.node-panel').locator('.el-switch').nth(1).click(); await saveWorkflow(page); const updated=await workflowInfo(backend,id); const updatedNode=updated.peworkflowDAG.nodes.find(n=>String(n.nodeId)===nestedId); expect(updatedNode).toMatchObject({nodeName:'alias 中文',enable:false,skipWhenFailed:true});
    await (await node(page,first)).click(); await page.locator('.canvas-toolbar').getByRole('button',{name:/Connect/}).click(); await (await node(page,second)).click(); await expect(page.locator('.dag-edge')).toHaveCount(4); await page.locator('.dag-edge').last().locator('.edge-hit').click({force:true}); await page.locator('.canvas-toolbar').getByRole('button',{name:'Delete',exact:true}).click(); await expect(page.locator('.dag-edge')).toHaveCount(3);
    await (await node(page,second)).click();const jobSelector=formItem(page.locator('.node-panel'),'Job name').locator('.el-select');await jobSelector.click();await jobSelector.locator('input').fill(firstName);await page.locator('.el-select-dropdown:visible').getByText(firstName,{exact:true}).click();await input(page.locator('.node-panel'),'Node parameter','中文😀 &+%#\nquoted "node"');await saveWorkflow(page);const rebound=(await workflowInfo(backend,id)).peworkflowDAG.nodes.find(n=>String(n.nodeId)===second);expect(String(rebound.jobId)).toBe(String(jobs[0]));expect(rebound.nodeParams).toBe('中文😀 &+%#\nquoted "node"');expect((await workflowInfo(backend,id)).peworkflowDAG.edges).toHaveLength(3);let managerRow=await findWorkflow(page,id);await expect(managerRow).toContainText(`${runId}_workflow_allnodes`);await input(page.locator('main'),'Workflow ID','');await input(page.locator('main'),'Keyword',`${runId}_workflow_allnodes`);const search=await clickAndResponse(page,'/workflow/list',()=>page.getByRole('button',{name:'Query',exact:true}).click());expect(search.data.data.map(wf=>String(wf.id))).toEqual([id]);managerRow=selectors.row(page,id);await managerRow.getByRole('button',{name:'Edit',exact:true}).click();await expect(page).toHaveURL(new RegExp('workflowId='+id));await expect(page.locator('.dag-node')).toHaveCount(4);await testInfo.attach('workflow-node-definition',{body:JSON.stringify({workflowId:id,lifecycle:updated.lifeCycle,metadata:{wfName:updated.wfName,wfDescription:updated.wfDescription,maxWfInstanceNum:updated.maxWfInstanceNum},dag:(await workflowInfo(backend,id)).peworkflowDAG}),contentType:'application/json'});
  } finally { await clean(backend,workflows,jobs); }
});

test('UI-022/023/024/025/026/040 · true and false branches, real Worker results, node logs/download, nested navigation and deep links',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(300_000); await enterSamples(page,credentials); const jobs=[],workflows=[],instances=[];
  try {
    const aName=`${runId}_workflow_branch_a`, bName=`${runId}_workflow_branch_b`; jobs.push(await createJob(page,backend,aName)); jobs.push(await createJob(page,backend,bName));
    await newWorkflow(page,`${runId}_workflow_branch_child`); await importJob(page,aName); const child=await saveWorkflow(page); workflows.push(child);
    await newWorkflow(page,`${runId}_workflow_branches`); const a=await importJob(page,aName),b=await importJob(page,bName);
    const control=await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.canvas-toolbar').getByRole('button',{name:/Condition/}).click()); const condition=String(control.data[0].id); await connect(page,condition,a,'Y'); await connect(page,condition,b,'N'); await expect(page.locator('.dag-edge')).toHaveCount(2); await editCondition(page,condition,'return true');
    await page.locator('.canvas-toolbar').getByRole('button',{name:/Subprocesses/}).click(); const drawer=page.getByRole('dialog').filter({visible:true}).last(); await input(drawer,'Workflow ID',child); await drawer.getByRole('button',{name:'Query',exact:true}).click(); const childNode=await clickAndResponse(page,'/workflow/saveNode',()=>selectors.row(page,`${runId}_workflow_branch_child`).getByRole('button',{name:/Import|引入/,exact:true}).click());const nested=String(childNode.data[0].id);await expect(drawer).not.toBeVisible();await (await node(page,nested)).click();await input(page.locator('.node-panel'),'Node parameter','{"nested":"中文😀"}');await connect(page,a,nested);
    const id=await saveWorkflow(page);workflows.push(id);
    const params='中文😀 &+%# "workflow params"';const execution=await runWorkflow(page,id,params);instances.push(execution);const result=await waitWorkflow(backend,execution,[4]);expect(result.wfInitParams).toBe(params);expect(result.peworkflowDAG.nodes.find(n=>String(n.nodeId)===condition).result).toBe('true');expect(result.peworkflowDAG.nodes.find(n=>String(n.nodeId)===b).disableByControlNode).toBe(true);expect(result.peworkflowDAG.nodes.find(n=>String(n.nodeId)===a).status).toBe(5);
    await page.goto('/#/oms/wfInstanceDetail?wfInstanceId='+execution);await expect(page.locator('.instance-heading')).toContainText(execution);await expect(page.locator('.dag-node')).toHaveCount(4);const originalTransform=await (await node(page,a)).getAttribute('transform');await (await node(page,a)).click();await page.locator('.workflow-canvas').press('Delete');const viewBox=await (await node(page,a)).boundingBox();await page.mouse.move(viewBox.x+40,viewBox.y+30);await page.mouse.down();await page.mouse.move(viewBox.x+80,viewBox.y+70,{steps:5});await page.mouse.up();await expect(page.locator('.dag-node')).toHaveCount(4);expect(await (await node(page,a)).getAttribute('transform')).toBe(originalTransform);await expect(page.locator('.canvas-toolbar').getByRole('button',{name:/Connect|Import job|Delete/})).toHaveCount(0);await (await node(page,a)).click();await expect(page.locator('.canvas-details')).toContainText(result.peworkflowDAG.nodes.find(n=>String(n.nodeId)===a).instanceId);await page.locator('.canvas-details').getByRole('tab',{name:'Log',exact:true}).click();await page.locator('.log-toolbar .el-switch').click();await expect(page.locator('.instance-log')).toContainText('StandaloneProcessorDemo finished process,success: true',{timeout:30_000});
    const download=page.waitForEvent('download');await page.locator('.canvas-details').getByRole('button',{name:'Download',exact:true}).click();const file=await download,filename=testInfo.outputPath('workflow-node.log');await file.saveAs(filename);expect(await fs.readFile(filename,'utf8')).toContain('StandaloneProcessorDemo finished process,success: true');await testInfo.attach('workflow-log-hash',{body:JSON.stringify({sha256:await fileHash(filename)}),contentType:'application/json'});
    await (await node(page,condition)).click();await expect(page.locator('.canvas-details .monaco-editor')).toBeVisible();await expect(page.locator('.canvas-details .code-toolbar')).toHaveCount(0);
    await (await node(page,nested)).click();const nestedResult=result.peworkflowDAG.nodes.find(n=>String(n.nodeId)===nested);expect(nestedResult.nodeParams).toBe('{"nested":"中文😀"}');const nestedInstance=nestedResult.instanceId;const childResult=await backend.call('/wfInstance/info?wfInstanceId='+nestedInstance);expect(JSON.parse(childResult.wfInitParams)).toMatchObject(JSON.parse(result.wfContext));await page.locator('.canvas-details').getByRole('button',{name:'Detail',exact:true}).click();await expect(page).toHaveURL(new RegExp('wfInstanceId='+nestedInstance));await page.reload();await expect(page.locator('.instance-heading')).toContainText(nestedInstance);await page.goBack();await expect(page.locator('.instance-heading')).toContainText(execution);const tab=await page.context().newPage();await tab.goto(page.url());await expect(tab.locator('.instance-heading')).toContainText(execution);await expect(tab.locator('.dag-node')).toHaveCount(4);await tab.close();
    await page.goto('/#/oms/workflowEditor?workflowId='+id);await expect(page.locator('.dag-node')).toHaveCount(4);await editCondition(page,condition,'return false');await saveWorkflow(page);const falseExecution=await runWorkflow(page,id);instances.push(falseExecution);const falseResult=await waitWorkflow(backend,falseExecution,[4]);expect(falseResult.peworkflowDAG.nodes.find(n=>String(n.nodeId)===condition).result).toBe('false');expect(falseResult.peworkflowDAG.nodes.find(n=>String(n.nodeId)===a).disableByControlNode).toBe(true);expect(falseResult.peworkflowDAG.nodes.find(n=>String(n.nodeId)===b).status).toBe(5);await testInfo.attach('workflow-branch-results',{body:JSON.stringify({workflowId:id,execution,trueNodes:result.peworkflowDAG.nodes,falseExecution,falseNodes:falseResult.peworkflowDAG.nodes,params,nestedInstance,childInitParams:childResult.wfInitParams}),contentType:'application/json'});
  } finally {await clean(backend,workflows,jobs,instances);}
});

test('UI-024/025 · failed-node marking and retry preserve failed and successor states',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(180_000);await enterSamples(page,credentials);const jobs=[],workflows=[],instances=[];
  try {
    const bad=`${runId}_workflow_failure`,next=`${runId}_workflow_afterfailure`;jobs.push(await createJob(page,backend,bad,demoProcessor,'failed'));jobs.push(await createJob(page,backend,next));await newWorkflow(page,`${runId}_workflow_retry`);const first=await importJob(page,bad),second=await importJob(page,next);await connect(page,first,second);const id=await saveWorkflow(page);workflows.push(id);const execution=await runWorkflow(page,id);instances.push(execution);const failed=await waitWorkflow(backend,execution,[3]);expect(failed.peworkflowDAG.nodes.find(n=>String(n.nodeId)===first).status).toBe(4);
    await page.goto('/#/oms/wfInstanceDetail?wfInstanceId='+execution);await expect(page.locator('.dag-node')).toHaveCount(2);await clickAndResponse(page,'/wfInstance/retry',()=>page.locator('.instance-actions').getByRole('button',{name:'Retry',exact:true}).click());const retried=await waitWorkflow(backend,execution,[3]);const newInstance=retried.peworkflowDAG.nodes.find(n=>String(n.nodeId)===first).instanceId;expect(newInstance).not.toBe(failed.peworkflowDAG.nodes.find(n=>String(n.nodeId)===first).instanceId);
    await page.locator('.instance-actions').getByRole('button',{name:'Refresh',exact:true}).click();await (await node(page,first)).click();await expect(page.locator('.canvas-toolbar').getByRole('button',{name:'Marked Success',exact:true})).toBeEnabled();const marked=await clickAndResponse(page,'/wfInstance/markNodeAsSuccess',()=>page.locator('.canvas-toolbar').getByRole('button',{name:'Marked Success',exact:true}).click());expect(marked.success).toBe(true);expect((await backend.call('/instance/detailPlus',{method:'POST',data:{appId:backend.appId,instanceId:String(newInstance)}})).status).toBe(4);const afterMark=await backend.call('/wfInstance/info?wfInstanceId='+execution);expect(afterMark.peworkflowDAG.nodes.find(n=>String(n.nodeId)===first).status).toBe(5);expect(afterMark.status).toBe(3);await clickAndResponse(page,'/wfInstance/retry',()=>page.locator('.instance-actions').getByRole('button',{name:'Retry',exact:true}).click());const recovered=await waitWorkflow(backend,execution,[4]);expect(recovered.peworkflowDAG.nodes.find(n=>String(n.nodeId)===first).status).toBe(5);expect(recovered.peworkflowDAG.nodes.find(n=>String(n.nodeId)===second).status).toBe(5);await testInfo.attach('workflow-mark-retry-results',{body:JSON.stringify({workflowId:id,execution,failedNodes:failed.peworkflowDAG.nodes,retriedNodes:retried.peworkflowDAG.nodes,markedNodes:afterMark.peworkflowDAG.nodes,recoveredNodes:recovered.peworkflowDAG.nodes,originalRetriedJobStillFailed:true}),contentType:'application/json'});
  } finally {await clean(backend,workflows,jobs,instances);}
});

test('UI-023 · running workflow stop, management copy/enable/delete and page reset',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(150_000);await enterSamples(page,credentials);const jobs=[],workflows=[],instances=[];
  try {
    const name=`${runId}_workflow_slow`;jobs.push(await createJob(page,backend,name,timeoutProcessor,'30000'));await newWorkflow(page,`${runId}_workflow_stop`);await importJob(page,name);const id=await saveWorkflow(page);workflows.push(id);const execution=await runWorkflow(page,id);instances.push(execution);const running=await waitWorkflow(backend,execution,[2]);await page.goto('/#/oms/wfInstanceDetail?wfInstanceId='+execution);await expect(page.locator('.instance-actions')).toBeVisible();const runningNode=running.peworkflowDAG.nodes[0];await expect.poll(async()=> (await backend.call('/instance/detailPlus',{method:'POST',data:{appId:backend.appId,instanceId:String(runningNode.instanceId)}})).status).toBe(3);await (await node(page,String(runningNode.nodeId))).click();await expect(page.locator('.canvas-details')).toContainText(String(runningNode.instanceId));await expect(page.locator('.canvas-details')).toContainText('Running');const cancelledStopRequests=[];const observeStop=request=>{if(request.url().split('?')[0].endsWith('/wfInstance/stop'))cancelledStopRequests.push(request.url());};page.on('request',observeStop);await page.locator('.instance-actions').getByRole('button',{name:'Stop',exact:true}).click();await confirmDialog(page,false);expect(cancelledStopRequests).toEqual([]);page.off('request',observeStop);expect((await backend.call('/wfInstance/info?wfInstanceId='+execution)).status).toBe(2);await page.locator('.instance-actions').getByRole('button',{name:'Stop',exact:true}).click();const stopped=await clickAndResponse(page,'/wfInstance/stop',()=>confirmDialog(page));expect(stopped.success).toBe(true);await waitWorkflow(backend,execution,[10]);await page.locator('.instance-actions').getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.instance-heading')).toContainText('Stopped');
    let row=await findWorkflow(page,id);await row.locator('.el-switch').click();await expect.poll(async()=> (await workflowInfo(backend,id)).enable).toBe(false);await page.reload();row=await findWorkflow(page,id);await expect(row.getByRole('switch')).not.toBeChecked();await row.locator('.el-switch').click();await expect.poll(async()=> (await workflowInfo(backend,id)).enable).toBe(true);await page.reload();row=await findWorkflow(page,id);await expect(row.getByRole('switch')).toBeChecked();const copied=await clickAndResponse(page,'/workflow/copy',()=>row.getByRole('button',{name:'Copy',exact:true}).click());expect(copied.success).toBe(true);const copyId=String(copied.data);workflows.push(copyId);expect((await workflowInfo(backend,copyId)).peworkflowDAG.nodes).toHaveLength(1);row=await findWorkflow(page,copyId);const cancelledDeleteRequests=[];const observeDelete=request=>{if(request.url().split('?')[0].endsWith('/workflow/delete'))cancelledDeleteRequests.push(request.url());};page.on('request',observeDelete);await row.getByRole('button',{name:'Delete',exact:true}).click();await confirmDialog(page,false);expect(cancelledDeleteRequests).toEqual([]);page.off('request',observeDelete);expect(await workflowInfo(backend,copyId)).toBeTruthy();await row.getByRole('button',{name:'Delete',exact:true}).click();await selectors.confirm(page).getByRole('button',{name:/^(OK|Confirm)$/}).click();await expect(selectors.row(page,String(copyId))).not.toBeVisible();workflows.splice(workflows.indexOf(copyId),1);await page.reload();await input(page.locator('main'),'Workflow ID',copyId);await clickAndResponse(page,'/workflow/list',()=>page.getByRole('button',{name:'Query',exact:true}).click());await expect(page.locator('.el-table__body-wrapper tr')).toHaveCount(0);
    await page.getByRole('button',{name:'Reset',exact:true}).click();await expect(page.locator('.el-table')).toBeVisible();await page.goto('/#/oms/wfinstance');await input(page.locator('main'),'WorkflowInstanceId',execution);await page.getByRole('button',{name:'Query',exact:true}).click();await expect(selectors.row(page,execution)).toContainText('Stopped');await page.getByRole('button',{name:'Reset',exact:true}).click();await testInfo.attach('workflow-stop-results',{body:JSON.stringify({workflowId:id,execution,runningNode,stopCancelledStatus:2,cancelledStopRequestCount:cancelledStopRequests.length,cancelledDeleteRequestCount:cancelledDeleteRequests.length,disableEnableStateSurvivedHardRefresh:true,stoppedStatus:10,copiedWorkflowId:copyId,copyDeleteCancelled:true,copyDeleteConfirmed:true}),contentType:'application/json'});
  } finally {await clean(backend,workflows,jobs,instances);}
});

test('UI-021/022/023/034 · import selections across pages, parallel join, all metadata, new tabs and explicit invalid inputs',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(360_000);await enterSamples(page,credentials);const jobs=[],workflows=[],instances=[];
  try {
    const prefix=`${runId}_workflow_bulk_`;for(let index=0;index<9;index++)jobs.push(await createJob(page,backend,prefix+index));
    await newWorkflow(page,`${runId}_workflow_join`);await page.locator('.canvas-toolbar').getByRole('button',{name:/Import job/}).click();const drawer=page.getByRole('dialog').filter({visible:true}).last();await input(drawer,'Keyword',prefix);await clickAndResponse(page,'/job/list',()=>drawer.getByRole('button',{name:'Query',exact:true}).click());await expect(drawer.locator('.el-table__body-wrapper tr').filter({hasText:prefix})).toHaveCount(8);const selectedJobs=[];
    for(const index of [0,1]){const row=drawer.locator('.el-table__body-wrapper tr').nth(index);selectedJobs.push((await row.locator('td').nth(1).innerText()).trim());await row.locator('.el-checkbox').click();}
    await drawer.locator('.el-pagination').getByText('2',{exact:true}).click();await expect(drawer.locator('.el-table__body-wrapper tr')).toHaveCount(1);selectedJobs.push((await drawer.locator('.el-table__body-wrapper tr').first().locator('td').nth(1).innerText()).trim());await drawer.locator('.el-table__body-wrapper tr').first().locator('.el-checkbox').click();
    const imported=await clickAndResponse(page,'/workflow/saveNode',()=>drawer.getByRole('button',{name:'Bulk Import',exact:true}).click());expect(imported.success).toBe(true);expect(imported.data).toHaveLength(3);expect(imported.data.map(n=>String(n.jobId)).sort()).toEqual(selectedJobs.sort());await expect(drawer).not.toBeVisible();const [left,right,join]=imported.data.map(n=>String(n.id));await connect(page,left,join);await connect(page,right,join);const id=await saveWorkflow(page);workflows.push(id);
    const execution=await runWorkflow(page,id);instances.push(execution);const result=await waitWorkflow(backend,execution,[4]);expect(result.peworkflowDAG.nodes.every(n=>n.status===5)).toBe(true);const actualDetails=Object.fromEntries(await Promise.all(result.peworkflowDAG.nodes.map(async current=>[String(current.nodeId),await backend.call('/instance/detailPlus',{method:'POST',data:{appId:backend.appId,instanceId:String(current.instanceId)}})])));for(const upstream of [left,right])expect(Date.parse(actualDetails[join].actualTriggerTime)).toBeGreaterThanOrEqual(Date.parse(actualDetails[upstream].finishedTime));await testInfo.attach('workflow-parallel-timing',{body:JSON.stringify(Object.fromEntries(Object.entries(actualDetails).map(([nodeId,detail])=>[nodeId,{actualTriggerTime:detail.actualTriggerTime,finishedTime:detail.finishedTime,status:detail.status}]))),contentType:'application/json'});
    await page.goto('/#/oms/workflowEditor?workflowId='+id);await expect(page.locator('.dag-node')).toHaveCount(3);await input(page.locator('main'),'Workflow name',`${runId}_workflow_join_edited`);await input(page.locator('main'),'Description','全字段😀 metadata');await choose(page,page.locator('main'),'Schedule info','CRON');await page.getByPlaceholder('Cron expression for CRON or empty for API').fill('0 0 0 * * ?');await page.getByRole('combobox',{name:'Start time',exact:true}).fill('2028-01-01 00:00:00');await page.getByRole('combobox',{name:'Start time',exact:true}).press('Enter');await page.getByRole('combobox',{name:'Finished time',exact:true}).fill('2029-01-01 00:00:00');await page.getByRole('combobox',{name:'Finished time',exact:true}).press('Enter');await page.getByRole('spinbutton',{name:'Max instance num',exact:true}).fill('2');await page.getByRole('spinbutton',{name:'Max instance num',exact:true}).press('Tab');
    const alarm=formItem(page.locator('main'),'Alarm config').getByRole('combobox');await alarm.focus();await alarm.press('ArrowDown');const menuId=await alarm.getAttribute('aria-controls');expect(menuId).toBeTruthy();const option=page.locator('[id="'+menuId+'"]').getByRole('option').first();await expect(option).toBeVisible();await option.click();await expect(formItem(page.locator('main'),'Alarm config').locator('.el-tag')).toHaveCount(1);await page.locator('.editor-heading h2').click();const request=page.waitForRequest(r=>r.url().split('?')[0].endsWith('/workflow/save')&&r.method()==='POST');await saveWorkflow(page);const sent=(await request).postDataJSON();expect(sent.notifyUserIds).toHaveLength(1);const read=await workflowInfo(backend,id);expect(read).toMatchObject({wfName:`${runId}_workflow_join_edited`,wfDescription:'全字段😀 metadata',timeExpressionType:'CRON',timeExpression:'0 0 0 * * ?',maxWfInstanceNum:2});expect(read.notifyUserIds.map(String)).toEqual(sent.notifyUserIds.map(String));expect(read.lifeCycle).toMatchObject({start:1830268800000,end:1861891200000});
    const cronResult=await clickAndResponse(page,'/validate/timeExpression',()=>page.getByRole('button',{name:'Validate',exact:true}).click());expect(cronResult.success).toBe(true);expect(cronResult.data.length).toBeGreaterThan(0);await expect(selectors.dialog(page).locator('.trigger-time')).toHaveCount(cronResult.data.length);await expect(selectors.dialog(page)).not.toContainText('Invalid Date');await selectors.dialog(page).getByRole('button',{name:'Close this dialog'}).click();
    await (await node(page,join)).click();const json='{"message":"中文😀",\n "quote":"\\\"", "line":"first\\nsecond"}';await input(page.locator('.node-panel'),'Node parameter',json);await saveWorkflow(page);await page.reload();await (await node(page,join)).click();await expect(formItem(page.locator('.node-panel'),'Node parameter').locator('textarea')).toHaveValue(json);await testInfo.attach('workflow-all-fields-screen',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
    const url=page.url();const tab=await page.context().newPage();await tab.goto(url);await expect(tab.locator('.dag-node')).toHaveCount(3);await expect(tab.locator('.editor-heading')).toContainText(`${runId}_workflow_join_edited`);await tab.close();await page.locator('.editor-heading').getByRole('button',{name:'Back',exact:true}).click();await expect(page).toHaveURL(/oms\/workflow$/);await page.goBack();await expect(page).toHaveURL(new RegExp('workflowId='+id));await expect(page.locator('.dag-node')).toHaveCount(3);
    const control=await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.canvas-toolbar').getByRole('button',{name:/Condition/}).click());const condition=String(control.data[0].id);await connect(page,condition,left,'Y');await connect(page,condition,right,'N');await connect(page,condition,join,'Y');await expect(page.locator('.dag-edge')).toHaveCount(4);await expect(page.locator('.el-message--warning').last()).toContainText(/condition|branch/i);
    await editCondition(page,condition,'return true');await (await node(page,condition)).click();const editor=page.locator('.node-panel .monaco-editor');await editor.click({position:{x:100,y:30}});await page.keyboard.press('ControlOrMeta+A');await page.keyboard.press('Backspace');await page.keyboard.press('Delete');await expect(page.locator('.dag-node')).toHaveCount(4);const invalid=await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.node-panel').getByRole('button',{name:'Save',exact:true}).click());expect(invalid.success).toBe(false);expect((await workflowInfo(backend,id)).peworkflowDAG.nodes).toHaveLength(3);await editCondition(page,condition,'return true');await (await node(page,condition)).click();await page.locator('.workflow-canvas').press('Delete');await expect(page.locator('.dag-node')).toHaveCount(3);await expect(page.locator('.dag-edge')).toHaveCount(2);await saveWorkflow(page);await page.reload();await expect(page.locator('.dag-node')).toHaveCount(3);
    await page.goto('/#/oms/workflowEditor');await expect(page.locator('.dag-node')).toHaveCount(0);await input(page.locator('main'),'Workflow name',`${runId}_empty`);await page.locator('.editor-heading').getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.el-message--warning').last()).toContainText(/Import a job|empty/i);await page.goto('/#/oms/wfInstanceDetail');await expect(page).toHaveURL(/oms\/wfinstance/);await expect(page.locator('.el-message--warning').last()).toContainText(/workflow instance/i);
    await testInfo.attach('workflow-fields',{body:JSON.stringify({workflowId:id,selectedJobIds:selectedJobs,notifyUserIds:sent.notifyUserIds.map(String),lifecycle:read.lifeCycle}),contentType:'application/json'});
  } finally {await clean(backend,workflows,jobs,instances);}
});

test('UI-021/022/023/025 · real invalid Groovy, disabled and skip-failed nodes, ID switching and concurrency failure',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(300_000);await enterSamples(page,credentials);const jobs=[],workflows=[],instances=[];
  try {
    const badName=`${runId}_workflow_skip_failed`,goodName=`${runId}_workflow_skip_next`,slowName=`${runId}_workflow_concurrent`;
    jobs.push(await createJob(page,backend,badName,demoProcessor,'failed'));jobs.push(await createJob(page,backend,goodName));jobs.push(await createJob(page,backend,slowName,timeoutProcessor,'30000'));
    await newWorkflow(page,`${runId}_workflow_skip_enabled`);const disabled=await importJob(page,goodName),bad=await importJob(page,badName),good=await importJob(page,goodName);await connect(page,disabled,bad);await connect(page,bad,good);
    await (await node(page,disabled)).click();await page.locator('.node-panel .el-switch').nth(0).click();await (await node(page,bad)).click();await page.locator('.node-panel .el-switch').nth(1).click();expect(disabled).not.toBe(good);const skipId=await saveWorkflow(page);workflows.push(skipId);
    const skipExecution=await runWorkflow(page,skipId);instances.push(skipExecution);const skipped=await waitWorkflow(backend,skipExecution,[4]);const disabledNode=skipped.peworkflowDAG.nodes.find(n=>String(n.nodeId)===disabled),badNode=skipped.peworkflowDAG.nodes.find(n=>String(n.nodeId)===bad);expect(disabledNode.enable).toBe(false);expect(disabledNode.instanceId ?? null).toBeNull();expect(badNode).toMatchObject({status:4,skipWhenFailed:true});expect(skipped.peworkflowDAG.nodes.find(n=>String(n.nodeId)===good).status).toBe(5);
    await page.goto('/#/oms/wfInstanceDetail?wfInstanceId='+skipExecution);await (await node(page,bad)).click();await expect(page.locator('.canvas-details')).toContainText(String(badNode.instanceId));await expect(page.locator('.canvas-details')).toContainText('Failed');
    await newWorkflow(page,`${runId}_workflow_invalid_script`);const yes=await importJob(page,goodName),no=await importJob(page,goodName);const control=await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.canvas-toolbar').getByRole('button',{name:/Condition/}).click());const condition=String(control.data[0].id);await connect(page,condition,yes,'Y');await connect(page,condition,no,'N');await editCondition(page,condition,'return this is ??? invalid groovy');const invalidId=await saveWorkflow(page);workflows.push(invalidId);const invalidExecution=await runWorkflow(page,invalidId);instances.push(invalidExecution);const invalid=await waitWorkflow(backend,invalidExecution,[3]);expect(invalid.result).toContain("can't evaluate decision node");expect(invalid.peworkflowDAG.nodes.filter(n=>n.nodeType===1).every(n=>n.instanceId==null)).toBe(true);
    await page.goto('/#/oms/wfInstanceDetail?wfInstanceId='+invalidExecution);await expect(page.locator('.instance-heading')).toContainText('Failed');await expect(page.locator('.instance-summary')).toContainText("can't evaluate decision node");await testInfo.attach('invalid-groovy-visible-result',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});await (await node(page,condition)).click();await expect(page.locator('.canvas-details .monaco-editor')).toBeVisible();
    await page.goto('/#/oms/workflowEditor?workflowId='+invalidId);await (await node(page,condition)).click();await input(page.locator('.node-panel'),'Node name','unsaved discard');await page.evaluate(id=>{location.hash='/oms/workflowEditor?workflowId='+id;},skipId);await expect(page.locator('.editor-heading')).toContainText(`${runId}_workflow_skip_enabled`);await expect(page.locator('.dag-node')).toHaveCount(3);await expect(page.locator('.node-panel')).toHaveCount(0);expect((await workflowInfo(backend,invalidId)).peworkflowDAG.nodes.find(n=>String(n.nodeId)===condition).nodeName).not.toBe('unsaved discard');
    await page.goto('/#/oms/workflowEditor?workflowId=900000000000000001');await expect(page).toHaveURL(/oms\/workflow$/);await expect(page.locator('.el-message--warning').last()).toBeVisible();await page.goto('/#/oms/wfInstanceDetail?wfInstanceId=900000000000000001');await expect(page).toHaveURL(/oms\/wfinstance$/);await expect(page.locator('.el-message--warning').last()).toBeVisible();
    await newWorkflow(page,`${runId}_workflow_limit`);await importJob(page,slowName);const limitedId=await saveWorkflow(page);workflows.push(limitedId);const running=await runWorkflow(page,limitedId);instances.push(running);await waitWorkflow(backend,running,[2]);const rejected=await runWorkflow(page,limitedId);instances.push(rejected);const concurrencyFailure=await waitWorkflow(backend,rejected,[3]);expect(concurrencyFailure.result).toMatch(/concurr|instance|并发/i);await page.goto('/#/oms/wfInstanceDetail?wfInstanceId='+rejected);await expect(page.locator('.instance-heading')).toContainText('Failed');await expect(page.locator('.instance-summary')).toContainText(concurrencyFailure.result);
    await page.evaluate(id=>{location.hash='/oms/wfInstanceDetail?wfInstanceId='+id;},running);await expect(page.locator('.instance-heading')).toContainText(running);await page.locator('.instance-actions').getByRole('button',{name:'Stop',exact:true}).click();await clickAndResponse(page,'/wfInstance/stop',()=>confirmDialog(page));await waitWorkflow(backend,running,[10]);await clickAndResponse(page,'/wfInstance/retry',()=>page.locator('.instance-actions').getByRole('button',{name:'Retry',exact:true}).click());await waitWorkflow(backend,running,[4]);await page.locator('.instance-actions').getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.instance-heading')).toContainText('Success');
    await testInfo.attach('workflow-control-results',{body:JSON.stringify({skipExecution,disabledInstanceId:disabledNode.instanceId??null,skipFailedJobInstanceId:String(badNode.instanceId),invalidExecution,invalidResult:invalid.result,concurrencyExecution:rejected,concurrencyResult:concurrencyFailure.result}),contentType:'application/json'});
  } finally {await clean(backend,workflows,jobs,instances);}
});

test('UI-020/021/022/034 · independent copied graph, lifecycle boundary guard and readable deterministic layout',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(180_000);await enterSamples(page,credentials);const jobs=[],workflows=[];
  try {
    const jobName=`${runId}_workflow_这是一个很长的中文节点名称用于验证缩放和图形文字可读性😀`;jobs.push(await createJob(page,backend,jobName));await newWorkflow(page,`${runId}_workflow_layout_original`);const first=await importJob(page,jobName,jobs[0]),second=await importJob(page,jobName);await connect(page,first,second);
    await page.getByRole('combobox',{name:'Finished time',exact:true}).fill('2030-01-01 00:00:00');await page.getByRole('combobox',{name:'Finished time',exact:true}).press('Enter');const id=await saveWorkflow(page);workflows.push(id);const original=await workflowInfo(backend,id);expect(original.lifeCycle).toMatchObject({start:null,end:1893427200000});await saveWorkflow(page);expect((await backend.call('/workflow/list',{method:'POST',data:{appId:backend.appId,keyword:`${runId}_workflow_layout_original`,index:0,pageSize:100}})).data).toHaveLength(1);
    await page.locator('.canvas-toolbar').getByRole('button',{name:'Auto Fit',exact:true}).click();const layout=await page.locator('.dag-node').evaluateAll(elements=>Object.fromEntries(elements.map(el=>[el.dataset.nodeId,el.getAttribute('transform')])));const originalPosition=await (await node(page,first)).getAttribute('transform'),box=await (await node(page,first)).boundingBox();await page.mouse.move(box.x+40,box.y+30);await page.mouse.down();await page.mouse.move(box.x+65,box.y+90,{steps:8});await page.mouse.up();expect(await (await node(page,first)).getAttribute('transform')).not.toBe(originalPosition);await saveWorkflow(page);await page.reload();await expect(page.locator('.dag-node')).toHaveCount(2);await page.locator('.canvas-toolbar').getByRole('button',{name:'Auto Fit',exact:true}).click();expect(await page.locator('.dag-node').evaluateAll(elements=>Object.fromEntries(elements.map(el=>[el.dataset.nodeId,el.getAttribute('transform')])))).toEqual(layout);expect((await workflowInfo(backend,id)).peworkflowDAG).toEqual(original.peworkflowDAG);
    await page.locator('.canvas-toolbar').getByRole('button',{name:'Zoom out',exact:true}).click();await page.locator('.canvas-toolbar').getByRole('button',{name:'Zoom In',exact:true}).click();await page.locator('.canvas-toolbar').getByRole('button',{name:'Auto Fit',exact:true}).click();for(const current of [first,second]){await expect((await node(page,current)).locator('title')).toHaveText(jobName);const bounds=await (await node(page,current)).boundingBox(),svg=await page.locator('.dag-svg').boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(svg.x-1);expect(bounds.x+bounds.width).toBeLessThanOrEqual(svg.x+svg.width+1);}
    await (await node(page,first)).click();await input(page.locator('.node-panel'),'Node parameter','draft must not persist');await page.getByRole('combobox',{name:'Start time',exact:true}).fill('2031-01-01 00:00:00');await page.getByRole('combobox',{name:'Start time',exact:true}).press('Enter');const writes=[];const collect=request=>{if(['/workflow/save','/workflow/saveNode'].some(path=>request.url().split('?')[0].endsWith(path)))writes.push(request.url());};page.on('request',collect);await page.locator('.editor-heading').getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.el-message--warning').last()).toContainText(/life|start|end/i);expect(writes).toEqual([]);page.off('request',collect);expect((await workflowInfo(backend,id)).peworkflowDAG).toEqual(original.peworkflowDAG);await page.reload();
    const row=await findWorkflow(page,id);const copied=await clickAndResponse(page,'/workflow/copy',()=>row.getByRole('button',{name:'Copy',exact:true}).click());expect(copied.success).toBe(true);const copyId=String(copied.data);workflows.push(copyId);await expect(page).toHaveURL(new RegExp('workflowId='+copyId));await expect(page.locator('.dag-node')).toHaveCount(2);const beforeCopy=await workflowInfo(backend,copyId);expect(beforeCopy.peworkflowDAG.nodes.map(n=>String(n.nodeId)).some(nodeId=>[first,second].includes(nodeId))).toBe(false);await input(page.locator('main'),'Workflow name',`${runId}_workflow_copy_edited`);const copyFirst=String(beforeCopy.peworkflowDAG.nodes[0].nodeId);await (await node(page,copyFirst)).click();await input(page.locator('.node-panel'),'Node parameter','copy-specific 中文😀');await saveWorkflow(page);const afterCopy=await workflowInfo(backend,copyId);expect(afterCopy.peworkflowDAG.nodes.find(n=>String(n.nodeId)===copyFirst).nodeParams).toBe('copy-specific 中文😀');expect((await workflowInfo(backend,id)).peworkflowDAG).toEqual(original.peworkflowDAG);expect((await workflowInfo(backend,id)).wfName).toBe(`${runId}_workflow_layout_original`);
    await testInfo.attach('workflow-layout-copy',{body:JSON.stringify({workflowId:id,copyId,originalNodeIds:[first,second],copyNodeIds:beforeCopy.peworkflowDAG.nodes.map(n=>String(n.nodeId)),layout,lifecycle:original.lifeCycle}),contentType:'application/json'});await testInfo.attach('readable-native-graph',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
  } finally {await clean(backend,workflows,jobs);}
});

test('UI-022 · delayed real save responses cannot overwrite another workflow identity or draft',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(180_000);await enterSamples(page,credentials);const jobs=[],workflows=[];let release;
  async function holdRealResponse(endpoint) {
    let ready,delivered;const pending=new Promise(resolve=>{ready=resolve;}),finished=new Promise(resolve=>{delivered=resolve;}),gate=new Promise(resolve=>{release=resolve;});
    await page.route('**'+endpoint,async route=>{const response=await route.fetch();ready();await gate;await route.fulfill({response});delivered();},{times:1});
    return {pending,finished};
  }
  try {
    const jobName=`${runId}_workflow_delayed_job`;jobs.push(await createJob(page,backend,jobName));await newWorkflow(page,`${runId}_workflow_delayed_old`);const oldNode=await importJob(page,jobName);const oldId=await saveWorkflow(page);workflows.push(oldId);await newWorkflow(page,`${runId}_workflow_delayed_new`);const newNode=await importJob(page,jobName);const newId=await saveWorkflow(page);workflows.push(newId);
    await page.goto('/#/oms/workflowEditor?workflowId='+oldId);await (await node(page,oldNode)).click();await input(page.locator('.node-panel'),'Node parameter','old node write accepted by Server');const oldNodes=await holdRealResponse('/workflow/saveNode'),graphWrites=[];const collect=request=>{if(request.url().split('?')[0].endsWith('/workflow/save'))graphWrites.push(request.postDataJSON());};page.on('request',collect);await page.locator('.editor-heading').getByRole('button',{name:'Save',exact:true}).click();await oldNodes.pending;
    await page.evaluate(id=>{location.hash='/oms/workflowEditor?workflowId='+id;},newId);await expect(page.locator('.editor-heading')).toContainText(`${runId}_workflow_delayed_new`);await (await node(page,newNode)).click();await input(page.locator('.node-panel'),'Node parameter','new draft remains 中文😀');release();await oldNodes.finished;await expect(page.locator('.editor-heading').getByRole('button',{name:'Save',exact:true})).not.toHaveClass(/is-loading/);expect(graphWrites).toEqual([]);page.off('request',collect);await expect(formItem(page.locator('.node-panel'),'Node parameter').locator('textarea')).toHaveValue('new draft remains 中文😀');expect((await workflowInfo(backend,newId)).peworkflowDAG.nodes.map(n=>String(n.nodeId))).toEqual([newNode]);await saveWorkflow(page);expect((await workflowInfo(backend,newId)).peworkflowDAG.nodes[0].nodeParams).toBe('new draft remains 中文😀');expect((await workflowInfo(backend,oldId)).peworkflowDAG.nodes[0].nodeParams).toBe('old node write accepted by Server');
    await page.evaluate(id=>{location.hash='/oms/workflowEditor?workflowId='+id;},oldId);await expect(page.locator('.editor-heading')).toContainText(`${runId}_workflow_delayed_old`);await input(page.locator('main'),'Workflow name',`${runId}_workflow_delayed_saved`);const oldSave=await holdRealResponse('/workflow/save');await page.locator('.editor-heading').getByRole('button',{name:'Save',exact:true}).click();await oldSave.pending;await page.evaluate(id=>{location.hash='/oms/workflowEditor?workflowId='+id;},newId);await expect(page.locator('.editor-heading')).toContainText(`${runId}_workflow_delayed_new`);release();await oldSave.finished;await expect(page.locator('.editor-heading').getByRole('button',{name:'Save',exact:true})).not.toHaveClass(/is-loading/);await expect(page).toHaveURL(new RegExp('workflowId='+newId));expect((await workflowInfo(backend,oldId)).wfName).toBe(`${runId}_workflow_delayed_saved`);expect((await workflowInfo(backend,newId)).wfName).toBe(`${runId}_workflow_delayed_new`);
    await testInfo.attach('delayed-real-response-result',{body:JSON.stringify({oldId,newId,oldNode,newNode,realServerNodeWriteReadBack:true,realServerWorkflowWriteReadBack:true,newWorkflowRemainedIndependent:true,oldGraphNotWrittenIntoNewWorkflow:true}),contentType:'application/json'});
  } finally {release?.();await page.unrouteAll({behavior:'wait'});await clean(backend,workflows,jobs);}
});

test('UI-021/034 · conditional branch reconnection and native Monaco JSON/JavaScript/Groovy mode round trips',async({page,backend,credentials},testInfo)=>{
  test.setTimeout(150_000);await enterSamples(page,credentials);const jobs=[],workflows=[];
  try {
    const jobName=`${runId}_workflow_language_job`;jobs.push(await createJob(page,backend,jobName));await newWorkflow(page,`${runId}_workflow_languages`);const a=await importJob(page,jobName),b=await importJob(page,jobName),replacement=await importJob(page,jobName);const control=await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.canvas-toolbar').getByRole('button',{name:/Condition/}).click());const condition=String(control.data[0].id);await editCondition(page,condition,'return true');await connect(page,condition,a,'Y');await connect(page,condition,b,'N');await connect(page,condition,replacement,'Y');await expect(page.locator('.dag-edge')).toHaveCount(2);
    await page.locator('.dag-edge').filter({has:page.locator('.branch-label',{hasText:'Y'})}).locator('.edge-hit').click({force:true});await page.locator('.canvas-toolbar').getByRole('button',{name:'Delete',exact:true}).click();await expect(page.locator('.dag-edge')).toHaveCount(1);await connect(page,condition,replacement,'Y');await expect(page.locator('.dag-edge')).toHaveCount(2);const id=await saveWorkflow(page);workflows.push(id);const graph=await workflowInfo(backend,id);expect(graph.peworkflowDAG.edges.find(edge=>String(edge.to)===replacement).property).toBe('true');expect(graph.peworkflowDAG.edges.find(edge=>String(edge.to)===b).property).toBe('false');expect(graph.peworkflowDAG.edges.some(edge=>String(edge.to)===a)).toBe(false);
    await (await node(page,condition)).click();await page.locator('.node-panel .code-toolbar .el-select').click();await page.getByRole('option',{name:'JSON',exact:true}).click();const json='{"message":"中文😀",\n "quote":"\\\"", "line":"first\\nsecond"}';await editCondition(page,condition,json,true);expect((await workflowInfo(backend,id)).peworkflowDAG.nodes.find(current=>String(current.nodeId)===condition).nodeParams).toBe(json);
    await page.locator('.node-panel .code-toolbar .el-select').click();await page.getByRole('option',{name:'JavaScript',exact:true}).click();await clickAndResponse(page,'/workflow/saveNode',()=>page.locator('.node-panel').getByRole('button',{name:'Save',exact:true}).click());expect((await workflowInfo(backend,id)).peworkflowDAG.nodes.find(current=>String(current.nodeId)===condition).nodeParams).toBe(json);await editCondition(page,condition,'return true');await page.locator('.node-panel .code-toolbar .el-select').click();await page.getByRole('option',{name:'Groovy',exact:true}).click();await saveWorkflow(page);await page.reload();await expect(page.locator('.dag-edge')).toHaveCount(2);await (await node(page,condition)).click();await expect(page.locator('.node-panel .code-toolbar')).toContainText('Groovy');expect((await workflowInfo(backend,id)).peworkflowDAG.nodes.find(current=>String(current.nodeId)===condition).nodeParams).toBe('return true');
    await testInfo.attach('monaco-and-reconnection',{body:JSON.stringify({workflowId:id,condition,removedYTarget:a,newYTarget:replacement,unchangedNTarget:b,persistedEdges:graph.peworkflowDAG.edges,jsonRoundTrip:json,languageSwitchDidNotTransformCode:true,restoredExecutableGroovy:'return true'}),contentType:'application/json'});
  } finally {await clean(backend,workflows,jobs);}
});


test('UI-024 · Workflow instance list cancel/confirm stop, failed retry and successful recovery',async({page,backend,credentials},info)=>{
  test.setTimeout(240_000);await enterSamples(page,credentials);const jobs=[],workflows=[],instances=[];
  async function listRow(id){await page.goto('/#/oms/wfinstance');await input(page.locator('main'),'WorkflowInstanceId',id);await clickAndResponse(page,'/wfInstance/list',()=>page.getByRole('button',{name:'Query',exact:true}).click());const row=selectors.row(page,String(id));await expect(row).toBeVisible();return row;}
  try {
    const slowName=`${runId}_list_slow`;jobs.push(await createJob(page,backend,slowName,timeoutProcessor,'30000'));await newWorkflow(page,`${runId}_list_stop`);await importJob(page,slowName);const slowId=await saveWorkflow(page);workflows.push(slowId);const slow=await runWorkflow(page,slowId);instances.push(slow);await waitWorkflow(backend,slow,[2]);let row=await listRow(slow);await expect(row).toContainText('Running');let stopRequests=0;const observe=request=>{if(request.url().split('?')[0].endsWith('/wfInstance/stop'))stopRequests++;};page.on('request',observe);await row.getByRole('button',{name:'Stop',exact:true}).click();await confirmDialog(page,false);expect(stopRequests).toBe(0);expect((await backend.call('/wfInstance/info?wfInstanceId='+slow)).status).toBe(2);await variantProof(info,'UI-024','wfinstance-stop-cancel',{wfInstanceId:slow,realListButton:true,zeroRequests:stopRequests,independentStatus:2});
    await row.getByRole('button',{name:'Stop',exact:true}).click();const stopped=await clickAndResponse(page,'/wfInstance/stop',()=>confirmDialog(page));expect(stopped.success).toBe(true);await waitWorkflow(backend,slow,[10]);await clickAndResponse(page,'/wfInstance/list',()=>page.getByRole('button',{name:'Refresh',exact:true}).click());await expect(selectors.row(page,slow)).toContainText('Stopped');page.off('request',observe);await variantProof(info,'UI-024','wfinstance-stop',{wfInstanceId:slow,confirmedActualListButton:true,status:10});
    const failedName=`${runId}_list_failed`;const job=await createJob(page,backend,failedName,demoProcessor,'failed');jobs.push(job);const nextName=`${runId}_list_next`;jobs.push(await createJob(page,backend,nextName));await newWorkflow(page,`${runId}_list_retry`);const failedNode=await importJob(page,failedName),nextNode=await importJob(page,nextName);await connect(page,failedNode,nextNode);const id=await saveWorkflow(page);workflows.push(id);const failed=await runWorkflow(page,id);instances.push(failed);const before=await waitWorkflow(backend,failed,[3]);row=await listRow(failed);await expect(row).toContainText('Failed');const retryFailed=await clickAndResponse(page,'/wfInstance/retry',()=>row.getByRole('button',{name:'Retry',exact:true}).click());expect(retryFailed.success).toBe(true);const again=await waitWorkflow(backend,failed,[3]);expect(String(again.peworkflowDAG.nodes[0].instanceId)).not.toBe(String(before.peworkflowDAG.nodes[0].instanceId));await clickAndResponse(page,'/wfInstance/list',()=>page.getByRole('button',{name:'Refresh',exact:true}).click());await expect(selectors.row(page,failed)).toContainText('Failed');
    await page.goto('/#/oms/wfInstanceDetail?wfInstanceId='+failed);await (await node(page,failedNode)).click();const marked=await clickAndResponse(page,'/wfInstance/markNodeAsSuccess',()=>page.locator('.canvas-toolbar').getByRole('button',{name:'Marked Success',exact:true}).click());expect(marked.success).toBe(true);const failedChild=String(again.peworkflowDAG.nodes.find(n=>String(n.nodeId)===failedNode).instanceId);expect((await backend.call('/instance/detailPlus',{method:'POST',data:{instanceId:failedChild}})).status).toBe(4);row=await listRow(failed);const retrySuccess=await clickAndResponse(page,'/wfInstance/retry',()=>row.getByRole('button',{name:'Retry',exact:true}).click());expect(retrySuccess.success).toBe(true);const recovered=await waitWorkflow(backend,failed,[4]);const succeeded=recovered.peworkflowDAG.nodes.find(n=>String(n.nodeId)===nextNode);expect(succeeded.status).toBe(5);expect((await backend.call('/instance/detailPlus',{method:'POST',data:{instanceId:String(succeeded.instanceId)}})).status).toBe(5);await clickAndResponse(page,'/wfInstance/list',()=>page.getByRole('button',{name:'Refresh',exact:true}).click());await expect(selectors.row(page,failed)).toContainText('Success');await variantProof(info,'UI-024','wfinstance-retry',{wfInstanceId:failed,originalChildInstanceId:before.peworkflowDAG.nodes.find(n=>String(n.nodeId)===failedNode).instanceId,retriedFailedChildInstanceId:failedChild,recoveredSuccessorChildInstanceId:succeeded.instanceId,actualListRetryTwice:true,failureStillVisible:true,originalFailedChildStillFailed:true,failedNodeMarkedThroughActualDetailToolbar:true,successorExecutedByRealWorker:true,finalSuccess:4});
  } finally {await clean(backend,workflows,jobs,instances);}
});


test('UI-036 · Workflow complete original Server metadata and explicit null survive name-only editing',async({page,backend,credentials},info)=>{
  test.setTimeout(120_000);await enterSamples(page,credentials);const jobs=[],workflows=[];
  try {
    const jobName=`${runId}_metadata_job`;jobs.push(await createJob(page,backend,jobName));await newWorkflow(page,`${runId}_metadata_workflow`);await importJob(page,jobName);const id=await saveWorkflow(page);workflows.push(id);const original=await workflowInfo(backend,id);const users=await backend.call('/user/list');expect(users.length).toBeGreaterThan(0);const preset={id,appId:backend.appId,wfName:original.wfName,wfDescription:null,enable:false,timeExpressionType:'CRON',timeExpression:'0 0 1 * * ?',maxWfInstanceNum:3,notifyUserIds:[String(users[0].id)],lifeCycle:{start:null,end:1900000000000},dag:{nodes:original.peworkflowDAG.nodes.map(n=>({nodeId:String(n.nodeId)})),edges:original.peworkflowDAG.edges}};await backend.call('/workflow/save',{method:'POST',data:preset});const before=await workflowInfo(backend,id);await page.goto('/#/oms/workflowEditor?workflowId='+id);await page.reload();await expect(page.locator('.dag-node')).toHaveCount(1);await input(page.locator('main'),'Workflow name',`${runId}_metadata_renamed`);const request=page.waitForRequest(r=>r.url().split('?')[0].endsWith('/workflow/save')&&r.method()==='POST');await saveWorkflow(page);const sent=(await request).postDataJSON();await page.reload();await expect(page.locator('.editor-heading')).toContainText(`${runId}_metadata_renamed`);const after=await workflowInfo(backend,id);const fields=['wfDescription','enable','timeExpressionType','timeExpression','maxWfInstanceNum','notifyUserIds','lifeCycle','peworkflowDAG','gmtCreate'];await info.attach('workflow-metadata-before-after',{body:JSON.stringify({before,sent,after}),contentType:'application/json'});for(const field of fields)expect(after[field]).toEqual(before[field]);for(const field of fields.filter(field=>!['peworkflowDAG','gmtCreate','notifyUserIds'].includes(field)))expect(sent[field]).toEqual(before[field]);expect(sent.notifyUserIds.map(String)).toEqual(before.notifyUserIds.map(String));expect(after.wfName).toBe(`${runId}_metadata_renamed`);expect(after.wfDescription).toBeNull();expect(after.lifeCycle.start).toBeNull();await variantProof(info,'UI-036','workflow-preserve-unknown',{workflowId:id,fieldsReadBackAndPreserved:fields,before,after,explicitNullDescription:true,endOnlyLifeCyclePreserved:true,onlyNameEditedOnPage:true,hardReload:true,formalServerTypedUnknownFields:'WorkflowInfoVO does not return arbitrary future top-level keys; future DTO forwarding is tested separately at unit-contract level.',supplementalUnitReport:'.runtime/console-vue3/workflow-lifecycle-units.json',supplementalUnitAssertion:'workflow editor persisted nodes and metadata forwards unknown fields already returned by a future Server while changing only the name'});
  } finally {await clean(backend,workflows,jobs);}
});

test('UI-025/038 · stale network failures and stop confirmations cannot change the new workflow route target',async({page,backend,credentials},info)=>{
  test.setTimeout(180_000);await enterSamples(page,credentials);const jobs=[],workflows=[],instances=[],held=[],stops=[];
  async function holdOriginalAndAbort(path,idKey,id){let ready,release,done;const pending=new Promise(resolve=>{ready=resolve;}),gate=new Promise(resolve=>{release=resolve;}),finished=new Promise(resolve=>{done=resolve;});const observation={path,id:String(id),forwardedOriginalServer:false,networkAborted:false};await page.route('**'+path+'?**',async route=>{expect(new URL(route.request().url()).searchParams.get(idKey)).toBe(String(id));const response=await route.fetch();expect(response.ok()).toBe(true);observation.forwardedOriginalServer=true;ready();await gate;await route.abort('failed');observation.networkAborted=true;done();},{times:1});const value={pending,release,finished,observation};held.push(value);return value;}
  const observe=request=>{if(request.url().split('?')[0].endsWith('/wfInstance/stop'))stops.push(new URL(request.url()).searchParams.get('wfInstanceId'));};page.on('request',observe);
  try{
    const jobName=`${runId}_route_context_slow`;jobs.push(await createJob(page,backend,jobName,timeoutProcessor,'120000'));await newWorkflow(page,`${runId}_route_context_a`);await importJob(page,jobName);const workflowA=await saveWorkflow(page);workflows.push(workflowA);await newWorkflow(page,`${runId}_route_context_b`);await importJob(page,jobName);const workflowB=await saveWorkflow(page);workflows.push(workflowB);const instanceA=await runWorkflow(page,workflowA),instanceB=await runWorkflow(page,workflowB);instances.push(instanceA,instanceB);await waitWorkflow(backend,instanceA,[2]);await waitWorkflow(backend,instanceB,[2]);
    const oldEditor=await holdOriginalAndAbort('/workflow/fetch','workflowId',workflowA);await page.goto('/#/oms/workflowEditor?workflowId='+workflowA);await oldEditor.pending;await page.evaluate(id=>{location.hash='/oms/workflowEditor?workflowId='+id;},workflowB);await expect(page.locator('.editor-heading')).toContainText(`${runId}_route_context_b`);oldEditor.release();await oldEditor.finished;await page.waitForTimeout(1500);await expect(page).toHaveURL(new RegExp('workflowEditor\\?workflowId='+workflowB+'$'));await expect(page.locator('.editor-heading')).toContainText(`${runId}_route_context_b`);await expect(page.locator('.dag-node')).toHaveCount(1);
    const oldDetail=await holdOriginalAndAbort('/wfInstance/info','wfInstanceId',instanceA);await page.goto('/#/oms/wfInstanceDetail?wfInstanceId='+instanceA);await oldDetail.pending;await page.evaluate(id=>{location.hash='/oms/wfInstanceDetail?wfInstanceId='+id;},instanceB);await expect(page.locator('.instance-heading')).toContainText(instanceB);oldDetail.release();await oldDetail.finished;await page.waitForTimeout(1500);await expect(page).toHaveURL(new RegExp('wfInstanceDetail\\?wfInstanceId='+instanceB+'$'));await expect(page.locator('.instance-heading')).toContainText(instanceB);await expect(page.locator('.instance-summary')).toContainText('Running');
    await page.evaluate(id=>{location.hash='/oms/wfInstanceDetail?wfInstanceId='+id;},instanceA);await expect(page.locator('.instance-heading')).toContainText(instanceA);await page.locator('.instance-actions').getByRole('button',{name:'Stop',exact:true}).click();await expect(page.locator('.el-message-box')).toContainText(instanceA);await page.evaluate(id=>{location.hash='/oms/wfInstanceDetail?wfInstanceId='+id;},instanceB);await expect(page.locator('.instance-heading')).toContainText(instanceB);await expect(selectors.confirm(page)).not.toBeVisible();expect(stops).toEqual([]);await page.evaluate(async id=>{await document.querySelector('#app').__vue_app__.config.globalProperties.$router.push({name:'WorkflowInstanceDetail',query:{wfInstanceId:id}});},instanceA);await expect(page.locator('.instance-heading')).toContainText(instanceA);await page.locator('.instance-actions').getByRole('button',{name:'Stop',exact:true}).click();await expect(selectors.confirm(page)).toContainText(instanceA);await page.evaluate(async id=>{await document.querySelector('#app').__vue_app__.config.globalProperties.$router.push({name:'WorkflowInstanceDetail',query:{wfInstanceId:id}});},instanceB);await expect(page.locator('.instance-heading')).toContainText(instanceB);await expect(selectors.confirm(page)).toBeVisible();await expect(selectors.confirm(page)).toContainText(instanceA);await confirmDialog(page);await page.waitForTimeout(1000);expect(stops).toEqual([]);const stillA=await waitWorkflow(backend,instanceA,[2]),stillB=await waitWorkflow(backend,instanceB,[2]);await expect(page).toHaveURL(new RegExp('wfInstanceDetail\\?wfInstanceId='+instanceB+'$'));
    await page.locator('.instance-actions').getByRole('button',{name:'Stop',exact:true}).click();await expect(page.locator('.el-message-box')).toContainText(instanceB);const result=await clickAndResponse(page,'/wfInstance/stop',()=>confirmDialog(page));expect(result.success).toBe(true);await waitWorkflow(backend,instanceB,[10]);expect(stops).toEqual([instanceB]);expect((await waitWorkflow(backend,instanceA,[2])).status).toBe(2);
    const evidence={status:'PASS',testTitle:info.title,evidenceLayers:{staleNetworkResponse:'Real browser hash navigation and actual forwarded original Server request aborted at network layer',nativeHashConfirmation:'Real browser hash navigation automatically cancels ElementPlus confirmation with zero stop requests',programmaticRouteConfirmation:'Browser component/router integration fixture invokes the existing Vue Router push method; not claimed as a clickable user route action'},workflowA,workflowB,instanceA,instanceB,oldOriginalRequests:held.map(value=>value.observation),oldEditorErrorDidNotRedirectNewEditor:true,oldDetailErrorDidNotRedirectNewDetail:true,expiredStopConfirmationRequests:0,nativeHashChangeCanceledConfirmation:true,sameComponentVueRouterChangeExpiredConfirmation:true,independentStatusesAfterExpiredConfirmation:{a:stillA.status,b:stillB.status},freshStopRequestedOnlyCurrentInstance:stops,oldInstanceStillRunning:true};await fs.writeFile(info.outputPath('workflow-route-context-guard.json'),JSON.stringify(evidence,null,2));await info.attach('workflow-route-context-guard',{body:JSON.stringify(evidence),contentType:'application/json'});
  }finally{for(const value of held)value.release();await page.unrouteAll({behavior:'wait'});page.off('request',observe);await clean(backend,workflows,jobs,instances);}
});
