import { test, expect, selectors, runId, input, choose, enterSamples, saveDialog, clickAndResponse, confirmDialog } from './support.js'
import fs from 'node:fs/promises'
import http from 'node:http'
import crypto from 'node:crypto'

test('UI-017/018 · deterministic external Worker ledger: Broadcast/MR, fail-once retry and cancelled/confirmed stop', async ({ page, backend, credentials }, info) => {
  test.setTimeout(360_000)
  const jar = process.env.POWERJOB_E2E_CONTAINER_JAR
  test.skip(!jar, 'BLOCKED: a trusted LedgerProcessor JAR is required')
  await enterSamples(page, credentials)
  const events = [], attempts = new Map(), ids = [], instances = []
  let containerId
  const server = http.createServer(async (request, response) => {
    try {
      let body = ''
      for await (const chunk of request) body += chunk
      const event = JSON.parse(body)
      if (event.runId !== runId || request.method !== 'POST') { response.writeHead(403).end(); return }
      events.push({ ...event, receivedAt: Date.now() })
      const key = `${event.logicalNode}/${event.triggerKey}/${event.entityKey}`
      if (event.event === 'START') attempts.set(key, (attempts.get(key) || 0) + 1)
      response.writeHead(200, { 'Content-Type': 'application/json' }).end(JSON.stringify({ attempt: attempts.get(key) || 0 }))
    } catch { response.writeHead(400).end() }
  })
  await new Promise(resolve => server.listen(0, '0.0.0.0', resolve))
  const ledgerUrl = `http://host.docker.internal:${server.address().port}/events`
  async function proof(caseId, variantId, actual) {
    const result = { caseId, variantId, status: 'PASS', testTitle: info.title, actual }
    await fs.writeFile(info.outputPath(`variant-${caseId}-${variantId}.json`), JSON.stringify(result, null, 2))
    await info.attach(`${caseId}/${variantId}`, { body: JSON.stringify(result), contentType: 'application/json' })
  }
  async function create(mode, extra = {}) {
    await page.goto('/#/oms/job')
    await page.getByRole('button', { name: 'New job', exact: true }).click()
    const dialog = selectors.dialog(page), name = `${runId}_ledger_${mode.toLowerCase()}_${ids.length}`
    await input(dialog, 'Job name', name)
    await input(dialog, 'Job params', JSON.stringify({ runId, caseId: 'console-ui', appIdentity: 'synthetic', ledgerUrl, mode, node: name, n: 8, batchSize: 2, ...extra }))
    await choose(page, dialog, 'Execution config', { STANDALONE: 'Standalone', BROADCAST: 'Broadcast', MAP: 'MAP', MAP_REDUCE: 'MapReduce' }[mode], 0)
    await choose(page, dialog, 'Execution config', /External|EXTERNAL/, 1)
    await input(dialog, 'Execution config', `${containerId}#tech.powerjob.acceptance.fixture.LedgerProcessor`)
    await dialog.getByPlaceholder('Instance retry times', { exact: true }).fill('0')
    await dialog.getByPlaceholder('Task retry times', { exact: true }).fill('0')
    if (extra.designatedWorkers) await dialog.getByPlaceholder('Empty for all workers; ip:port,ip:port for specific', { exact: true }).fill(extra.designatedWorkers)
    await saveDialog(page, '/job/save')
    const id = (await backend.listJobs(name)).data[0].id
    ids.push(id)
    const saved = await backend.job(id)
    expect(saved.processorType).toBe('EXTERNAL')
    if (extra.designatedWorkers) expect(saved.designatedWorkers).toBe(extra.designatedWorkers)
    await page.reload()
    await input(page.locator('main'), 'Job ID', id)
    await page.getByRole('button', { name: 'Query', exact: true }).click()
    await selectors.row(page, String(id)).getByRole('button', { name: 'Edit', exact: true }).click()
    await expect(selectors.dialog(page)).toContainText('External')
    await expect(selectors.dialog(page).getByPlaceholder('Instance retry times', { exact: true })).toHaveValue('0')
    if (extra.designatedWorkers) await expect(selectors.dialog(page).getByPlaceholder('Empty for all workers; ip:port,ip:port for specific', { exact: true })).toHaveValue(extra.designatedWorkers)
    await selectors.dialog(page).getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(selectors.dialog(page)).not.toBeVisible()
    await selectors.row(page, String(id)).getByRole('button', { name: 'More', exact: true }).click()
    await page.locator('.el-dropdown-menu:visible').getByRole('button', { name: 'Export', exact: true }).click()
    await expect(selectors.dialog(page).locator('textarea')).not.toHaveValue('')
    const exported = JSON.parse(await selectors.dialog(page).locator('textarea').inputValue())
    expect(exported.processorType).toBe('EXTERNAL')
    expect(exported.jobParams).toBe(saved.jobParams)
    expect(exported.processorInfo).toBe(saved.processorInfo)
    await selectors.dialog(page).getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(selectors.dialog(page)).not.toBeVisible()
    const run = await clickAndResponse(page, '/job/run', () => selectors.row(page, String(id)).getByRole('button', { name: 'Run', exact: true }).click())
    expect(run.success).toBe(true)
    instances.push(run.data)
    return { id, instance: run.data, name }
  }
  async function row(instance) {
    await page.goto('/#/oms/instance')
    await input(page.locator('main'), 'Instance ID', instance)
    await page.locator('#instance_manager').getByRole('button', { name: 'Query', exact: true }).first().click()
    const result = selectors.row(page, String(instance))
    await expect(result).toBeVisible()
    return result
  }
  try {
    await page.goto('/#/oms/containermanage')
    await page.getByRole('button', { name: 'New container', exact: true }).click()
    const name = `${runId}_ledger_jar`
    await input(selectors.dialog(page), 'Name', name)
    await selectors.dialog(page).locator('.el-radio').filter({ hasText: 'FatJar' }).click()
    const upload = await clickAndResponse(page, '/container/jarUpload', () => selectors.dialog(page).locator('input[type="file"]').setInputFiles(jar))
    expect(upload.success).toBe(true)
    await saveDialog(page, '/container/save')
    containerId = (await backend.call('/container/list?appId=' + credentials.app_id)).find(item => item.containerName === name).id
    await page.locator('.container-card').filter({ hasText: name }).getByRole('button', { name: 'Deploy', exact: true }).click()
    await expect(page.locator('.deployment-log')).toContainText('deploy finished, congratulations!', { timeout: 90_000 })
    await selectors.dialog(page).getByRole('button', { name: 'Close this dialog' }).click()
    await expect(selectors.dialog(page)).not.toBeVisible()

    const workers = await backend.call('/system/listWorker?appId=' + credentials.app_id)
    const addresses = workers.filter(worker => worker.status !== 9999).map(worker => worker.address)
    expect(addresses).toHaveLength(2)
    const broadcast = await create('BROADCAST', { designatedWorkers: addresses.join(',') })
    await backend.waitInstance(broadcast.instance, [5])
    const commits = events.filter(event => event.logicalNode === broadcast.name && event.event === 'COMMIT')
    expect(commits).toHaveLength(2)
    expect(new Set(commits.map(event => event.worker)).size).toBe(2)
    for (const event of commits) expect(workers.map(worker => worker.address)).toContain(event.worker)
    await (await row(broadcast.instance)).getByRole('button', { name: 'Detail', exact: true }).click()
    await expect(selectors.dialog(page)).toContainText('Success')
    const broadcastDetail = await backend.call('/instance/detailPlus', { method: 'POST', data: { instanceId: broadcast.instance, customQuery: 'status in (5, 6) order by last_modified_time desc' } })
    expect(broadcastDetail.status).toBe(5)
    await proof('UI-017', 'detail-broadcast', { actualWorkers: commits.map(event => event.worker), ledgerCommits: 2, realPageDetail: true, independentDetail: true })
    await selectors.dialog(page).getByRole('button', { name: 'Close this dialog' }).click()

    const singleTarget = await create('BROADCAST', { designatedWorkers: addresses[0] })
    await backend.waitInstance(singleTarget.instance, [5])
    const singleCommits = events.filter(event => event.logicalNode === singleTarget.name && event.event === 'COMMIT')
    expect(singleCommits).toHaveLength(1)
    expect(singleCommits[0].worker).toBe(addresses[0])
    await proof('UI-012', 'designated-workers', { singleAndMultipleAddressesSaved: true, hardReloadReopenExport: true, multipleActualCommitWorkers: commits.map(event => event.worker), singleActualCommitWorker: singleCommits[0].worker })
    await proof('UI-012', 'processorType-external', { actualUISaveReloadReopenExport: true, originalParamsAndOtherFieldsKept: true, trueWorkerBusinessExecution: true })

    const map = await create('MAP')
    await backend.waitInstance(map.instance, [5])
    const mapEvents = events.filter(event => event.logicalNode === map.name)
    expect(mapEvents.filter(event => event.event === 'ROOT')).toHaveLength(1)
    expect(mapEvents.filter(event => event.event === 'COMMIT').map(event => event.value).sort((a, b) => a.i - b.i)).toEqual(Array.from({ length: 8 }, (_, i) => ({ i, square: i * i })))
    await info.attach('map-real-worker-business', { body: JSON.stringify({ inputCount: 8, exactlyEightSquaredCommits: true, oneRoot: true, actualWorkers: [...new Set(mapEvents.map(event => event.worker))] }), contentType: 'application/json' })

    const mr = await create('MAP_REDUCE')
    const mrInstance = await backend.waitInstance(mr.instance, [5])
    const mrEvents = events.filter(event => event.logicalNode === mr.name)
    expect(mrEvents.filter(event => event.event === 'ROOT')).toHaveLength(1)
    const squares = mrEvents.filter(event => event.event === 'COMMIT').map(event => event.value).sort((a, b) => a.i - b.i)
    expect(squares).toEqual(Array.from({ length: 8 }, (_, i) => ({ i, square: i * i })))
    const expectedHash = crypto.createHash('sha256').update(squares.map(value => `${value.i}:${value.square}\n`).join('')).digest('hex')
    expect(JSON.parse(mrInstance.result)).toMatchObject({ count: 8, uniqueCount: 8, sum: 140, sha256: expectedHash })
    await (await row(mr.instance)).getByRole('button', { name: 'Detail', exact: true }).click()
    await expect(selectors.dialog(page)).toContainText('uniqueCount')
    const taskQuery = selectors.dialog(page).locator('.task-query input')
    await expect(taskQuery).toBeVisible()
    await taskQuery.fill('status in (5, 6) order by last_modified_time desc')
    const queried = await clickAndResponse(page, '/instance/detailPlus', () => selectors.dialog(page).locator('.task-query').getByRole('button', { name: 'Query', exact: true }).click())
    expect(queried.success).toBe(true)
    expect(Array.isArray(queried.data.queriedTaskDetailInfoList)).toBe(true)
    const detailReadback = await backend.call('/instance/detailPlus', { method: 'POST', data: { instanceId: mr.instance, customQuery: 'status in (5, 6) order by last_modified_time desc' } })
    expect(queried.data.queriedTaskDetailInfoList).toEqual(detailReadback.queriedTaskDetailInfoList)
    await taskQuery.fill('DELETE FROM task_info')
    const illegal = await clickAndResponse(page, '/instance/detailPlus', () => selectors.dialog(page).locator('.task-query').getByRole('button', { name: 'Query', exact: true }).click())
    expect(illegal.success).toBe(false)
    await expect(selectors.dialog(page)).toBeVisible()
    await expect(page.locator('.el-message').last()).toBeVisible()
    await taskQuery.fill('status in (5, 6) order by last_modified_time desc')
    expect((await clickAndResponse(page, '/instance/detailPlus', () => selectors.dialog(page).locator('.task-query').getByRole('button', { name: 'Query', exact: true }).click())).success).toBe(true)
    await proof('UI-017', 'detail-custom-query', { readonlyValidQuery: true, independentReadback: true, illegalStatementRejectedBeforeExecution: true, visibleFailureAndRecovery: true })
    await proof('UI-017', 'detail-mapreduce', { rootCount: 1, exactInputItems: 8, exactSquares: true, sum: 140, sha256: expectedHash, pageTaskQuery: true })
    await selectors.dialog(page).getByRole('button', { name: 'Close this dialog' }).click()

    const retry = await create('STANDALONE', { failFirst: 1 })
    await backend.waitInstance(retry.instance, [4])
    const retried = await clickAndResponse(page, '/instance/retry', () => row(retry.instance).then(target => target.getByRole('button', { name: 'Retry', exact: true }).click()))
    expect(retried.success).toBe(true)
    const succeeded = await backend.waitInstance(retry.instance, [5])
    expect(succeeded.runningTimes).toBeGreaterThanOrEqual(2)
    expect(events.filter(event => event.logicalNode === retry.name && event.event === 'FAIL')).toHaveLength(1)
    expect(events.filter(event => event.logicalNode === retry.name && event.event === 'COMMIT')).toHaveLength(1)
    await page.getByRole('button', { name: 'Refresh', exact: true }).click()
    await expect(selectors.row(page, String(retry.instance))).toContainText('Success')
    await proof('UI-018', 'retry-failed', { failedOnce: true, manualRetrySameInstance: true, runningTimes: succeeded.runningTimes, exactlyOneCommit: true, successReadback: true })

    const stop = await create('STANDALONE', { sleepMs: 30000 })
    await backend.waitInstance(stop.instance, [3])
    await expect.poll(() => events.filter(event => event.logicalNode === stop.name && event.event === 'START').length).toBe(1)
    await (await row(stop.instance)).getByRole('button', { name: 'Detail', exact: true }).click()
    await expect(selectors.dialog(page)).toContainText('Running')
    await expect(selectors.dialog(page)).toContainText(String(stop.instance))
    await proof('UI-017', 'detail-normal-running', { actualWorkerStartLedger: true, realRunningInstance: true, exactId: true, noNodeDetailException: true })
    await selectors.dialog(page).getByRole('button', { name: 'Close this dialog' }).click()
    await expect(selectors.dialog(page)).not.toBeVisible()
    const rejectedRetry = await clickAndResponse(page, '/instance/retry', () => selectors.row(page, String(stop.instance)).getByRole('button', { name: 'Retry', exact: true }).click())
    expect(rejectedRetry.success).toBe(false)
    await expect(page.locator('.el-message').last()).toBeVisible()
    expect((await backend.waitInstance(stop.instance, [3])).status).toBe(3)
    await proof('UI-018', 'retry-terminal-feedback', { realRunningInstanceCannotRetry: true, originalServerRejection: true, errorVisible: true, stateStillRunning: true })
    await page.goto('/#/oms/home')
    const overview = await clickAndResponse(page, '/system/overview', () => page.getByRole('button', { name: 'Refresh', exact: true }).click())
    expect(overview.data.runningInstanceCount).toBeGreaterThanOrEqual(1)
    await expect(page.locator('.metric-card strong').nth(1)).toHaveText(String(overview.data.runningInstanceCount))
    let stopRequests = 0
    page.on('request', request => { if (request.url().split('?')[0].endsWith('/instance/stop')) stopRequests++ })
    let target = await row(stop.instance)
    await target.getByRole('button', { name: 'Stop', exact: true }).click()
    await confirmDialog(page, false)
    expect(stopRequests).toBe(0)
    expect((await backend.waitInstance(stop.instance, [3])).status).toBe(3)
    expect(events.filter(event => event.logicalNode === stop.name && event.event === 'COMMIT')).toHaveLength(0)
    await proof('UI-018', 'stop-cancel', { stillRunning: true, noCommit: true, cancelledPageConfirmation: true })
    target = await row(stop.instance)
    await target.getByRole('button', { name: 'Stop', exact: true }).click()
    await confirmDialog(page)
    await backend.waitInstance(stop.instance, [10])
    await expect.poll(() => events.filter(event => event.logicalNode === stop.name && event.event === 'INTERRUPTED').length, { timeout: 10_000 }).toBe(1)
    expect(events.filter(event => event.logicalNode === stop.name && event.event === 'COMMIT')).toHaveLength(0)
    await page.getByRole('button', { name: 'Refresh', exact: true }).click()
    await expect(selectors.row(page, String(stop.instance))).toContainText('Stopped')
    await proof('UI-018', 'stop-running', { interruptedLedger: true, noBusinessCommit: true, stoppedReadback: true, actualUIConfirmation: true })
    await page.goto('/#/oms/home')
    const afterStop = await clickAndResponse(page, '/system/overview', () => page.getByRole('button', { name: 'Refresh', exact: true }).click())
    await expect(page.locator('.metric-card strong').nth(1)).toHaveText(String(afterStop.data.runningInstanceCount))
    expect((await backend.waitInstance(stop.instance, [10])).status).toBe(10)
    await proof('UI-010', 'overview-states', { ownInstanceRunningThenStopped: true, runningMetricIndependentResponse: overview.data.runningInstanceCount, stoppedMetricIndependentResponse: afterStop.data.runningInstanceCount, simultaneousOtherLanesAllowed: true })
  } finally {
    await fs.writeFile(info.outputPath('synthetic-ledger.json'), JSON.stringify(events, null, 2))
    for (const instance of instances) await backend.call('/instance/stop?instanceId=' + instance, { allowFailure: true })
    for (const id of ids) await backend.deleteOwnedJob(id)
    if (containerId) await backend.call('/container/delete?containerId=' + containerId + '&appId=' + credentials.app_id)
    await new Promise(resolve => server.close(resolve))
  }
})
