import { test, expect, selectors, runId, input, choose, enterSamples, saveDialog, clickAndResponse, login, fileHash, demoProcessor, timeoutProcessor } from './support.js';
import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import JSONbig from 'json-bigint';

async function proof(info, caseId, variantId, actual) {
  const result={caseId,variantId,status:'PASS',testTitle:info.title,actual};
  await fs.writeFile(info.outputPath(`variant-${caseId}-${variantId}.json`),JSON.stringify(result,null,2));
  await info.attach(`${caseId}/${variantId}`,{body:JSON.stringify(result),contentType:'application/json'});
}
async function job(page,backend,name,params,processor=demoProcessor,external=false) {
  await page.goto('/#/oms/job');await page.getByRole('button',{name:'New job',exact:true}).click();const dialog=selectors.dialog(page);
  await input(dialog,'Job name',name);await input(dialog,'Job params',params);await choose(page,dialog,'Schedule info','API');await choose(page,dialog,'Execution config','Standalone',0);await choose(page,dialog,'Execution config',external?/External|EXTERNAL/:'BUILT_IN',1);await input(dialog,'Execution config',processor);await dialog.getByPlaceholder('Instance retry times',{exact:true}).fill('0');await dialog.getByPlaceholder('Task retry times',{exact:true}).fill('0');await saveDialog(page,'/job/save');const created=(await backend.listJobs(name)).data.find(value=>value.jobName===name);expect(created).toBeTruthy();return String(created.id);
}
async function jobRow(page,id){await page.goto('/#/oms/job');await input(page.locator('main'),'Job ID',id);await clickAndResponse(page,'/job/list',()=>page.getByRole('button',{name:'Query',exact:true}).click());return selectors.row(page,String(id));}
async function run(page,id){const row=await jobRow(page,id);const result=await clickAndResponse(page,'/job/run',()=>row.getByRole('button',{name:'Run',exact:true}).click());expect(result.success).toBe(true);return String(result.data);}
async function delayedRun(backend,credentials,id,delay){const response=await backend.request.post(backend.server+'/openApi/authApp',{data:{appName:credentials.app_name,encryptedPassword:credentials.app_password,encryptType:'NONE'}});const auth=await response.json();expect(auth.success,'Isolated app OpenAPI credentials must be valid').toBe(true);const started=await backend.request.post(backend.server+'/openApi/runJob2',{headers:{'X-POWERJOB-APP-ID':String(credentials.app_id),'X-POWERJOB-ACCESS-TOKEN':auth.data.token},data:{appId:credentials.app_id,jobId:id,delay}});const result=JSONbig({storeAsString:true}).parse(await started.text());expect(result.success).toBe(true);return String(result.data);}
async function instanceRow(page,id){await page.goto('/#/oms/instance');await input(page.locator('main'),'Instance ID',id);await clickAndResponse(page,'/instance/list',()=>page.locator('#instance_manager').getByRole('button',{name:'Query',exact:true}).click());const row=selectors.row(page,String(id));await expect(row).toBeVisible();return row;}
async function closeDialog(page){await selectors.dialog(page).getByRole('button',{name:'Close this dialog'}).click();await expect(selectors.dialog(page)).not.toBeVisible();}
async function download(page,info,name,scope=selectors.dialog(page)){const event=page.waitForEvent('download');await scope.getByRole('button',{name:'Download',exact:true}).click();const file=await event,filename=info.outputPath(name);await file.saveAs(filename);const bytes=await fs.readFile(filename);return {bytes,filename,sha256:await fileHash(filename)};}

test('UI-019 · real delayed multilevel sequence logs, refresh, scroll, switch, archive and legacy placeholder recovery',async({page,backend,credentials},info)=>{
  test.setTimeout(300_000);await enterSamples(page,credentials);const jar=process.env.POWERJOB_E2E_LOG_JAR;expect(jar,'A compiled bounded LogSequenceProcessor fixture is required').toBeTruthy();const roots=JSON.parse(process.env.POWERJOB_E2E_LOG_ROOTS||'[]').map(root=>path.resolve(root));expect(roots,'Exact private original Server online-log directories are required').toHaveLength(2);const jobs=[],instances=[],injections=[];let containerId;const marker=`${runId}_seq`, observed=[];
  const observe=response=>{if(response.url().split('?')[0].endsWith('/instance/log'))response.text().then(text=>{const body=JSON.parse(text);const instanceId=new URL(response.url()).searchParams.get('instanceId');observed.push({instanceId,at:Date.now(),index:new URL(response.url()).searchParams.get('index'),...body.data});}).catch(()=>{});};page.on('response',observe);
  try {
    await page.goto('/#/oms/containermanage');await page.getByRole('button',{name:'New container',exact:true}).click();const name=`${runId}_log_jar`;await input(selectors.dialog(page),'Name',name);await selectors.dialog(page).locator('.el-radio').filter({hasText:'FatJar'}).click();const uploaded=await clickAndResponse(page,'/container/jarUpload',()=>selectors.dialog(page).locator('input[type=file]').setInputFiles(jar));expect(uploaded.success).toBe(true);await saveDialog(page,'/container/save');containerId=String((await backend.call('/container/list?appId='+credentials.app_id)).find(c=>c.containerName===name).id);await page.locator('.container-card').filter({hasText:name}).getByRole('button',{name:'Deploy',exact:true}).click();await expect(page.locator('.deployment-log')).toContainText('deploy finished, congratulations!',{timeout:90_000});await closeDialog(page);
    const processor=`${containerId}#tech.powerjob.acceptance.fixture.LogSequenceProcessor`;const id=await job(page,backend,`${runId}_log_sequence`,`${marker}|15000|3|12000|80`,processor,true);jobs.push(id);const first=await delayedRun(backend,credentials,id,10000);instances.push(first);expect(BigInt(first)).toBeGreaterThan(2n**53n);const row=await instanceRow(page,first);await row.getByRole('button',{name:'Detail',exact:true}).click();await selectors.dialog(page).getByRole('tab',{name:'Log',exact:true}).click();await expect(page.locator('.instance-log')).toContainText('SYSTEM: There is no online log',{timeout:5000});const early=await page.locator('.instance-log').innerText();await page.locator('.log-toolbar .el-switch').click();await expect(page.locator('.instance-log')).toContainText(marker+' seq=000',{timeout:35_000});await page.locator('.instance-detail .el-pagination').getByText('2',{exact:true}).click();await expect(page.locator('.instance-log')).toContainText(marker+' seq=079');await expect(page.locator('.instance-log')).toContainText(marker+' seq=080',{timeout:35_000});await expect.poll(()=>observed.filter(log=>log.instanceId===first&&log.data?.includes(marker)).map(log=>log.totalPages).filter((value,index,array)=>array.indexOf(value)===index).length,{timeout:45_000}).toBeGreaterThanOrEqual(2);await backend.waitInstance(first,[5],90_000);await page.locator('.log-toolbar').getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.instance-detail .el-pagination')).toContainText('5');await page.locator('.instance-detail .el-pagination').getByText('5',{exact:true}).click();await expect(page.locator('.instance-log')).toContainText(marker+' seq=239');await proof(info,'UI-019','live-log-refresh',{instanceId:first,marker,actualReports:observed.filter(value=>value.instanceId===first).map(({at,index,totalPages,data})=>({at,index,totalPages,lastSequence:data?.match(/seq=\d+/g)?.at(-1)})),multipleRealReports:true,levels:['INFO','WARN','ERROR'],unicodeMultiline:true});await proof(info,'UI-019','log-early-late',{instanceId:first,earlyDisplay:early,lateSequence:239,realWorkerSource:true});
    const scroll=page.locator('.instance-log');await scroll.hover();await page.mouse.wheel(0,650);await expect.poll(()=>scroll.evaluate(element=>element.scrollTop)).toBeGreaterThan(0);await page.locator('.log-toolbar').getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.locator('.log-toolbar').getByRole('button',{name:'Download',exact:true})).toBeVisible();await expect(scroll).toContainText(marker+' seq=239');await proof(info,'UI-019','log-scroll',{instanceId:first,actualScrollTop:await scroll.evaluate(element=>element.scrollTop),refreshReadable:true,downloadReachable:true});
    const complete=await download(page,info,'sequence-archived.log');const contents=complete.bytes.toString('utf8');expect(contents).not.toContain('SYSTEM: There is no online log');for(let seq=0;seq<240;seq++){const key=marker+' seq='+String(seq).padStart(3,'0');expect(contents.match(new RegExp(key+' 中文😀 line-one','g'))).toHaveLength(1);expect(contents.match(new RegExp(key+' line-two','g'))).toHaveLength(1);}for(const level of ['INFO','WARN','ERROR'])expect(contents).toContain(' '+level+' '+marker);let source;await expect.poll(async()=>{for(const root of roots){const filename=path.join(root,first+'-stable.log');try{const bytes=await fs.readFile(filename);if(bytes.includes(Buffer.from(marker+' seq=239'))){source={filename,bytes};return true;}}catch{}}return false;},{timeout:90_000}).toBe(true);expect(source.bytes).toEqual(complete.bytes);await proof(info,'UI-019','archived-download',{instanceId:first,expectedSequenceCount:240,eachSequenceExactlyOnce:true,originalStableFileBytesMatch:true,sha256:complete.sha256,bytes:complete.bytes.length});await closeDialog(page);
    const secondMarker=`${runId}_other`;const secondJob=await job(page,backend,`${runId}_log_other`,`${secondMarker}|0|1|0|2`,processor,true);jobs.push(secondJob);const second=await run(page,secondJob);instances.push(second);await backend.waitInstance(second,[5]);const baseline=observed.filter(log=>log.instanceId===first).length;await (await instanceRow(page,second)).getByRole('button',{name:'Log',exact:true}).click();await expect.poll(async()=>{const content=await selectors.dialog(page).innerText();if(content.includes(secondMarker))return content;await closeDialog(page);await selectors.row(page,second).getByRole('button',{name:'Log',exact:true}).click();return selectors.dialog(page).innerText();},{timeout:35_000,intervals:[1500,2000,3000]}).toContain(secondMarker);expect(await selectors.dialog(page).innerText()).not.toContain(marker+' seq=');const secondFile=await download(page,info,'second-instance.log');expect(secondFile.bytes.toString('utf8')).toContain(secondMarker);expect(secondFile.bytes.toString('utf8')).not.toContain(marker+' seq=');await page.waitForTimeout(5500);expect(observed.filter(log=>log.instanceId===first)).toHaveLength(baseline);await proof(info,'UI-019','log-switch-instance',{first,second,noOldInstanceRequestsAfterClose:true,onlySecondMarkerInViewAndDownload:true,secondSHA256:secondFile.sha256});await closeDialog(page);
    // Inject only a newly produced exact instance's stable cache. Its real archive remains the recovery source.
    const owner=await backend.waitInstance(first,[5]);expect(String(owner.jobId)).toBe(id);expect((await backend.job(id)).jobName).toBe(`${runId}_log_sequence`);for(const root of roots){expect(path.isAbsolute(root)).toBe(true);expect(root.endsWith(path.join('powerjob','server','online_log'))).toBe(true);const filename=path.join(root,first+'-stable.log');let backup=null;try{backup=await fs.readFile(filename);}catch{}injections.push({filename,backup});await fs.mkdir(root,{recursive:true});await fs.writeFile(filename,'SYSTEM: There is no online log for this job instance.');expect((await fs.stat(filename)).size).toBe(53);}
    await (await instanceRow(page,first)).getByRole('button',{name:'Log',exact:true}).click();await expect(selectors.dialog(page)).toContainText(marker+' seq=000',{timeout:30_000});const restored=await download(page,info,'legacy-recovered.log');expect(restored.bytes).toEqual(complete.bytes);await proof(info,'UI-019','legacy-placeholder',{instanceId:first,exactPlaceholderBytes:53,realOriginalArchiveRecovered:true,originalSHA256:complete.sha256,recoveredSHA256:restored.sha256,onlyOwnedFreshInstanceInjected:true});
  } finally {
    page.off('response',observe);for(const injected of injections){if(injected.backup)await fs.writeFile(injected.filename,injected.backup);else await fs.rm(injected.filename,{force:true});}for(const instance of instances)await backend.call('/instance/stop?instanceId='+instance,{allowFailure:true});for(const id of jobs)await backend.deleteOwnedJob(id);if(containerId)await backend.call('/container/delete?containerId='+containerId+'&appId='+credentials.app_id);await fs.writeFile(info.outputPath('log-responses-synthetic.json'),JSON.stringify(observed,null,2));
  }
});

test('UI-019 · original Server business-error download is visible and never saved as log',async({page,backend,credentials},info)=>{
  await enterSamples(page,credentials);let id;try{id=await job(page,backend,`${runId}_download_error`,'success');const instance=await run(page,id);await backend.waitInstance(instance,[5]);await (await instanceRow(page,instance)).getByRole('button',{name:'Log',exact:true}).click();let downloads=0,businessFailure;page.on('download',()=>downloads++);await page.route('**/instance/downloadLog4Console?**',async route=>{const headers={...route.request().headers(),appid:'invalid-synthetic-app-id'};const response=await route.fetch({headers});const text=await response.text();let body;try{body=JSON.parse(text);}catch{body={unexpectedResponse:text};}businessFailure={success:body.success,code:body.code,message:body.message||body.msg,contentType:response.headers()['content-type'],unexpectedResponse:body.unexpectedResponse};await route.fulfill({response});});await selectors.dialog(page).getByRole('button',{name:'Download',exact:true}).click();await expect(page.locator('.el-message--error').last()).toBeVisible();await page.waitForTimeout(1000);expect(downloads).toBe(0);expect(businessFailure.success).toBe(false);expect(businessFailure.contentType).toContain('json');await proof(info,'UI-019','download-json-error',{controlledInvalidAppIdOnlyForOneDownload:true,instanceId:instance,responseFromActualServer:true,jsonFailure:businessFailure,visibleError:true,zeroDownloads:downloads});}finally{if(id)await backend.deleteOwnedJob(id);}
});

test('UI-035 · actual Chrome native 200 percent zoom login, task save/run and online log download',async({backend,credentials},info)=>{
  test.setTimeout(150_000);const directory=info.outputPath('isolated-native-zoom');await fs.mkdir(directory,{recursive:true});await fs.writeFile(path.join(directory,'manifest.json'),JSON.stringify({manifest_version:3,name:'Isolated acceptance native zoom',version:'1.0',permissions:['tabs'],background:{service_worker:'worker.js'}}));await fs.writeFile(path.join(directory,'worker.js'),'chrome.runtime.onInstalled.addListener(()=>{});');await fs.writeFile(path.join(directory,'zoom.html'),'<!doctype html><title>Native zoom controller</title>');const context=await chromium.launchPersistentContext(path.join(directory,'profile'),{executablePath:process.env.POWERJOB_E2E_CHROME,viewport:null,args:['--enable-unsafe-extension-debugging','--window-size=1440,1000'],ignoreDefaultArgs:['--disable-extensions'],acceptDownloads:true});let id;const errors=[];
  try{const browser=context.browser(),cdp=await browser.newBrowserCDPSession(),version=await cdp.send('Browser.getVersion');const extension=await cdp.send('Extensions.loadUnpacked',{path:directory});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>localStorage.setItem('oms_lang','en'));await page.goto(process.env.POWERJOB_E2E_BASE_URL+'/#/loginHomepage');const before=await page.evaluate(()=>({dpr:devicePixelRatio,width:innerWidth,height:innerHeight,cssZoom:getComputedStyle(document.body).zoom}));const control=await context.newPage();await control.goto('chrome-extension://'+extension.id+'/zoom.html');const zoom=await control.evaluate(async origin=>{const tab=(await chrome.tabs.query({})).find(tab=>tab.url?.startsWith(origin));await chrome.tabs.setZoom(tab.id,2);return chrome.tabs.getZoom(tab.id);},process.env.POWERJOB_E2E_BASE_URL);await expect.poll(()=>page.evaluate(()=>devicePixelRatio)).toBe(before.dpr*2);const after=await page.evaluate(()=>({dpr:devicePixelRatio,width:innerWidth,height:innerHeight,cssZoom:getComputedStyle(document.body).zoom}));expect(zoom).toBe(2);expect(after.cssZoom).toBe('1');expect(after.width).toBeCloseTo(before.width/2,0);const originalGoto=page.goto.bind(page);page.goto=(url,options)=>originalGoto(url.startsWith('/')?process.env.POWERJOB_E2E_BASE_URL+url:url,options);await login(page,credentials);await enterSamples(page,credentials);id=await job(page,backend,`${runId}_native_zoom`,'success');expect((await backend.job(id)).jobName).toBe(`${runId}_native_zoom`);const instance=await run(page,id);await backend.waitInstance(instance,[5]);await (await instanceRow(page,instance)).getByRole('button',{name:'Detail',exact:true}).click();await selectors.dialog(page).getByRole('tab',{name:'Log',exact:true}).click();await page.locator('.log-toolbar .el-switch').click();await expect(page.locator('.instance-log')).toContainText('StandaloneProcessorDemo finished process,success: true',{timeout:30_000});const file=await download(page,info,'native-zoom.log');expect(file.bytes.toString('utf8')).toContain('StandaloneProcessorDemo finished process,success: true');expect(errors).toEqual([]);await proof(info,'UI-035','zoom-200',{browser:version.product,mechanism:'chrome.tabs.setZoom',nativeZoom:zoom,before,after,actualLoginSaveRunAndDownload:true,jobId:id,instanceId:instance,logSha256:file.sha256,bytes:file.bytes.length,consoleErrors:errors});await info.attach('native-zoom-screen',{body:await page.screenshot({fullPage:true,mask:[page.locator('input[type=password]')]}),contentType:'image/png'});}finally{if(id)await backend.deleteOwnedJob(id);await context.close();await fs.rm(path.join(directory,'profile'),{recursive:true,force:true});}
});


test('UI-016 · real delayed/running/success/failed timestamps, retry counts, exact long IDs and application switch',async({page,backend,credentials},info)=>{
  test.setTimeout(240_000);await enterSamples(page,credentials);const jobs=[],instances=[],states=[];let namespaceId,appId;
  async function inspect(instance,status,label){const row=await instanceRow(page,instance);await expect(row).toContainText(label);const listed=await backend.waitInstance(instance,[status]);for(const key of ['actualTriggerTime','finishedTime'])await expect(row).toContainText(listed[key]);await row.getByRole('button',{name:'Detail',exact:true}).click();const detail=await backend.call('/instance/detailPlus',{method:'POST',data:{instanceId:instance}});await expect(selectors.dialog(page)).toContainText(instance);await expect(selectors.dialog(page)).toContainText(label);for(const key of ['expectedTriggerTime','actualTriggerTime','finishedTime'])if(detail[key])await expect(selectors.dialog(page)).toContainText(detail[key]);await expect(selectors.dialog(page)).not.toContainText(/NaN|Invalid Date|undefined/);const cell=selectors.dialog(page).locator('.el-descriptions__cell').filter({hasText:'Running times'}).locator('..').locator('.el-descriptions__content');if(await cell.count())await expect(cell).toHaveText(String(detail.runningTimes));expect(BigInt(instance)).toBeGreaterThan(2n**53n);states.push({instanceId:instance,status,listed:{actualTriggerTime:listed.actualTriggerTime,finishedTime:listed.finishedTime},detail:{runningTimes:detail.runningTimes,expectedTriggerTime:detail.expectedTriggerTime,actualTriggerTime:detail.actualTriggerTime,finishedTime:detail.finishedTime},exactDecimalShown:true,serverFormattedTimesUnchanged:true});await closeDialog(page);return detail;}
  try {
    const slow=await job(page,backend,`${runId}_timestamp_slow`,'30000',timeoutProcessor);jobs.push(slow);
    // Original OpenAPI creates a genuine delayed WAITING instance; the page performs every observation.
    const instance=await delayedRun(backend,credentials,slow,20_000);instances.push(instance);await inspect(instance,1,'Waiting');await backend.waitInstance(instance,[3],45_000);await inspect(instance,3,'Running');await backend.waitInstance(instance,[5],60_000);await inspect(instance,5,'Success');
    const bad=await job(page,backend,`${runId}_timestamp_failed`,'failed');jobs.push(bad);const failed=await run(page,bad);instances.push(failed);await backend.waitInstance(failed,[4]);const first=await inspect(failed,4,'Failed');let row=await instanceRow(page,failed);const retried=await clickAndResponse(page,'/instance/retry',()=>row.getByRole('button',{name:'Retry',exact:true}).click());expect(retried.success).toBe(true);await backend.waitInstance(failed,[4]);const second=await inspect(failed,4,'Failed');expect(second.runningTimes).toBe(first.runningTimes+1);await proof(info,'UI-016','timestamps-id-display',{states,waitingRunningSuccessFailure:true,actualRetryTimesIncreased:true,allIDsAboveSafeInteger:true,timezone:await page.evaluate(()=>Intl.DateTimeFormat().resolvedOptions().timeZone),browserDisplaysOriginalServerStrings:true});
    const emptyName=`${runId}_instance_empty`;await page.goto('/#/admin/namespace');await page.getByRole('button',{name:'Add',exact:true}).click();await input(selectors.dialog(page),'Code',emptyName);await input(selectors.dialog(page),'Name',emptyName);await saveDialog(page,'/namespace/save');namespaceId=(await backend.call('/namespace/list',{method:'POST',data:{codeLike:emptyName,index:0,pageSize:10}})).data[0].id;await page.goto('/#/admin/app');await page.getByRole('button',{name:'Add',exact:true}).click();await choose(page,selectors.dialog(page),'Namespace',new RegExp(emptyName));await input(selectors.dialog(page),'appName',emptyName);await input(selectors.dialog(page),'Name',emptyName);await input(selectors.dialog(page),'Password',`Synthetic.${runId}`);await saveDialog(page,'/appInfo/save');appId=(await backend.call('/appInfo/list',{method:'POST',data:{appNameLike:emptyName,showMyRelated:false,index:0,pageSize:10}})).data[0].id;await input(page.locator('main'),'appName',emptyName);await page.getByRole('button',{name:'Query',exact:true}).click();await selectors.row(page,emptyName).getByRole('button',{name:'Enter',exact:true}).click();await expect(page).toHaveURL(/oms\/home/);const empty=await clickAndResponse(page,'/instance/list',()=>page.goto('/#/oms/instance'));expect(empty.success).toBe(true);expect(empty.data.totalItems).toBe(0);expect(await page.evaluate(()=>localStorage.getItem('Power_appId'))).toBe(String(appId));await expect(page.locator('.el-table__body-wrapper tr')).toHaveCount(0);await expect(page.locator('.el-table__empty-text')).toBeVisible();await enterSamples(page,credentials);await instanceRow(page,instance);await expect(selectors.row(page,instance)).toContainText('Success');expect(await page.evaluate(()=>localStorage.getItem('Power_appId'))).toBe(String(credentials.app_id));await proof(info,'UI-016','app-switch-instances',{samplesAppId:String(credentials.app_id),emptyAppId:String(appId),actualEmptyAppTotal:0,zeroOldRowsInNewApp:true,returnRestoresCorrectInstance:instance,normalPageAppEntryBothWays:true});
  } finally {for(const instance of instances)await backend.call('/instance/stop?instanceId='+instance,{allowFailure:true});for(const id of jobs)await backend.deleteOwnedJob(id);if(appId)await backend.call('/appInfo/delete?appId='+appId,{method:'POST',data:{},appId});if(namespaceId)await backend.call('/namespace/delete?id='+namespaceId,{method:'DELETE',namespaceId});}
});
